### ISSUE TITLE
`check.nobs.vs.nRE` really should not stop in some case where  nobs(.) = rank(Z)

### ISSUE THREAD

**Issue by mmaechler** [lme4/lme4#175]
An example from the Bates-Pinheiro book and among the `nlme` package examples/checks/..  shows IMHO that  our _in_famous check that the
number of observations should exceed rank(Z)  can be very much undesirable :

```
data(ergoStool, package="nlme")
try(## ==> error because nobs = #{random effects}:
fm <- lmer(effort ~ (Type | Subject),data=ergoStool)
)
## Error in checkZdims(reTrms$Ztlist, n = n, control, allow.n = FALSE) : 
##   no. random effects (=36) >= no. observations (=36) for term: (Type | Subject)
```

Ok, at this point, some users will give up and think that lme4 / lmer()  cannot fit this simple model that has been fit for years by `lme()` in the `nlme` package..
More confident users will investigate and hopefully find a solution such as

```
fm <- lmer(effort ~ (Type | Subject),
           data=ergoStool,
           control = lmerControl(check.nobs.vs.nRE = "warning"))
## Warning messages:
## 1: In checkZdims(reTrms$Ztlist, n = n, control, allow.n = FALSE) :
##   no. random effects (=36) >= no. observations (=36) for term: (Type | Subject)
## 2: In checkZrank(reTrms$Zt, n = n, control, nonSmall = 1e+06) :
##   number of observations (=36) <= rank(Z) (=36); variance-covariance matrix will be unidentifiable
## 3: In checkConv(attr(opt, "derivs"), opt$par, checkCtrl = control$checkConv,  :
##   Model is nearly unidentifiable: large eigenvalue ratio
##  - Rescale variables?
```

Hmm..  what should Joe Average UseR conclude from these _three_ warnings,
notably from the claim that the  var-cov matrix will not be useful?
If she's brave (or careless ;-), the next step is just as usual:

```
summary(fm)
## ....................
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr             
##  Subject  (Intercept) 10.64037 3.2620                    
##           TypeT2      16.60932 4.0755   -0.90            
##           TypeT3       8.27599 2.8768   -0.81  0.88      
##           TypeT4       2.94266 1.7154   -0.55  0.48  0.82
##  Residual              0.08423 0.2902                    
## Number of obs: 36, groups: Subject, 9

## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  11.3989     0.4135   27.57
```

which really looks "perfect".. and one starts to wonder about the warnings above.
How can the var-cov be "bad" and then summary so fine?
Well, let's try to be more careful and look at the likelihood profiles and confidence intervals:

```
system.time( pf1 <- profile(fm, which="beta_") )## 4.7 sec on fast lynne (2014 i7)
confint(pf1)
##                2.5 %   97.5 %
## (Intercept) 8.091832 14.70598
```

all looks fine ... and the (_three_ !) warnings above seem even more misleading...

**Comment by jongjay70** [comment]
Hi everyone,

I am running a multilevel growth curve model to examine predictors of social anhedonia (SA) trajectory through ages 12, 15 and 18. SA is a continuous numeric variable. The age variable (Index1) has been coded as 0 for age  12, 1 for age 15 and 2 for age 18. I am currently using a time varying predictor, stress (LSI), which was measured at ages 12, 15 and 18, to examine whether trajectory/variation in LSI predicts difference in SA trajectory. LSI is a continuous numeric variable. The data has been converted to long format with SA in 1 column, LSI in the other, ID in another and age in another column. I used the code below to run my model using lmer. However, I get the following error. Please let me know how I can solve this error. Please note that I have 50% missing data in SA at age 12, which I am handling using the REML method.
modelLSI_maineff_RE <- lmer(SA ~ Index1* LSI+ (1 + Index1+LSI |ID),
                            data = LSIDATA, control = lmerControl(optimizer ="bobyqa"), REML=TRUE)
summary(modelLSI_maineff_RE)
Error: number of observations (=1080) <= number of random effects (=1479) for term (1 + Index1 + LSI | ID); the random-effects parameters and the residual variance (or scale parameter) are probably unidentifiable

 I did test the within-person variance for the LSI variable and the within-person variance is significant from the Greenhouse-Geisser, Hyunh-Feidt tests.

Also, for some reason, the model runs if I specify the random effects as either of these 2 models. However, I want to know whether variation in LSI predicts variation in SA trajectory between and within people. Hence, I need both age and LSI in the random effects. 
  modelLSI1 <- lmer(SA ~ Index1* LSI+ (1 + Index1 |ID),
                            data = LSIDATA, control = lmerControl(optimizer ="bobyqa"), REML=TRUE)
OR
  modelLSI2 <- lmer(SA ~ Index1* LSI+ (1 +LSI |ID),
                            data = LSIDATA, control = lmerControl(optimizer ="bobyqa"), REML=TRUE)

Please let me know how I can solve my error and examine the random effect of LSI and age.  I also tried control = lmerControl(check.nobs.vs.nRE = "ignore") which gave me the following output but it doesn't match the output that SAS proc mixed gave me.  (Code: proc mixed covtest noclprint data= LSIDATA method = REML ;
class ID; 
model SA= Index1 LSI Index1*LSI/solution ddfm = SATTERTHWAITE ;
random intercept Index1 LSI/sub=ID type=csh; )
 
 modelLSI_maineff_RE <- lmer(SA ~ Index1* LSI+ (1 + Index1+LSI |ID), 
                          data = LSIDATA,
                   control = lmerControl(check.nobs.vs.nRE = "ignore",
              optimizer ="bobyqa", check.conv.singular = .makeCC(action = "ignore",  tol = 1e-4)), REML=TRUE)
> summary(modelLSI_maineff_RE)
Linear mixed model fit by REML. t-tests use Satterthwaite's method ['lmerModLmerTest']
Formula: SA ~ Index1 * LSI + (1 + Index1 + LSI | ID)
   Data: LSIDATA
Control: lmerControl(check.nobs.vs.nRE = "ignore", optimizer = "bobyqa",  
    check.conv.singular = .makeCC(action = "ignore", tol = 1e-04))

REML criterion at convergence: 7299.6

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.7289 -0.4832 -0.1449  0.3604  4.5715 

Random effects:
 Groups   Name        Variance Std.Dev. Corr       
 ID       (Intercept) 30.2919  5.5038              
          Index1       2.4765  1.5737   -0.15      
          LSI          0.1669  0.4085   -0.23  0.70
 Residual             24.1793  4.9172              
Number of obs: 1080, groups:  ID, 493

Fixed effects:
             Estimate Std. Error        df t value Pr(>|t|)    
(Intercept)  24.68016    0.39722 313.43436  62.133  < 2e-16 ***
Index1        0.98495    0.23626 362.75018   4.169 3.83e-05 ***
LSI          -0.05197    0.06226 273.85575  -0.835   0.4046    
Index1:LSI    0.09797    0.04506 426.01185   2.174   0.0302 *  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
           (Intr) Index1 LSI   
Index1     -0.645              
LSI        -0.032  0.057       
Index1:LSI  0.015  0.037 -0.695
