### ISSUE TITLE
'data' not being stored in model breaks update() in glmer.nb

### ISSUE THREAD

**Issue by karlic** [lme4/lme4#176]
Calling glmer.nb() results in a model with data stored as '..2'. This then breaks calls to (e.g.) update(). Bug(?) exists in version release and development versions.

MWE:
library(lme4)
mu <- 1.3
size <- 6.3
dfErrors <- data.frame(cbind(rnbinom(10, size = size, mu = mu),rep(1:2)))
names(dfErrors) <- c("Error", "PersonID")
glmer.nb(Error ~ 1 + (1 | PersonID), data = dfErrors)

Generalized linear mixed model fit by maximum likelihood ['glmerMod']
 Family: Negative Binomial(30282.92) ( log )
Formula: Error ~ 1 + (1 | PersonID) 
   Data: ..2                                                       <---- SHOULD BE "dfErrors"
     AIC      BIC   logLik deviance df.resid 
 27.7661  28.6738 -10.8830  21.7661        7 
Random effects:
 Groups   Name        Std.Dev.
 PersonID (Intercept) 0.0000  
 Residual             0.9335  
Number of obs: 10, groups: PersonID, 2
Fixed Effects:
(Intercept)  
    -0.3567  
Warning message:
In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  :
  iteration limit reached

NOTE THE "Data: ..2"

R version 3.0.2 (2013-09-25)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lme4_1.1-4   Matrix_1.1-2

loaded via a namespace (and not attached):
[1] grid_3.0.2      lattice_0.20-24 MASS_7.3-29     minqa_1.2.2    
[5] nlme_3.1-113    splines_3.0.2   tcltk_3.0.2     tools_3.0.2

**Comment by mmaechler** [comment]
Is the same as #266 and also a problem in #318 .. hopefully solved simultaneously ... as @bbolker says above, with "a lot of love"  :+1:
