### ISSUE TITLE
upstream nloptr issues

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#215]
Now that we're importing nloptr (in order to use its bobyqa implementation, and possibly other optimizers) we have two minor issues we might want to chat with its maintainer about:

* it's not clear whether `nloptr` can be installed offline from source (e.g. by users behind a firewall), because part of the installation procedure requires downloading the nlOpt source from the nlOpt web page.  There ought to be a workaround for this (perhaps there already is).
* nloptr doesn't behave very nicely when the function is imported but the package is not attached, because it depends on a data object (`default.nlopt.options` or something like that) from the package, which isn't accessible.  We have a kluge in place at the moment. Going forward we could either `Depend:` on the package or try to figure out a better way to access that info (perhaps the package maintainer could write and export a trivial function that wraps the data??)

**Comment by cderv** [comment]
Hi, 

@bbolker, you said :
> it's not clear whether nloptr can be installed offline from source (e.g. by users behind a firewall), because part of the installation procedure requires downloading the nlOpt source from the nlOpt web page. There ought to be a workaround for this (perhaps there already is).

Do you know if there is a workaround to this ? 
I can't install lme4 in an offline machine because of nloptr.
Thanks!

**Comment by bbolker** [comment]
also, for reference, http://stackoverflow.com/questions/29716857/installing-nloptr-on-linux
