### ISSUE TITLE
"bootstrap runs failed" in bootMer within confint.merMod

### ISSUE THREAD

**Issue by pcdjohnson** [lme4/lme4#231]
I’ve been using confint.merMod to get 95% CIs by parametric bootstrapping, and have been getting the warnings of the type "In bootMer(object, bootFun, nsim = nsim, ...) : some bootstrap runs failed (30/100)”. The function still returns CIs using the bootstrap samples that didn’t fail, but I don’t think these CIs are valid as the failures are very unlikely to be a random sample. Here’s an example using the grouseticks data. I chose this data set because it’s a classic example data set so presumably isn’t pathological, but I’ve been encountering the same problem with other apparently healthy glmer fits.

> library(lme4)
> full_mod1  <- glmer(TICKS ~ YEAR+scale(HEIGHT)+(1|BROOD)+(1|INDEX)+(1|LOCATION), family="poisson", data=grouseticks)
> set.seed(12345)
> confint(full_mod1, method = "boot", boot.type = "basic", nsim = 100, parallel = "multicore", ncpus = 8)
Computing bootstrap confidence intervals ...
                                2.5 %     97.5 %
sd_(Intercept)|INDEX     0.4624700492  0.6550336
sd_(Intercept)|BROOD     0.5740796527  1.0482547
sd_(Intercept)|LOCATION  0.2497343230  1.0574176
(Intercept)             -0.0002611865  0.7208569
YEAR96                   0.7770837606  1.5857202
YEAR97                  -1.4648325648 -0.4484355
scale(HEIGHT)           -1.1335522182 -0.5879858
Warning message:
In bootMer(object, bootFun, nsim = nsim, ...) :
  some bootstrap runs failed (30/100)

(NB I scaled height to prevent a warning but it makes no difference to the likelihood.)

I tried to replicate the problem using bootMer directly to produce fixed effect estimates from 10 samples:

> bootMer(full_mod1, fixef, nsim = 10)$t
      (Intercept)    YEAR96     YEAR97 scale(HEIGHT)
 [1,]   0.6387534 0.7467317 -1.1291369    -0.8741711
 [2,]          NA        NA         NA            NA
 [3,]   0.1920928 1.3666922 -0.5821328    -0.6742498
 [4,]          NA        NA         NA            NA
 [5,]          NA        NA         NA            NA
 [6,]   0.5312426 0.9639612 -1.1041643    -0.7550492
 [7,]          NA        NA         NA            NA
 [8,]   0.2328530 1.1016917 -0.8010541    -0.8480263
 [9,]   0.2685594 1.2806690 -0.7452719    -0.8302675
[10,]   0.1726928 1.1423894 -0.8989542    -1.0344128
Warning message:
In bootMer(full_mod1, fixef, nsim = 10) : some bootstrap runs failed (4/10)

…and get the same problem, not surprisingly. Here’s a manual version of what (I believe) bootMer is doing:

> simTICKS.tab <- simulate(full_mod1, nsim=10)
> t(apply(simTICKS.tab, 2, function(simTICKS) fixef(glmer(simTICKS ~ YEAR+scale(HEIGHT)+(1|BROOD)+(1|INDEX)+(1|LOCATION), family="poisson", data=grouseticks))))
       (Intercept)    YEAR96     YEAR97 scale(HEIGHT)
sim_1    0.1793276 1.2265976 -0.5753168    -0.6435871
sim_2    0.3918824 1.4583529 -0.8958396    -0.8513233
sim_3    0.2565916 1.1230342 -0.9369728    -1.0817019
sim_4    0.3507285 1.1865904 -1.0654895    -0.9193403
sim_5    0.5688213 0.7291811 -0.9734654    -0.8575988
sim_6    0.6160919 1.0552260 -1.5139770    -1.0050926
sim_7    0.1594954 1.1342809 -1.0624134    -0.8107930
sim_8    0.7956874 0.8290606 -1.2491060    -1.0024299
sim_9    0.3081545 1.2677562 -1.0398100    -0.9458849
sim_10   0.4325345 0.9390844 -0.9241206    -0.7341589

…no errors, not even a warning. The discrepancy between bootMer and the DIY version above appears to arise from the bootMer fitting function, refit, being less tolerant of warning signs (non-convergence?) than glmer, which can be seen by putting refit into the DIY bootstrap:

> t(apply(simTICKS.tab, 2, function(simTICKS) fixef(refit(full_mod1, simTICKS))))
Warning messages:
1: In pwrssUpdate(pp, resp, tolPwrss, GQmat, compDev, fac, verbose) :
  Cholmod warning 'not positive definite' at file:../Cholesky/t_cholmod_rowfac.c, line 431
2: In pwrssUpdate(pp, resp, tolPwrss, GQmat, compDev, fac, verbose) :
  Cholmod warning 'not positive definite' at file:../Cholesky/t_cholmod_rowfac.c, line 431
Error in t(apply(simTICKS.tab, 2, function(simTICKS) fixef(refit(full_mod1,  : 
  error in evaluating the argument 'x' in selecting a method for function 't': Error in t(apply(simTICKS.tab, 2, function(simTICKS) fixef(refit(full_mod1,  : 
  (maxstephalfit) PIRLS step-halvings failed to reduce deviance in pwrssUpdate

My questions are: 

Should I trust the error- and warning-free DIY bootstrap results? I would say “yes”, on the (slightly vague) basis that glmer produced no warnings, and that the original model fits well to what is a pretty information-rich data set. So is bootMer being oversensitive? I’m aware that there have been some teething problems with the optimisers and convergence checks in lme4 1.0+ — are these ongoing? 

> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-apple-darwin13.1.0 (64-bit)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lme4_1.1-7   Rcpp_0.11.2  Matrix_1.1-4

loaded via a namespace (and not attached):
[1] boot_1.3-11     grid_3.1.1      lattice_0.20-29 MASS_7.3-33     minqa_1.2.3     nlme_3.1-117    nloptr_1.0.0    splines_3.1.1   tools_3.1.1

**Comment by bbolker** [comment]
Latest investigations (posted at http://ms.mcmaster.ca/~bolker/misc/boot_reset.html) suggest that the problem is somehow in the resetting of `@resp$lp0`, the baseline linear predictor ... but Steve Walker says he has evidence of more fundamental deep-copying issues ...

**Comment by stevencarlislewalker** [comment]
`lp0` is not a field in a `glmResp` object.  However, `lp0`, which lives in the environment of the deviance function, is derived from `@resp$eta`.  The problem _could_ be related to the fact that deep copying is not working at present.  Here is an example with a recently pulled `lme4`:
```r
> gm <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
+             data = cbpp, family = binomial)
> gm@resp$eta
 [1] -0.8087134 -1.8006384 -1.9369296 -2.3884588 -1.6974362 -2.6893612
 [7] -2.8256524 -0.9924771 -1.9844020 -2.1206933 -2.5722225 -1.3593198
[13] -2.3512448 -2.4875360 -2.9390652 -1.5886282 -2.5805531 -2.7168444
[19] -3.1683736 -1.7988148 -2.7907398 -2.9270310 -3.3785602 -0.5093804
[25] -1.5013053 -1.6375966 -2.0891258 -0.7992023 -1.6361190 -2.6280440
[31] -2.7643352 -3.2158644 -1.9394519 -2.9313768 -3.0676681 -3.5191973
[37] -1.4833005 -2.4752255 -2.6115167 -3.0630459 -1.4633458 -2.4552708
[43] -2.5915620 -3.0430912 -2.0883963 -3.0803213 -3.2166125 -3.6681417
[49] -0.4279911 -1.4199160 -1.5562073 -2.0077365 -1.9289459 -2.9208708
[55] -3.0571621 -3.5086913
> gm@resp$copy()$eta
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[39] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by bbolker** [comment]
This appears to be a problem with the `new` method for `glmResp` objects, not with deep copying.  I have a fix but can't push it right now possibly because of github/ddos/chinese issues?  Or maybe you've already found/fixed it -- now I'm trying to pull ...

**Comment by stevencarlislewalker** [comment]
No I haven't pushed anything today.

**Comment by stevencarlislewalker** [comment]
Do you have a fix for `new`, deep copying, or `refit`?  Or some combo?

**Comment by stevencarlislewalker** [comment]
Ah I see what you mean, stepping through `$copy` shows that `eta` doesn't diverge until `new` is called.

**Comment by stevencarlislewalker** [comment]
Yes, the problem, as I think you are saying, is here `eta <<- numeric(length(y))` in `glmResp$initialize`.

**Comment by bbolker** [comment]
Have fixed that problem, but it doesn't fix the larger `reset()` problem.  I think we still need to go through and see exactly how `lp0` is being reset (and figure out how it ought to be).  Right now we have `baseOffset <- object@resp$offset; ...; lp0=object@resp$eta - baseOffset`.  I don't know whether one or both of these ought to be deep copies, nor whether they are being set correctly, nor whether this will actually work (given that `eta` and `offset` are both in different conditions at the beginning and end of each stage of the fitting process ...)

**Comment by stevencarlislewalker** [comment]
In response to a suggestion by @bbolker, I just tried changing
```{r}
rr <- object@resp$copy()
```
to
```{r}
fam <- eval(parse(text = object@call$family))()
rr <- mkRespMod(object@frame, family = fam)
```
in `refit.merMod`, but it doesn't help.  Some seeds that didn't work, do work with this change, but others that worked before don't with the change.

**Comment by bbolker** [comment]
latest suggestion is to review the evidence that the issue is within the linear predictor slot of the respMod object; for each seed, try copying the linear predictor slot of an update(...) call to that of a refit() call and confirm that solves the problem

**Comment by stevencarlislewalker** [comment]
After a very productive meeting with @bbolker yesterday, we now seem to have a much more robust `refit.merMod`.  The fix required three actions, all of which unsurprisingly were ultimately @bbolker's ideas:  (1) fix old TODO items in the initialize methods of the reference classes, (2) run a `glmerPwrssUpdate` to propagate the effects of the new response to the objects in the reference classes, and (3) construct a new response module rather than use the copy.  I am still perplexed why this last step is necessary, but as we discussed it shouldn't be expensive relative to constructing a new predictor module, which we still avoid.

TODO: (1) do something about NLMM's, (2) look into some of the loosened tolerances that were required to pass the tests.

**Comment by bbolker** [comment]
And the original example above works perfectly!  Woo-hoo!

**Comment by mmaechler** [comment]
Congratulations - Ben and Steven!

**Comment by pcdjohnson** [comment]
That’s great — I also checked that the original examples (both confint and bootMer) work on lme4 version 1.1-8. Many thanks for your efforts in fixing this.
