### ISSUE TITLE
bootMer (and others?) handle separate offset term improperly

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#250]
When offsets are specified as a separate argument (rather than as a term within the model formula), `bootMer` (and possibly other simulate/predict-related methods?) doesn't handle them correctly.

(Obvious workaround is to include the offset in the formula ...)

Simulate data/setup:

```
library(lme4)
set.seed(101)
dd <- data.frame(x=runif(200),
                 f=rep(1:20,each=10),
                 o=rnorm(200,mean=2))
dd$y2 <- suppressMessages(simulate(~x+(1|f)+offset(o),
               family="gaussian",
               newdata=dd,
               newparams=list(theta=1,beta=c(0,2),sigma=1))[[1]])
```

Works OK when offset is in formula:
```
fm4 <- lmer(y2~x+(1|f)+offset(o),
             data=dd)
mySumm2 <- function(fit) return(c(fixef(fit),getME(fit,'theta')))
bb2 <- bootMer(fm4,mySumm2,nsim=10)
bb2$t0
##  (Intercept)             x f.(Intercept) 
##    0.2698297     2.0224857     0.9652773 
colMeans(bb2$t)
##  (Intercept)             x f.(Intercept) 
##    0.3983454     1.9291971     1.0817904
```

Fails when offset is a separate argument:
```
fm5 <- lmer(y2~x+(1|f), offset=dd$o,
             data=dd)
bb3 <- bootMer(fm5,mySumm2,nsim=10)
bb3$t0  ## same as above
colMeans(bb3$t)
##  (Intercept)             x f.(Intercept) 
##   -1.7877924     2.0861201     0.6819505
```

**Comment by pitakakariki** [comment]
I've tracked it down to this line in `predict.merMod`.

    offset <- rowSums(object@frame[grepl("offset\\(.*\\)", names(object@frame))])

The regexp is missing the offset in `fm5` because:

    names(fm4@frame)
    # [1] "y2"        "x"         "f"         "offset(o)"
    names(fm5@frame)
    # [1] "y2"       "x"        "f"        "(offset)"

So a simple fix might be:

    offset <- rowSums(object@frame[grepl("\\(?offset(\\(.*\\))?\\)?", names(object@frame))])

Or, depending on taste, you might want to change the code that sets the name to `(offset)`.

**Comment by pitakakariki** [comment]
I'm not sure if the regexp is for some tricky technical reason that I can't see, but could the offset come straight from the object's storage?

**Comment by bbolker** [comment]
The regexp certainly seems like an Original Sin (using string-matching for anything); I will try changing this to `model.offset` (which looks at the `terms` object) and/or `@resp$offset` and see if it seems to work generally.

When we add you to the list of lme4 authors, how would you like to be listed ... ?
