### ISSUE TITLE
Issue with predict when dropping rank-deficient columns

### ISSUE THREAD

**Issue by jwijffels** [lme4/lme4#251]
Hi, I encountered the following issue when predicting alongside a model when the fixed effect model matrix is rank deficient.
The following shows the error. It drops the x1 fixed effect variable from the model, but then predict does not work even though the model returns something.
Is this expected behaviour?
```
require(lme4)
x <- data.frame(id = factor(sample(10, 100, replace = TRUE)))
x$y <- rnorm(nrow(x))
x$x1 <- 1
x$x2 <- ifelse(x$y<0, rnorm(nrow(x), mean=1), rnorm(nrow(x), mean=-1))
m <- lmer(y ~ x1 + x2 + (1 | id), data=x)
## fixed-effect model matrix is rank deficient so dropping 1 column / coefficient
m
## Linear mixed model fit by REML ['lmerMod']
## Formula: y ~ x1 + x2 + (1 | id)
## Data: x
## REML criterion at convergence: 252.1038
## Random effects:
##   Groups   Name        Std.Dev.
## id       (Intercept) 0.0000  
## Residual             0.8323  
## Number of obs: 100, groups:  id, 10
## Fixed Effects:
##   (Intercept)           x2  
## 0.02455      0.37791  
predict(m, newdata=x)
## Error in X %*% fixef(object) : non-conformable arguments
```

**Comment by mensurationist** [comment]
Hi all,  

I wonder if the problem persists in bootMer?  e.g., following the previous example,

> boot.vc <- bootMer(x = m,                                                                                                                                               
                   FUN = function(x) sqrt(unlist(VarCorr(x))),                                                                                                            
                   parallel = "multicore",                                                                                                                                
                   ncpus = detectCores(),                                                                                                                                 
                   nsim = 100)                                                                                                                                            

Error in sim.reff + matrix(rnorm(n * nsim), ncol = nsim) :
  non-conformable arrays

Best wishes

Andrew

**Comment by bbolker** [comment]
More proximal/easier:  

```
simulate(m, nsim = 1, use.u=FALSE, newdata=x)  ## OK
simulate(m, nsim = 1, use.u =FALSE)                     ## fails
```


simulate(m, nsim = 1, use.u = FALSE, na.action = na.exclude)

**Comment by mensurationist** [comment]
Thanks Ben ---

Andrew

On Thu, Jun 25, 2015 at 4:10 PM, Ben Bolker <notifications@github.com>
wrote:

> More proximal/easier:
>
> simulate(m, nsim = 1, use.u=FALSE, newdata=x)  ## OK
> simulate(m, nsim = 1, use.u =FALSE)                     ## fails
>
> simulate(m, nsim = 1, use.u = FALSE, na.action = na.exclude)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lme4/lme4/issues/251#issuecomment-115271301>.
>



-- 
Andrew Robinson
Deputy Director, CEBRA, School of Biosciences
Reader & Associate Professor in Applied Statistics  Tel: (+61) 0403 138 955
School of Mathematics and Statistics                        Fax: +61-3-8344
4599
University of Melbourne, VIC 3010 Australia
Email: a.robinson@ms.unimelb.edu.au
Website: http://www.ms.unimelb.edu.au/~andrewpr

MSME: http://www.crcpress.com/product/isbn/9781439858028
FAwR: http://www.ms.unimelb.edu.au/~andrewpr/FAwR/
SPuR: http://www.ms.unimelb.edu.au/spuRs/

**Comment by bbolker** [comment]
This seems to be fixed.
