### ISSUE TITLE
Failed fitting a mixed model (one fixed, one random) with lme4

### ISSUE THREAD

**Issue by mashu** [lme4/lme4#265]
Hi,

I am trying to fit a model from a book
**Introduction to Mixed Modelling: Beyond Regression and Analysis of Variance by N. W. Galwey**
Chapter 1, file [house price, latitude.dat](http://www.wiley.com/legacy/wileychi/mixed-modelling/supp/intro_to_mixed_modelling.zip).

With nlme I could fit a model: fixed lattitude and random effect town
```
data = read.table("house price, latitude.dat",header = T)
lme(log10(price_pounds) ~ latitude,data=data, random = ~ 1 | town)
Linear mixed-effects model fit by REML
  Data: data 
  Log-restricted-likelihood: 25.06061
  Fixed: log10(price_pounds) ~ latitude 
(Intercept)    latitude 
 9.49679317 -0.08147014 

Random effects:
 Formula: ~1 | town
        (Intercept)  Residual
StdDev:   0.1401131 0.1307764

Number of Observations: 64
Number of Groups: 11 
```
However with lme4 and equivalent model specification as far as I understood in private thread, fitting alghoritm does not converage.
```
lmer(log10(price_pounds) ~  latitude  + 1|town,data=data)
Linear mixed model fit by REML ['lmerMod']
Formula: log10(price_pounds) ~ latitude + 1 | town
   Data: data
REML criterion at convergence: -53.1872
Random effects:
 Groups   Name        Std.Dev. Corr 
 town     (Intercept) 3.57351       
          latitude    0.06438  -1.00
 Residual             0.13057       
Number of obs: 64, groups:  town, 11
Fixed Effects:
(Intercept)  
      5.119  
Warning messages:
1: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.0387022 (tol = 0.002, component 1)
2: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model is nearly unidentifiable: large eigenvalue ratio
 - Rescale variables?
```

I tried other optimizer from optimx package, but with no success. Is it a user error ?

**Comment by bbolker** [comment]
I was sloppy in e-mail: sorry. The correct formula is `log10(price_pounds) ~  latitude  + (1|town)` (the parentheses around `(1|town)` are necessary so that R doesn't interpret `latitude + 1` as the left-hand side of the random-effects term.
