### ISSUE TITLE
Export formatVC 

### ISSUE THREAD

**Issue by palday** [lme4/lme4#268]
I'm currently writing a [LaTeX-based pretty-printer](http://bitbucket.org/palday/lmerout/) for various things related to lmer (model summaries, ANOVAs, Wald tests via the car package, etc). Rather than reinvent the wheel, I've found it easy to use formatVC() to get the basic structure for displaying the random-effect summary If I want to submit this package to CRAN, then accessing non-exported functions in other packages is a big no-no, and so I wanted to suggest that you export this function.

If you feel that this function should remain internal, than I would create a copy in my project (which is also GPL) -- would "lme4 Contributors" suffice for authors in the copyright notice? What year would be appropriate?

**Comment by bbolker** [comment]
"lme4 Contributors" would be just fine for acknowledgement -- might as well make it this year.

  I'm not in principle opposed to exporting formatVC; we thought we had eliminated a lot of the need for it by making an as.data.frame.VarCorr.merMod (horrible name, but oh well) method available, but I can see that your requirement might differ from that.

If there are no objections from other authors I can go ahead and make this (trivial) change.

The only sticking point I can see is that there's no definite target right now for releasing the next version of lme4 (1.1.8) to CRAN; I've been thinking about this for a while, but preparing a new release of a widely used package requires a little bit of effort, and there are a few minor but sticky decisions we'll have to make.  (I may open "release version 1.1.8" as a new issue for discussion ...)

**Comment by palday** [comment]
Hmmm, upon closer inspection, as.data.frame.VarCorr.merMod may actually cover my use case. Update to follow.

**Comment by palday** [comment]
as.data.frame.VarCorr.merMod does indeed cover my use case.
