### ISSUE TITLE
plan next release (1.1-8+)

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#269]
We should aim for a release sometime in the near (?) future, for three reasons:

* coordinate with `glmer` paper
* push current improvements/fixes to CRAN
* inspire cleanup and fixes

Discussion encouraged here of "release critical" vs. "release strongly desired" vs "release wish list" ... (I think there is actually very little in the first category, but lots in the second ...

**Comment by stevencarlislewalker** [comment]
Here's my list:

######  Release strongly desired

1. Get `logLik.merMod` to return the log of the likelihood _including proportionality constants_ and for _every value of `nAGQ`_ (e.g. #161, 829bbbc9e0f3f).  I think this is especially important to clean up before I begin working on the `glmer` paper again.
2. Resolve `master`/`flexLambda` diffs (e.g. #230, #241).

###### Release wish list

3. Get `flexLambda` _really_ up and running (#224, #237).

**Comment by bbolker** [comment]
######  Release strongly desired

* sort out details/make a decision about appropriate scaling and thresholds for convergence testing (reduce false positives)
* ditto, default optimizers (i.e., should we go ahead and switch to `nloptwrap`?)
* resolve failure to properly reset internal structures when using `refit`, i.e. https://github.com/lme4/lme4/issues/231 and related

**Comment by bbolker** [comment]
After further discussion with Steve, here are my release-strongly-desired (if not 100% release-critical issues):

* diagnose/resolve UBSAN issues described [here](http://www.stats.ox.ac.uk/pub/bdr/memtests/UBSAN-gcc/lme4-Ex.Rout), [here](http://www.stats.ox.ac.uk/pub/bdr/memtests/UBSAN-gcc/lme4/) (this probably requires a modern/recent clang compiler setup and deserves a separate issue). (At least a good faith effort to resolve these will probably be required by CRAN.)
* try to resolve `refit()` issues with GLMMs https://github.com/lme4/lme4/issues/231 ; latest suggestion for strategy is to call `mkRespMod` to create a new response module from scratch, since this shouldn't (???) require symbolic permutation or any of the really expensive operations ...
* *don't* do anything new with convergence testing https://github.com/lme4/lme4/issues/120 (except modifying the scaled gradient from `solve(grad,Hessian)` (which is clearly wrong) to `solve(grad,chol(Hessian))`, but *do* add a new help page (`convergence.Rd`) that talks about the issues, suggests a gold standard (refit with several optimizers and hope for consensus).  It can incorporate some of the material from the [rpubs troubleshooting example](https://rpubs.com/bbolker/lme4trouble1) and the latest set of [toast-scraping convergence analysis](https://github.com/lme4/lme4/blob/ea50b8276b3fd593c3fd925983494d07fb8173c8/misc/issues/penicillin_conv.pdf)

**Comment by bbolker** [comment]
We're getting very close now.

* give `HLMdiag` maintainer a few days to fix issues, assist as necessary
* update `NEWS` file
* consider sorting out the `logLik`/`deviance` mess, if easy (or at least document issues); @stevencarlislewalker ?
* export `print.summary.merMod` etc. as requested by @stevencarlislewalker for `lme4ord`

**Comment by mmaechler** [comment]
* I'd like to add a  sigma()  generic function to R-devel, before we release, and add code in lme4 which will import the new `sigma()` from R-devel before our release.
* I've looked at man/convergence.Rd .. fixed one typo, re-indented (notably the overlong source lines) and slightly tweaked the example.
* I'd like to help with your 4th item, exporting `print.summary..`.  ... ah I see `lme4ord` on github..

**Comment by mmaechler** [comment]
Forgot:  Yesterday, a new version of `Matrix`, 1.2-1, was released to CRAN.  There, I've changed the depency to `R >= 3.0.1` which also allowed to move `methods` from `Depends:` to `Imports:`.
 I think we should do "the same" for `lme4`, i.e., finally require R >= 3.0.x, and can finally clean up stuff,
notably drop `Rcpp` from Depends (and add the version requirement to `LinkingTo`), but I think quite a few more simplifications.

**Comment by mmaechler** [comment]
* Forgot 2: I've added `maxit` optional argument to refit(), mkdevfun() {for GLMM}, because we have an example in the `refit` tests which needs more iterations.... and that change entails more functions...
so I'm still not finished...  all this should really just be "new feature", so it should not possibly have an effect on downstream..

**Comment by bbolker** [comment]
@mmaechler, fine with me on all counts (I like backward compatibility but ... also, hopefully the miniCRAN/checkpoint framework that Revolution R has put together will help out people who desperately need to use old versions for some reason).  (Do we have to jump through any hoops to make the `sigma()` accessor work with both R-release and R-devel?) Could you go ahead and make these changes, or delegate as you prefer?

I think I probably will go ahead and re-run all the reverse dependency checks once we've finished this stuff.  It's very slow on the machine I have it on but hopefully will be somewhat faster (e.g. < 1 day) since I will only have to test 117 packages, not install dependencies for them and sort out problems with system tools/dependencies (tcltk, OpenBUGS, etc..)

**Comment by mmaechler** [comment]
@bbolker : yes,  there are a few hoops for `sigma()` to jump through.  I have not yet added them to `lme4`, but to another package of mine `robustbase` (well only to the R-forge version of that) so this should be quick to do for lme4. ..
Indeed something I plan to do "first thing" tomorrow, because about 20 minutes ago, I have committed
the `sigma()` S3 generic with two methods to `R-devel`... and so you will see the result when checking lme4 with the latest R-devel soon.

**Comment by stevencarlislewalker** [comment]
* consider sorting out the logLik/deviance mess, if easy (or at least document issues); @stevencarlislewalker ?

I think we should add to the documentation (or as @mmaechler suggests point from the documentation to) a table describing the various kinds of deviance that one might like to get from a fitted GLMM object (see my response to @bbolker and @dmbates here: https://github.com/lme4/lme4/commit/c49cb45556f).  I'm not so sure anymore that it is necessary to add yet another extraction function or add yet more arguments to existing extractors.  Clear documentation should be enough.

I may have also discovered the underlying problem with #161 (see changes to `mist/notes/deviance.rmd` here: https://github.com/lme4/lme4/commit/770347040).  Do we want to change this in the upcoming release?  It could potentially cause downstream issues.

* export print.summary.merMod etc. as requested by @stevencarlislewalker for lme4ord

Unfortunately what I really need are all of the little helper functions for `print.merMod` and `print.summary.merMod` (e.g. `.prt.methTit`, `.prt.family`, `famlink`, `.prt.call`).  Maybe for now it would be easier to just copy those functions into `lme4ord`, with the possibility of exporting them in `lme4` once `lme4ord` stabilizes a little more.

**Comment by bbolker** [comment]
closing (now we can start listing requests/milestones for 1.1-9 release ...)
