### ISSUE TITLE
predict.merMod fails without all factor levels in newdata

### ISSUE THREAD

**Issue by jknowles** [lme4/lme4#275]
This might be a duplicate of #143 and #153, but below is a reproducible example.

```R
library(lme4) # dev or CRAN version
data(sleepstudy)
sleepstudy$noiseFactor <- ifelse(runif(nrow(sleepstudy)) > 0.8, "Yes", "No") # add a factor
fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
fm2 <- lmer(Reaction ~ Days + noiseFactor + (Days | Subject), sleepstudy)
# This works
predict(fm1, newdata = fm1@frame[2, ]) # predict 1 row of data
# Now with a factor
predict(fm2, newdata = fm2@frame[2, ])
```

The second call results in the error:

```
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
```

This is problematic for producing predictions on new data frames where not all factor levels are present on the fly, or for scoring new data with predictions where not all factor levels are necessarily present.

**Comment by bbolker** [comment]
thanks (sigh)

**Comment by jknowles** [comment]
I'm happy to take a look at a fix. 

I just would want to confirm that the expected behavior should be that `predict(fm2, newdata...)` would produce a prediction applying the coefficient corresponding to the factor level contained in the observations in the data.frame?

**Comment by bbolker** [comment]
absolutely.  I think there is some possibly-useful commentary in the previous issues.

**Comment by rubenarslan** [comment]
I am predicting successfully (well not entirely, or why am I checking the issue list of this repo...) with a subset of factor levels. So I was surprised to see this issue and tried to reproduce it.

Maybe you knew this already, but the bug here only happens if you use a character which is transformed into a factor by lme4 (so that contrast cannot reconstruct the levels).
So at least there's an easy workaround.

```r
library(lme4) # dev or CRAN version
data(sleepstudy)
set.seed(1)
# note the factor() call
sleepstudy$noiseFactor <- factor(ifelse(runif(nrow(sleepstudy)) > 0.8, "Yes", "No")) # add a factor
fm2 <- lmer(Reaction ~ Days + noiseFactor + (Days | Subject), sleepstudy)
# Now with two factors

# works even though row 2 and 3 have just one level.
predict(fm2, newdata = fm2@frame[2:3, ])

# if you predict with a single row you get
predict(fm2, newdata = fm2@frame[3, ])
```
> Error: sum(nb) == q is not TRUE

Fix would probably be something along the lines of 
`newdata$noiseFactor = factor(newdata$noiseFactor, levels = levels(fit@frame$noiseFactor))`

in a general form, somewhere appropriate.

**Comment by bbolker** [comment]
Hmm.  Can no longer reproduce? WIth current (I think) version I get in trouble with character vectors but not with factors.  Thinking of adding a "convert all chars to factors in original model frame" step ...

```
    ss <- sleepstudy
    set.seed(1)
    ss$noiseChar <- ifelse(runif(nrow(sleepstudy)) > 0.8, "Yes", "No")
    ss$noiseFactor <- factor(ss$noiseChar)
    fm2 <- lmer(Reaction ~ Days + noiseChar + (Days | Subject), ss)
    predict(fm2, newdata = model.frame(fm2)[2:3, ])
    predict(fm2, newdata = model.frame(fm2)[3, ])
    ## Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
    ##   contrasts can be applied only to factors with 2 or more levels
    fm3 <- lmer(Reaction ~ Days + noiseFactor + (Days | Subject), ss)
    expect_equal(predict(fm3, newdata = model.frame(fm3)[2:3, ])[2],
                 predict(fm3, newdata = model.frame(fm3)[3, ]))
```
