### ISSUE TITLE
CRAN warnings about 

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#278]
we're getting WARNINGs about overwriting S3 methods from `nlme`.  Will have to read up on the Right Way to do this ...
```
checking use of S3 registration ... WARNING
Registered S3 methods in standard package(s) overwritten by 'lme4':
method package
coef.lmList nlme
formula.lmList nlme
update.lmList nlme 
```

**Comment by mmaechler** [comment]
We should rather try to get current lme4 to CRAN.  Many of the warnings and notes there only apply to "ancient"  lme4 1.1-7 :-)

**Comment by stevencarlislewalker** [comment]
Well no one has mentioned any release critical issues at #269, so maybe we can just release?

**Comment by stevencarlislewalker** [comment]
...but I guess S3 registration should be considered release critical.

**Comment by mmaechler** [comment]
Yes, @stevencarlislewalker ,  and indeed that warning is with current lme4  (and is pretty new in R-devel only).  I'm having a look.

**Comment by mmaechler** [comment]
After a long look, I don't see a good way to *not* get these warnings in R-devel.
I would argue that the warnings are false positives.   After all we are allowed to export functions and methods with changed functionality, notably changed with respect to a package that we not even depend on (but just very partially import).
@bbolker , package maintainer: Would you ask cran@r-proj.. about it ... or tell me to do it (tomorrow my time).

**Comment by bbolker** [comment]
(1) message sent; (2) this issue arises in the `*.lmList` interface, which has needed some love/thought for some time (i.e. see https://github.com/lme4/lme4/issues/26)

**Comment by mmaechler** [comment]
As we are violating CRAN / R policies by "tampering with the methods table of a base package"
(we do change the table of stats::coef, e.g.),
we should change.

1) Keep `lmList()` the function
2) Rename `"lmList"` the class name and adapt the S3 methods correspondingly.
   I propose we use `"lmList4"` matching our package name.

**Comment by bbolker** [comment]
Agreed.

**Comment by mmaechler** [comment]
2d429e4 and bunch of previous commits now have made "huge" progress:
We do use class `"lmList4"` now, and many methods now work on the result of `lmList()` which did not work at all previously, such as `fitted()`, `fixef()`, `plot()`, `qqnorm()`.  

Note that the "lmList4" class may have to change even more, once we consider more cases and want to provide much of the functionality of `nlme` package's class and methods.
As the basic issue is solved, I close it now.
