### ISSUE TITLE
predict problem with/without 

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#279]
Reported [on StackOverflow](http://stackoverflow.com/questions/28356192/predict-glmer-on-training-set-differs-with-and-without-newdata?noredirect=1#comment45096549_28356192).

`predict` apparently behaves differently (for random-slope models) if `newdata` is specified (calling the same data frame used in the original model fit) or if it is not.

```
library("lme4")
m1 <- lmer(Reaction ~ Days + (Days||Subject), sleepstudy)
p1 <- predict(m1, type="response")
p2 <- predict(m1, type="response", newdata=sleepstudy)
all.equal(p1,p2)  ## should be TRUE
```

* works for me on (2015-02-05 r67737) Platform: i686-pc-linux-gnu (32-bit) (v 1.1-8)
* ... and on R version 3.1.2 (2014-10-31) Platform: x86_64-apple-darwin10.8.0 (64-bit)` (v. 1.1-8)
* and for Gavin Simpson on  `lme4 1.1-7 (on linux, R 3.1.1)`

**fails**

* for the [SO poster](http://stackoverflow.com/users/2250190/user20650) (ubuntu 12.04, R3.1.2, lme4 1.1.7)
* ... and on Windows8 .1 x64, R3.1.2, lme1.1.7
* for Jack Tanner (Windows 7 x64, R 3.1.2, lme4 1.1.8)

**Comment by user20650-david** [comment]
Hi Ben

It does appear to be loacalised to certain PC's , but I get the same results on another PC (Windows8 x64.1, R3.1.2, lme1.1.7 as well as my ubuntux32 laptop (as above) . If its any use, below is a summary of the predicted values that i get when running the above commands

    summary(p1)
    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    211.0   260.8   297.0   298.5   328.6   458.0 
    summary(p2)
    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    -58.13  225.50  297.00  298.50  375.00  693.30 
    all.equal(p1, p2)
    [1] "Mean relative difference: 0.2945899"

![rplot](https://cloud.githubusercontent.com/assets/10900223/6093688/819e9b4e-af01-11e4-9f65-011ecc210427.png)

**Comment by bbolker** [comment]
do you have access to any systems that do *not* show the problem?  It will help enormously if we can get some systematic idea on which systems it does or doesn't work (and/or, ideally, get access for an lme4 developer to a platform/OS/R version/lme4 version combo where it doesn't work)

**Comment by bbolker** [comment]
... also, are you willing to try with the very latest Github version (`devtools::install_github("lme4/lme4")`)?  There were some changes to the prediction code in Nov 2014 ...

**Comment by bbolker** [comment]
is this https://github.com/lme4/lme4/issues/257 ?

**Comment by user20650-david** [comment]
Yes!!, using the latest Github version has fixed it (only tried on my ubuntu laptop). Thanks very much.

From your earleir comment - the problem persisted on all my systems but was removed when setting the `re.form=NA`.

**Comment by bbolker** [comment]
Turns out to be identical to #257
