### ISSUE TITLE
glmer.nb doesn't take subset argument

### ISSUE THREAD

**Issue by rubenarslan** [lme4/lme4#285]
easy to work around of course:

    library(lme4)
    data(sleepstudy)
    glmer.nb(Reaction > 250 ~ Days + (1|Subject), data = sleepstudy)
    glmer.nb(Reaction > 250 ~ Days + (1|Subject), data = sleepstudy, subset = Subject != 370)

> Error in glmer.nb(Reaction > 250 ~ Days + (1 | Subject), data = sleepstudy,  : 
  object 'Subject' not found

**Comment by bbolker** [comment]
I think I've got fixes for this.  One question:

- `mkRespMod` doesn't allow logical responses unless `family="binomial"`, so to make these examples run you'd need `as.numeric(Reaction>250)`.  I'm OK with that (this is a pretty artificial example anyway), but I'd be open to arguments that logical responses should be coerced to numeric in this case?

**Comment by mmaechler** [comment]
yes, coerce them silently,  "numeric", well, to  integer more specifically

**Comment by bbolker** [comment]
this is fixed (although I'm not sure the coercion is actually a good idea ...)
