### ISSUE TITLE
Find Match by considering a row value and checking with all values of other data frame 

### ISSUE THREAD

**Issue by uthsavi** [lme4/lme4#292]
I have tried various way of matching this , when i try out with small data values it works wonder! but when i apply the same logic and code for huge values it throws error 

**sample** 

**Source**                                     ** Master  **                       

 chang chun petrochemical         CHANG CHUN GROUP                 
 chang chun plastics                    CHURCH AND DWIGHT CO INC         
 church  dwight                            CITRIX SYSTEMS ASIA PACIFIC P L    
 citrix systems  pacific                  CNH INDUSTRIAL N.V`                        

**code**

`for (i in 100){
  gr1$x[i] = agrep(gr1$Source[i], gr2$Master, value = TRUE, max = list(del = 0.2, ins = 0.3, sub = 0.4))
  gr2$Y[i] = agrep(gr1$Source[i], gr2$Master, value = FALSE, max = list(del = 0.2, ins = 0.3, sub = 0.4))
}`

**error:**

`Error in `$<-.data.frame`(`*tmp*`, "x", value = c(NA, NA, " church  dwight  " : 
  replacement has 3 rows, data has 100`

**desired Result**

  chang chun petrochemical                      CHANG CHUN GROUP
   chang chun plastics                               CHANG CHUN GROUP
   church  dwight                                       CCITRIX SYSTEMS ASIA PACIFIC
    citrix systems  pacific                            CHURCH AND DWIGHT CO INC

**Comment by bbolker** [comment]
This looks like it's in absolutely the wrong place, i.e. has nothing (that I can see) to do with mixed models or `lme4`. A more general R forum would be a good idea, but I would also recommend reading about how to supply a [reproducible example](http://tinyurl.com/reproducible-000) ...
