### ISSUE TITLE
refactor lmerControl/glmerControl

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#293]
`lmerControl` and `glmerControl` have *lots* of shared parameters

```
library("lme4")
f1 <- formals(lmerControl)
f2 <- formals(glmerControl)
sum(sapply(names(f1),
    function(n) n %in% names(f2) && isTRUE(all.equal(f1[[n]],f2[[n]]))))
## 14
length(f1)  ## 18
length(f2)  ## 22
```

Is there a nice way to refactor this so that it's easy to document
but not too ridiculous in terms of maintenance?  (Write an underlying
merControl() function?)

**Comment by bbolker** [comment]
this is done in 51ed20393fc9de135d8c6880 and following, but runs into a problem with the way I've implemented it, which is via `match.call()` and `eval()`; we either have to use `lme4:::merControl` (which raises a NOTE in CRAN checks), or we have to export `merControl`, which will make the documentation a bit uglier.

**Comment by mmaechler** [comment]
Thank you for taking up this (informal) issue of a long time ago [I already had it as "TODO" years ago].   Your approach using eval() is fine.
I think we should export  merControl  and add it to the same help page as [g]lmerControl.
Other package authors importing lme4 may use  `merControl()` to build their own *Control() function, so exporting would make some sense.
