### ISSUE TITLE
Tests fail when MEMSS is not installed

### ISSUE THREAD

**Issue by hadley** [lme4/lme4#299]
```
checking tests ... ERROR
Running the tests in ‘tests/AAAtest-all.R’ failed.
Last 13 lines of output:
         warning = function(c) invokeRestart("muffleWarning"))
  2: eval(code, new_test_environment)
  3: eval(expr, envir, enclos)
  4: data("Orthodont", package = "MEMSS") at test-methods.R:131
  5: find.package(package, lib.loc, verbose = verbose)
  6: stop(gettextf("there is no package called %s", sQuote(pkg)), domain = NA)
  7: .handleSimpleError(function (e) 
     {
         e$calls <- head(sys.calls()[-seq_len(frame + 7)], -2)
         signalCondition(e)
     }, "there is no package called 'MEMSS'", quote(find.package(package, lib.loc, verbose = verbose)))
  Error: Test failures
  Execution halted
```

You can use `skip_if_not_installed()` to avoid this problem

**Comment by bbolker** [comment]
I'm a little surprised by this since MEMSS *is* in "Suggests:" in the DESCRIPTION ... ?  I thought it was OK to depend on such packages being installed when running tests?  Or am I misunderstanding something?

**Comment by hadley** [comment]
It's semi-ok - R-exts is a bit murky, but suggests that you should be able to run `R CMD check` even when no suggested packages are installed.  I don't install suggested packages, because anything I can do to save some time when checking the ~500 packages that depend on testthat helps. It's not a big deal if you don't fix it, but it makes it a little less likely that I'll pick up on real problems when I do my checks.

**Comment by bbolker** [comment]
Hmm.  I don't mind protecting in this way, but ... I sense a little bit of dependency hell looming, because `skip_if_not_installed()` doesn't seem to exist in the CRAN version (0.9.1) of testthat, so we'd have to upgrade to the development version of `testthat` to use this functionality.  On the other hand, I could just fall back to `if (!require("MEMSS")) ...`  Thoughts?

**Comment by stevencarlislewalker** [comment]
I can't think of any reason why `if (require("MEMSS"))` wouldn't be fine, at least in the short term.

**Comment by hadley** [comment]
@bbolker doh, didn't think of that. It's fine to skip the skipping for now ;)

**Comment by bbolker** [comment]
Closed by https://github.com/lme4/lme4/commit/f3b8b2adcb080317919705b479134343eb990535

**Comment by bbolker** [comment]
BTW I did notice that there was an `if (require(MEMSS))` clause elsewhere in the tests, so it's certainly something we've been concerned about in the past, makes sense to be consistent.

**Comment by mmaechler** [comment]
@hadley : I think you misunderstood something in R-exts (or I misunderstood what you said):  As a rule, `R CMD check` should definitely be run in an environment where suggested packages are installed (and found in `.libPaths`).  For "quick and dirty" pre-testing, which we (package authors in general) want to be fast, there are provisions to do checking without those packages.
Using   `if(require(<pkg>) )`  and similar in all examples, vignettes, demos and tests where suggested packages appear has always been strongly recommended and eventually required,  for very good reasons, I'd say.

**Comment by hadley** [comment]
@mmaechler I guess the question is when I run revdep checks for CRAN, should these be quick and dirty or full? (and the empirical answer to that question seems to be that quick-and-dirty is ok)

**Comment by mmaechler** [comment]
@hadley: Sure.  Now I see what you  meant.  I thought @bbolker was talking about 'R CMD check' of our package...
