### ISSUE TITLE
Unexpected error in simulate.merMod

### ISSUE THREAD

**Issue by tmalsburg** [lme4/lme4#305]
Using the latest development version of R and lme4:

```R
    library(lme4)
    d <- sleepstudy
    d$Subject <- factor(rep(1:18, each=10))
    fm1 <- lmer(Reaction ~ Days + (Days | Subject), d)
    # Add 18 new subjects for power analysis:
    d <- rbind(sleepstudy, sleepstudy)
    d$Subject <- factor(rep(1:36, each=10))
    d[d$Subject %in% 19:36,]$Reaction <- NA
    simulate(fm1, newdata=d, allow.new.levels=T, nsim=1)
```

This gives me an error:

    Error in `row.names<-.data.frame`(`*tmp*`, value = c("1", "2", "3", "4",  : 
    invalid 'row.names' length

However, when I skip the second to last line (where the NAs are assigned), I don’t get an error.  For the purpose of the simulation it shouldn’t matter what the content of the Reaction column is, right?

**Edit:** Fixed a mistake in the example code.

**Comment by tmalsburg** [comment]
Here is another variation where I also get the error with `ifelse` when the Subject indicator is an integer instead of a factor:

```R
    d <- sleepstudy
    # Use integer for Subject:
    d$Subject <- rep(1:18, each=10)
    fm1 <- lmer(Reaction ~ Days + (Days | Subject), d)
    # Add 18 new subjects:
    d <- rbind(sleepstudy, sleepstudy)
    d$Subject <- rep(1:36, each=10)
    d$Reaction <- ifelse(d$Subject %in% 19:36, NA, d$Reaction)
    simulate(fm1, newdata=d, allow.new.levels=T, nsim=1)
```

`simulate` seems to be making assumptions about `newdata` based on the original data used for fitting `fm1`, and when `newdata` is actually new these assumptions can lead to errors.

**Comment by tmalsburg** [comment]
This is very likely the same problem as #197.  Added a comment there.

**Comment by bbolker** [comment]
Hmm.  Probably related to #197, but I don't know if it's exactly the same (given that that issue was successfully closed ...) -- may be a byproduct of recent commits attempting to fix other problems.

**Comment by tmalsburg** [comment]
In the discussion of  #197, you had already [mentioned](https://github.com/lme4/lme4/issues/197#issuecomment-40328419) that there is might be problems related to NAs and rownames. That's why I moved to that issue.  But feel free to reopen this one.
