### ISSUE TITLE
warning message from lmerTest

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#309]
This isn't really our problem, but I've noticed that `lmerTest` gives a warning with `summary()`

```
library(lmerTest)
lmod <-  lmer(Reaction ~ Days + (Days|Subject), data=sleepstudy)    
summary(lmod)
...
## Warning message:
## In summary.merMod(model, ddf = "lme4") : additional arguments ignored
```

It would be a courtesy to figure out what's going on here and let the maintainer know.

**Comment by mmaechler** [comment]
Actually, in a recent internal discussion,  other R core members made a partly valid point that such warnings about unused "..."  in methods should not be done, in principle.  By that argument,it would be our problem...  not yet sure..

**Comment by bbolker** [comment]
I did contact Alexandra Kuznetsova (the package maintainer) about this, it might be something she can fix relatively easily on her side.  It's an interesting general policy question, I can see arguments in both directions.

**Comment by bbolker** [comment]
fixed in [latest r-forge version of `lmerTest`](https://r-forge.r-project.org/scm/viewvc.php/pkg/lmerTest/R/generalFunctions.R?view=markup&revision=90&root=lmertest).  

I'm going to close this, but will point out for the record that on my system (32-bit linux) tests fail because I fail to get the expected error in `tests/testContrasts.R` ...

```
## here an error produces
tools::assertError(stopifnot(all.equal(logLik(modelCarrots.treat), 
                                       logLik(modelCarrots.sas))))

tools::assertError(stopifnot(all.equal(VarCorr(modelCarrots.treat), 
                                       VarCorr(modelCarrots.sas), tol = 1e-5)))
```
