### ISSUE TITLE
error function for binary data

### ISSUE THREAD

**Issue by quantdaddy** [lme4/lme4#312]
For binary data, is lmer minimizing the sum of square of error between y_i and m(\gamma_i) where m is the sigmoid link function and \gamma_i is a linear function of the input data OR is it maximizing the binomial log likelihood as we do in logistic regression? 

Thanks!

**Comment by stevencarlislewalker** [comment]
This question is not appropriate for this forum.  Please post to the R-sig-ME list.

But to quickly answer your question in brief, it is maximizing a binomial log likelihood, but not exactly the one used in logistic regression.  In particular, `glmer` fits generalized linear mixed models (GLMMs) by maximum likelihood.
