### ISSUE TITLE
Silent change in confint.merMod behaviour?

### ISSUE THREAD

**Issue by sjPlot** [lme4/lme4#315]
In one of my function of my package I use the `lme4::confint.merMod` method to compute confidence intervals. I was using **lme4 1.1-7**, but recently updated to **1.1-8** and it seems that the default output has changed, breaking some of my functions that rely on the `confint.merMod` function

    > # lme 1.1-8
    > library(lme4)
    > # create binary response
    > sleepstudy$Reaction.dicho <- dicho(sleepstudy$Reaction, dichBy = "md")
    > fit <- glmer(Reaction.dicho ~ Days + (Days | Subject),
    +              sleepstudy,
    +              family = binomial("logit"))
    > 
    > lme4::confint.merMod(fit, method = "Wald")
                     2.5 %    97.5 %
    .sig01              NA        NA
    .sig02              NA        NA
    .sig03              NA        NA
    (Intercept) -6.1145457 -1.517322
    Days         0.4308423  1.350849

However, with **lme 1.1-7** the output was

                     2.5 %    97.5 %
    (Intercept) -6.1145457 -1.517322
    Days         0.4308423  1.350849

Is there a way to repdroduce the former output from version 1.1-7? Or what would be a safe way to get confidence intervals for intercept and model terms only (as in 1.1-7)?

**Comment by bbolker** [comment]
This is in `NEWS`:

> `confint(.,method="Wald")` result now contains rows for random effects parameters (values set to `NA`) as well as for fixed-effect parameters

does

     lme4::confint.merMod(fit, method = "Wald",parm="beta_")

work for you? (I could add this back-compatibility point to the NEWS file, although obviously it won't show up on CRAN ...)

**Comment by sjPlot** [comment]
Thanks, I must have missed that when reading the package news. And yes, it was my copy & paste fault that `library(sjmisc)` was not in the above example.

And, finally: ` lme4::confint.merMod(fit, method = "Wald",parm="beta_")` works fine! Thanks!
