### ISSUE TITLE
interaction between glmer.nb and effects package

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#318]
Let's see if we can hack this on our side by putting `th` somewhere in the environment: if not we may need to ask the `effects` maintainers for help.

```
set.seed(101)
dd <- expand.grid(f1=factor(1:3),f2=factor(1:3),g=1:10,rep=1:10)
dd$y <- rnbinom(nrow(dd),mu=2,size=0.5)
library(lme4)
g1 <- glmer.nb(y~f1*f2+(1|g),data=dd)
library(effects)
library(MASS)
effect("f1*f2",g1)
## Error in negative.binomial(theta = th) : object 'th' not found
```

**Comment by mmaechler** [comment]
Hmm, this should be possible.  I'll have a look.

**Comment by mmaechler** [comment]
Getting the `th` was easy enough.  Now, getting the `..2` replaced by the data frame is a bit more,
(not doing that leads to the next error from  the  `effect(....)` call above.

On the way, I'm flexibilizing  glmer.nb() ... something which we had wanted to do anyway.
Have many changes, not yet committed, sorry, but more tomorrow.
