### ISSUE TITLE
lmList not fully implemented yet?

### ISSUE THREAD

**Issue by kaYcee** [lme4/lme4#320]
I'm using lm4 v1.1-8 and it seems that both the offset and weights parameter are ignored by lmList(..., offset=..., weights=...). The estimates do not change when these parameters are varied:

lmList(Reaction ~ Days | Subject, sleepstudy)
lmList(Reaction ~ Days | Subject, weights=runif(nrow(sleepstudy)), sleepstudy)
lmList(Reaction ~ Days | Subject, offset=rep(100, nrow(sleepstudy)), sleepstudy)

Furthermore, under some circumstances lmList produces all NAs when, in fact, correct estimates are returned by both lm and lmList from nlme.

Simple Example:
x <- c(1,2,3,4,5,6,7,8)
y <- c(2,2,5,4,3,1,2,1)
g <- c(1,1,1,2,2,3,3,3)
dat <- data.frame(x=x, y=y, g=g)
lmList(y ~ x | g, data=dat)

**Output from lme4:lmList:**
Call: lmList(formula = y ~ x | g, data = dat) 
Coefficients:
  (Intercept)  x
1          NA NA
2          NA NA
3          NA NA
Degrees of freedom: 8 total; 2 residual
Residual standard error: 1.040833

**Output from nlme:lmList:**
Call:
  Model: y ~ x | g 
   Data: dat 
Coefficients:
    (Intercept)             x
1 -2.051160e-15  1.500000e+00
2  8.000000e+00 -1.000000e+00
3  1.333333e+00 -1.570092e-16
Degrees of freedom: 8 total; 2 residual
Residual standard error: 1.040833

**Comment by bbolker** [comment]
Second example is because `lme4::lmList` was assuming the grouping variable is a factor.  I *think* the rest is fixed in 69daaffb0562cb381 (but still needs better tests)

**Comment by kaYcee** [comment]
Hi Ben
thx for the quick fix! Unfortunately, predict(...) on an lmList-object now returns an error if provided with both the newdata(...) and the se.fit = TRUE parameters (which used to work before the fix was applied):

**Simple Example:**
x <- c(1,2,3,4,5,6,7,8)
y <- c(2,2,5,4,3,1,2,1)
g <- c(1,1,1,2,2,3,3,3)
dat <- data.frame(x=x, y=y, g=g)
lmList(y ~ x | g, data=dat) # working fine
lml <- lmList(y ~ x | g, offset = g, data=dat) # working fine too
predict(lml, se.fit = TRUE) # OK
predict(lml, newdata = data.frame(x = 3.5), se.fit = TRUE) # RETURNS ERROR

**Error Message:**
*Error in data.frame(fit = aux$fit, se.fit = aux$se.fit * poolSD/aux$res) : 
  arguments imply differing number of rows: 3, 1*

At first I thought it had to do with the offset param, but if left out in the model the following error is returned when calling predict:
*Error in structure(x@call[["formula"]], class = "formula") : 
       trying to get slot "call" from an object (class "lmList4") that is not an S4 object*

**Comment by bbolker** [comment]
That's a sort of weird example, because the data for `y` and `z` are missing from the data frame.  Is it really what you intended? If `m0` is the model without intercept, then  `predict(m0, se.fit=TRUE, newdata=data.frame(x=3.5,y=2,z=3))` works fine.

Also, `offset = g` (i.e. setting the offset equal to the grouping variable) is kind of strange ... it's rather difficult to refit with a different number of groups.

Can you clarify whether these reflect real use cases?  I agree that the error messages could be clearer, but I will invest more effort in fixing stuff that's causing an actual problem with your work ...

**Comment by kaYcee** [comment]
Hi Ben

thx again for your quick reply! Maybe I should have sticked to the sleepstudy example. So find here an adjusted version where I tried to perform the following steps:
1. One model per Subject, estimate both intercept and slope (lmList)
2. Pick particular Subject and fix the intercept, estimate slope (pure lm)
3. Repeat step 2, but this time for all Subjects (lmList)

```R
## try model with variable intercept
m3 <- lmList(Reaction ~ Days | Subject, sleepstudy)
summary(m3)
# now get predictions for 4 Days and each Subject
predict(m3, newdata = data.frame(Days = 4), data = sleepstudy) # OK, returns 18 items (1 per subject)
predict(m3, newdata = data.frame(Days = 4), data = sleepstudy, se.fit = TRUE) # OK

## pick particular Subject, say 308 and perform linear regression with fixed intercept of 200
sleepstudy.308 <- subset(sleepstudy, Subject==308)
sleepstudy.308$off <- rep(200, nrow(sleepstudy.308))
m308 <- lm(Reaction ~ Days - 1, offset = off, sleepstudy.308)
summary(m308)
# now get prediction for 4 Days
predict(m308, newdata = data.frame(Days = 4, off = 200), data = sleepstudy.308) # OK, returns 1 item
predict(m308, newdata = data.frame(Days = 4, off = 200), data = sleepstudy, se.fit = TRUE) # OK

## now try with all subjects
sleepstudy$off <- rep(200,nrow(sleepstudy))
m4 <- lmList(Reaction ~ Days - 1 | Subject, offset = off, sleepstudy) # OK
summary(m4)
# now get predictions for 4 Days and each Subject
predict(m4, newdata = data.frame(Days = 4, off = 200), data = sleepstudy) # BROKEN, returns 180 items now
predict(m4, newdata = data.frame(Days = 4, off = 200), data = sleepstudy, se.fit = TRUE) # FAILS
```

I understand from the R documentation on Fitting Linear Models (http://web.mit.edu/r_v3.0.1/lib/R/library/stats/html/lm.html) that predict.lm ignores the offset param so I have to add the intercept manually later on, which is fine. But for some reason predict together with lmList and offset returns much more values than expected.

**Comment by bbolker** [comment]
I'll have to take a look.  It's a little harder because we are at present just copying the `predict` method from `lmList`, so I'll have to dig in and see if/how we have to modify it (and why changing the code as I just did made the predictions fail;  do you know offhand if the example fails before I made the changes?).  The main problem is likely to be that `nlme`'s version of `lmList` doesn't (as far as I can see) handle offsets at all -- which makes sense as it was only designed for linear models, where it's easy to achieve the effect of offsets outside the model.

**Comment by kaYcee** [comment]
Just found a workaround. By using offset() inside the formula instead of using it as a parameter the predictions seem to work. With the formula-way your predict method works fine even in the currently available (unpatched) version (1.1-8):
```R
## now try with all subjects
sleepstudy$off <- rep(200,nrow(sleepstudy))
m5 <- lmList(Reaction ~ Days + offset(off) - 1 | Subject, sleepstudy) # OK
summary(m5)
# now get predictions for 4 Days and each Subject
predict(m5, newdata = data.frame(Days = 4, off = 200), data = sleepstudy) # OK, returns 18 items
predict(m5, newdata = data.frame(Days = 4, off = 200), data = sleepstudy, se.fit = TRUE) # OK
```

Although this workaround doesn't apply for the weights() param, the offset case can be handled fine. I noticed that even predict.lm treats offset() inside the formula and offset() as a parameter differently and returns a wrong number of predictions in the latter case, where it returns as many fitted values as there were offset-values specified, which is kinda weird.

**Comment by bbolker** [comment]
It would be nice to put a test in for now that stops with an error if someone tries to do predictions from a model with an `offset()` argument (to prevent weird answers as in your "BROKEN" example from being produced/propagating) ...

**Comment by jonbaron1944** [comment]
I have a weird example in which lmList seems to omit cases randomly. Data are in http://finzi.psych.upenn.edu/~baron/delete.me/data.csv.

Compare l1 and t1. I thought that this had something to do with na.action, which I cannot figure out how to use, but that does not seem to be the problem.

d1 <- read.csv("data.csv")

l1 <- coef(lmList(prop.invested~decision.num+confidence.lag|subj,d1))

t1 <- matrix(NA,108,3)
for (i in 1:108) {
  t1[i,] <- coef(lm(prop.invested~decision.num+confidence.lag,data=d1[d1$subj==i,]))
}
