### ISSUE TITLE
Invalid power in formula

### ISSUE THREAD

**Issue by tmalsburg** [lme4/lme4#323]
When I specify this formula

    y~(a+b+c)^1+(1|d) 

I got the following error:

    Error in terms.formula(formula, data = data) : invalid power in formula

Correct me if I'm wrong, but this used to work in earlier versions of lme4.  It's unfortunate that this has been removed because it was really useful.  It allowed the user to (temporarily) remove all interactions by just changing one number.  Removing this use of ^1 also breaks old code.  Can we please have it back? :-)

**Comment by bbolker** [comment]
Hmmm.  Are you sure/can you document that? I ask because this fails:

```
fm <- lm(Reaction~Days^1,sleepstudy)
## Error in terms.formula(formula, data = data) : invalid power in formula
```
and in general we're just using R's existing machinery to process formulae, so working around that could be hard.  Maybe this is something that changed in base R??

**Comment by tmalsburg** [comment]
Ha, I may have hallucinated that.  I'll check and raise the issue on r-devel if it did work at some point.  (Perhaps I'll do it even if it didn't work because I see no reason why such a formula should be invalid.)

**Comment by bbolker** [comment]
A little poking around at https://github.com/wch/r-source/commits/916c0ba510b59ae88a1e3ebe5d68bb63874049a4/src/library/stats/src/model.c suggests the relevant code entered `model.c` sometime around May 20 2012, although it may have migrated from another part of the code ...

**Comment by bbolker** [comment]
moved to `model.c` in SVN 59396:
```
r59396 | ripley | 2012-05-22 02:23:01 -0400 (Tue, 22 May 2012) | 1 line

migrate terms.formula to stats (again)
```
... but I'm not sure where it moved *from*.

**Comment by mmaechler** [comment]
Well, just trying on an old version, I've use  R 2.0.1 (2001)  and R 2.14.1 (2011)  and both give exactly the same error  
```
terms(z ~ (x+y)^1)
Error in terms.formula(z ~ (x + y)^1) : Invalid power in formula
```
-- so someone had thought '1' was an invalid power (no, I'm kidding: .. the error message comes later than where the problem happens)
... and if you are really  nit-picking you could also want that  ^0  worked ... and it does neither.

**Comment by tmalsburg** [comment]
@mmaechler thanks for checking -- and for reminding me that I have to work on my nitpicking skills ;-)
