### ISSUE TITLE
new: segmentation fault in profile(.)

### ISSUE THREAD

**Issue by mmaechler** [lme4/lme4#327]
It's in the example on the profile-methods  help page and is only run when  `lme4:::testLevel() > 1`.

@bbolker : Maybe set the environment variable in our Travis script ? 
--> ok, just done that now. 1bea42cc45c9cc

**Comment by bbolker** [comment]
Works for me (Ubuntu 12.04, 32-bit).  If this is related to https://github.com/lme4/lme4/issues/319 , I predict it will work OK on Travis (since #319-related tests succeed there).

**Comment by mmaechler** [comment]
​Wow.. what a cute old version ... is that a  docker file?

The reason I ​ made this an issue: I **always** run with  testlevel > 1... and hence for me this example has always run in the last couple of months, never segfaulted.  Now you have changed profile() slightly... my suspicion was that the seg.fault has been triggered by these changes..
This would be quite astonishing to me if related to #319.

**Comment by bbolker** [comment]
OK, more info is useful.  Will it be fairly easy for you to find/fix?

(12.04 works for me and I keep not wanting to take the energy to deal with the inevitable disruption of upgrading, although it is getting to be time ...)

**Comment by mmaechler** [comment]
It is intermittent... i.e. not systematically reproducible...
..
and no, even if it was deterministic I expect it would be hard to fix for me.. because I expect deep magic C++ allocating/freeing/pointers/...

As it is not easily reproducible, and Travis also does not "see" it, let's close it for now
