### ISSUE TITLE
Additional arguments to refit.merMod

### ISSUE THREAD

**Issue by pitakakariki** [lme4/lme4#342]
There appear to be a few problems with the additional argument handling in `refit`.

I'll use the first example from `?glmer` so this is easy to reproduce:

    gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
              data = cbpp, family = binomial)

First problem: the `verbose` argument seems to work, but it generates a warning:

    refit(gm1, verbose=3)

This will print out lots of info about the pwrssUpdate steps, but will also give the warning:

    Warning message:
    In refit.merMod(gm1, verbose = 3) :
      additional arguments to refit.merMod ignored

**Comment by pitakakariki** [comment]
Second problem: specifying both `control` and `verbose`.

This seems to work correctly. It fails to converge (because of the inappropriate `maxfun`), and has the correct verbosity.

    refit(gm1, control=glmerControl(optCtrl=list(maxfun=5)), verbose=3)

If you swap them around,

    refit(gm1, verbose=3, control=glmerControl(optCtrl=list(maxfun=5)))

then `verbose` still works but it looks like `control` is ignored. Same problem for example in

    refit(gm1, foo="bar", control=glmerControl(optCtrl=list(maxfun=5)))

i.e. it's not something special about `verbose`, it's `refit` expecting `control` to be the first `...` argument.

**Comment by pitakakariki** [comment]
One of the early `if` clauses is the following:

    if(ll <- length(l... <- list(...)) > 0) {

This is assigning `TRUE` or `FALSE` to `ll`, because the outer `<-` takes precedence over the `>` comparison. I think this clause was meant to be:

    if((ll <- length(l... <- list(...))) > 0) {

**Comment by mmaechler** [comment]
@pitakakariki : you are so right .. a bit embarrassing.. I've fixed at least that.. {and before pusing my commit, need to clean up git mess in my working directory}

**Comment by pitakakariki** [comment]
I don't have time to test this, but a fix for the rest might be to replace

    if (ll == 1L && names(l...)[1] == "control") {
        ctrl.arg <- l...$control
    }
    else {
        warning("additional arguments to refit.merMod ignored")
    }

with

    if("control" %in% names(l...)) ctrl.arg <- l...$control

    if(!all(names(l...) %in% c("control", "verbose"))) {
        warning("additional arguments to refit.merMod ignored")
    }
