### ISSUE TITLE
VarCorr generic has a very restrictive argument structure 

### ISSUE THREAD

**Issue by paul-buerkner** [lme4/lme4#347]
Due to the popularity of lme4, many R-users know the VarCorr method to extract the covariance structure of mixed models. Accordingly, other packages fitting mixed models may also want to include a VarCorr method for their fitted model objects.  

To avoid function masking, it makes sence to import the generic from lme4. Unfortunately, the argument structure of the VarCorr generic is currently very restrictive. In particular, it has no `...` argument that would allow to define new arguments for new methods. 

Do you think it is possible to extent the VarCorr generic by `...`, or even simplify it to `VarCorr(x, ...)`?

**Comment by bbolker** [comment]
This sounds like a good idea to me, but the `VarCorr` generic in lme4 is actually imported (and re-exported) from `nlme`, so I think this request would have to go to R-core (the maintainers of `nlme`) - @mmaechler might be able to comment on the most appropriate channel for the request.  (It's also been around for quite a long time (it's in the oldest version on CRAN - 3.1.1, from 1999), which may help explain why the authors weren't thinking quite as hard about future compatibility ...)

**Comment by mmaechler** [comment]
Sounds very reasonable to me.  I hope to get to it (adding `...` arg in `nlme`).  It has other changes and so a new release would make sense.

**Comment by paul-buerkner** [comment]
Thank you both for your quick responses!
