### ISSUE TITLE
lme4::sigma is still being exported in R-devel 3.3.0 when the binary package is installed

### ISSUE THREAD

**Issue by pitakakariki** [lme4/lme4#348]
This is happening when I install the 3.3 binary for `lme4_1.1-10` on Windows (7 and 8):

    > library(lme4)
    Loading required package: Matrix

    Attaching package: ‘lme4’

    The following object is masked from ‘package:stats’:

        sigma

This could cause problems for packages that import `sigma` from `stats`:

    > gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
    +               data = cbpp, family = binomial)
    > 
    > lme4::sigma(gm1)
    [1] 1
    > stats::sigma(gm1)
    [1] 1.15581

It works correctly when I install from source, either from CRAN or Github.

---

More details:

    > remove.packages("lme4")
    Removing package from ‘C:/Users/pete/Documents/R/win-library/3.3’
    (as ‘lib’ is unspecified)
    > install.packages("lme4")
    Installing package into ‘C:/Users/pete/Documents/R/win-library/3.3’
    (as ‘lib’ is unspecified)
    trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/lme4_1.1-10.zip'
    Content type 'application/zip' length 4787293 bytes (4.6 MB)
    downloaded 4.6 MB

    package ‘lme4’ successfully unpacked and MD5 sums checked

    The downloaded binary packages are in
	    C:\Users\pete\AppData\Local\Temp\RtmpoPGRew\downloaded_packages

    > lme4::sigma
    function (object, ...) 
    UseMethod("sigma")
    <environment: namespace:lme4>
    > getRversion()
    [1] ‘3.3.0’
    > sessionInfo()
    R Under development (unstable) (2016-01-12 r69936)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows >= 8 x64 (build 9200)

    locale:
    [1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252   
    [3] LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                        
    [5] LC_TIME=English_New Zealand.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    loaded via a namespace (and not attached):
     [1] minqa_1.2.4     MASS_7.3-45     Matrix_1.2-3    tools_3.3.0     Rcpp_0.12.3    
     [6] splines_3.3.0   nlme_3.1-122    grid_3.3.0      nloptr_1.0.4    lme4_1.1-10    
    [11] lattice_0.20-33

If I install from source it's fine!

    > remove.packages("lme4")
    Removing package from ‘C:/Users/pete/Documents/R/win-library/3.3’
    (as ‘lib’ is unspecified)
    > install.packages("lme4", type="source")
    Installing package into ‘C:/Users/pete/Documents/R/win-library/3.3’
    (as ‘lib’ is unspecified)
    trying URL 'https://cran.rstudio.com/src/contrib/lme4_1.1-10.tar.gz'
    Content type 'application/x-gzip' length 3687247 bytes (3.5 MB)
    downloaded 3.5 MB

    * installing *source* package 'lme4' ...
    ...
    * DONE (lme4)

    The downloaded source packages are in
    	‘C:\Users\pete\AppData\Local\Temp\Rtmp0MrgNh\downloaded_packages’
    > lme4::sigma
    Error: 'sigma' is not an exported object from 'namespace:lme4'
    > getRversion()
    [1] ‘3.3.0’
    > sessionInfo()
    R Under development (unstable) (2016-01-12 r69936)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows >= 8 x64 (build 9200)

    locale:
    [1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252   
    [3] LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                        
    [5] LC_TIME=English_New Zealand.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    loaded via a namespace (and not attached):
     [1] minqa_1.2.4     MASS_7.3-45     Matrix_1.2-3    tools_3.3.0     Rcpp_0.12.3    
     [6] splines_3.3.0   nlme_3.1-122    grid_3.3.0      nloptr_1.0.4    lme4_1.1-10    
    [11] lattice_0.20-33

**Comment by bbolker** [comment]
Interesting.  Seems this might be something to take this up with the CRAN maintainers - we don't have any control of the way the binaries are built (I'm assuming/guessing that it's something about the binary build process on CRAN, not just something odd/surprising about the binary build process itself). At the moment the only system I have R-devel installed on is Linux, so I can't easily check ...

**Comment by pitakakariki** [comment]
I just built the current github version in Windows 7 using `devtools` and R-devel. It works as expected, so this points to the CRAN build process I think?

I also tried the obviously wrong thing and built the binary package in R-3.2.3. Can confirm that this will cause `sigma` to be exported by `lme4` in R-devel.

**Comment by mmaechler** [comment]
So I think it is clear that this is not a bug in `lme4`, nor otherwise an issue we can do anything about
(are you sure there *are* R 3.3.x binary packages anywhere for you to download ??).  So I strongly suggest to close this issue.

**Comment by pitakakariki** [comment]
nb: there are binaries available at:

    https://cran.r-project.org/bin/windows/contrib/3.3/lme4_1.1-10.zip

**Comment by pitakakariki** [comment]
I'm guessing the issue will magically disappear when 3.3.0 is released, but do you mind if I email Uwe Ligges and get him to have a look at this? I can still send him a link to this issue if it's closed.

**Comment by bbolker** [comment]
I certainly don't mind.  It will save us the trouble ...

**Comment by pitakakariki** [comment]
Done, thanks.

**Comment by pitakakariki** [comment]
Problem solved.

> Simple to explain:
> 
> 
> So far the R-3.3.x repository is just a link to the 3.2.x repository.
> 
> Given you experience problems, it seems to be the right time to ship true 3.3.x binaries via CRAN.
> I just deleted the symlink and starting to rsync. I guess CRAN will have the right binary within a day or > two.
> 
> Please try again on Tuesday and report if the problem persists.
> 
> Best,
> Uwe Ligges

**Comment by mmaechler** [comment]
>>>>> Peter Green <notifications@github.com>
>>>>>     on Sun, 17 Jan 2016 14:41:16 -0800 writes:

    > Problem solved.

indeed, and I was right that there are no 3.3.x-built binaries.
