### ISSUE TITLE
Issue with the predict function of glmer

### ISSUE THREAD

**Issue by andrluis** [lme4/lme4#351]
I`m getting an error when running this example from the lme4 package pg. 85

(gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 |herd), cbpp, binomial))
    str(p0 <- predict(gm1))            # fitted values
    str(p1 <- predict(gm1,re.form=NA))  # fitted values, unconditional (level-0)
    newdata <- with(cbpp, expand.grid(period=unique(period), herd=unique(herd)))
    str(p2 <- predict(gm1,newdata))    # new data, all RE
    str(p3 <- predict(gm1,newdata,re.form=NA)) # new data, level-0
    str(p4 <- predict(gm1,newdata,re.form= ~(1|herd))) # explicitly specify RE
    stopifnot(identical(p2, p4))

Error:

Error in model.matrix(model$fixed, data = newdata, contrasts.arg = NULL) : 
  object 'model' not found
Called from: model.matrix(model$fixed, data = newdata, contrasts.arg = NULL)

I`m having the same issue to use the predict function in my own data.
Thanks.

Andre

**Comment by pitakakariki** [comment]
You might need to specify the version of `lme4` and R you're using (the code you've supplied runs fine for me).

Easiest way to do this is to use the output from `sessionInfo()`.

**Comment by bbolker** [comment]
In addition to @pitakakariki's advice, try this from a clean R session? (Use `R --vanilla` if possible)

**Comment by andrluis** [comment]
Hi Peter:

Unfortunately, I`m having the same problem.

My R version is:

R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

My lme4 version is:

lme4_1.1-10

What would you suggest to fix the problem?

Thanks,

Andre

**Comment by bbolker** [comment]
I can't reproduce with

R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

If we can't reproduce this it's going to be almost impossible to fix ... and I don't have a Yosemite machine or virtual machine handy. Just confirming, this is definitely run from a clean session?  What do you get with `find("model")` ? `find("model.matrix")` ?

**Comment by andrluis** [comment]
Hi Ben:

Yes, I restart R and run the example from lme4 documentation. However, got
the same errors.

For:
> find("model")
character(0)

For:

> find("model.matrix")
[1] "package:stats"

Thanks a million.

**Comment by bbolker** [comment]
OK, this is going to get harder now.  At which point do you get the error (i.e., there are 5 `predict()` statements in your example above. Do they all fail?  Which ones work?)  Does `example("predict.merMod")` work ?

Furthermore, I'm having trouble finding the offending code line in the current code base.  I can find "$fix":

```
bolker@xubuntu-VirtualBox:~/R/pkgs/lme4git/lme4/R$ grep "\$fix" *.R
lmer.R:        if (!is.null(start$fixef) && nAGQ==0)
lmer.R:            stop("should not specify both start$fixef and nAGQ==0")
modular.R:            noFixef <- is.null(start$fixef)
modular.R:                fixef <- start$fixef
```

but not "model$fix" ...

```
bolker@xubuntu-VirtualBox:~/R/pkgs/lme4git/lme4/R$ grep "model\$fix" *.R
``

**Comment by andrluis** [comment]
These examples are actually from predict.merMod. All the five failed.

The problem I`m finding is attached together with the example I`m running
using the lme4 example.

Thanks, Professor Bolker.

**Comment by andrluis** [comment]
Hey Folks:

Actually, it was a function I had created that was causing the problems. First, I run the same code in another mac with the same system and it was great! Then, I worked on my and found the function and fix it.
Now everything runs great!!!
Thanks a lot,

Andre
