### ISSUE TITLE
add library(lattice) to vignette appropriately, or re-export xyplot/qqmath/dotplot

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#355]
Spencer Graves e-mails to say that running the code from the vignette as it appears in the PDF (p. 33) doesn't work because lattice isn't already loaded.

  We can fix this by adding library(lattice) or (perhaps better?) re-exporting the relevant stuff from lattice ...

**Comment by mmaechler** [comment]
I'd prefer not re-exporting but adding a   ` require("lattice")`   (sic!)   to the vignette.  
Re-exporting is somewhat confusing to the user who does not easily find where the function is from
(and hence where the detailed docs are).
The vignette is for the user so should show what she is supposed to do

**Comment by bbolker** [comment]
OK.  (I sometimes find it a nuisance to remember to `require("lattice")` before doing diagnostic plots/ranef plots, but I see your point.)  Very much off-topic, but can you explain your preference for `require()` vs. `library()` or point to a discussion? (I don't have strong feelings at all; the only difference I can see is that `require()` returns a logical, but for lattice the value will be always be TRUE unless something is really messed up ...)

**Comment by bbolker** [comment]
Note connection to https://github.com/lme4/lme4/issues/337

**Comment by mmaechler** [comment]
- require(<package>)   to have more people stop using the word library for a package.
- the **invisible** return value is good idea (in general) because then
    `if((require(<pkg>)) { ... } `
then comes natural for the cases needed.
