### ISSUE TITLE
glmer model in R does not work

### ISSUE THREAD

**Issue by saudisadiq** [lme4/lme4#357]
I am analysing a dataset 'qaaf' (attached) using logistic regression analysis. 
The dataset includes:
1. speaker: participants in my study
2. item: words as used by my participants
3. realisation: the dependent variable (whether a speaker uses a CA or MA form). The target is achieved if CA is used (=1) and not so if MA (=0) is used.
4. gender: independent variable (2 levels: male and female)
5. age.group: independent variable (3 levels: young, middle-aged and old)
6. education: independent variable (3 levels: secondary or below, university and postgraduate)
7. residence: independent variable (3 levels: villager, migrant (to town) and urbanite)

I am testing whether my speakers use the CA form or not. This is the form of the prestigious dialect in Egypt. If they use MA, this means that they use their traditional dialect. I am trying to find out which factor (independent variable) is responsible or more reponsilbe for using the CA form. 
To run the model, I did some leveling as follows:

> attach(qaaf)
> qaaf$education = factor(education, levels=c("secondary or below", "university", "postgraduate"))
> qaaf$residence = factor(residence, levels=c('villager', 'migrant', 'urbanite'))
> qaaf$age.group = factor(age.group, levels=c('young', 'middle-aged', 'old'))

As the target is CA and this (alphabetically) takes the 0 value, I used this code:

< qaaf$convergence <- qaaf$realisation == 'CA'

to change the value of CA from 0 to 1.  Now the dependent variable is called 'convergence'. 
I installed and ran the following packages:
RcppEigen
Rcpp
minqa
lme4
After that, I ran the model:

< model1 <- glmer(convergence ~ gender + age.group + education + residence + 
                                        (1|item) + (1|speaker), data=qaaf,family='binomial')

This model, as you see, has four fixed variables (gender, age.group, education and residence) and two random factors (speaker and item).
Then, R gave me this warning message:

    Error in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, 
     : (converted from    warning) 
     Model failed to converge with max|grad| = 0.515371 (tol = 0.001, component 1)

When I used

< summary(model1)

I got the following results:

       Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) [
       glmerMod]
       Family: binomial  ( logit )
       Formula: convergence ~ gender + real.age + education + residence + (1 |  
       item) + (1 | speaker)
       Data: qaaf
       AIC      BIC   logLik deviance df.resid 
       932.4    989.2   -457.2    914.4     4055 
      Scaled residuals: 
       Min       1Q   Median       3Q      Max 
       -16.6678  -0.0234   0.0017   0.0109   1.7649 
      Random effects:
      Groups    Name          Variance     Std.Dev.
       item        (Intercept)    17.32           4.161   
       speaker   (Intercept)     76.97          8.773   
        Number of obs: 4064, groups:  item, 1309; speaker, 62
       Fixed effects:
                                           Estimate       Std. Error      z value     Pr(>|z|)    
        (Intercept)                     -7.14712      4.57435         -1.562      0.11819    
        gendermale                   0.09012       2.01552         0.045       0.96434    
        real.age                        -0.04892      0.07759         -0.631      0.52833    
        educationuniversity         6.55968      3.02740         2.167        0.03025 *  
        educationpostgraduate    8.76250      3.14421         2.787        0.00532 ** 
        residencemigrant             8.54280     3.75147         2.277        0.02277 *  
        residenceurbanite           11.69649     2.38945        4.895        9.83e-07 ***
        Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
         Correlation of Fixed Effects:
            (Intr) gndrml real.g edctnn edctnp rsdncm
         Model failed to converge with max|grad| = 0.812105 (tol = 0.001, component 1)

The results show that gender and age.group are not significant factors. To check their significance in interaction, I ran the following model:

< model2 <- glmer(convergence ~ gender*age.group +   (1|item) + 
                            (1|speaker),data=qaaf, family='binomial')

Model2  gave these results:

     Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
      Family: binomial  ( logit )
      Formula: convergence ~ gender * age.group + (1 | item) + (1 | speaker)
      Data: qaaf
      AIC      BIC   logLik deviance df.resid 
      958.2   1008.7   -471.1    942.2     4056 
     Scaled residuals: 
      Min       1Q   Median       3Q      Max 
    -17.1303  -0.0266   0.0013   0.0089   1.5898 
     Random effects:
     Groups      Name        Variance     Std.Dev.
     item           (Intercept)     20.8         4.561  
     speaker       (Intercept)     186.9       13.670  
     Number of obs: 4064, groups:  item, 1309; speaker, 62
     Fixed effects:
                                                          Estimate       Std. Error      z value        Pr(>|z|)    
     (Intercept)                                      10.895          1.583               6.883           5.87e-12 ***
     gendermale                                     -4.137          4.874               -0.849           0.3960    
     age.groupmiddle-aged                    -14.212         7.511                -1.892          0.0585 .  
     age.groupold                                  -1.880           6.339                 -0.297          0.7668    
     gendermale:age.groupmiddle-aged   16.104           8.911                 1.807            0.0707 .  
     gendermale:age.groupold                  -5.845         10.730                -0.545          0.5859    
    Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

My questions:
1. Can I trust the results in model 1 and report them even though there is a warning message?
2. Sometimes the warning message looks like

          Warning messages:
          1: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
           unable to evaluate scaled gradient
          2: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
         Model failed to converge: degenerate  Hessian with 2 negative eigenvalues

Can I report the results with such warning message as well?
2. Can I say that age.group is significant as it is in model2? And, in model2, what is the default level to which 'gendermale:age.groupmiddle-aged' is compared? Is 'middle-aged female' the default?
3. What is the best way to plot the results in the two models?

**Comment by bbolker** [comment]
This is not really a good venue for general modeling/use-of-`lme4` questions, rather for bug reports and development issues.  Can you please forward your question to `r-sig-mixed-models@r-project.org`?  (The data set was not attached; it's probably best to post it to some public site, as attachments are often dropped by mailing list/forum software.)  Have you looked at `?convergence`?  (Hint: you almost certainly have *complete separation* in your data.)
