### ISSUE TITLE
confint Chooses Different Parameters for Different Methods

### ISSUE THREAD

**Issue by billdenney** [lme4/lme4#358]
I have constructed a lmer model with two levels of nested of random effects, one residual effect, and two fixed effects.

The model generally looks like:

    mymodel <- lmer(Y~X+(1|A/B), data=mydata)

When I run confint on that model selecting which parameter to extract, the parameter selected by number differs when I choose different confidence interval methods.

    confint(mymodel, parm=1, method="profile")

Chooses the random effect A.  parm=2 chooses B; parm=3 chooses the residual error; parm=4 chooses "(Intercept)", and parm=5 chooses X.

    confint(mymodel, parm=1, method="Wald")

Chooses the "(Intercept)".  parm=2 chooses X; parm=3 gives a subscript out of bounds error.

I understand that Wald may not calculate intervals for the random effects and residual error, but it seems like all methods should choose parameter numbers in the same order (perhaps fixed then random then residual).

**Comment by bbolker** [comment]
Hmm.  What version are you running?  With latest CRAN version (1.1-11), all of this seems to work fine.

```
dd <- data.frame(X=runif(1000),
                     A=factor(rep(1:20,each=50)),
                     B=factor(rep(1:25,40)))
library("lme4")
dd$Y <- simulate(~X+(1|A/B), newdata=dd,
                     family=gaussian(),
                     newparams=list(beta=c(1,1),theta=c(1,2),
                                    sigma=1),seed=101)[[1]]
m1 <- lmer(Y~X+(1|A/B),dd)                     
confint(m1,parm=1,method="Wald")
##        2.5 % 97.5 %
## .sig01    NA     NA
confint(m1,parm=1,method="profile")
##            2.5 %   97.5 %
## .sig01 0.8510785 1.059326
confint(m1,parm=3,method="Wald")
##        2.5 % 97.5 %
## .sigma    NA     NA
confint(m1,parm=3,method="profile")
##            2.5 %   97.5 %
## .sigma 0.9883914 1.119038
```

**Comment by billdenney** [comment]
I'm using version 1.1-7.

Given your output, my issues appears to be fixed between these two versions.  Thanks for checking it, and I'll close the issue.
