### ISSUE TITLE
note on build about 'family' in lme4 and MatrixModels

### ISSUE THREAD

**Issue by vnijs** [lme4/lme4#360]
FYI with lme4 (1.1-10) and MatrixModels (0.4-1) I'm seeing the following note:

Note: the specification for S3 class “family” in package ‘MatrixModels’ seems equivalent to one from package ‘lme4’: not turning on duplicate class definitions for this class.

**Comment by bbolker** [comment]
This seems harmless, but it's worth checking. @mmaechler , do you have a suggestion on how to structure things to avoid this?  Could it be fixed on the `lme4` side, the `MatrixModels` side, or does it lie somewhere in between?

**Comment by bbolker** [comment]
I can't repliicate this with MatrixModels 0.4-1 and development `lme4` (although both `MatrixModels` and `lme4` do export `mkRespMod` functions ...)

**Comment by vnijs** [comment]
The message does seem to have disappeared. Thanks.
