### ISSUE TITLE
Error loading package lme4

### ISSUE THREAD

**Issue by Deretz04** [lme4/lme4#367]
When loading lme4 package using R or R Studio, I get the following error message:
Loading required package: Matrix
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘nlme’ 3.1-122 is already loaded, but >= 3.1.123 is required
Error: package or namespace load failed for ‘lme4’
I have tried updating packages, even uninstalled and reinstalled r and R Studio. Still get the same message after installing new R.

**Comment by bbolker** [comment]
Can you be a little more specific about what you've done?  What mirror are you using, what version of R do you have? In particular, if you open a clean R session and run 
```
options(repos="https://cran.rstudio.com")
a1 <- available.packages()
a1[a1[,"Package"]=="nlme",]
sessionInfo()
```
what do you get?

Just guessing, but there *might* be an issue with `update.packages()` if it is for some reason (e.g. you're installing R as administrator but running it is a non-admin user) with updating system packages rather than user-installed packages ...

Since this is the second query we've had about `nlme` versions, it seems like this might turn into a FAQ ...

**Comment by Deretz04** [comment]
This is the output I get when I paste your code into a new R session. 
 options(repos="https://cran.rstudio.com")
> a1 <- available.packages()
> a1[a1[,"Package"]=="nlme",]
                               Package                                Version 
                                "nlme"                              "3.1-124" 
                              Priority                                Depends 
                         "recommended"        "graphics, stats, R (>= 3.0.2)" 
                               Imports                              LinkingTo 
                      "utils, lattice"                                     NA 
                              Suggests                               Enhances 
                         "Hmisc, MASS"                                     NA 
                               License                        License_is_FOSS 
                          "GPL (>= 2)"                                     NA 
                 License_restricts_use                                OS_type 
                                    NA                                     NA 
                                 Archs                                 MD5sum 
                                    NA                                     NA 
                      NeedsCompilation                                   File 
                                 "yes"                                     NA 
                            Repository 
"https://cran.rstudio.com/src/contrib" 
> sessionInfo()
I see it is showing nlme version 3.1-124. Why then, am I still getting the error message showing "...3.1-122 is already loaded"? I have been using the Revolution Analytics mirror in Dallas, TX.

**Comment by bbolker** [comment]
OK, try this: 

- start a *clean* R session (`R --vanilla` if possible, or unselect "Restore .RData into workspace at startup" in Tools/Global Options, or delete/temporarily remove any `.RData` file in your working directory).

```
sessionInfo()  ## see if you have a *clean* session (your session above isn't clean, it has non-default
                       ## packages loaded)
packageVersion("nlme")
sapply(.libPaths(),packageVersion,pkg="nlme")  ## see if you have multiple versions installed
require("lme4")
```

And let us know what happens.

This seems to be more of an R-configuration than a specifically `lme4`-related issue, but again, if it's going to be a FAQ then it's worth trying to sort out what's going on ...

**Comment by Deretz04** [comment]
I think you have pinpointed the problem...
sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.3
> packageVersion("nlme")
[1] ‘3.1.124’
> sapply(.libPaths(),packageVersion,pkg="nlme")  ## see if you have multiple versions installed
$`C:/Users/Heath/Documents/R/win-library/3.2`
[1]   3   1 124

$`C:/Program Files/R/R-3.2.3/library`
[1]   3   1 122

> require("lme4")
Loading required package: lme4
Loading required package: Matrix
I am no longer getting the error message when I load lme4. Should I delete the source folder that R was pulling version 3.1-122 from, or just leave it since it is working now? I'm not sure why I have two versions of "nlme" saved in two different locations. Thanks for your help!

**Comment by bbolker** [comment]
try `install.packages("nlme",lib=.libPaths()[2])`.  Don't delete the source folder -- it contains all of your base R packages!
