### ISSUE TITLE
Afex or car ANOVA models vs lme4?. Observed variables

### ISSUE THREAD

**Issue by skanskan** [lme4/lme4#378]
Hello.

I don't know if this is the proper place to ask this 
just in case, I've also posted my question here

> https://stackoverflow.com/questions/37102075/how-to-convert-afex-or-car-anova-models-to-lmer-observed-variables

but nobody replies.

In the afex package we can find this example of ANOVA analysis:
data(obk.long, package = "afex")
# estimate mixed ANOVA on the full design:
# can be written in any of these ways: 

```
aov_car(value ~ treatment * gender + Error(id/(phase*hour)), data = obk.long,
        observed = "gender")

aov_4(value ~ treatment * gender + (phase*hour|id), data = obk.long,
        observed = "gender")

aov_ez("id", "value", obk.long, between = c("treatment", "gender"), 
       within = c("phase", "hour"), observed = "gender")
```

My question is, How can I write the same model in lme4? In particular, I don't know how to include the "observed" term?

If I just write
```
lmer(value ~ treatment * gender + (phase*hour|id), data = obk.long,
     observed = "gender")
```
I get an error telling that observed is not a valid option.

Furthermore, if I just remove the observed option lmer produces the error:
`Error: number of observations (=240) <= number of random effects (=240) for term (phase * hour | id); the random-effects parameters and the residual variance (or scale parameter) are probably unidentifiable.`

Where in the lmer syntax do I specify the "between" or "within" variable?. As far as I know you just write the dependent variable on the left side and all other variables on the right side, and the error term as (1|id).

The package "car" uses the idata for the intra-subject variable.

**Comment by bbolker** [comment]
This isn't really the right place; I've [answered it on StackOverflow](http://stackoverflow.com/questions/37102075/how-to-convert-afex-or-car-anova-models-to-lmer-observed-variables). Perhaps we should spell it out somewhere:

- StackOverflow, [CrossValidated](http://stats,stackexchange.com), or `r-sig-mixed-models@r-project.org` for general "how do I? what does this mean?" questions
- this issues list for bugs, presumptive bugs, infelicities, wish-list items
- e-mail to lme4 authors (i.e. results of `maintainer("lme4")`) for specific, private queries [previous two venues preferred whenever possible]
