### ISSUE TITLE
lmList issue with NA values

### ISSUE THREAD

**Issue by EricBrooks2** [lme4/lme4#382]
lmList has unexpected behavior when the data contains other columns that are not being used. It seems as if what might be occurring is that it's running the na.action on the entire data frame in the beginning. Compare:

    mtcars$yvar <- mtcars$mpg > 19
    lmList(yvar ~ hp | vs, family=binomial, mtcars)
to

    mtcars$yvar <- mtcars$mpg > 19
    mtcars$nacolumn <- NA
    lmList(yvar ~ hp | vs, family=binomial, mtcars)

**Comment by bbolker** [comment]
Hmm, I can't replicate.  

```
R Under development (unstable) (2016-04-14 r70486)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lme4_1.1-13  Matrix_1.2-5

loaded via a namespace (and not attached):
 [1] minqa_1.2.4     MASS_7.3-45     compiler_3.4.0  tools_3.4.0    
 [5] Rcpp_0.12.4     splines_3.4.0   nlme_3.1-127    grid_3.4.0     
 [9] nloptr_1.0.4    lattice_0.20-33
```

**Comment by EricBrooks2** [comment]
Ok, I looked further and the problem is entirely mine (I was using the wrong version of R). It's all fine now. Thanks.
