### ISSUE TITLE
libz.a: No such file or directory - when try to install lme4

### ISSUE THREAD

**Issue by LMtx** [lme4/lme4#383]
Hello,

When I try to install lme4 package:
> install.packages("lme4")

R tries to install dependencies:
> also installing the dependencies ‘minqa’, ‘RcppEigen’

but that installation fail:

> gfortran -m64   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/lib64/gfortran/modules  -c updatebobyqa.f -o updatebobyqa.o
g++ -m64 -shared -L/usr/lib64/R/lib -ldl -lpthread -lc -lrt -lcurl -lidn -lssh2 -lssh2 -lssl -lcrypto -lssl -lcrypto -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lldap -lz -lrt -o minqa.so altmov.o bigden.o biglag.o bobyqa.o bobyqb.o lagmax.o minqa.o newuoa.o newuob.o prelim.o rescue.o trsapp.o trsbox.o trstep.o uobyqa.o uobyqb.o update.o updatebobyqa.o -ldl -lpthread -lrt /builddir/build/BUILD/R-3.3.0/zlib-1.2.8/target/usr/lib64/libz.a /builddir/build/BUILD/R-3.3.0/bzip2-1.0.6/target/usr/lib64/libbz2.a /builddir/build/BUILD/R-3.3.0/xz-5.2.2/target/usr/lib64/liblzma.a /builddir/build/BUILD/R-3.3.0/pcre-8.38/target/usr/lib64/libpcre.a /builddir/build/BUILD/R-3.3.0/curl-7.48.0/target/usr/lib64/libcurl.a -lcurl -lidn -lssh2 -lssl -lcrypto -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lldap -lz -lgfortran -lm -L/usr/lib64/R/lib -lR
g++: /builddir/build/BUILD/R-3.3.0/zlib-1.2.8/target/usr/lib64/libz.a: No such file or directory
g++: /builddir/build/BUILD/R-3.3.0/bzip2-1.0.6/target/usr/lib64/libbz2.a: No such file or directory
g++: /builddir/build/BUILD/R-3.3.0/xz-5.2.2/target/usr/lib64/liblzma.a: No such file or directory
g++: /builddir/build/BUILD/R-3.3.0/pcre-8.38/target/usr/lib64/libpcre.a: No such file or directory
g++: /builddir/build/BUILD/R-3.3.0/curl-7.48.0/target/usr/lib64/libcurl.a: No such file or directory
make: *** [minqa.so] Error 1 

I am aware that it is not strictly lme4 issue but I could not find any help at google. Any help/ideas are welcome :)

**Comment by bbolker** [comment]
some googling makes it look like the same as these issues: are you on CentOS?

- https://www.centos.org/forums/viewtopic.php?t=58067
- http://stackoverflow.com/questions/37432130/error-installing-hmisc-in-r-3-3-0-on-centos-6-7

**Comment by LMtx** [comment]
Yes, that is centos but I would rather not use that kind of solution on a production server.

Thanks for your input!

**Comment by bbolker** [comment]
Since I think your problem is basically a CentOS/R 3.3.0 configuration issue and not an lme4 issue (note that you ran into problems installing minqa, not lme4 itself), I'm going to close this; I suggest that you follow up on StackOverflow, or a CentOS forum/mailing list, or possibly the `r-devel@r-project.org` mailing list.  R has never been super-kind about compatibility with older production versions of OSs; one alternative you could try would be downgrading to an earlier version of R in order to build the binaries (I don't think any of the dependencies in the lme4 toolchain *require* 3.3.0 ...

Good luck.

**Comment by LMtx** [comment]
Thanks for updated answer - that looks like more proper solution.
