### ISSUE TITLE
Error when trying to use `fortify`: Replacement has different number of rows from data

### ISSUE THREAD

**Issue by thvasilo** [lme4/lme4#390]
I'm building a model on a subset of a `data.table` in a manner similar like this:

```
library(caret)
library(data.table)
user_sample <- fread('mydata.csv', **various args**)
trainIndex <- createDataPartition(user_sample$id,
                                  p = .8,
                                  list = FALSE,
                                  times = 1)

trainSample <-  user_sample[trainIndex,]
testSample <-  user_sample[!trainIndex,]

me_model <- lmer(dependent ~ feat1 +  feat2 + feat3 + (1 | id), data = trainSample)
```

When I then try to run `fortify` to reproduce the diagnostic plots with `ggplot2` I get the following error:

```
 mef <- fortify.merMod(me_model, id=0.05)
Error in `$<-.data.frame`(x, name, value) : 
  replacement has 440016 rows, data has 441696
```

Any idea what might be causing this?

EDIT: Some of the predictors could include NA values as well, maybe that is the cause?

**Comment by bbolker** [comment]
`NA`s would indeed be my guess.  Along with the rest of the hadley/tidyverse, I've been moving away from fortify toward the tools in the `broom` package, `augment` in this case -- I should test that out and see if it's robust (and if so, deprecate `fortify.merMod` ...)

**Comment by thvasilo** [comment]
Hello, @bbolker, thanks for the quick reply.

I've tried removing all the NAs, but still get a similar error:

```
# feat3 was the only one with NAs
user_clean <- user_sample[is.finite(rowSums(user_sample[,.(feat3)]))]
assertthat::assert_that(sum(is.na(user_clean) == 0)

# Use user_clean instead of user_sample...
```

I'll try out `augment` from `broom`.

What I'm looking to do is extract some info from the model in order to plot the residuals (similar to what `plot.merMor` does) but color the data by level (`id` in my case).

I was hoping to achieve that through `ggplot2`. Any suggestion on how I might do that? I have too many levels to do a facet plot.
