### ISSUE TITLE
error when calling lmer within another function using ellipsis (For error catching)

### ISSUE THREAD

**Issue by dealeyj** [lme4/lme4#391]
I have a function created called factory that returns warnings and errors as well as the call, and am using this with the lmer function. When running on R3.2.2 and lme4 1.1-9 the function works fine, but when upgrading to R3.3.1 and lme4 1.1-12 the function stops working.

I've narrowed the issue down to the checkFormulaData function, and within that the missDataFun. This function is new somewhere between 1.1-9 and 1.1-12.

The function returns ex=..2 referring to the second call in the factory function, rather than the ..2 call itself.
Reproducible example below. Apologies if this is not technically an issue with lmer, but an issue with my function. Please close and I will post to stackoverflow to make more general.

Debugs are required in the following order once inside the lmer function
```
debug(lmer)
debug(lFormula)
debug(checkFormulaData)
debug(missDataFun)
```

```
library(lme4)
df<-data.frame(region=c(rep("A",4),rep("B",4)),depVar=c(10,15,12,10,30,24,20,24),var1=c(1,2,3,4,1,2,3,4),var2=c(0,0,1,1,0,0,1,1))

factory <- function(fun,...){
  warn <- err <- NULL
  res <- withCallingHandlers(
    tryCatch(fun(...), error=function(e) {
      err <<- conditionMessage(e)
      NULL
    }), warning=function(w) {
      warn <<- append(warn, conditionMessage(w))
      invokeRestart("muffleWarning")
    })
  return(list(res, warn=warn, err=err))
}

lmer(depVar~var1+(var2|region),data=df) #this works fine
factory(lmer,formula=depVar~var1+(var2|region),data=eval(df)) #this returns an error about not being able to find the dataset

```

**Comment by dealeyj** [comment]
partly solved by using a do.call function. Unfortunately the data then comes out in the summary and could potentially write a lot of lines

```
factory <- function(fun,...){
  ellipsis<-list(...)
  warn <- err <- NULL
  res <- withCallingHandlers(
    tryCatch(do.call(fun,ellipsis), error=function(e) {
      err <<- conditionMessage(e)
    }), warning=function(w) {
      warn <<- append(warn, conditionMessage(w))
      invokeRestart("muffleWarning")
    })
  return(list(res, warn=warn, err=err))
}
```

**Comment by bbolker** [comment]
you can potentially hack around the second problem by modifying the @call slot ...
