### ISSUE TITLE
glmer.nb; na.action=na.exclude

### ISSUE THREAD

**Issue by Ratana2712** [lme4/lme4#399]
Hi, I'm new to glmer.nb, as well as glm or lme.......... 
I'm trying to fit the mixed effects negative binomial from the data with missing values label as NA. 
At first I fit the model with na.action=na.omit, it work fine. Then I want to plot residuals with explain variable (in order to go to next step with auto-correlate and spatial correlate), but it doesn't work due to the difference length between residuals and variable. 
I try to fit the same model but with na.action=na.exclude that I hope to get the full length of residuals, but na.exclude option doesn't work!
Below is the example of model fitting with error message:
BT.f1 <- formula(BT~ Pool+(1|fWH.ID))
BT1 <- glmer.nb(BT.f1, offset=WH.data$Trapnights,
	na.action=na.exclude, data=WH.data)
**Error in while ((it <- it + 1) < limit && abs(del) > eps) { : 
  missing value where TRUE/FALSE needed**

Thanks,
Ratana

**Comment by bbolker** [comment]
Reproducible example:

```
set.seed(101)
dd <- data.frame(BT=rnbinom(500,mu=5,size=2),
                 Pool=rnorm(500),
                 fWH.ID=sample(20,size=500,replace=TRUE),
                 Trapnights=sample(5,size=500,replace=TRUE))
dd$Pool[sample(500,5)] <- NA
library(lme4)
m1 <- glmer.nb(BT~Pool+(1|fWH.ID),offset=dd$Trapnights,
               na.action=na.exclude,data=dd)
```

**Comment by bbolker** [comment]
thanks for the bug report, I think this should be fixed now in the development version
