### ISSUE TITLE
Potentially confusing behaviour for simulate.formula with binomial models.

### ISSUE THREAD

**Issue by pitakakariki** [lme4/lme4#400]
This is some of the example code from `?simulate.merMod`.

```
gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
             data = cbpp, family = binomial)

params <- list(theta=0.5,beta=c(2,-1,-2,-3))
simdat <- with(cbpp,expand.grid(herd=levels(herd),period=factor(1:4)))
simdat$size <- 15
simdat$incidence <- sample(0:1,size=nrow(simdat),replace=TRUE)

form <- formula(gm1)[-2]

simulate(form,newdata=simdat,family=binomial,
    newparams=params)[[1]]
# theta parameter vector not named: assuming same order as internal vector
# beta parameter vector not named: assuming same order as internal vector
#  [1] 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 0 1 0 1
[56] 0 0 0 1 0
```

It's simulating from a Bernoulli, and there's not really any way for it to know anything else was intended. But it looks like something the example was meant to produce something more like:

```
simulate(gm1)
#    sim_1.incidence sim_1.V2
# 1                0       14
# 2                1       11
# 3                0        9
# 4                0        5
# 5                2       20
# 6                2       16
# 7                2       19
# ...
```

Note that the following doesn't work though:

```
simulate(cbind(incidence, size - incidence)  ~ period + (1 | herd),
             newdata=simdat, family=binomial, newparams=params)[[1]]
# theta parameter vector not named: assuming same order as internal vector
# beta parameter vector not named: assuming same order as internal vector
#       incidence  
#  [1,]         1 0
#  [2,]         1 0
#  [3,]         0 1
#  [4,]         1 0
#  [5,]         1 0
```

This does, but it's a little bit clunky with the `simdat$size`:

```
simulate(cbind(incidence, size - incidence) ~ period + (1 | herd),
             newdata=simdat, family=binomial, newparams=params, weights=simdat$size)[[1]]
# theta parameter vector not named: assuming same order as internal vector
# beta parameter vector not named: assuming same order as internal vector
#       incidence   
#  [1,]        11  4
#  [2,]        14  1
#  [3,]        11  4
#  [4,]        14  1
#  [5,]        13  2
```

Would it make more sense for `simulate.formula` to populate weights based on the row sums of the response?

**Comment by pitakakariki** [comment]
I think this is just a 2-line change. In `binomial_simfun`:

```
Y <- rbinom(n, size = wts, prob = ftd)
YY <- cbind(Y, wts - Y)
```

becomes:

```
Y <- rbinom(n, size = rowSums(y), prob = ftd)
YY <- cbind(Y, rowSums(y) - Y)
```

**Comment by pitakakariki** [comment]
Spoke too soon, that change works but breaks some other stuff. If people think the change is worthwhile I'll try to track down those breakages.

**Comment by bbolker** [comment]
it might be worth it.  I have to admit that I've always found the two-column-matrix approach to binomial models clunky; in some ways I'd rather have a consistent framework that gave a fractional value corresponding to the right weights.  Maybe spend not-too-long seeing if there's an easy way to make everything work?

**Comment by pitakakariki** [comment]
Ah, my change will override whatever the user specifies in the `weights` argument.

Looks like there won't be an easy way to fix that. At the moment I don't think there's any way for `binomial_simfun` to tell if `wts` came from the user or was populated by `.simulateFun`.

**Comment by mmaechler** [comment]
Indeed, @pitakakariki .  And this confusion/amibiguity about what 'weightis` can mean is  the reason why I, contrary to @bbolker , have never liked to use weights for binomial glm(m)s, but would always have referred the two-column-matrix approach which leaves no ambiguity (and also allows other weights to be specified, e.g., in some robustness re-weighting schemes.          Assuming that  `simulate.formula` work with binomial weights - as the current implementation - therefore is "dangerous" for people like me (and Peter Green) who'd prefer the un-amibiguous 2-column form.

**Comment by pitakakariki** [comment]
I figure this can be closed now?
