### ISSUE TITLE
rules formula creation 

### ISSUE THREAD

**Issue by Sandy4321** [lme4/lme4#405]
pls help find rules for formula creation
for example I try to understand this 
m = lmer(WPM ~ Keyboard * Posture + (1|Keyboard:Posture:Trial) + (1|Subject), data=mbltxttrials)

or

m = lmer(WPM ~ (Keyboard * Posture)/Trial  + (1|Subject), data=mbltxttrials) 
it is from week 9 
https://www.coursera.org/learn/designexperiments/home/week/9
from 
Designing, Running, and Analyzing Experiments
by University of California, San Diego

**Comment by bbolker** [comment]
Could you please subscribe to r-sig-mixed models (at https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models ) and post this question there?
