### ISSUE TITLE
Can't pass a function to lmerControl optimizer

### ISSUE THREAD

**Issue by pitakakariki** [lme4/lme4#408]
The line `if (control$optimizer=="none")` will error if `optimizer` is a function rather than a string.

This can be a problem if the function you want to pass isn't exported from your namespace.

I think this would work as intended if the `==` were replaced with `identical(control$optimizer, "none")`.

**Comment by pitakakariki** [comment]
I have a workaround, but it's really ugly and involves overloading the `==` function.

**Comment by bbolker** [comment]
Huh.  Is this option even documented anywhere??   If not, could we make `NULL` be the way to specify no optimization? Then we could say `if(length(

**Comment by bbolker** [comment]
Huh.  Is this option even documented anywhere? (I don't remember adding it ...)   If not, could we make `NULL` be the way to specify no optimization? Then we could say `if (length(control$optimizer)==0) ...`

**Comment by pitakakariki** [comment]
I only knew about it because my code tripped the error.

**Comment by pitakakariki** [comment]
Still got a `browser()` call left in there.

**Comment by bbolker** [comment]
ooops.

**Comment by bbolker** [comment]
Pretty sure this is fixed now.
