### ISSUE TITLE
Fit a linear mixed model with only 1 group

### ISSUE THREAD

**Issue by PMassicotte** [lme4/lme4#411]
Dear Ben. This is a follow up regarding the discussion we had over stackoverflow (<http://stackoverflow.com/questions/39718754/fixing-variance-values-in-lme4>). If you remember, you helped us (my collegue @JacobCarstensen and I) to fit a `lme()` model where we wanted to fix in advance the variance values. You proposed a solution that worked fine (see bellow).

``` r
library(lme4)
#> Loading required package: Matrix
set.seed(101)
ss <- sleepstudy[sample(nrow(sleepstudy), size = round(0.9 * nrow(sleepstudy))), 
  ]
m1 <- lmer(Reaction ~ Days + (1 | Subject) + (0 + Days | Subject), ss)

summary(m1)
#> Linear mixed model fit by REML ['lmerMod']
#> Formula: Reaction ~ Days + (1 | Subject) + (0 + Days | Subject)
#>    Data: ss
#> 
#> REML criterion at convergence: 1580.8
#> 
#> Scaled residuals: 
#>     Min      1Q  Median      3Q     Max 
#> -3.8827 -0.4678  0.0175  0.4966  4.9724 
#> 
#> Random effects:
#>  Groups    Name        Variance Std.Dev.
#>  Subject   (Intercept) 703.38   26.521  
#>  Subject.1 Days         35.34    5.945  
#>  Residual              687.02   26.211  
#> Number of obs: 162, groups:  Subject, 18
#> 
#> Fixed effects:
#>             Estimate Std. Error t value
#> (Intercept)  251.552      7.324   34.35
#> Days          10.379      1.573    6.60
#> 
#> Correlation of Fixed Effects:
#>      (Intr)
#> Days -0.199

fixef(m1)
#> (Intercept)        Days 
#>   251.55172    10.37874

dd <- as.function(m1)

ff <- dd(c(0, 0))

opt <- list(par = c(0, 0), fval = ff, conv = 0)

lmod <- lFormula(Reaction ~ Days + (1 | Subject) + (0 + Days | Subject), ss)

m1X <- mkMerMod(environment(dd), opt, lmod$reTrms, fr = lmod$fr, mc = quote(hacked_lmer()))


buildMM <- function(theta) {
  
  dd <- as.function(m1)
  
  ff <- dd(theta)
  
  opt <- list(par = c(0, 0), fval = ff, conv = 0)
  
  mm <- mkMerMod(environment(dd), opt, lmod$reTrms, fr = lmod$fr, mc = quote(hacked_lmer()))
  
  return(mm)
}

objfun <- function(x, target = c(700, 30)) {
  
  mm <- buildMM(sqrt(x))
  
  return(sum((unlist(VarCorr(mm)) - target)^2))
}
```

Fix variances to 700 and 30.

``` r
s0 <- c(700, 30)/sigma(m1)^2

opt <- optim(fn = objfun, par = s0)
#> Warning in sqrt(x): NaNs produced

mm_final <- buildMM(sqrt(opt$par))
```

This works fine!

``` r
summary(mm_final)
#> Linear mixed model fit by REML ['lmerMod']
#> 
#> REML criterion at convergence: 1581
#> 
#> Scaled residuals: 
#>     Min      1Q  Median      3Q     Max 
#> -3.8453 -0.4798  0.0206  0.4994  4.9268 
#> 
#> Random effects:
#>  Groups    Name        Variance Std.Dev.
#>  Subject   (Intercept) 700      26.458  
#>  Subject.1 Days         30       5.477  
#>  Residual              700      26.458  
#> Number of obs: 162, groups:  Subject, 18
#> 
#> Fixed effects:
#>             Estimate Std. Error t value
#> (Intercept)  251.580      7.330   34.32
#> Days          10.378      1.479    7.02
#> 
#> Correlation of Fixed Effects:
#>      (Intr)
#> Days -0.215
```

Now, we are wondering if it possible to force a lmer model with random effect to be fitted on data with only one level? We want to do this to keep the same model structure in rare case where our data only contains 1 grouping level. In a previous step, we manually fix variance of the random effects, hence we do not need to estimate it. To be clearer, the objective is not to estimate the variance components of the mixed model, but to estimate how pre-specified variances for a number of random factors affect the standard error of a mean value. For example, if Y = μ + A + B + C + ε and we know (from other analyses) `V[A]`, `V[B]`, `V[C]` and `V[ε]` then what is the variance of our estimate of μ when estimated from a data set that also contains information on the levels of the random factors A, B and C? Hopefully, there is an easy way with `lmer()` or at least getting the design matrix for the random factors out so that the covariance structure for all the random components can be calculated. For information, this can be done easily in SAS with the hold-option to the parms statement in PROC MIXED, but apparently this is not as easily done in lmer().

``` r
ss2 <- subset(ss, Subject == 308)
m2 <- lmer(Reaction ~ Days + (1 | Subject) + (0 + Days | Subject), ss2)
#> Error: grouping factors must have > 1 sampled level
```

With regards,
Philippe

**Comment by bbolker** [comment]
Without spending too much time thinking about it: (1) errors like this can be overridden: see `?lmerControl` (specifically `control=lmerControl(check.nlev.gtr.1="ignore")`) (2) you can get the random-effects design matrix out via `getME(<fitted_model>,"Z")` ... do those comments solve your problem?

**Comment by PMassicotte** [comment]
@bbolker I will explore your ideas tomorrow and close the issue if it (hopefully) fixes it!

**Comment by PMassicotte** [comment]
Thank oyu @bbolker for your assistance. `control=lmerControl(check.nlev.gtr.1 = "ignore")` was indeed what we needed.

One more question if you allow me. Using the above code, we fix in advance variances. Is it also possible to fix the `Residuals` variance?

**Comment by bbolker** [comment]
It's difficult to fix residual variance in lme4.  I think you can use the blme package (a thin Bayesian wrapper around lme4) to constrain residual variance by putting a point prior on it. This has been discussed on `r-sig-mixed-models@r-project.org` under the topic of fixing residual variance to zero (which can't be done, but residual variance *can* be fixed to be very small): see e.g. [here](https://stat.ethz.ch/pipermail/r-sig-mixed-models/2014q1/021655.html)

**Comment by PMassicotte** [comment]
Thank you for your assistance and keep up the good job.

**Comment by robin-in-thenorth** [comment]
Great I have been wondering how to do this!
Isnt the following line redundant:
m1X <- mkMerMod(environment(dd), opt, lmod$reTrms, fr = lmod$fr, mc = quote(hacked_lmer()))
