### ISSUE TITLE
Unnecessary warning in predict.merMod when using non-standard factor contrasts

### ISSUE THREAD

**Issue by CDEager** [lme4/lme4#414]
When I fit a mixed effects regression where a factor is included in both the fixed and random effects, and the factor has non-standard contrasts (e.g. sum contrasts where the deviations are +/- 0.5 rather than +/- 1), warnings are issued in the **merMod** method for **predict**.  The predictions are still correct, but the warnings are unnecessary.  If you remove the contrast attribute from the factor before using **predict**, then an error occurs in **mkNewReTrms**.  If you use the **contrasts** argument to **lmer** rather than assigning the contrasts to the factors within the data frame, then the contrasts are only applied to the fixed effects and not to the random effects.  The following code simulates an example of the issue.

```R
library(lme4)
#> Loading required package: Matrix

# simulate data
set.seed(1)
dat <- data.frame(
  fac = rep(c("a", "b"), 100),
  grp = rep(1:25, each = 4))
dat$y <- 0
contr <- 0.5 * contr.sum(2)
rownames(contr) <- c("a", "b")
colnames(contr) <- "a"

lmod <- lFormula(y ~ fac + (1 + fac | grp), dat, contrasts = list(fac = contr))

# contrasts correctly assigned for fixed effects
head(lmod$X)
#>   (Intercept) faca
#> 1           1  0.5
#> 2           1 -0.5
#> 3           1  0.5
#> 4           1 -0.5
#> 5           1  0.5
#> 6           1 -0.5

# contrasts ignored in random effects
lmod$reTrms$cnms
#> $grp
#> [1] "(Intercept)" "facb"
t(lmod$reTrms$Zt)[1:5, 1:2]
#> 5 x 2 sparse Matrix of class "dgCMatrix"
#>   1 1
#> 1 1 .
#> 2 1 1
#> 3 1 .
#> 4 1 1
#> 5 . .

contrasts(dat$fac) <- contr
lmod <- lFormula(y ~ fac + (1 + fac | grp), dat)

# contrasts correctly assigned for fixed effects
head(lmod$X)
#>   (Intercept) faca
#> 1           1  0.5
#> 2           1 -0.5
#> 3           1  0.5
#> 4           1 -0.5
#> 5           1  0.5
#> 6           1 -0.5

# contrasts correctly assigned for random effects
lmod$reTrms$cnms
#> $grp
#> [1] "(Intercept)" "faca"
t(lmod$reTrms$Zt)[1:5, 1:2]
#> 5 x 2 sparse Matrix of class "dgCMatrix"
#>   1    1
#> 1 1  0.5
#> 2 1 -0.5
#> 3 1  0.5
#> 4 1 -0.5
#> 5 .  .  

# simulate model
mm <- cbind(lmod$X, t(lmod$reTrms$Zt))
b <- c(0, 1)
L <- t(chol(matrix(c(1, .5, .5, 1), 2, 2)))
g <- matrix(scale(rnorm(50))[, 1], 2, 25)
g <- L %*% g
g[2, ] <- g[2, ] * 0.5
bg <- c(b, as.vector(g))
dat$y <- as.vector(mm %*% bg) + rnorm(nrow(dat), 0, 0.25)
dat$y <- scale(dat$y)[, 1]

# run model; summary looks fine
mod <- lmer(y ~ fac + (1 + fac | grp), dat)
summary(mod)
#> Linear mixed model fit by REML ['lmerMod']
#> Formula: y ~ fac + (1 + fac | grp)
#>    Data: dat
#> 
#> REML criterion at convergence: 149.7
#> 
#> Scaled residuals: 
#>     Min      1Q  Median      3Q     Max 
#> -1.9971 -0.5208 -0.1168  0.6289  2.1907 
#> 
#> Random effects:
#>  Groups   Name        Variance Std.Dev. Corr
#>  grp      (Intercept) 0.67691  0.8227       
#>           faca        0.37496  0.6123   0.57
#>  Residual             0.05034  0.2244       
#> Number of obs: 200, groups:  grp, 25
#> 
#> Fixed effects:
#>              Estimate Std. Error t value
#> (Intercept) 2.606e-15  1.653e-01   0.000
#> faca        9.063e-01  1.265e-01   7.164
#> 
#> Correlation of Fixed Effects:
#>      (Intr)
#> faca 0.545 

# predictions of data are correct but generate warnings
preds <- predict(mod, dat)
#> Warning message:
#> contrasts dropped from factor fac
all.equal(preds, fitted(mod))
#> TRUE

# removing the contrasts within the data frame results in an error
attr(dat$fac, "contrasts") <- NULL
predict(mod, dat)
#> Error in FUN(X[[i]], ...) : 
#>   random effects specified in re.form that were not present in original model
```

If you replace the line

```R
mfnew <- model.frame(delete.response(Terms), newdata,
  na.action = na.action, xlev = orig_levs)
```

in **predict.merMod** with

```R
isFacND <- which(vapply(newdata, is.factor, FUN.VALUE = TRUE))

newdata2 <- newdata
for (j in isFacND) {
  attr(newdata2[[j]], "contrasts") <- NULL
}

mfnew <- model.frame(delete.response(Terms), newdata2,
  na.action = na.action, xlev = orig_levs)
```

then **predict.merMod** works without issuing the warnings.  It is by no means a critical issue, but the warnings are misleading since the contrasts are not actually being ignored; they are just dropped in the call to **model.frame** that creates **mfnew** and then reassigned in the call to **model.matrix** through the **contrasts.arg** argument.  I'm not sure if the above fix prevents that warning from being issued when it actually should be issued though, and I don't know if it causes other problems I'm not thinking of.  Or is there already a solution for this issue I haven't found?

**Comment by bbolker** [comment]
I've looked at this a bit.  The warning comes from `stats::model.frame.default()`. It looks like this is a more-or-less-unavoidable consequence of specifying `xlevs` when using a data frame containing factors with contrasts specified.

The solution suggested seems reasonable, but I've opted to simply `suppressWarnings()` on this particular `model.frame()` call.  That carries a tiny risk of masking other, more significant warnings from the call (as far as I know R has no method for suppressing a specific message: see [this discussion](https://stat.ethz.ch/pipermail/r-devel/2012-October/065089.html). In contrast

- making a new copy of the data frame in order to drop the contrasts could be expensive if the data set is large
- dropping contrasts *in situ* could be confusing/dangerous at some point in the future (as far as I can tell `newdata` is not used for anything else in the rest of the `predict` function, but that could change ...)
