### ISSUE TITLE
lme4 fails to calculate random intercepts with no warnings

### ISSUE THREAD

**Issue by ejolly** [lme4/lme4#419]
Having a peculiar issue where given 2 datasets with the same exact formatting, 2 models specified exactly the same way don't produce the same random effects structure.  The design of the data is such that each there are 48 unique subjects each with a single observation in 4 conditions. Outcome variable is the 'dv' column, predictor variable is the 'cond' column, and grouping variable is the 'sub' column. 

The first model runs as expected, with subject level random intercepts, as examined using `coef(model)`, while the other assumes a fixed intercept for all subjects. This is despite the fact that both models are specified identically. There are no convergence, or variance issue warnings and subjects do in fact have different means (average response across all 4 conditions), so the intercepts should vary. 

Taking out the first 33 rows of the dataset (which is first 33 subjects within condition 0) make lme4 calculate random intercepts properly. I can't seem to isolate this to a weird data point however, and all types and code is identical between models. Totally stuck as to why a weird data point (if that's really the problem) should be confusing how lme4 calculates random effects. 

See code below to reproduce issues with the following data files:
[data_files.zip](https://github.com/lme4/lme4/files/1006091/data_files.zip)

```
library('lme4')
data_dir = '/Path/to/data/dir/'
#Load in data and set types
goodDat = read.csv(paste(data_dir,'ROI_2_noX.csv',sep=""))
goodDat$dv <-as.numeric(goodDat$dv)
goodDat$cond <- as.factor(goodDat$cond)
#4 levels make the first the reference 
goodDat$cond <- relevel(goodDat$cond,ref="0");
goodDat$sub <- as.factor(goodDat$sub)

#Same for bad example
badDat = read.csv(paste(data_dir,'ROI_3_noX.csv',sep=""))
#badDat = badDat[34:192,] #This works! uncomment it to see the proper random effects in the second model
badDat$dv <-as.numeric(badDat$dv)
badDat$cond <- as.factor(badDat$cond)
#4 levels make the first the reference
badDat$cond <- relevel(badDat$cond,ref="0");
badDat$sub <- as.factor(badDat$sub)

#Good model with expected random intercepts for subjects
model = lmer('dv~cond + (1|sub)',data=goodDat)
summary(model)
coef(model)

#Bad model with no subject random intercepts
model = lmer('dv~cond + (1|sub)',data=badDat)
summary(model)
coef(model)

**Comment by bbolker** [comment]
This is not a bug: depending on which data are included in the model, the result may (or may not) be a *singular fit*, with an estimated among-subject variance of zero (or very close to zero). That's why the coefficients are the same across all subjects in the second case.  I'm not sure I can tell you  *exactly* why omitting that particular set of points leads to a singular fit.  As shown below, you appear to have heterogeneous residual variance among subjects, which could be helping to make things wonky.

```
#Bad model with no subject random intercepts
badModel = update(goodModel,data=badDat)
summary(badModel)
coef(model)

## try omitting 'outlier' (still singular)
otherBadModel = 
  update(goodModel,
         data=subset(badDat,dv>-2))

## omit specified points (not singular)
rescueModel = 
  update(goodModel,
         data=badDat[34:192,])

## graphical investigation
library(ggplot2)
ggplot(badDat,aes(cond,dv,group=sub))+
  geom_line()+
  geom_line(data=badDat[34:192,],colour="red")

## check variance components
lapply(lme4:::namedList(rescueModel,otherBadModel,
            badModel,goodModel),VarCorr)

## try looking at residuals from a linear model;
## any clearer? (no ...)
badDat$lmres <- residuals(lm(dv~cond,data=badDat))
ggplot(badDat,aes(cond,lmres,group=sub))+
  geom_line()+
  geom_line(data=badDat[34:192,],colour="red")

ggplot(transform(badDat,sub=reorder(sub,abs(lmres))),
       aes(sub,lmres))+
  geom_boxplot()

## fit with nlme so we can allow for heterogeneous variance among subjects
library(nlme)
## this fit is equivalent to 'badModel'
m0Model <- lme(dv~cond,random=~1|sub,data=badDat,
               control=lmeControl(msMaxEval=1000,msMaxIter=250))

## this fit allows for het variance: non-singular, and better according
##  to likelihood ratio test (but worse according to AIC)
m1Model <- lme(dv~cond,random=~1|sub,data=badDat,
    weights=varIdent(form=~1|sub),
    control=lmeControl(msMaxEval=1000,msMaxIter=250))
anova(m0Model,m1Model)
```

**Comment by bbolker** [comment]
PS: this is further support for the idea that `lme4` should issue at least a message (if not a warning) when fits are singular.
