### ISSUE TITLE
Simulate from a formula, where the response variable isn't in newdata

### ISSUE THREAD

**Issue by pitakakariki** [lme4/lme4#422]
library(lme4)
    fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)

    form <- formula(fm1)
    plist <- list(beta=fixef(fm1), theta=getME(fm1, "theta"), sigma=sigma(fm1))

The following works as expected:

```
head(simulate(form, newparams=plist, family="gaussian", newdata=sleepstudy))
#      sim_1
# 1 289.3823
# 2 256.2211
# 3 226.8160
# 4 306.9871
# 5 274.6075
# 6 321.2461
```

However, if we remove the `Reaction` column from `sleepstudy`, `simulate` no longer works:

```
head(simulate(form, newparams=plist, family="gaussian", newdata=sleepstudy[-1]))
#  Error in eval(expr, envir, enclos) : object 'Reaction' not found
```

There's an easy workaround - just remove the lhs from the formula:

```
head(simulate(form[-2], newparams=plist, family="gaussian", newdata=sleepstudy[-1]))
#      sim_1
# 1 251.4170
# 2 273.7553
# 3 233.0799
# 4 253.1544
# 5 256.0082
# 6 229.2000
```

**Comment by bbolker** [comment]
Should this be fixed or merely documented?  `?simulate.merMod` does say

>  object: (for ‘simulate.merMod’) a fitted model object or (for ‘simulate.formula’) a (one-sided) mixed model formula, as described for ‘lmer’.

This is admittedly terse.

On the one hand, it wouldn't be very hard at all to tell `simulate.merMod` to automatically drop the LHS of a formula, if it exists.  On the other hand, perhaps just make the docs a little more explicit would be sufficient.

**Comment by pitakakariki** [comment]
Slightly embarrassed to admit I did not check the documentation before submitting this issue 😳

The LHS can be relevant when we're simulating binomial data, so it won't be as simple as just dropping the LHS. How about I have a closer look and try to send a pull request in a few days?

**Comment by bbolker** [comment]
Having a closer look is fine.  However, when simulating binomial data the N is determined by the `weights` argument (is that documented?  I don't know offhand), so we don't really ever (that I can think of) need the LHS ...

**Comment by pitakakariki** [comment]
Determined by `weights` first, but can also come from LHS. But the LHS determines if the simulations are in matrix or proportion form:

> For binomial models, `simulate.formula` looks for the binomial size first in the `weights` argument (if it's supplied), second from the left-hand side of the formula (if the formula has been specified in success/failure form), and defaults to 1 if neither of those have been supplied. Simulated responses will be in matrix form if the supplied formula has a matrix-valued left-hand side, otherwise they will be given as proportions.

It looks like it was me that changed this back in https://github.com/lme4/lme4/issues/400

**Comment by pitakakariki** [comment]
Looks like any change here would involve some messy sort-of-evaluation of the lhs without actually evaluating it. Have added a small clarification to the docs instead.
