### ISSUE TITLE
Issues inserting starting value for theta in glmer.nb()

### ISSUE THREAD

**Issue by timothyslau** [lme4/lme4#423]
Hello,

I'm having trouble inserting a starting value for theta into `glmer.nb`. Would someone mind showing me a quick example please?

sincerely,
Noob Noobigan

**Comment by bbolker** [comment]
at present this isn't possible; `glmer.nb` estimates a starting theta value automatically by fitting a `glmer` model with `family=poisson` and using machinery from the `MASS` package to estimate an overdispersion parameter from the residuals (see `lme4:::est_theta`).  It wouldn't be terribly hard to add machinery to `glmer.nb` to allow the user to specify a starting value in the `start` argument.  Can you give an example where this is useful/necessary?

**Comment by timothyslau** [comment]
@bbolker , Oh yes, I've been editing and modifying models with additional variables and interactions and when I have multiple random slopes going, it adds a lot more time to estimate theta for each model when I already have a pretty good idea of what it is/should be from the previous model I just used. I use glmer.nb frequently and often with large data sets, this added feature would be very helpful for efficiency in model building, similar to the utility of the `update()` function.

Here's an example of what I'd like to be able to do:

```
# dummy data
set.seed(101)
dd <- expand.grid(f1 = factor(1:3),
                  f2 = LETTERS[1:2], g=1:9, rep=1:15,
          KEEP.OUT.ATTRS=FALSE)

summary(mu <- 5*(-4 + with(dd, as.integer(f1) + 4*as.numeric(f2))))
dd$y <- rnbinom(nrow(dd), mu = mu, size = 0.5)

# dummy model
m.nb <- glmer.nb(y ~ f1 + f2 + (1|g), data=dd, verbose=TRUE)

# model with an added interaction and a pre-specified theta value
m.nb2 <- glmer.nb(y ~ f1 + f2 + f1:f2 + (1|g), data=dd, verbose=TRUE, initCtrl = list(theta = getME(m.nb, "glmer.nb.theta")))
```

**Comment by bbolker** [comment]
closing this, will reopen if requested
