### ISSUE TITLE
options(warnPartialMatchDollar = TRUE)

### ISSUE THREAD

**Issue by rubenarslan** [lme4/lme4#426]
I recently turned this on to avoid making mistakes
`options(warnPartialMatchDollar = TRUE)`

Now I get the following warning messages when calling lmer

1: In ll$mu : partial match of 'mu' to 'mustart'
2: In opt$conv : partial match of 'conv' to 'convergence'
3: In opt$conv : partial match of 'conv' to 'convergence'

and the following when calling summary
In famL$fami : partial match of 'fami' to 'family'

Of course this is nothing major, but since there doesn't seem to be a way to get warned about partial matches only in code that I am "guilty of", I'd appreciate this being changed.

**Comment by bbolker** [comment]
the `opt$conv` ones may be slightly trickier than one would initially guess (I think some of the optimization functions we use return a `$convergence` element while others return `$conv`, and we were using partial matching to handle that situation) -- but we can write a `getConv()` wrapper for that pretty easily.

**Comment by bbolker** [comment]
I think this is fixed in  68f7883 .  Double-check on your end?
