### ISSUE TITLE
Hang when using update with a piped-in dataset

### ISSUE THREAD

**Issue by rubenarslan** [lme4/lme4#427]
To do robustness analyses, I fit a lot of models by first running some trivial operations on the data (e.g. excluding certain subsets) and then piping the modified dataset to `update`.
This used to work fine.

Now, there's a big difference in the time it takes to fit the model when the data is piped as opposed to the dataset name being named directly.

In the example below it's only two-fold, but with my actual dataset of 30k rows and 500 columns, this easily prevents the updated model from being fit within 12 hours (interrupted after trying that overnight).

I think this problem occurring falls together with a recent update from lme4 1.12.0 to 1.13.0 and Matrix 1.2-8 to 1.2-10. I know that I changed from those versions from my packrat lockfile in my version control, but it may not have been the only change (e.g. I also changed tibble 1.2->1.3.3, but I tried to make an example without tibble).

```r
library(lme4)
library(magrittr)

data('sleepstudy')
sleepstudy = dplyr::bind_rows(replicate(1000, sleepstudy, simplify = F))
(fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy))

less_ctrl_formula = update.formula(formula(fm1), new = . ~ . - Days)

system.time({
update(fm1, formula = less_ctrl_formula, data = sleepstudy) -> fewer_controls
})

system.time({
	sleepstudy %>%
	update(fm1, formula = less_ctrl_formula, data = .) -> fewer_controls2
})
```

**Comment by bbolker** [comment]
Wow, I have no idea.  Hard to imagine it's a `Matrix` issue. Somewhat surprising that there's a 1.1.12 -> 1.1.13 difference, as the relevant [NEWS file entries](https://github.com/lme4/lme4/blob/master/inst/NEWS.Rd#L35) don't show much.  More thoroughly, `git diff 51c47d716 01a4d79  -- R/*.R` looks at all the R-code differences between (approximately) the 1.1.12 and 1.1.13 releases (we really should do better about tagging releases to make that easier!).

Will see what I can find. (In the meantime, the workaround is obvious ...)

**Comment by bbolker** [comment]
Can you please install the latest development version (1.1-14; `devtools::install_github("lme4/lme4")`) and try again/run some benchmarks?  I ran this on Linux with the dev version and was surprised to see no particular difference; ran it on MacOS with 1.1-13 and did see a difference; then upgraded MacOS to 1.1-14 and the difference went away.  I think this may be related to https://github.com/lme4/lme4/issues/410 , which I fixed a few days ago ...

**Comment by pitakakariki** [comment]
Yeah I thought this sounded a bit like https://github.com/lme4/lme4/issues/410, can confirm that latest build is fine.

**Comment by rubenarslan** [comment]
Yes, the update fixes both my mock example and my real problem. Thanks a lot. Sorry I didn't try the Github version first.
The obvious workaround of not piping in the data wasn't enough, because this apparently also occurred in some other cases where the place to look for the data wasn't obvious (ie. updating a model in a function or knitr child document).
