### ISSUE TITLE
xyplot not working with lme4 package

### ISSUE THREAD

**Issue by erpar12** [lme4/lme4#429]
Hi,

I recently started to use R for mixed linear regressions with the lme4 package. I am trying to do a xyplot, which should be possible with the lme4 package. However, after trying to write the code

xyplot(predscore ~ cohort90, data = datapred, groups = schoolid, type = c("p", "l"), col = "blue")

I get this message:
Error: impossible to find function "xyplot".

After, I tried to load the lattice package, but it tells me that lattice is imported by lme4, nlme and Matrix and can't be unloaded. Is there any problems at the moment with the xyplot?

Thank you for the help!

**Comment by bbolker** [comment]
You need to run `library(lattice)` before you use `xyplot`.  Importing a package such as `xyplot` in R makes it available for internal use by the package, but doesn't expose the package's functions for general use.
