### ISSUE TITLE
glmmsr breakage

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#438]
something between 1.1-13 release and 1.1-14 release breaks the following code from the glmmsr package:

```
library(glmmsr)
library(BradleyTerry2)
result <- rep(1, nrow(flatlizards$contests))
flatlizards_glmmsr <- c(list(result = result,
                             winner = flatlizards$contests$winner,
                             loser = flatlizards$contests$loser),
                        flatlizards$predictors)
fit_1 <- glmm(result ~ 0 + Sub(ability[winner] - ability[loser]),
              ability[liz] ~ 0 + SVL[liz] + (1 | liz),
              data = flatlizards_glmmsr, family = binomial(link = "probit"),
              method = "Laplace", control = list(check_Laplace = FALSE),
              verbose = 0)
```

With stock CRAN version it gives the following error/traceback:
```
Error in reTrms$flist[i, , drop = FALSE] : incorrect number of dimensions
> traceback()
9: `[fr`(ability, winner)
8: is_modfr(modfr1)
7: `-fr`(`[fr`(ability, winner), `[fr`(ability, loser))
6: eval(subexpr_mod, envir = data_subexpr)
5: eval(subexpr_mod, envir = data_subexpr)
4: FUN(X[[i]], ...)
3: lapply(subs, parse_sub, data = data, family = family)
2: find_modfr_glmm(formula, subformula = subformula, data = data, 
       family = family, weights = weights, offset = offset)
1: glmm(result ~ 0 + Sub(ability[winner] - ability[loser]), ability[liz] ~ 
       0 + SVL[liz] + (1 | liz), data = flatlizards_glmmsr, family = binomial(link = "probit"), 
       method = "Laplace", control = list(check_Laplace = FALSE), 
       verbose = 0)
```

Don't know what caused this - something about deparsing?  Try `git bisect` ... ?

**Comment by heogden** [comment]
Thank you for letting me know. The problem was due to assuming that reTrms$flist is a data frame, when it is now a list.
https://github.com/lme4/lme4/blob/68f78835c54fb1d141cc1cf9b648fd337c64e40f/R/utilities.R#L196-L197
I have fixed this in glmmsr (https://github.com/heogden/glmmsr/commit/ec843ede78e0e86ac520053007654abacee004a8) and will submit a new version of glmmsr to CRAN with this change.

**Comment by bbolker** [comment]
thank you very much!

for what it's worth, this change was made because I was experimenting with some cases where random effects were applied to branches of a phylogenetic tree, so that the number of levels of different grouping factors might be different ...
