### ISSUE TITLE
How to specify user-defined matrix Z?

### ISSUE THREAD

**Issue by zhengyangGWAS** [lme4/lme4#439]
Hi,

In genetic studies, we usually include the genetic relatedness matrix as a variance component, so we have this following model:
Y~Xbeta+Zb+error, 
where beta are the fixed effects, b~N(0,sigma^2*I) are the random effects, error are the random error, Z is the known genetic relatedness matrix. So how to use lme4 to fit this model if we know X and Z beforehand? I can use the package "nlme" to do it using the code like 
lme(y~-1+X, random=list(group=pdIdent(~-1+Z))),
but how to do it using lme4? 

Thank you. 
Zhengyang

**Comment by bbolker** [comment]
can you please post this question to `r-sig-mixed-models@r-project.org`? (subscribe to the list first - you can easily find how to subscribe by googling)  The short answer is that there are several add-on/downstream packages designed for this application (pedigreeMM is one of them, but I think there are others; maybe check the list of dependencies on the CRAN lme4 page for likely-sounding titles)
