### ISSUE TITLE
fix lme4 for testthat changes ...

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#444]
```
== CHECK RESULTS ========================================

*   checking tests ...
    ```
     ERROR
    Running the tests in ‘tests/AAAtest-all.R’ failed.
    Last 13 lines of output:
      2: compare(act$val, exp$val, ..., check.attributes = FALSE)
      3: compare.default(act$val, exp$val, ..., check.attributes = FALSE)
      4: all.equal(x, y, ...)
      5: all.equal.list(x, y, ...)
      6: all.equal(target[[i]], current[[i]], check.attributes =
check.attributes, use.names = use.names,
             ...)
      7: all.equal.numeric(target[[i]], current[[i]], check.attributes
= check.attributes,
             use.names = use.names, ...)

      ══ testthat results
═══════════════════════════════════════════════════════════
      OK: 731 SKIPPED: 1 FAILED: 1
      1. Error: basic intercept + slope '||' works
(@test-doubleVertNotation.R#7)

      Error: testthat unit tests failed
      Execution halted
    ```
```

**Comment by bbolker** [comment]
There are some apparently spurious commas in the `expect_equivalent` call, but ...  ?

**Comment by mmaechler** [comment]
It wasn't me who has so much loved `testthat`.. ;-\   I was a bit appalled by the automatic e-mail that the testthat maintainer sent yesterday, announcing that the new version breaks our package checks *and* he plans to release `testthat` to CRAN on Nov 13...

**Comment by bbolker** [comment]
can't reproduce, closing for now.
