### ISSUE TITLE
residual variance estimates fixed to 1

### ISSUE THREAD

**Issue by MelLinde** [lme4/lme4#450]
Hi,

I use lme4 to model methylation count data. I specify my response as cbind(methylation count, unmethylation count) and use the argument family=binomial.
I model thousands of different CpG sites and always get a residual variance estimate of 1.

> attr(VarCorr(mod.trt), "sc")^2
[1] 1

So, I was wondering if the residual variance for proportional data is fixed to 1 (like for binary data) and where I can find more information on that?

Best regards and many thanks,
Melanie

**Comment by bbolker** [comment]
It's slightly more complicated than that, but basically yes. Can you provide a little more context? What do you want to use the residual variance to do?

**Comment by MelLinde** [comment]
Hi again, 

Thanks for your reply. I don't need to use the residual variance for further analysis. In my data set I have count information for 500,000 CpG sites over 64 samples. 32 per treatment group. I model each site separately to see if there is a significant difference between the treatments and therefore use a loop. Since I cannot look at the summary of each site, I saved different estimates from the loop and recognised that the residual standard deviation is always 1. To evaluate the model fit, I would like to understand why the residual variance is fixed to one.

**Comment by bbolker** [comment]
Can we please continue this conversation on the r-sig-mixed-models mailing list? (Note that you should subscribe first, and give a summary of the conversation so far ... is "site" the same as "sample" in your comment above?)
