### ISSUE TITLE
try harder to construct correct levels when predicting from new data frame

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#452]
https://stackoverflow.com/questions/48461980/prediction-in-r-glmm

**Comment by JoFAM** [comment]
@bbolker 

This is a consequence of using `model.frame`  [here](https://github.com/lme4/lme4/blob/master/R/predict.R) at line 372 and following. 

I don't have the time now to dive into it myself, but I believe the argument `xlev` of `model.frame()` could be of help here. 

From `?model.frame`:

>  The levels of any factors in the data frame are adjusted according to the drop.unused.levels and xlev arguments.

So extracting the levels of the factors from the object and using these later on seems like the route to go.

**Comment by bbolker** [comment]
yes, thanks. Regarding `xlev`, we do use it elsewhere, I'm not sure how this case slipped through.

**Comment by bbolker** [comment]
example from SO:

```
library(dplyr)
set.seed(101)
n = 300
xx<-c("r1","r2","r3","r4","r5")
xxx<-c("e1","e2","e3")
p=0.3
df1 <- data_frame(
  xx1 = runif(n, min = 0, max = 10),
  xx2 = runif(n, min = 0, max = 10),
  xx3 = runif(n, min = 0, max = 10),
 School = factor(sample(xxx, n,re=TRUE)),
 Rank = factor(sample(xx, n,re=TRUE)),
 yx = as.factor(rbinom(n, size = 1, prob = p))
)
n11 = data.frame(School="e3",Rank="r2",xx1=8.58,xx2=8.75,xx3=7.92)
library(lme4)
mm2 <- glmer(yx ~ xx1 + xx2 + xx3 + Rank +  (Rank | School), data = df1, 
family = "binomial",control = glmerControl(calc.derivs = FALSE))
predict(mm2, n11, type="response") #No meu caso especifico
```

**Comment by bbolker** [comment]
fixed by last PR/round of commits
