### ISSUE TITLE
install.packages

### ISSUE THREAD

**Issue by nkabouche** [lme4/lme4#454]
Hi,
Is it necessary to specify the path of the library when installing packages;
I'm just typing (install.packages(x) ) in the R console, could this cause problem when calling 
this package by (library(x) )

**Comment by bbolker** [comment]
This doesn't seem to be lme4-specific at all. Unless you're doing something tricky, you shouldn't need to specify anything about library paths. Please forward this question, with more details about what you're doing and what's not working, to `r-help@r-project.org` (you may need to subscribe to the list first [here](https://stat.ethz.ch/mailman/listinfo/r-help))
