### ISSUE TITLE
new notes with latest r-devel

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#455]
Lots of "no visible binding for <<-" notes when installing.  Almost all of these are in the initialization method for `mer` objects in  `AllClass.R`.  They're messy, could cause concern among users and/or complaints from CRAN?  Can we replace these with `assign()`, or do we need `globalVariables` ?

> Typical examples are the fields and methods in reference classes,
     which appear to be global objects to ‘codetools’.  (This case is
     handled automatically by ‘setRefClass()’ and friends, using the
     supplied field and method names.)

```
Note: no visible binding for '<<-' assignment to 'beta0' 
Note: no visible binding for '<<-' assignment to 'cnms' 
Note: no visible binding for '<<-' assignment to 'covar' 
Note: no visible binding for '<<-' assignment to 'delb' 
Note: no visible binding for '<<-' assignment to 'delu' 
Note: no visible binding for '<<-' assignment to 'eta' 
Note: no visible binding for '<<-' assignment to 'flist' 
Note: no visible binding for '<<-' assignment to 'gam' 
Note: no visible binding for '<<-' assignment to 'Gp' 
Note: no visible binding for '<<-' assignment to 'Lambdat' 
Note: no visible binding for '<<-' assignment to 'LamtUt' 
Note: no visible binding for '<<-' assignment to 'Lind' 
Note: no visible binding for '<<-' assignment to 'lower' 
Note: no visible binding for '<<-' assignment to 'lowerbd' 
Note: no visible binding for '<<-' assignment to 'mu' 
Note: no visible binding for '<<-' assignment to 'n' 
Note: no visible binding for '<<-' assignment to 'ncols' 
Note: no visible binding for '<<-' assignment to 'nctot' 
Note: no visible binding for '<<-' assignment to 'nlenv' 
Note: no visible binding for '<<-' assignment to 'nlevs' 
Note: no visible binding for '<<-' assignment to 'nlmod' 
Note: no visible binding for '<<-' assignment to 'nms' 
Note: no visible binding for '<<-' assignment to 'offsets' 
Note: no visible binding for '<<-' assignment to 'pnames' 
Note: no visible binding for '<<-' assignment to 'Ptr' 
Note: no visible binding for '<<-' assignment to 'REML' 
Note: no visible binding for '<<-' assignment to 'RZX' 
Note: no visible binding for '<<-' assignment to 'sig' 
Note: no visible binding for '<<-' assignment to 'sqrtrwt' 
Note: no visible binding for '<<-' assignment to 'sqrtXwt' 
Note: no visible binding for '<<-' assignment to 'theta' 
Note: no visible binding for '<<-' assignment to 'u0' 
Note: no visible binding for '<<-' assignment to 'upperbd' 
Note: no visible binding for '<<-' assignment to 'useSc' 
Note: no visible binding for '<<-' assignment to 'Ut' 
Note: no visible binding for '<<-' assignment to 'Utr' 
Note: no visible binding for '<<-' assignment to 'V' 
Note: no visible binding for '<<-' assignment to 'Vtr' 
Note: no visible binding for '<<-' assignment to 'VtV' 
Note: no visible binding for '<<-' assignment to 'wtres' 
Note: no visible binding for '<<-' assignment to 'xstep' 
Note: no visible binding for '<<-' assignment to 'xtol' 
Note: no visible binding for '<<-' assignment to 'Xwts' 
Note: no visible binding for '<<-' assignment to 'y' 
```

**Comment by pitakakariki** [comment]
Is there a reason this `initialize` method doesn't have `.Object` as its first argument?

**Comment by mmaechler** [comment]
IMO `globalVariables` is a really bad idea: It applies globally to the whole package. 
I really don't know why "they" introduced it... w/o me or anybody else noticing what a bad idea it was...

About the warnings: They may be overzealous and "go away" before R-devel becomes 3.5.0... but of course they are bothering now.
They are from the  reference classes code.  Did you check if the reference class "setup" we use is still according to the documented way to this?    If yes, and if these warnings are still there in a week or so, we should raise this on R-devel  (or I should raise it within R-core).

**Comment by mmaechler** [comment]
The very latest R-devel  does not show those notes if I use   `--as-cran`   
Can you try to to reproduce them telling us exactly *how* ?
If others confirm the messages are gone, we can close this issue.

**Comment by bbolker** [comment]
Clarification: these notes are emitted **not** when checking (e.g. `R CMD check --as-cran`), but when installing (`R CMD build --no-build-vignettes lme4; R CMD INSTALL lme4_1.1-16.tar.gz`)

**Comment by mmaechler** [comment]
Thank you, Ben.    It seems an accident that these reference class setups produce such warnings.. and will hopefully been corrected soon (within days) in R-devel.

**Comment by bbolker** [comment]
I think this is fixed now (I'm using svn rev 74611; not sure where it was corrected, and probably won't bother figuring out).
