### ISSUE TITLE
lme4 installation failing because of nlopt dependency

### ISSUE THREAD

**Issue by koutbo6** [lme4/lme4#469]
on RStudio Version 1.1.447 and using packrat using mac os v10.13.4 
Unable to install lme4 and getting the following output:

```bash
checking for nlopt.h... no
configure: Need to download and build NLopt
trying URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
Error in download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  : 
  cannot open URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
Execution halted
configure: Starting to install library to /private/var/folders/k7/kz35m7lx6r9d7_f903tkdpzc0000gn/T/RtmpqP0cG2/R.INSTALL678540ac94b/nloptr/nlopt-2.4.2
./configure: line 3325: cd: nlopt-2.4.2: No such file or directory
isres/isres.c: No such file or directory
util/qsort_r.c: No such file or directory
util/qsort_r.c: No such file or directory
```

**Comment by bbolker** [comment]
This is a failure in installing the `nloptr` package that `lme4` depends on.  As such, I'm not sure how helpful we can be (aka "this isn't our fault!")

I didn't have any trouble downloading that file just now (via `wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz`). Could it be/have been a (hopefully transient) network error?  Are you behind a firewall/do you need to do something with proxy settings?

**Comment by koutbo6** [comment]
Interestingly I could download the file myself as well, but the installation fails for some reason.

I was wondering if anyone else is facing the same issue? Could it be an rstudio issue?

**Comment by bbolker** [comment]
Maybe try this on r-sig-mixed-models@r-project.org, or r-help@r-project.org ?  Many more people read those lists than read the lme4 issues list. Have you tried it from a plain R session? Does it work outside of packrat?

**Comment by koutbo6** [comment]
just in case someone faces the same issue,
I upgraded from R v3.3 to R v3.5 and it worked fine and managed to load the nlopt library with no issues
