### ISSUE TITLE
Conditioning the random intercept on predictors other than X covariates

### ISSUE THREAD

**Issue by yashreem** [lme4/lme4#471]
Hi, 
I am working with a random intercept model. I have the usual "X" vector of covariates and one id variable which will make up the random intercept. Now I wish to add group-level predictors (which are NOT in the X vector) such that the random intercept depends on these predictors. I tried to use the syntax as suggested in Gelman and Hill:

data$u.full <- data$u[data$id]
fit<-lmer(dep_var~ X1+ u.full + (1|id), data=data)

The new column data$u.full is NA and I get the following error:
 Invalid grouping factor specification, ID

I would be grateful to get help here.

Thank you.

**Comment by bbolker** [comment]
Can you please post this to `r-sig-mixed-models@r-project.org`, if possible including a short *reproducible* example? FWIW it seems that you're having R data-manipulation problems rather than specifically mixed-model problems ...

**Comment by yashreem** [comment]
Yes, I will. Thanks for your reply.
