### ISSUE TITLE
lme4 (glmer) NAs

### ISSUE THREAD

**Issue by MichaelRatajczak** [lme4/lme4#472]
Hi,

First, apologies if I am asking something that has an obvious answer.

Second, I am wondering how does lme4, specifically glmer, treat NAs as default? I noticed that I get different results, depending on how I treat missing values in the dataset.

For example, here I manually removed all rows with missing values from the dataset:
`Random effects:`
 `Groups     Name        Variance Std.Dev.`
 `STUDENT_ID (Intercept) 0.1906   0.4366`  
`Number of obs: 19008, groups:  STUDENT_ID, 84`

`Fixed effects:`
             `Estimate Std. Error z value Pr(>|z|)`    
`(Intercept)  -0.11626    0.05740  -2.025   0.0428 *`  
`TEST_NUMBER2  0.31578    0.04327   7.298 2.92e-13 ***`
`TEST_NUMBER3  0.66743    0.04445  15.015  < 2e-16 ***`
`TEST_NUMBER4  0.51201    0.04508  11.359  < 2e-16 ***`

Here I left rows with empty cases:

`Random effects:`
 `Groups     Name        Variance Std.Dev.`
 `STUDENT_ID (Intercept) 0.1906   0.4366`  
`Number of obs: 19008, groups:  STUDENT_ID, 84`

`Fixed effects:`
             `Estimate Std. Error z value Pr(>|z|)`    
`(Intercept)  -0.11626    0.05740  -2.026   0.0428 *`  
`TEST_NUMBER2  0.31578    0.04326   7.299 2.89e-13 ***`
`TEST_NUMBER3  0.66743    0.04444  15.017  < 2e-16 ***`
`TEST_NUMBER4  0.51201    0.04507  11.360  < 2e-16 ***`

And here I recoded rows with empty cases to "NA" in each case:

`Random effects:`
 `Groups     Name        Variance Std.Dev.`
`STUDENT_ID (Intercept) 0.1679   0.4097`
`Number of obs: 21504, groups:  STUDENT_ID, 84`

`Fixed effects:`
             `Estimate Std. Error z value Pr(>|z|)`
`(Intercept)   0.31400    0.05284   5.942 2.81e-09 ***`
`TEST_NUMBER2 -0.01816    0.03975  -0.457    0.648`
`TEST_NUMBER3  0.39225    0.04070   9.638  < 2e-16 ***`
`TEST_NUMBER4  0.36471    0.04061   8.981  < 2e-16 ***`

I am wondering, why are the coefficients so different when I recode the empty cases to "NA"? I thought the NAs would be omitted, leading to the same coefficients as in the models above?

Thank-you in advance,

Michael

**Comment by bbolker** [comment]
Can you please clarify what you mean by "empty cases" and "recod[ing] empty cases to NA"? What exactly are you setting to NA? I can't quite tell what you've done here. (As you point out, the top two  examples give identical results.)  A (small) reproducible example might help ...
