### ISSUE TITLE
Syntax for adding group-level predictors

### ISSUE THREAD

**Issue by yashreem** [lme4/lme4#473]
Hi,
I am working with a random intercept model. I have the usual "X" vector of covariates and one id variable which will make up the random intercept. Now I wish to add group-level predictors (which are NOT in the X vector) such that the random intercept depends on these predictors.
For example, 
Response variable: Production of maize
Covariate: Size of plot
Group-level predictor: Age of farmer
ID variable: Household_ID

I wish to confirm the syntax for including the group-level "Age of farmer" variable.
fit<-lmer(Production~ Size+ Age+ (1|Household_ID), data=data)

Is this correct or is there another way of declaring the group-level predictor in the formula?

Thank you

**Comment by dmbates** [comment]
Yes, your formulation is correct.

I would mention two additional points:
- it is best to send questions of usage like this to the R-SIG-Mixed-Models@R-project.org mailing list (see https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models for details).  Often the responses from that list are faster than from an issue in this repository.
- the concept of the "level" of a covariate in the fixed-effects is a distraction (sometimes called a "red herring" in colloquial English).  It is an artifact of the way that "multilevel" models were formulated and not relevant in the formulation we use.

**Comment by yashreem** [comment]
Thank you very much for your reply. This was very helpful.

**Comment by yashreem** [comment]
Can you please explain your second point in detail: How would one then interpret the beta coefficient of "size" covariate?

**Comment by bbolker** [comment]
With Doug's permission, you could post his comment and your question on `r-sig-mixed-models` ... better to have those kinds of questions viewable, and answerable, by a broader audience.

**Comment by yashreem** [comment]
Now I am wondering how does lmer
really distinguish between the usual X covariates and group-level
predictors? We have not really differentiated them in the formula. How does
lmer construe Age to only impact the random intercept?

Thank you very much,

Regards,

Yashree

**Comment by dmbates** [comment]
For fixed-effects terms there is no distinction between covariates defined at different "levels".  You are assuming that the model is defined and the parameters estimated as described in the multilevel modeling literature.  It isn't.  We described the methods that are used in lme4 in a [paper](https://www.jstatsoft.org/article/view/v067i01) where you can see that they do not involve levels in either the definition of the model or the evaluation of the likelihood.

**Comment by yashreem** [comment]
Alright. Thanks for the explanation.

**Comment by AntonGollwitzer** [comment]
Actually, your formula has a Type I error problem. You must include the random slope of size of plot. 

So: fit<-lmer(Production~ Size+ Age+ (1+Size|Household_ID), data=data)

See here:
https://www.researchgate.net/publication/322600137_Why_You_Should_Always_Include_a_Random_Slope_for_the_Lower-Level_Variable_Involved_in_a_Cross-Level_Interaction

**Comment by bbolker** [comment]
See also Schielzeth, Holger, and Wolfgang Forstmeier. “Conclusions beyond Support: Overconfident Estimates in Mixed Models.” Behavioral Ecology 20, no. 2 (March 1, 2009): 416–20. https://doi.org/10.1093/beheco/arn145.

**Comment by AntonGollwitzer** [comment]
Oh also, Ben while you're here. Can I ask a quick question? If I have a single group level predictor and a individual-level outcome variable, can I write an Lmer just for the single group-level predictor. So for instance, say I'm predicting weight for individuals based off of ice cream sales and I have samples in many different countries. Note that weight varies by individual, but ice-cream sales are at the group level so each country has a single unique ice-cream sales amount. The data is set up as follows: 
1 column is participant number (id). Let's say 1,000 rows. 
1 column is weight (weight) the value is unique for each participant.
1 column is country (country) the name of each country. Country is not unique to participant (i.e., there are many participants in each country). 
1 column is ice cream sold (iceSales). iceSales is not unique to participant as it is at the country level. That is, it is unique to country (i.e., the same ice cream sale value is found for all participants based on the country they are in). 

Could I simply do:

fit<-lmer(weight~ iceSales + (1|Country), data=data)

I know that there are cases where crossed level interactions are asked (like the original question in this thread). But in this case, all I care about is the group-level effect. So, relating this back to the original question here, could someone do: 

fit<-lmer(Production~ Age+ (1|Household_ID), data=data)
