### ISSUE TITLE
Using lmm to perform ICC for reliability study (not a technical issue)

### ISSUE THREAD

**Issue by bernard-liew** [lme4/lme4#475]
Dear In-Charge,

 Forgive me if this is inappropriate, and please delete this issue if so. I am doing a reliability study, using the methods of https://www.ncbi.nlm.nih.gov/pubmed/28505546. I have a question on the lmer formulation and the use of the variance components.

Background: I have 20 subjects, 2 fixed raters, 2 testing sessions, and 10 trials per sessions. my dependent variable is a continuous variable (scale 1-10). Sessions are nested within each subject-assessor combination. I desire a ICC (3) formulation of inter-rater and inter-session reliability from the variance components.

My lmer model is:

lmer (dv ~ rater + (1|subj) + (|subj:session), data = df)

Question: 
1) is the model formulation right? and is my interpretation of the variance components right?
2)  inter-rater ICC = var (subj) / (var(subj) + var (residual)) # I read that the variation of raters will be lumped with the residual
3) inter-session ICC =( var (subj) + var (residual)) /( var (subj) + var (subj:session) + var (residual))  

I appreciate the kind response.

Kind regards,
Bernard

**Comment by bbolker** [comment]
The model formulation looks reasonable (did you mean to leave out the 1 in the second random-effects term, i.e. `(1|subj:session)`?  You could also express it (equivalently) as `~ rater + (1|subj/session)` ...  I *think* your ICC calcs are OK, but it would be better to post this to `r-sig-mixed-models@r-project.org`, where it will be more widely read (and read by people with more experience in ICC).
