### ISSUE TITLE
Parallel allFit

### ISSUE THREAD

**Issue by sciatro** [lme4/lme4#477]
`allFit` is a a very helpful part of the package, albeit a somewhat hidden one. For larger fits it takes a long time. Could the loop over the various optimizers be made (optionally if dependencies are a concern) parallel to speed things up on multi-core systems?

**Comment by bbolker** [comment]
this is added (not yet well tested!) in c77f0659807c8a7d6aed245e8e3f724b6da2eeab

**Comment by bbolker** [comment]
closing until such time as someone finds that it doesn't actually work ...
