### ISSUE TITLE
coerce vcov from dpoMatrix to regular matrix?

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#488]
There turn out to be contexts where downstream package authors assume they can take `diag(vcov(x))`, which doesn't work if the right `Matrix` methods aren't available ("Error in diag(x) : no method for coercing this S4 class to a vector").  

For example, see the examples of `influence.merMod`: https://github.com/lme4/lme4/blob/master/man/influence.merMod.Rd#L105

How wrong would it be to coerce the output of `vcov.merMod` to be an ordinary matrix rather than a dpoMatrix? 

(particularly interested in @mmaechler's opinion on this one)

**Comment by mmaechler** [comment]
Please don't go to use `as.matrix()` here.  `"dpoMatrix" ` implicitly knows already properties R code can and will reuse.
I'm finally -- after looking now -- almost sure there is a bug here, not in `lme4` but I think in R. I may be able to workaround the bug in the next version of `Matrix` which is "imminent" (well, rev.dep checks gave errors which I think are spurious).   I hope to get back to this later today, or at least with 24h.  (busy teaching, et al)

**Comment by bbolker** [comment]
OK, thanks!  Since I didn't have a reason beyond minor convenience, if you say there's a good reason I'm perfectly happy to leave it as is.

**Comment by mmaechler** [comment]
>>>>> Ben Bolker 
>>>>>     on Mon, 29 Oct 2018 12:38:35 +0000 writes:

    > OK, thanks!  Since I didn't have a reason beyond minor
    > convenience, if you say there's a good reason I'm
    > perfectly happy to leave it as is.

A workaround for now, we can do in lme4 code: add is to use  Matrix::diag()
instead of  diag(),  i.e., e.g.

  Matrix::diag(vcov( * ))   instead of
          diag(vcov( * ))

Martin

**Comment by bbolker** [comment]
Thanks.  The main problem/reason I might have wanted to make this change is for compatibility with downstream code that we don't control (e.g. `car::influence.merMod()`, `stats::confint.default()`) that assumes that `diag(vcov(.))` will work without specification or coercion ...
