### ISSUE TITLE
Model failed to converge with max|grad|

### ISSUE THREAD

**Issue by Valabe** [lme4/lme4#489]
I have to run a lmer with a log transformed response variable, a continuous variable as fixed effect and and a nested random effect:

`first<-lmer(logterrisize~spm + (1|studyarea/teriid),
            data = Data_table_for_analysis_Character_studyarea,
            control=lmerControl(optimizer="Nelder_Mead",
                                 optCtrl=list(maxfun=1e4)))`

I got this error message: Error in length(value <- as.numeric(value)) == 1L : Downdated VtV is not positive definite

I tried this with bobyqa() as optimization argument and got this warning messages:

`1: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, : 
Model failed to converge with max|grad| = 0.753065 (tol = 0.002, component
1) 2: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,:
Model is nearly unidentifiable: very large eigenvalue-Rescale variables?`

my summary looks like this:

`Linear mixed model fit by REML ['lmerMod'] 
Formula: logterrisize ~ spm + (1 studyarea/teriid) Data: Data_table_for_analysis_Character_studyareaControl: lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 10000)) REML criterion at convergence: -6079.6Scaled residuals: 
   Min         1Q     Median         3Q        Max 
-3.639e-07 -4.962e-08  3.310e-09  5.293e-08  9.725e-07 
Random effects:
 Groups           Name        Variance  Std.Dev.
 teriid:studyarea (Intercept) 1.291e-01 3.593e-01
 studyarea        (Intercept) 1.944e-02 1.394e-01
 Residual                     4.506e-15 6.712e-08
Number of obs: 273, groups:  teriid:studyarea, 66; studyarea, 22
Fixed effects:
 Estimate Std. Error t value
(Intercept)  1.480e+00  5.631e-02   26.28
spm         -5.785e-16  8.507e-10    0.00
Correlation of Fixed Effects:
 (Intr) spm 0.000  convergence code: 0
Model failed to converge with max|grad| = 0.753065 (tol = 0.002, component1)
Model is nearly unidentifiable: very large eigenvalue - Rescale variables?`

my data looks like following:

show(logterrisize) [1] 1.3317643 1.3317643 1.3317643 0.1295798 0.1295798 1.5051368 1.5051368 1.5051368 1.5051368 [10] 1.5051368 1.5051368 1.5051368 1.5051368 1.5051368 1.5051368 1.5051368 1.5051368 1.5051368 [19] 1.5051368 1.5051368 1.5051368 1.4665993 1.4665993 1.4665993 1.8282328 1.8282328 1.9252934 [28] 1.9252934 1.9252934 2.3006582 2.3006582 2.5160920 2.7774040 2.7774040 3.3398623 3.3398623 [37] 3.4759297 1.2563594 1.6061204 1.6061204 1.7835139 1.7835139 2.1669498 2.1669498 2.1669498 [46] 2.1669498 0.7264997 0.7458155 0.8380524 0.8380524 0.8380524 0.8380524 0.8380524 0.8380524

 show(spm)  [1] 18.461538 22.641509 35.172414 10.418006 15.611285  3.482143  3.692308  4.483986  4.821429 [10]  6.000000  6.122449  6.176471  6.220736  6.260870  6.593407  7.010309  9.200000  9.473684 [19]  9.600000 12.600000 14.200000 16.146179 28.125000 30.099010 13.731343 14.432990 11.089109 [28] 17.960526 32.903226  8.955224 33.311688  8.800000 11.578947 20.000000 14.455446 18.181818 [37] 28.064516 25.684211 17.866667 23.142857 18.208955 20.536913 11.419355 11.593220 12.703583 [46] 20.000000  3.600000 11.320755  6.200000  6.575342 12.800000 19.109589 20.124224 22.941176 [55]  4.600000  6.600000  6.771160  8.000000 19.200000 19.400000 22.773723  3.333333  4.214047
Studyarea are character names and teriID represents continuous numbers of the study sites.

Did I forget anything to include to the equation while using a log transformed variable? Thanks!

EDIT: I used ?convergence to check on convergence errors. I tried this:

## 3. recompute gradient and Hessian with Richardson extrapolation

`devfun <- update(first, devFunOnly=TRUE)
if (isLMM(first)) {
pars <- getME(first,"theta")
} else {## GLMM: requires both random and fixed parameters
pars <- getME(first, c("theta","fixef"))
}
if (require("numDeriv")) {
 cat("hess:\n"); print(hess <- hessian(devfun, unlist(pars)))
cat("grad:\n"); print(grad <- grad(devfun, unlist(pars)))
cat("scaled gradient:\n")
print(scgrad <- solve(chol(hess), grad))}`

and got this answer:

`hess:
      [,1]      [,2]
[1,] 147.59157 -14.37956
[2,] -14.37956 120.85329
grad:
[1] -222.1020 -108.1038
scaled gradient:
[1] -19.245584  -9.891077
`
Unfortunately I don´t know what the answer should tell me.

**Comment by Valabe** [comment]
Just forgot, I also crossposted this question on stackoverflow: https://stackoverflow.com/questions/53034261/warning-lme4-model-failed-to-converge-with-maxgrad

**Comment by bbolker** [comment]
Please don't crosspost (but thanks for saying that you did, and providing the link).  I've answered on SO: the basic problem is that you have multiple observations in your data set of territory size per territory ID, but they all have the same response value, so your territory-ID random effect is confounded with everything else.

**Comment by AnahiF** [comment]
Hi!! I have the same problem of Valabe, and I would like how can I resolve it. This is my model:
`M.4=glmer(Cuenta~carga*categ.asoc+(1|campo/foto) +offset(log(area.foto)),family=poisson(link = "log"),data=tipocat)`    
And my datatable is attached. I hope you can help me! 
[data.xlsx](https://github.com/lme4/lme4/files/4369867/data.xlsx)

**Comment by bbolker** [comment]
Could you please post this question to r-sig-mixed-models@r-project.org?  The basic issue is that you have something like complete separation (extreme parameter values) because you have very little data in your baseline level) - 10 values all equal to exactly 1.

```
with(tipocat,table(categ.asoc,Cuenta))

library(dotwhisker)
library(broom.mixed)
dwplot(M.4,effects="fixed")
library(ggplot2); theme_set(theme_bw())
ggplot(tipocat,aes(carga,Cuenta/area.foto,colour=categ.asoc))+
    stat_sum(alpha=0.5)+facet_wrap(~categ.asoc,nrow=1)
```

```
library(dotwhisker)
library(broom.mixed)
dwplot(M.4,effects="fixed")
library(ggplot2); theme_set(theme_bw())
ggplot(tipocat,aes(carga,Cuenta/area.foto,colour=categ.asoc))+
    stat_sum(alpha=0.5)+facet_wrap(~categ.asoc,nrow=1)
```

**Comment by AnahiF** [comment]
Thank you for your quick response!!
