### ISSUE TITLE
allFit print method throws error

### ISSUE THREAD

**Issue by ctgrubb** [lme4/lme4#490]
allFit's print method is throwing an error. Summary seems to work fine.

gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
             data = cbpp, family = binomial)

gm_all <- allFit(gm1)
gm_all

Error in FUN(X[[i]], ...) : 
  trying to get slot "className" from an object of a basic class ("logical") with no slots

**Comment by bbolker** [comment]
thanks!
