### ISSUE TITLE
simulate.merMod: non-conformable arrays

### ISSUE THREAD

**Issue by LisetteVaja** [lme4/lme4#493]
When using the following code adapted from [here](https://gist.github.com/tmalsburg/df66e6c2ab494fad83ee):

`lmm1 <- lmer(activity ~ dpi + Genetic_Group + Sex +  (1|Pen) + (1|pig_id) , df_prechallenge)
df$simulated <- simulate(lmm1, seed=1, newdata=df[-4], re.form=NA, allow.new.levels=T)$sim_1 `

It results in the following error: 
`Error in sim.reff + if (cond.sim) matrix(rnorm(n * nsim), ncol = nsim) else 0 : 
  non-conformable arrays`

I already dropped the 'activity' column, so I'm lost on what to do to solve this. I would like to obtain predicted values for all data from my model (lmer) based on the first 23 days (dpi). So I run my model on a subset, and try to predict values on the whole data frame. 

The predict works fine! 
`df$predict <- predict(lmm1, newdata = df, allow.new.levels=T)`
However, I believe that predict doesn't take my random effects into account?

**Comment by bbolker** [comment]
Can we have a reproducible example please?  I've simulated some data that look as much like your data as I can manage, but it doesn't give the same error.  At the very least, can we see `str(df_prechallenge)` and `str(df[-4])`? 

```
set.seed(101)
dd <- data.frame(activity=rnorm(1000),
                 dpi=rnorm(1000),
                 Genetic_Group=factor(sample(1:5,size=1000,replace=TRUE)),
                 Sex=sample(c("F","M"),size=1000,replace=TRUE),
                 Pen=sample(1:20,size=1000,replace=TRUE),
                 pig_id=sample(1:100,size=1000,replace=TRUE))
library(lme4)
form <- activity ~ dpi + Genetic_Group + Sex + (1|Pen) + (1|pig_id)
mm <- model.matrix(nobars(form)[-2],data=dd)
dd$activity <- simulate(form,
         family=gaussian,
         newdata=dd,
         newparams=list(beta=rnorm(ncol(mm)),
                        theta=c(2,2),
                        sigma=1))[[1]]
lmm1 <- lmer(form , data=dd)

ns <- 5
simdd <- data.frame(
                 dpi=rnorm(ns),
                 Genetic_Group=factor(sample(1:5,size=ns,replace=TRUE)),
                 Sex=sample(c("F","M"),size=ns,replace=TRUE),
                 Pen=20+(1:ns),  ## make sure we have new levels
                 pig_id=sample(1:110,size=ns,replace=TRUE))

simulate(lmm1, seed=1, newdata=simdd, re.form=NA, allow.new.levels=TRUE)
```
