### ISSUE TITLE
release-critical/wishlist for 1.1-20?

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#498]
CRAN is asking for a new lme4 version by January 27 (not our fault; flags popping up because of various changes on the CRAN side).  AFAICT we've fixed the issues that CRAN wants resolved, and the current master branch (which includes the switch to `nloptwrap`) doesn't cause any reverse-dependency problems.  Are there any other *minor* updates that we'd like to sneak in at this point? My list:

- send a heads-up e-mail to `r-sig-mixed-models` about the change in optimizer ...
- revisit the `influence.merMod` stuff: I recall there were some loose ends there that John Fox had commented on.

**Comment by dmbates** [comment]
Sounds good to me
