### ISSUE TITLE
Can I set random effects a constant while fitting a lmer model？

### ISSUE THREAD

**Issue by Simon-Zhen** [lme4/lme4#499]
I have a dataset, called `data_a`, and a `lmer()` model as follows:

```
fit_lmer <- lmer(formula = pxi_formula, data = data_a, REML = FALSE)
fit_lmer 
Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: y ~ (1 | p) + (1 | i)
   Data: data_long
      AIC       BIC    logLik  deviance  df.resid 
 34139.66  34165.73 -17065.83  34131.66      4996 
Random effects:
 Groups   Name        Std.Dev.
 p        (Intercept) 2.213   
 i        (Intercept) 5.822   
 Residual             7.067   
Number of obs: 5000, groups:  p, 100; i, 50
Fixed Effects:
(Intercept)  
     0.8251 
```

which contain two random effects, p(2.213) and i(5.822), and the residual(7.067). 
Now there another dataset, called `data_b`, with the same structure. I would like to set the two random effects and the residual as the same(p effect = 2.213, i effect = 5.822, residual = 7.067), and test how it fits to `data_b`. How should I do? (Or in other words, use the model fit_lmer(estimated from data_a) to fit data_b)
refit() doesn't work because two dataset gose different
May the argument "offset" in lmer() works? I don't know how to write this code.

**Comment by bbolker** [comment]
This is not too hard, and I'll answer it here, but I'd like to ask that in future you ask questions like this on `r-sig-mixed-models@r-project.org`, where it will reach a wider audience: see the [where to ask? section of the README](https://github.com/lme4/lme4/#where-to-get-help).

The code below does what you want, I think. *Warning*: you shouldn't compare the deviances/REML criteria *between* data sets, only between parameters for the *same* data set; almost all statistical theory compares fits of different models to the same data set.

First try: this holds the RE variances constant, but not the residual variance.

```
library(lme4)
## fit original model
fm1 <- lmer(Reaction~Days+(Days|Subject), sleepstudy)

## construct new data
newdata <- sleepstudy
newdata$Reaction <- simulate(fm1,seed=101)[[1]]

## build model with the same formula, options etc., but new response var
fm2 <- update(fm1, data=newdata)
## extract the deviance (actually the REML-criterion) function
ff <- as.function(fm2)
## evaluate REML criterion at parameter values (RE only) estimated for data set 1
REML1 <- ff(getME(fm1,"theta"))
## check: evaluate at parameter values estimated for data set 2
(REML2 <- ff(getME(fm2,"theta")))
## should be the same as what we get directly from the model
all.equal(REMLcrit(fm2),REMLcrit(fm2))
```

Second try: this uses `devfun2()` to fix the residual variance as well, but can only be done with ML (not REML) fits:
```
fm1ML <- refitML(fm1)
fm2ML <- refitML(fm2)
## convert
p1 <- Cv_to_Sv(getME(fm1ML,"theta"), s= sigma(fm1ML))
p2 <- Cv_to_Sv(getME(fm2ML,"theta"), s= sigma(fm2ML))
ff2 <- devfun2(fm2ML, useSc=TRUE)
ff2(p1)
ff2(p2)
deviance(fm2ML)
```

**Comment by Simon-Zhen** [comment]
> This is not too hard, and I'll answer it here, but I'd like to ask that in future you ask questions like this on `r-sig-mixed-models@r-project.org`, where it will reach a wider audience: see the [where to ask? section of the README](https://github.com/lme4/lme4/#where-to-get-help).
> 
> The code below does what you want, I think. _Warning_: you shouldn't compare the deviances/REML criteria _between_ data sets, only between parameters for the _same_ data set; almost all statistical theory compares fits of different models to the same data set.
> 
> First try: this holds the RE variances constant, but not the residual variance.
> 
> ```
> library(lme4)
> ## fit original model
> fm1 <- lmer(Reaction~Days+(Days|Subject), sleepstudy)
> 
> ## construct new data
> newdata <- sleepstudy
> newdata$Reaction <- simulate(fm1,seed=101)[[1]]
> 
> ## build model with the same formula, options etc., but new response var
> fm2 <- update(fm1, data=newdata)
> ## extract the deviance (actually the REML-criterion) function
> ff <- as.function(fm2)
> ## evaluate REML criterion at parameter values (RE only) estimated for data set 1
> REML1 <- ff(getME(fm1,"theta"))
> ## check: evaluate at parameter values estimated for data set 2
> (REML2 <- ff(getME(fm2,"theta")))
> ## should be the same as what we get directly from the model
> all.equal(REMLcrit(fm2),REMLcrit(fm2))
> ```
> Second try: this uses `devfun2()` to fix the residual variance as well, but can only be done with ML (not REML) fits:
> 
> ```
> fm1ML <- refitML(fm1)
> fm2ML <- refitML(fm2)
> ## convert
> p1 <- Cv_to_Sv(getME(fm1ML,"theta"), s= sigma(fm1ML))
> p2 <- Cv_to_Sv(getME(fm2ML,"theta"), s= sigma(fm2ML))
> ff2 <- devfun2(fm2ML, useSc=TRUE)
> ff2(p1)
> ff2(p2)
> deviance(fm2ML)
> ```

Thanks a lot and so annoy to bother you
