### ISSUE TITLE
How to resolve the error about “mkRespMod” on lme4

### ISSUE THREAD

**Issue by 51sep** [lme4/lme4#503]
I got the error the below. I couldn’t find why the error was happened. 
If possible, could you give me some advice?

```
mkRespMod(fr, nlenv = nlenv, nlmod = nlmod) 
```
> ERROR: is.numeric(val <- eval(nlmod, nlenv)) is not TRUE

This is my program. I’d like to want the four parameters(v, ke,ka1,ka2).
If it’s an easy mistake, sorry about that..

```
model <- function(Time,vd, k10,k12,k21) {
    v <- vd
   ke <- k10
   ka1 <- k12
   ka2 <- k21
  ALPHA<-((ke+ka1+ka2)+sqrt((ke+ka1+ka2)**2-4*ka2*ke))/2;
  BETA <-((ke+ka1+ka2)-sqrt((ke+ka1+ka2)**2-4*ka2*ke))/2;
  A<-100/v*(ALPHA-ka2)/(ALPHA-BETA);
 B<-100/v*(ka2-BETA)/(ALPHA-BETA);
 f <- A * exp(-ALPHA * Time) + B * exp(-BETA * Time)
  return(f)
}

nfun<-deriv(~model, namevec=c("vd","k10","k12","k21"), 
function.arg=c("Time","vd","k10","k12","k21"))
nlmer.2cbr<-nlmer(Concentration~nfun(Time, vd, k10, k12, k21) ~ (vd|Id)+(k10|Id)+(k12|Id)+(k21|Id),
                  data=dt00,
                  start=list(nlpars= c(vd=500, k10=0.1, k12=0.2, k21=0.1)),
                  verbose = T)
```

**Comment by bbolker** [comment]
This was much harder than I expected/than it probably should be.  Bottom line,  it seems you need to specify the model to `deriv()` as an **expression**.  My fit failed with these particular made-up data, but that's a different problem ...

```
library(lme4)
library(ggplot2)

model <- function(Time,v, ke,ka1,ka2) {
    ALPHA <- ((ke+ka1+ka2)+sqrt((ke+ka1+ka2)**2-4*ka2*ke))/2
    BETA <- ((ke+ka1+ka2)-sqrt((ke+ka1+ka2)**2-4*ka2*ke))/2
    A <- 100/v*(ALPHA-ka2)/(ALPHA-BETA)
    B <- 100/v*(ka2-BETA)/(ALPHA-BETA)
    f <- A * exp(-ALPHA * Time) + B * exp(-BETA * Time)
  return(f)
}

nId <- 20
dd <- expand.grid(Id=factor(1:nId),Time=0:20)
set.seed(101)
parms <- data.frame(Id=factor(1:nId),
                    v=rnorm(nId,mean=500,sd=50),
                    ke=rnorm(nId,mean=0.1,sd=0.01),
                    ka1=rnorm(nId, mean=0.2, sd=0.02),
                    ka2=rnorm(nId, mean=0.1, sd=0.01))
dd <- merge(dd,parms,by="Id")

## apply converts to a matrix -- need to ditch Id column first
dd2 <- dd
dd2$Concentration0 <- apply(dd[-1], 1, function(x) do.call(model, as.list(x)))
dd2$Concentration <- dd2$Concentration0+rnorm(nrow(dd),0,sd=0.001)

library(ggplot2)
ggplot(dd2,aes(Time,Concentration0,colour=Id))+
    geom_line()+
    geom_point(aes(y=Concentration))

nfun <- deriv(~model, namevec=c("v","ke","ka1","ka2"), 
              function.arg=c("Time","v","ke","ka1","ka2"))

## examine nfun: it's not right

## http://adv-r.had.co.nz/Computing-on-the-language.html#substitute
substitute_q <- function(x, env) {
    call <- substitute(substitute(y, env), list(y = x))
    eval(call)
}

f <- expression(A * exp(-ALPHA * Time) + B * exp(-BETA * Time))
ss <- list(f=quote(A * exp(-ALPHA * Time) + B * exp(-BETA * Time)),
           ALPHA=quote(((ke+ka1+ka2)+sqrt((ke+ka1+ka2)**2-4*ka2*ke))/2),
           BETA=quote(((ke+ka1+ka2)-sqrt((ke+ka1+ka2)**2-4*ka2*ke))/2),
           A=quote(100/v*(ALPHA-ka2)/(ALPHA-BETA)),
           B=quote(100/v*(ka2-BETA)/(ALPHA-BETA)))
## need to substitute A, B first ...
ss2 <- substitute_q(ss$f,ss[c("A","B")])
## then ALPHA, BETA
ss3 <- substitute_q(ss2,ss[c("ALPHA","BETA")])

## now derivfun works
nfun <- deriv(ss3,namevec=c("v","ke","ka1","ka2"), 
      function.arg=c("Time","v","ke","ka1","ka2"))

## nfun isn't right ...
nlmer.2cbr <- nlmer(Concentration~nfun(Time, v, ke, ka1, ka2) ~
                        (v|Id)+(ke|Id)+(ka1|Id)+(ka2|Id),
                    data=dd2,
                    start=list(nlpars= c(v=500, ke=0.1, ka1=0.2, ka2=0.1)),
                    verbose = TRUE)
```

**Comment by bbolker** [comment]
closing this; feel free to reopen if necessary.

**Comment by 51sep** [comment]
Thank you very much! My program run! I got the result!
Anyway. actually, your sample didn't run on my PC environment.
I got the following Error. Maybe, it would be because of dummy data, I think.

::::::
length(value <- as.numeric(value)) == 1L ERROR
  step factor reduced below 0.001 without reducing pwrss
1: sqrt(.expr7):NaN
2: sqrt(.expr7):NaN
::::::

I would resolve this error too?
If possible, could you give me some advice again?

**Comment by bbolker** [comment]
My sample didn't run in *my* environment either - I think it's because I made up data with insufficient contrast ...  do you *need* it to run, or do you have data that produce the same kind of errors?

**Comment by 51sep** [comment]
I tried it again.
Hm..., I got the same following ERROR on my another data… maybe, it’s like yours.
::::::
length(value <- as.numeric(value)) == 1L ERROR
  step factor reduced below 0.001 without reducing pwrss

or

th(value <- as.numeric(value)) == 1L ERROR 
  Downdated VtV is not positive definite
::::::

At first, it was my lucky dummy data? I don’t know…
Anyway, here is my dummy data.
`	Id	Dose	Time	Concentration	Weight	Sex
1	1	100	5	1.625	79.6	1
2	1	100	10	1.384	79.6	1
3	1	100	15	1.28	79.6	1
4	1	100	20	1.105	79.6	1
5	1	100	30	0.973	79.6	1
6	1	100	45	0.806	79.6	1
7	1	100	60	0.74	79.6	1
8	1	100	90	0.582	79.6	1
9	1	100	120	0.53	79.6	1
10	1	100	150	0.458	79.6	1
11	1	100	180	0.416	79.6	1
12	1	100	240	0.342	79.6	1
13	1	100	300	0.321	79.6	1
14	1	100	360	0.246	79.6	1
15	2	150	5	1.525	89.6	1
16	2	150	10	1.384	89.6	1
17	2	150	15	1.1	89.6	1
18	2	150	20	1.05	89.6	1
19	2	150	30	0.873	89.6	1
20	2	150	45	0.806	89.6	1
21	2	150	60	0.74	89.6	1
22	2	150	90	0.582	89.6	1
23	2	150	120	0.53	89.6	1
24	2	150	150	0.458	89.6	1
25	2	150	180	0.416	89.6	1
26	2	150	240	0.31	89.6	1
27	2	150	300	0.29	89.6	1
28	2	150	360	0.246	89.6	1
`
This was OK, but actually, it was only two subjects(n=2), and plus the following WORNING. And now, I tried for n=3, 4, 5. These were NG(not run: I got the same errors)… I didn’t know why… Sorry about that
::::::
1: vcov.merMod(object, use.hessian = use.hessian)
  variance-covariance matrix computed from finite-difference Hessian is
not positive definite or contains NA values: falling back to var-cov estimated from RX
::::::

++++++++++++++++
By the way, I have read about the same ERROR “Downdated VtV is not positive definite” on this site. The issue would be same as my data? Actually, whenever I get this error, I can’t find the result. Always it bother me...
::::::
Downdated VtV is not positive definite
::::::
If you know something about that and including my this issue, please give me advice...
