### ISSUE TITLE
1.1.21 release plans

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#506]
CRAN would like a new release soon (to deal with ERRORs on windows-oldrel and Solaris); these issues have already been fixed in the development version ...

There are plenty of issues on the table that we *could* try to address before submission: #502 (changing "singular fit" message); #501 (documentation/wording changes around convergence tests); #495 (suppressing multiple messages in bootMer etc.) There have also been (unconfirmed) reports that the new release is considerably slower [this was via e-mail, I can't find it now, and the original e-mailer hasn't gotten back to me ...]

Most of issues above are *documentation fixes*.  More radically, we could reduce the default `xtol_abs` and `ftol_abs` from 1e-6 to 1e-8. I don't know that the original values were chosen absolutely systematically; we had a consultant (Gabor Grothendieck) working on lme4.0/lme4 issues a few years ago. On principle I think this move (changing to a slower but safer default) is a good idea, but I'm worried about sparking another round of downstream-package issues ...

On balance, I think I'd like to *not* do the tolerance changes in a hurry. We nominally have a one-month blackout period before submitting again ([CRAN repo policy](https://cran.r-project.org/web/packages/policies.html) says '“no more than every 1–2 months” seems appropriate'), but practically speaking it usually takes us several weeks to get things together anyway ...

Opinions?

**Comment by bbolker** [comment]
Bump. Any thoughts?  At this point I've more or less resolved #495, #502.  Would be happy to accept documentation patches (#501).  Current version *appears* to pass on r-devel (Ubuntu), R-release+devel (win-builder), revdep-check (not Travis! need to sort that out ...) Current plan:

- announce on r-sig-mixed
- e-mail all downstream maintainers (I don't *think* anything's wrong, but we've been bitten by false negatives from revdep checking in the past)
- submit to CRAN sometime in the next week?

**Comment by palday** [comment]
I think the documentation fixes discussed in #501 would be a nice little "cheap" update. This would also be a nice waffle on the tolerance issue: include notes on the different default tolerances and the different meanings of the different tolerance parameters in `bobyqa`, `nloptwrap`, etc. I unfortunately won't get around to contributing this myself in time for the proposed release schedule.

**Comment by bbolker** [comment]
@palday: do you have time to take a quick look at https://github.com/lme4/lme4/blob/master/man/convergence.Rd ?

**Comment by palday** [comment]
Looks quite nice, a few small comments:

1. There's no mention of how to set the maximum number of iterations for `nloptwrap` (or did I miss it?) It's `maxeval`, if I recall correctly.
2. The tolerances mention "function value", but don't mention that the function in question is the deviance / likelihood (I think). I'm not sure if that comprehension hurdle is a good shibboleth for tinkering with the settings or should rather be documented.
3. In a similar vein, I don't know if we should explicitly mention that a the default `ftol` settings in `nloptwrap` can lead to optimization ending much sooner than the maximum number of iterations -- and potentially a fit very far from the optimum when the likelihood surface is quite flat (which I think is a situation the Barr et al. "keep it maximal" advice tends to create). This seems to be the biggest cause of non-convergence of `nloptwrap` fits that work with `bobyqa`.

**Comment by bbolker** [comment]
See what you think of  45c900d .  In particular I added

>    Changing \code{ftol_abs} and \code{xtol_abs} to stricter values (e.g. 1e-8) is a good first step for resolving convergence problems, at the cost of slowing down model fits.

**Comment by palday** [comment]
Looks good! The small heading/organizational change suggested by @mmaechler  won't change anything for a normal user. This is a huge boost having all of this available directly instead of having to search through the `nloptr` documentation.

**Comment by bbolker** [comment]
Submitting to CRAN today, hopefully (running one last round of tests).
