### ISSUE TITLE
suggest: rmarkdown?

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#509]
building on r-hub Solaris platform complains about:

> * checking re-building of vignette outputs ... NOTE
> Error in re-building vignettes:
> Warning in engine$weave(file, quiet = quiet, encoding = enc) :
> The vignette engine knitr::rmarkdown is not available, because the rmarkdown package is not installed. Please install it.

This is something we haven't seen from CRAN (yet), but should maybe be dealt with.  We have `VignetteBuilder: knitr` in the DESCRIPTION file, and `knitr` is in Suggests:.  I'm a little concerning about what other dependencies `Suggests: rmarkdown` will drag in, but maybe it's not so bad? (We already have `Suggests: testthat`.

**Comment by palday** [comment]
Have the knitr dependencies changed recently? What's the difference in dependencies between `knitr` and `rmarkdown`? I suspect most people who have `knitr` installed also have `rmarkdown` installed, so the difference shouldn't be huge for the average user.

**Comment by bbolker** [comment]
I think this has probably been around since we first added a markdown-based vignette, and that we haven't seen it before because we've never tried to test it on a system without `rmarkdown` installed. (As mentioned above, I saw this on an r-hub check.)

**Comment by singmann** [comment]
I can confirm that in `afex` I had to add `rmarkdown` to `Suggests` to get rid of all `R CMD check` messages after having a vignette with: `%\VignetteEngine{knitr::rmarkdown}`
I might have also only noticed this after checking on a new machine without `rmarkdown` installed.

**Comment by bbolker** [comment]
added to Suggests in 8cbaef9a6
