### ISSUE TITLE
warning with `3.6.0` 

### ISSUE THREAD

**Issue by IndrajeetPatil** [lme4/lme4#510]
With development version of R (`3.6.0`), I get the following warning when `lme4` is loaded after `car`-
```r
Registered S3 methods overwritten by 'lme4':
  method                          from
  cooks.distance.influence.merMod car 
  influence.merMod                car 
  dfbeta.influence.merMod         car 
  dfbetas.influence.merMod        car 
```

**Comment by bbolker** [comment]
That's as expected.  We've coordinated pretty carefully with John Fox to make sure that our versions are actually compatible.  At  some point in the future, presumably these methods will move out of `car` and live only in `lme4`.

**Comment by IndrajeetPatil** [comment]
Just a reminder that since `R 3.6.0` is now the current release, everyone is seeing these warnings; not just people who were experimentally using the development version of R.

**Comment by IndrajeetPatil** [comment]
@bbolker Any update on this? 

In an e-mail exchange, John had also mentioned that these methods will be removed from `car`. 

> The current versions of the car and lme4 packages both have influence.merMod() and related methods. They are essentially the same and the redundant functions will eventually be removed from the car package, with the following caveat: influence.merMod() in the development version of the car package on R-Forge supports parallel computation while influence.merMod() current in lme4 does not.

So I am wondering if I should raise this issue on `car` repo instead?

**Comment by bbolker** [comment]
Maybe? If `car` is going to remove them, then the message will go away when it does.  I don't know if John needs a reminder.  From that point of view there is no action required in `lme4`.  But it would be good either to raise a new issue to remind me (or someone else! I'll happily accept a pull request) to parallelize `influence.merMod`, or to edit the title of this issue accordingly ...  should be reasonably straightforward, the relevant code is [here](https://github.com/lme4/lme4/blob/master/R/methods.R#L71-L91) ...

**Comment by IndrajeetPatil** [comment]
I would have liked to make a `PR` if it was just a matter of replacing that small portion of code, but I compared the codes between `car:::influence.merMod` and `lme4:::influence.merMod` and they are not so similar. 
So it would be better if someone who is intimately aware of these details makes these changes. 

I can open a new issue so that someone else might take a stab at this.

**Comment by IndrajeetPatil** [comment]
Closing in favor of #607
