### ISSUE TITLE
allFit doesn't set optCtrl$algorithm for nloptwrap

### ISSUE THREAD

**Issue by scjs** [lme4/lme4#511]
https://github.com/lme4/lme4/blob/5c4aea18f79909bb8648fa2b9058ecf35cc8861f/R/allFit.R#L106

I think that `nloptWrap` here should have a lowercase `w` instead of a capital `W`, or this switch case doesn't come up when using the default `meth.tab` argument (line 7), and it will use the default `nloptwrap` algorithm both times.

**Comment by bbolker** [comment]
To be clear: are you proposing this as a solution to the issue?  Any chance you can give us a reproducible example? (It saves us a small amount of effort inventing one ourselves.)

**Comment by scjs** [comment]
Yes, I wanted to suggest this as a solution.

Here is an example showing that `optCtrl$algorithm` is not properly set when `nloptwrap` is used in `allFit`.

Set up the model:

```
library("lme4")

data("sleepstudy", package = "lme4")

mod <- lmer(
  formula = Reaction ~ Days + (1 | Subject),
  data = sleepstudy
)
```

Next, call `allFit` with the default arguments, including the default `meth.tab`.

```
fits <- allFit(mod)
```

In the default `meth.tab`, the 6th and 7th optimizers should use different algorithms (see line 10 of `allFit.R`), as shown here:

```
names(fits)
```

But `optCtrl` is still set to the default values (with no `algorithm`) for both:

```
attr(fits[[6]], "optCtrl")
attr(fits[[7]], "optCtrl")
```

Compare to using the `optimx` optimizer, which is the 5th optimizer for the default `meth.tab`. The call to `switch()` correctly sets the method for `optimix` on line 105:

```
attr(fits[[5]], "optCtrl")
```

**Comment by bbolker** [comment]
fixed in 538749

**Comment by scjs** [comment]
Thank you!
