### ISSUE TITLE
Error in if ((mdi <- max(d.i)) > 0) sum(d.i >= tol * mdi) else 0L : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by borrenp2** [lme4/lme4#513]
Hello! My name is Dan, I work in a plant breeding program and am currently analyzing height data. I am running a random effects model to estimate BLUPs for genotypes using different datasets (all subsets of a master file), but some datasets give me an error I have never seen before. I have attached an example of such a dataset, and am providing my printout, error, and session info below.

[Test HGT File.xlsx](https://github.com/lme4/lme4/files/3031696/Test.HGT.File.xlsx)

> rm(list = ls())
> library(openxlsx)
> 
> #Prep Phenotypic Data
> setwd("~/Desktop/MS Analysis/Validation Files/Current Versions")
> pheno <- read.xlsx("Test HGT File.xlsx")
> pheno$NAME <- as.factor(pheno$NAME)
> pheno$YR <- as.factor(pheno$YR)
> pheno$ENV <- as.factor(pheno$ENV)
> pheno$TEST <- as.factor(pheno$TEST)
> pheno$TRIALID <-as.factor(pheno$TRIALID)
> str(pheno)
'data.frame':	7343 obs. of  23 variables:
 $ PLOT   : chr  "1" "2" "3" "4" ...
 $ ROW    : chr  "1" "1" "1" "1" ...
 $ COL    : chr  "1" "2" "3" "4" ...
 $ NAME   : Factor w/ 2323 levels "12VTK6-104","12VTK6-116",..: 236 178 269 181 210 304 209 321 283 206 ...
 $ YR     : Factor w/ 5 levels "2013","2014",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ TEST   : Factor w/ 6 levels "ABB","ABBADV",..: 4 4 4 4 4 4 4 4 4 4 ...
 $ ENV    : Factor w/ 3 levels "OHNWB","OHVCB",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ REP    : chr  "1" "1" "1" "1" ...
 $ TRIALID: Factor w/ 51 levels "1320","1321",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ YLD    : num  64.2 47.1 32.4 61.7 72 57.3 18.2 60.7 46.1 68.8 ...
 $ TW     : num  55.5 55.7 NA 57.2 56.7 56.5 NA 58.7 57.8 56.8 ...
 $ AV     : num  2 1 3 2 2 2 2 2 3 2 ...
 $ HGT    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ LDG    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ HD     : num  145 145 143 143 144 143 143 143 143 143 ...
 $ MAT    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ FR     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ FRN    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ FRCOM  : num  NA NA NA NA NA NA NA NA NA NA ...
 $ FHBN   : num  NA NA NA NA NA NA NA NA NA NA ...
 $ SLBN   : num  NA NA NA NA NA NA NA NA NA NA ...
 $ SGBN   : num  NA NA NA NA NA NA NA NA NA NA ...
 $ PMN    : num  NA NA NA NA NA NA NA NA NA NA ...
> 
> #LMM Analysis
> library(lme4)
> options(lmerControl=list(check.nobs.vs.rankZ = "warning",
+                          check.nobs.vs.nlev = "warning",
+                          check.nobs.vs.nRE = "warning",
+                          check.nlev.gtreq.5 = "warning",
+                          check.nlev.gtr.1 = "warning"))
> 
> lmm.pheno.HGT <- lmer(HGT ~ (1|NAME)+(1|YR)+(1|YR:TEST)+(1|YR:NAME), data = pheno)
Error in if ((mdi <- max(d.i)) > 0) sum(d.i >= tol * mdi) else 0L : 
  missing value where TRUE/FALSE needed
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lme4_1.1-21    Matrix_1.2-16  openxlsx_4.1.0

loaded via a namespace (and not attached):
 [1] minqa_1.2.4     MASS_7.3-51.3   compiler_3.5.3  tools_3.5.3    
 [5] Rcpp_1.0.1      splines_3.5.3   nlme_3.1-137    grid_3.5.3     
 [9] nloptr_1.2.1    boot_1.3-20     zip_2.0.1       lattice_0.20-38
> 

I really have no clue on this. I formatted each dataset I am analyzing exactly the same way, but some give me the error message "Error in if ((mdi <- max(d.i)) > 0) sum(d.i >= tol * mdi) else 0L : missing value where TRUE/FALSE needed" after I run my model where similar datasets do no such thing. Convergence warnings pop up for some datasets, I do not know if that could be a related issue or not.

I apologize if this issue has come up elsewhere, but my fairly extensive search did not find anything. Any help on this would be greatly appreciated.

Dan

**Comment by bbolker** [comment]
I can confirm the error.  Seems to come from our code to check the rank of the Z matrix?? Will dig further.

**Comment by borrenp2** [comment]
Thank you so much, let me know if you need additional information from me.

**Comment by bbolker** [comment]
Error in if ((mdi <- max(d.i)) > 0) sum(d.i >= tol * mdi) else 0L : 
  missing value where TRUE/FALSE needed

**Comment by mmaechler** [comment]
Hmm, I'm very time constrained, sorry, but know we should get further:
  
This is a bug in `Matrix :: rankMatrix()`  ... I (as `Matrix` maintainer) can fix it such that it returns `NA` here and a warning... but that's almost surely suboptimal.

Can you/someone make a slightly (say 10 x, 50 x) smaller example still exhibiting the problem?
Yes, we need to get back this once we have more dedicated time.
