### ISSUE TITLE
Theoric rapid doubts about glmer()

### ISSUE THREAD

**Issue by davidbarscortina** [lme4/lme4#515]
Dear community,

Apologize me if is not an appropriate channel but I would like if someone could resolve two simple doubts but for me (as PhD student with a curiosity in statistics) I've not capable to solve by myself yet. 

1- As general rule, in glmer models if we have only one random effect, maybe it's more recommended always to perform a Gauss-Hermite Quadrature approximation instead of Laplace approximation because we can perform more than one iteration?

2 - I've read some posts addressing why the variance of Random effect differs between lmer and glmer... ([(https://stats.stackexchange.com/questions/115090/why-do-i-get-zero-variance-of-a-random-effect-in-my-mixed-model-despite-some-va)])...

Due to non-normality of my data (not attached), I need to use glmer, but how can I explain that the variance of my random variable (Horse) is practically 0??? 
Performing an analogous analysis by lmer (assuming badly "normality") the variance of my random variable (Horse) increased up to 33%!!!  I think that horse, must be an important value of explaining the variance of my model (as states lmer model). 

Therefore, I perform glmer and I obtained a variance for Horse as random effect of 0, meanwhile performing a lmer()  I obtained a variance for Horse as random effect of 33%. How can I assess the importance of the random effect on my model? How can I interpret well the model?

Thanks on advance for your help,

David Bars
PhD Student
University of Lleida // INRA Jouy-en-Josas

**Comment by bbolker** [comment]
These are good questions, but they're much more appropriate for `r-sig-mixed-models@r-project.org` (sorry if you've asked those questions there and they've slipped through the cracks -- if so, please repost there). "Where to get help" from the [README file](https://github.com/lme4/lme4/blob/master/README.md) notes:

-    r-sig-mixed-models@r-project.org for questions about lme4 usage and more general mixed model questions
-    https://github.com/lme4/lme4/issues for bug, infelicity, and wishlist reporting
-    The lme4 tag on StackOverflow for programming-related or the lme4-nlme tag on CrossValidated for statistics-related questions
-    maintainer e-mail only for urgent/private communications

**Comment by davidbarscortina** [comment]
Thanks Dr. Bolker. I will repost to mailing list another time but now
without the link hoping that this time works.

Yours sincerely,

David Bars
