### ISSUE TITLE
Inconsistent default between isSingular(tol=1e-5) and g/lmerControl(tol = 1e-4)

### ISSUE THREAD

**Issue by singmann** [lme4/lme4#519]
The default tolerance for the singularity checks differs between `isSingular()` and `g/lmerControl()`. The former has a tolerance of `1e-5`:
https://github.com/lme4/lme4/blob/e99afc1ffd2fd6081129a873aa94356a68b9c761/R/utilities.R#L1291

The latter uses per default `1e-4`:
https://github.com/lme4/lme4/blob/e66a5c1d90f3fd50b344d25c0603a24eb1218eda/R/lmerControl.R#L91

This can sometimes lead to apparently different conclusions between the fitted object and applying `isSingular()`. And my experience is that it takes some unnecessary time to figure this difference out.

I am happy to submit a pull request that sets the default in `isSingular()` to the same value as in `g/lmerControl()`.

**Comment by bbolker** [comment]
Good point. Hard to know which value is better to use: I doubt it makes much difference, but I would choose according to which one I thought more people had been using ...

**Comment by singmann** [comment]
I guess the `merControl` setting is the more common one, as anyone fitting a model with default setting implicitly uses those. You agree?

**Comment by mmaechler** [comment]
I agree @singmann .   What we should do is have the two cases _automagically_ use the same default, one using `formals(<the other>)`.  We do this in other places (and I do it in other packages, 
e.g.,`copula`.
I'm runing 'R CMD check` currently and will commit unless I see too many tests failing (in which case, I'd report back here first).

**Comment by bbolker** [comment]
@mmaechler: how did you do?  (You might need to pull first ...)  my only concern about `formals()` was that it might be too ugly in the formula argument list ...

**Comment by mmaechler** [comment]
I did well... I thought I did push... seem to have missed that ?

**Comment by bbolker** [comment]
I don't see a commit from you since May 3, at least on the master branch ...

**Comment by mmaechler** [comment]
yeah.. it's there on my computer at ETH uncommitted even.. need to run checks (again! last run "gone"), then commit and push.. I hope to get there before bed time ;-)
