### ISSUE TITLE
drop1(glmer(...)) doesn't work if glmer includes start = <list>

### ISSUE THREAD

**Issue by stgries** [lme4/lme4#521]
It seems as if `drop1` (and also `add1)` do not work on a glmer model whose start parameter was defined with `getME(some.other.model0 c("theta", "fixef"))`, as exemplified below:

    rm(list=ls(all=TRUE)); set.seed(1); library(lme4)
    summary(x <- data.frame(
       RESP=sample(letters[1:2], 600, replace=TRUE),
       PRED1=sample(letters[5:6], 600, replace=TRUE),
       PRED2=rnorm(600),
       RANEF=sample(letters[1:2], 600, replace=TRUE)))

    m1 <- glmer(RESP ~ PRED1+PRED2+(1|RANEF), family=binomial, data=x)
    m2 <- update(m1, start=getME(m1, c("theta", "fixef")))

    drop1(m1) # fine
    drop1(m2) # not fine:
    # Error in getStart(start, lower = rho$lower, pred = rho$pp, "theta") :
    #   incorrect number of fixef components (!=2)

**Comment by mmaechler** [comment]
Which R version did you use to generate your `x` above?  This is very crucial as  sample() has changed with R 3.6.0!

**Comment by stgries** [comment]
Oops, sorry, I forgot my sessionInfo:

    sessionInfo()
    R version 3.6.0 (2019-04-26)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Linux Mint 19.1

    Matrix products: default
    BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
    LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

    locale:
     [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
     [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
    [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    loaded via a namespace (and not attached):
    [1] compiler_3.6.0 tools_3.6.0

**Comment by mmaechler** [comment]
I'm testing a relatively simple fix which works here..  will commit later today if checks pass.

**Comment by mmaechler** [comment]
unfortunately the simple fix is not okay,.. breaking in other situations where getSigma() used to work..... postponing the fix a bit

**Comment by stgries** [comment]
Sure, thanks for your efforts!
