### ISSUE TITLE
allFit error 'second argument must be a list'

### ISSUE THREAD

**Issue by hyha0310** [lme4/lme4#523]
I'm fairly new to the game and am learning to use glmer. Kept running into convergence warnings and decided to use allFit.R to see how the different optimizers work with my current models. When I call allFit(m1), where m1 is my model, it returns: 

bobyqa : Error in do.call(if (isGLMM(m)) glmerControl else lmerControl, ctrl) : 
  second argument must be a list

It seems to be referring to line111 of allFit.R. Please excuse me if I have missed previous posts with this issue and if you could redirect me, I would be very much be grateful. Otherwise, please have a look at the issue and enlighten me with what may be wrong. Thanks very much in advance. 

Here is my glmer function call:
m1<- (count ~ 1+ response + response:valence2+response:facial_expression + response:TEMP_mean + response:liwc.category:percentage, data = data, family = poisson, offset = log(rep(1, nrow(data))), control = glmerControl(optCtrl = list(maxfun = 100000)))

**Comment by bbolker** [comment]
I suspect this is the same as #520 .  Can you do `remotes::install_github("lme4/lme4")` and see if it fixes the problem ? (you may need to `install.packages("remotes")` first, and you will need development tools installed.)

**Comment by bbolker** [comment]
can you see if the latest development version solves this problem for you?

**Comment by GerritEichner** [comment]
Hi, Ben, just jumping in because I had the same problem and followed your advice to check out the "latest development version" from `remotes::install_github("lme4/lme4")`. It worked for me for an LMM. Thx for your effort.

**Comment by nahorp** [comment]
I've tried this after installing the development version as well but still get the error,

```
bobyqa : Error in do.call(if (isGLMM(m)) glmerControl else lmerControl, ctrl) : 
  second argument must be a list
```

**Comment by SeanKu0102** [comment]
> I suspect this is the same as #520 , which @mmaechler fixed recently. Can you do `remotes::install_github("lme4/lme4")` and see if it fixes the problem ? (you may need to `install.packages("remotes")` first, and you will need development tools installed.)

Hey, Ben, I have tried what you say: `install.packages("remotes")` and `remotes::install_github("lme4/lme4").` However it still comes "bobyqa : Error in do.call(if (isGLMM(m)) glmerControl else lmerControl, ctrl) :  second argument must be a list", when I run `allFit()`. I don't know what should I do next....

**Comment by nahorp** [comment]
Hi SeanKu0102, I was in a similar boat as you. The below is what worked for me,

1. Remove lme using the `remove.packages` function
2. Restarting the R session. This may throw an error of not being able to find the lme4 package.
3. Use the `remotes::install_github("lme4/lme4")` command.

**Comment by bbolker** [comment]
@nahop, do you mean "remove `lme4` using the `remove.packages` function"? (I'm just asking because `lme` is also the name of a function in the `nlme` package ...) This step seems like it should normally be unnecessary, unless you have packages installed in more than one library (= directory location).

@SeanKu0102: if you can send a **reproducible** example (i.e., data and code I can use to try to trigger the error myself so I can debug it) I can try to see what's going on.  

I've just now bumped the version number of `lme4`, so if you re-install the development version and re-load the package, `packageVersion("lme4")` should give you `‘1.1.21.9002’` (if not, you failed to re-install/re-load it properly ...)

**Comment by nahorp** [comment]
@bbolker Yes, indeed the `lme4` package (i.e., not the function). I'm not sure if that is what 'solved' it or not but it worked after that and the error didn't come up anymore. I had tried only restarting the R session prior to removing it and restarting R as well, but that didn't work.

Regarding having more than one library, I only have one library for installing packages (which is the default directory location).
