### ISSUE TITLE
inconsistent renaming of interactions between ranef and fixef

### ISSUE THREAD

**Issue by gavril0** [lme4/lme4#526]
In some cases the name of the interaction for RE and FE are not consistent even if they are specified in a consistent manner. The issue appears to be a lack of consistency about when the interaction names are reordered alphabetically:

    d <- expand.grid(a=1:10, b=1:10, su=1:10)
    d$y <- with(d, rnorm(10)[su] + a*rnorm(10)[su] + b*rnorm(10)[su] + a*b*rnorm(10)[su])
    d$y <- d$y + rnorm(nrow(d))

    # no reordering
    x <- lmer(y ~ b*a + (b*a || su), d)
    names(fixef(x))     # b + a + b:a
    names(ranef(x)$su)  #  b + a + b:a

    # reordering only for REs
    x <- lmer(y ~ b*a + (a*b || su), d)
    names(fixef(x))     # b + a + b:a
    names(ranef(x)$su)  #  a + b + a:b  

    # consistent alphabetical reordering
    x <- lmer(y ~ a + b + b:a + (a + b + b:a || su), d)
    names(fixef(x))     # a b a:b
    names(ranef(x)$su)  # a b a:b

    # reordering only for FEs
    x <- lmer(y ~ a +  b + b:a + (a + 0 | su) + (b + 0 | su) + (b:a + 0 | su), d)
    names(fixef(x) )   # a + b + a:b
    names(ranef(x)$su) # a + b + b:a

    # warning message about missing slope when interaction names are not consistent
    insight::get_variance(x)

I found the issue when using `performance::r2`, which calls `insight::get_variance(x)`  and checks for consistency between names of REs and FEs.

**Comment by gavril0** [comment]
I found that call to `update.formula` can change the order of the terms in the interaction. I don't know if this is relevant in the way `ranef` and `fixef` are built in `merMod` objects but it plays a role in the following case. 
        
`MuMIn::r.squaredGLMM` does a check of consistency between  REs derived from `VarCorr` and RE in a model matrix reconstructed  by `MuMIn::.remodmat`. There is an error message with some formulae because the order of the terms in the interactions is changed by `update.formula` which is called in the code to rebuild the model matrix (see `MuMIn:::.ranform`).  For example:

   > update.formula(~ a:c + b:c, ~. + 1)
   ~a:c + c:b

Here is a complete example

    set.seed(2)
    d <- expand.grid(a=c(0,1), b=NA, c=1:10, su=1:10)
    d$b <- 1-d$a
    d$y <- rnorm(10)[d$su] + d$c*rnorm(10)[d$su] +  rnorm(nrow(d))

    x <- lmer(y ~a:c + b:c + (1 | su) + (a:c + 0 | su)  + (b:c + 0 | su),d)
    performance::r2(x)       # Warning mesage
    MuMIn::r.squaredGLMM(x)  # Error message
    summary(x)

Interestingly, the same model with formula specified in following manner does not give warning/error message because names are consistent  (`b:c` is consistently changed to `c:b`)

    x <- lmer(y ~a:c + b:c + (a:c + b:c || su),d)
    performance::r2(x)       # Ok
    MuMIn::r.squaredGLMM(x)  # Ok
    summary(x)

**Comment by bbolker** [comment]
Hmmm. As of today I get no (relevant) warnings or errors when running `performance::r2(x)` and `MuMIn::r.squaredGLMM(x)` in the examples above. Perhaps the downstream packages have improved their checking machinery to be robust to ordering differences? (Anything involving string ordering *could* be a locale difference (I'm in `en_US.UTF-8`), although in this case I doubt it ...)

other attached packages:
[1] lme4_1.1-24   Matrix_1.2-18

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        lattice_0.20-41   MASS_7.3-53       grid_4.1.0       
 [5] MuMIn_1.43.17     nlme_3.1-149      stats4_4.1.0      bayestestR_0.7.2 
 [9] performance_0.5.0 minqa_1.2.4       nloptr_1.2.2.2    boot_1.3-25      
[13] splines_4.1.0     statmod_1.4.34    compiler_4.1.0    insight_0.9.6

**Comment by bbolker** [comment]
A little bit more investigation/explanation of how and when the reordering happens.

```r
dd <- data.frame(a=rnorm(5),b=rnorm(5))
cc <- function(f) colnames(model.matrix(f,dd))[-1]
cc(~a*b)
## [1] "a"   "b"   "a:b"
cc(~b*a)
## [1] "b"   "a"   "b:a"
cc(~a+b+b:a)
## [1] "a"   "b"   "a:b"
cc(~b+a+b:a)
## [1] "b"   "a"   "b:a"
cc(~b:a)
## [1] "b:a"
cc(~a+b+b:a)
## [1] "a"   "b"   "a:b"
```

So, basically, the rules are that (1) the fixed effects, and the terms in any individual random effect, are evaluated (put into `model.matrix()` *separately*); (2) `model.matrix()` orders interaction terms by the *order of terms previously seen in the formula*.

Given that this is pretty deeply baked in (we *could* write code that forcibly reorders interaction terms, but it seems reasonably easy to work around), and that current versions of the downstream packages seem to handle this OK, I'm going to go ahead and close this ...
