### ISSUE TITLE
qqmath

### ISSUE THREAD

**Issue by HywelMJ** [lme4/lme4#527]
function not found

**Comment by bbolker** [comment]
this isn't particularly clear.  qqmath is part of the lattice package; lme4 only provides a particular methods for it (`qqmath.merMod`, `qqmath.ranef`).  So you either need `library(lattice); qqmath(...)` or `lattice::qqmath(...)`.  If you can point to a particular part of the documentation that's unclear, we can try to improve it.

**Comment by HywelMJ** [comment]
Sorry to have been curt. Attempting to run qqmath simply gives a message "...could not find function "qqmath". The documentation of plot.merMod doesn't mention that lattice is required other than - I now see - including 'require("lattice") ' in the Examples.

**Comment by bbolker** [comment]
Tried to clarify in e570ad9
