### ISSUE TITLE
boundary (singlular) message when isSingular(m) is FALSE

### ISSUE THREAD

**Issue by srcorsi-USGS** [lme4/lme4#529]
Are there legitimate instances where the message "boundary (singular) fit: see ?isSingular" occurs, but isSingular(m) results in a FALSE value? Here is what I see with my current model:

> m <- lmer(form[[f]],data=model_df_scaled)
boundary (singular) fit: see ?isSingular
> isSingular(m)
[1] FALSE

where form = log_response ~ T : cosDate + Turbidity_mean : cosDate + T : sinDate + Turbidity_mean : sinDate + sinDate + cosDate + (T  | abbrev)

**Comment by singmann** [comment]
This is likely due to the problem discussed in #519, which was fixed by @mmaechler. I expect this behaviour should not appear any more with the latest development version.

**Comment by srcorsi-USGS** [comment]
Thanks for the link. That answers the question
