### ISSUE TITLE
Solving the same for several outcomes

### ISSUE THREAD

**Issue by AlejandroCatalina** [lme4/lme4#532]
Hi, 

I am trying to solve the following formula with `lmer`:

```
cbind(y.1, y.2, y.3) ~ u + (u | floor_id) + (u | county_id)
```
which works fine for standard `lm` models without the group terms, but it fails when I have the mixed effects terms with the following error:

```
Error in initializePtr() : updateMu: Size mismatch
```

If this is not the right place to post this issue please tell me, I appreciate any pointers forward.

**Comment by bbolker** [comment]
lme4 doesn't implement multi-response models ... for more
discussion/advice, please repost this (or a modified version) on
r-sig-mixed-models@r-project.org ...

**Comment by AlejandroCatalina** [comment]
Okay, thank you very much.

Best,
Alejandro
