### ISSUE TITLE
NA Data Gives Inaccurate Error of "Invalid grouping factor specification"

### ISSUE THREAD

**Issue by billdenney** [lme4/lme4#533]
When all of a column is `NA`, an error of "Invalid grouping factor specification" is given instead of a more accurate error indicating that a covariate is NA (ideally indicating which covariate is the issue would help).

I found the solution from here:
https://stackoverflow.com/questions/41134146/error-invalid-grouping-factor-specification?rq=1

``` r
library(lme4)
#> Loading required package: Matrix

data <- sleepstudy
fm2 <- lmer(Reaction ~ Days + (1| Subject), data)
summary(fm2)
#> Linear mixed model fit by REML ['lmerMod']
#> Formula: Reaction ~ Days + (1 | Subject)
#>    Data: data
#> 
#> REML criterion at convergence: 1786.5
#> 
#> Scaled residuals: 
#>     Min      1Q  Median      3Q     Max 
#> -3.2257 -0.5529  0.0109  0.5188  4.2506 
#> 
#> Random effects:
#>  Groups   Name        Variance Std.Dev.
#>  Subject  (Intercept) 1378.2   37.12   
#>  Residual              960.5   30.99   
#> Number of obs: 180, groups:  Subject, 18
#> 
#> Fixed effects:
#>             Estimate Std. Error t value
#> (Intercept) 251.4051     9.7467   25.79
#> Days         10.4673     0.8042   13.02
#> 
#> Correlation of Fixed Effects:
#>      (Intr)
#> Days -0.371

data_bad <- data
data_bad$Days <- NA_real_
fm2_bad <- lmer(Reaction ~ Days + (1| Subject), data_bad)
#> Error: Invalid grouping factor specification, Subject
summary(fm2_bad)
#> Error in summary(fm2_bad): object 'fm2_bad' not found
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bbolker** [comment]
The proximal cause here is that `model.frame()` drops *all* of the rows in the data set, leading downstream to a factor with zero levels. It's too bad to add yet another check, and I'm not 100% sure where to put it: in `lFormula`, `glFormula`? within `checkFormulaData`?

**Comment by mmaechler** [comment]
What if you use such all-NA variables in `lm()` ?

```
> lm(Reaction ~ Days, data_bad)
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases

> lm(Reaction ~ Days+Subject, data_bad)
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
> 
```
The first one does build a `model.matrix()` successfully and then has  `lm.fit()` do the check.

The 2nd one actually does fail when trying to set contrasts inside `model.matrix.default()`,
but I would say both cases give useful and correct error messages.
Maybe we should take these as example?

**Comment by bbolker** [comment]
added a test like `lm.fit` in 6592d9ceb3cbb
