### ISSUE TITLE
MIxed Effects Logistic Regression error "rank deficient"

### ISSUE THREAD

**Issue by davidcanarte** [lme4/lme4#534]
Hello... I am running mixed effects logistic regression that is throwing the following error

"fixed-effect model matrix is rank deficient so dropping 1 column / coefficient" 

This model is the full random-intercept model with all level-1 and level-2 predictors. I did not have this error with the previous models. 

I counted the amount of variables included in the formula vis-a-vis those in the regression output and they match. 

Does anyone have an idea what's going on? Should I disregard these results?

**Comment by bbolker** [comment]
Can you please post this to `r-sig-mixed-models@r-project.org`? The [README for this repository](https://github.com/lme4/lme4/blob/master/README.md) (which is posted on the front page of the repo, though it's easy to miss if you come to straight to the issues list - we should do something about that) has a "where to ask" section that says that the issues list is for "bug, infelicity, and wishlist reporting" -- I'd judge that this is instead a usage question and thus belongs on `r-sig-mixed-models` ...

A little more detail would probably be useful when you post to the mailing list.

I think `fixef(your_model, add.dropped=TRUE)` should include the coefficients that have been dropped from the model (as `NA` values ...)

**Comment by Atsui1012** [comment]
Thank you very much for your help.

When we ran Package lme4 to our longitudinal data, we got following warnings repeatedly.

> fixed-effect model matrix is rank deficient so dropping 2 columns / coefficients
> boundary (singular) fit: see ?isSingular 
Nevertheless, we got some results. Are these valid?
When I look for the Q&A in some Statistic Forums, sometimes I found the previous answer that we do not have to care these warnings.

In actuality, how do we deal with these warnings?

Thank you for your time.

**Comment by Atsui1012** [comment]
Thank you very much for your help.
When we ran Package lme4 to our longitudinal data, we got following warnings repeatedly.

> fixed-effect model matrix is rank deficient so dropping 2 columns / coefficients
> boundary (singular) fit: see ?isSingular 

Nevertheless, we got some results. Are these valid?
When I look for the Q&A in some Statistic Forums, sometimes I found the previous answer that we do not have to care these warnings.
In actuality, how do we deal with these warnings?

Thank you for your time.

**Comment by mmaechler** [comment]
Same as above: 

>  post this to `r-sig-mixed-models@r-project.org`? The [README for this repository](https://github.com/lme4/lme4/blob/master/README.md) is relevant.  Very short answer "_it depends"_ and that's why it's really a waste to ask this in a GH issue.
