### ISSUE TITLE
glmer doesn't work in R 3.5.3

### ISSUE THREAD

**Issue by supermartha** [lme4/lme4#535]
Running R 3.5.3, if I try to make a binomial glmer model I get the following error:

```
> myModel <- glmer(am ~ mpg + (1|carb), dat=mtcars, family="binomial")
Error in mkdevfun(rho, nAGQinit, maxit = maxit, verbose = verbose, control = control) : 
  extends(rho.cld <- getClass(class(rho$resp)), "lmResp") is not TRUE
```

I also get the same error if I try example(glmer). Here's my sessionInfo:

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lattice_0.20-38 lme4_1.1-21     Matrix_1.2-16 
```

It worked fine when I was running R 3.2.3.

**Comment by bbolker** [comment]
Hmmm, this is surprising. We haven't seen any other reports like this.  Works fine for me on MacOS in R 3.5.2 (the closest I have available to 3.5.3); it also passes all of the CRAN checks on 3.5.3 under Windows and 3.5.2 under OSX ("oldrel").

Is this from a clean session?  I hate to ask, but is there any chance you could update R to the latest version (3.6.1), which would make it easier to debug the problem if it persists?

I don't see how it would make much of a difference but the version I ran uses Matrix 1.2-17.

**Comment by supermartha** [comment]
Ahhh, starting a new session helped me to figure this out -- I had a function in my workspace called getClass which had overwritten the lme4 getClass function. (In R 3.2.3 it seems I was running an older version of lme4 where that function didn't exist.) Thanks for your help!

**Comment by bbolker** [comment]
this report was useful in helping fix a corner case -- thanks!  (the development version should now work even if you have a `getClass` function defined in the global workspace ...)
