### ISSUE TITLE
The `.fitted` column returned by `fortify.merMod()` is created from `predict()` instead of `fitted()`

### ISSUE THREAD

**Issue by alexdunlap** [lme4/lme4#536]
The `.fitted` column returned by `fortify.merMod()` is created from `predict()` instead of `fitted()`. Can this be changed by either calling `fitted()` or renaming it to `.predict`?

https://github.com/lme4/lme4/blob/0ed6252d8aa9a9929bf919ec36d9e1150fda0ddd/R/plot.R#L415

The examples given in the documentation for `plot.merMod` indicate that plotting data as a function of `fitted()`

```R
## standardized residuals versus fitted values by gender
plot(fm1, resid(., scaled=TRUE) ~ fitted(.) | Sex, abline = 0)
```

is equivalent to plotting data as a function of the `.fitted` column.

```
## we can create the same plots using ggplot2 and the fortify() function
fm1F <- fortify.merMod(fm1)
ggplot(fm1F, aes(.fitted,.resid)) + geom_point(colour="blue") +
       facet_grid(.~Sex) + geom_hline(yintercept=0)
## note: Subjects are ordered by mean distance
```
https://www.rdocumentation.org/packages/lme4/versions/1.1-21/topics/plot.merMod

But this would not be the case for models fit by `glmer()` with any family other than Gaussian.

**Comment by bbolker** [comment]
hmm.  What if the `...` argument was passed through to `predict()`?  Then one could specify `fortify(m, type="response")` and get the same values as if `fitted()` was used ...

For what it's worth, `?ggplot2::fortify` itself says:

>Rather than using this function, I now recommend
> using the ‘broom’ package, which implements a much wider
>  range of methods. ‘fortify’ may be deprecated in the future.

Also FWIW, the behaviour of `fortify.merMod` matches that of `fortify` when applied to `glm` objects (which actually falls through to the `fortify.lm` method ...)

**Comment by alexdunlap** [comment]
Thanks for the response and pointing me to `broom`. Doesn't seem like an issue anymore especially since `fortify` is not recommended.

I can get behavior I was looking for with `augment` in `broom.mixed`:

```
install.packages("broom.mixed")
library("broom.mixed")
fm1F <- augment(fm1, type.predict= "response")
```
