### ISSUE TITLE
How to code a model with a Tlag, a correlation between variables, a covariate effect and a combined error model using nlmer?

### ISSUE THREAD

**Issue by MorganePhilipp** [lme4/lme4#537]
Dear @bbolker,

I try to code a PK model with lme4 and more precisely with nlmer however I have some issues .

First to be more precise I work on the theophylline data set. 
The model is a one-compartment model, with first-order absorption kinetics and linear elimination kinetics. The drug is administered orally.

I start to code it like that:

######################################################################
library("saemix")
library("nlme")
library("Matrix")
library("lme4")
library("ggplot2")

rm(list=ls())

Theoph.saemix <- read.csv("C:/Users/ADMIN MORGANE/CloudStation/Data/Theoph_data_4.csv", header = TRUE, sep=",")
Theoph.saemix

##### ka, V, Cl model #####

startvec <- c(lKe = log(0.0362/0.488), lKa = log(2.19), lCl = log(0.0362)) #warning, the vector should be done with ke and not with V

nform <- ~ Dose * exp(lKe + lKa - lCl) * (exp( -exp(lKe) * Time) - exp( -exp(lKa) * Time)) / (exp(lKa) - exp(lKe))
#nform

nlmer.theomod <- deriv(nform, namevec = c("lKe", "lKa", "lCl"), function.arg = c("Dose", "Time", "lKe", "lKa", "lCl"))
#nlmer.theomod

nlmer.fit <- nlmer(Concentration ~ nlmer.theomod(Dose, Time,lKe, lKa, lCl) ~ (lKe | Id) + (lKa | Id) + (lCl | Id), data = Theoph.saemix, start = list(nlpars = startvec))
nlmer.fit
####################################################################

I would like to add to my model:
- An absorption delay (Tlag)
- A correlation between V and Cl
- A covariate effect of the sex on Cl 
- A combined error model (additional + proportional error)

I can't figure out how to code these elements, could you help me? 

Best regards, 
Morgane PHILIPP

**Comment by bbolker** [comment]
This is probably more appropriate for `r-sig-mixed-models@r-project.org` ... a few quick comments. 

- `nlmer` is still immature in some ways, alas (e.g. see [here](https://rpubs.com/bbolker/3423) about the difficulties of implementing fixed-effect covariates on parameters; this is easy in `nlme`)
- several of your requests are going to be difficult to do within a standard Gaussian/least-squares framework ((1) correlation between V and Cl will require a multivariate observation model; (2) I would expect absorption delay to be *very* difficult if modeled as a discrete lag/delay-differential equation [if you want to stick with a model whose derivatives are known], you might be better off modeling it as one or more delay compartments for an exponential or Gamma/Erlang delay)
- have you explored the [Pharmacokinetics task view](https://cran.r-project.org/web/views/Pharmacokinetics.html) and the [nlmixr package](https://nlmixrdevelopment.github.io/nlmixr_bookdown/preface.html)?

**Comment by MorganePhilipp** [comment]
Dear @bbolker,

Thank you very much for your response and for the link, I will redirect my request.
