### ISSUE TITLE
 Unable to calculate Weights(Wi)

### ISSUE THREAD

**Issue by leefusi** [lme4/lme4#542]
I want to calculate weight，But the result I got was wrong.
![QQ截图20191019122324](https://user-images.githubusercontent.com/49238081/67137652-5b60be00-f26b-11e9-9b3a-c5bc1d6e7b5e.jpg)

**Comment by bbolker** [comment]
It's not clear to me what you want. (Are you trying to compute AIC weights? You would need a list of models for that ...) `weights()` returns any *a priori* weights that were specified in the model (e.g. to account for unequal sampling/expected differences in residual variance). If you can say what you aiming for and how you know the result is wrong, we might be able to help.  I'm going to ask you to please send your follow-up question to `r-sig-mixed-models@r-project.org`:

* it's a public list, please subscribe first at https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models
* if you want to show output, please post cut-and-pasted text, **not** a screenshot (image files will be stripped by the mailing list)
