### ISSUE TITLE
confint.merMod does not respond to the level-argument for type="boot"

### ISSUE THREAD

**Issue by sakritz** [lme4/lme4#543]
I am looking to compute 90% bootstrapped confidence intervals of multilevel regression models,  but whatever I feed to the argument, the output stays the same. 
However, it seems to work if you do not need bootstrapped confidence intervals and it also works for bootstrapped confidence intervals with normal lm-models.

The following all give exactly the same results:
``` 
set.seed(12345)
confint(model, level = .90, method = c("boot"), nsim = 500, boot.type = c("perc"))

set.seed(12345)
confint(model, level = .95, method = c("boot"), nsim = 500, boot.type = c("perc"))

set.seed(12345)
confint(model, level = .99, method = c("boot"), nsim = 500, boot.type = c("perc"))
```

**Comment by vasili111** [comment]
I confirm that issue. 
>With `method = "boot"` the `level` is not passed to the boot function. You can see the code with `getAnywhere('confint.merMod')`. The relevant code line is near the end: `bb <- bootMer(object, FUN = FUN, nsim = nsim, ...)`. And function `getAnywhere('bootMer')` does not have a `level`cargument.

> cran.r-project.org/web/packages/lme4/lme4.pdf on p.9 no level parameter too for `bootMer()`

(from: https://stackoverflow.com/questions/58611293/custom-boot-confidence-intervals-with-lme4)

Example code: https://stackoverflow.com/questions/58611293/custom-boot-confidence-intervals-with-lme4

Best solution is to add to `bootMer()` the `level` argument. 

Until then `bootMer()` should though error when `level` argument is passed for `boot` method. Also `bootMer()` and `confint()` sections in documentation need appropriate note.

**Comment by bbolker** [comment]
4947bd4a1 should resolve this, I think ... `bootMer` doesn't need a `level` argument (all it does is draw the bootstrap sample) ... but the `level` argument from `confint` needs to be passed through to `confint.bootMer` ...

**Comment by vasili111** [comment]
@bbolker Thank you. Is there any date when fixed version will be released in cran?

**Comment by bbolker** [comment]
We don't have a release planned, but it's probably time to start thinking about it; it's been 6 months and there have been a number of bug fixes (see [NEWS](https://github.com/lme4/lme4/blob/master/inst/NEWS.Rd)).  

If you have development tools (compilers etc.) installed, you can use the development version by using `remotes::install_github("lme4/lme4")` ...
