### ISSUE TITLE
default tol for check.conv.grad() in glmerControl() is still 1e-3

### ISSUE THREAD

**Issue by kkralicek0** [lme4/lme4#544]
I came across this [Cross Validated](https://stats.stackexchange.com/questions/226171/convergence-warning-in-lme4-not-in-glmmadmb) post that seemed to suggest that the default tolerance for checking gradient convergence was increased to 2e-3 from 1e-3. I'm running version 1.1-21 and it looks like the tol was increased for lmerControl() but not for glmerControl(). I wasn't sure how/where to mention this, or if it was intentional or not. 

Thanks!

**Comment by kkralicek0** [comment]
Yes - it doesn't look like that update has made it to CRAN yet. That post I linked seemed to suggest this was updated quite a while ago (2014), so I thought it was worth mentioning. So maybe not an 'issue'?

**Comment by bbolker** [comment]
That change only propagated to glmer a bit more recently,  sometime in March 2019. The [PDF manual on CRAN](https://cran.r-project.org/web/packages/lme4/lme4.pdf) confirms that the tolerances had not changed by 5 March when it went onto CRAN ...

**Comment by bbolker** [comment]
I suspect that the glmer change (in the development branch) didn't happen until around 01760cdea4 (3 Feb 2019) when we brought `glmerControl` into line with `lmerControl` ...
