### ISSUE TITLE
using `stats::` namespace for internal references in documentation

### ISSUE THREAD

**Issue by IndrajeetPatil** [lme4/lme4#547]
In one of the functions in my package, I am inheriting arguments from `lme4::lmer` and `lme4::glmer`-
```r
#' @inheritDotParams lme4::lmer
```
or
```r
#' @inheritDotParams lme4::glmer
```

But this is creating a `WARNING` in my `R CMD CHECK`-
```r
> checking Rd cross-references ... WARNING
  Missing link or links in documentation object 'grouped_glmer.Rd':
    '[lme4]{offset}' '[lme4]{model.offset}'
    '[lme4]{model.matrix.default}'
  
  Missing link or links in documentation object 'grouped_lmer.Rd':
    '[lme4]{list}' '[lme4]{offset}' '[lme4]{model.offset}'
  
  See section 'Cross-references' in the 'Writing R Extensions' manual.
```

This is because `offset` is in `stats` (`stats::offset`), but the documentation looks for it in `lme4` (`lme4::offset`). (And the same for other functions.)

![image](https://user-images.githubusercontent.com/11330453/68993204-b3dca880-0875-11ea-8355-b9ee66865e06.png)

Can `lme4` documentation be changed so that this `WARNING` is not produced?

**Comment by bbolker** [comment]
Hmm, I'm not quite sure why this is happening.  Could it be a Roxygen buglet? (See [here](https://github.com/r-lib/roxygen2/blob/e016a7020de1a4ca6a695e7f1eb1b43ffe83e27f/R/rd-inherit.R#L188-L190) for the relevant code).  

I don't see how `::` is going to help.  This is not a reference in code, but in documentation.

I guess we could add an explicit package cross-link (i.e. \code{\link[stats]{offset}}) here, following the [Writing R Extensions section on cross-references](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Cross_002dreferences), although I don't see why this should be necessary ...

> There are two other forms of optional argument specified as \link[pkg]{foo} and \link[pkg:bar]{foo} to link to the package pkg, to files foo.html and bar.html respectively. These are rarely needed, perhaps to refer to not-yet-installed packages (but there the HTML help system will resolve the link at run time) or in the normally undesirable event that more than one package offers help on a topic107 (in which case the present package has precedence so this is only needed to refer to other packages). They are currently only used in HTML help (and ignored for hyperlinks in LaTeX conversions of help pages), and link to the file rather than the topic (since there is no way to know which topics are in which files in an uninstalled package). The only reason to use these forms for base and recommended packages is to force a reference to a package that might be further down the search path

 Can I ask that you bring this up on the Roxygen issues list for clarification?

**Comment by IndrajeetPatil** [comment]
Done. And also tagged you in the issue.
