### ISSUE TITLE
Scaled residuals are computed incorrectly in version 3.5.1 of R

### ISSUE THREAD

**Issue by CElliott316** [lme4/lme4#548]
```
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
# Install nlme and lme4, if necessary.
library(nlme)
fm1Rail.lmer <- lmer(travel ~ (1|Rail), data = Rail)
summary(fm1Rail.lmer)
#Scaled residuals: 
#     Min       1Q   Median       3Q      Max 
# -1.61883 -0.28218  0.03569  0.21956  1.61438 
# Compute:
min(residuals(fm1Rail.lmer)/sd(residuals(fm1Rail.lmer)))
[1] -1.923314
 -1.923314 != -1.61883
```

I did this problem in Mathematica, and the residuals lmer returns are correct.  So, it must be that the scaled residuals are computed incorrectly, at least in version 3.5.1.  If you want to know why not using latest version of R, I put off installing it until the new one comes out on or around 12/12/2019.  Thanks for your help.

**Comment by bbolker** [comment]
Quick answer (to be extended later, I hope): the residuals are scaled by `sigma(fit)` rather than by `sd(residuals(fit))`; these values are different. (`sigma` is computed as the *penalized weighted residual SS* rather than the residual SS.)

**Comment by CElliott316** [comment]
Dividing by sigma(fit) does produce the same answer as in the book I am using.  Thanks.
