### ISSUE TITLE
anova returns no values

### ISSUE THREAD

**Issue by CElliott316** [lme4/lme4#549]
```
library(nlme)
 fm1Rail.lmer <- lmer(travel ~ (1|Rail), data = Rail)
anova(fm1Rail.lmer)
Analysis of Variance Table
     Df Sum Sq Mean Sq F value
```

**Comment by bbolker** [comment]
The `anova` table for lmer only does tests for fixed effects; it is not a general-purpose ANOVA table as seen in more "classical" treatments (where we can get all the sums of squares/mean squares by method of moments and do appropriate F-tests).

This is documented, more or less, in `?lme4::anova.merMod`. I don't know if fuller documentation would be useful, or if we should message/warn in the trivial-fixed-effects case ... ?

>"anova": returns the sequential decomposition of the contributions
          of fixed-effects terms or, for multiple arguments, model
          comparison statistics.
