### ISSUE TITLE
glmer: std::bac_alloc 

### ISSUE THREAD

**Issue by cccfran** [lme4/lme4#550]
I encounter the following error messages when using glmer with `control = glmerControl(calc.derivs = FALSE)` and `nAGQ = 0`. 

`Error in pwrssUpdate(pp, resp, tol = tolPwrss, GQmat = GHrule(0L), compDev = compDev,  : 
  std::bad_alloc`

Not sure what caused this?

Edit: possibly running out of RAM.

**Comment by bbolker** [comment]
Running out of RAM sounds about right.  Have you had any further insights?  Does this happen with other control settings, or *only* with `nAGQ=0` ?

**Comment by bbolker** [comment]
I'm going to close this unless/until we can get a reproducible example.  Seems pretty clear from a little bit of googling that this is a failure to allocate requested memory.
