### ISSUE TITLE
?export parallel utilities?

### ISSUE THREAD

**Issue by mebrooks** [lme4/lme4#551]
I copied some old code from `bootMer` (dated 21 April 2017) to make my own bootstrapping function for [my own package](https://github.com/mebrooks/selfisher/blob/master/selfisher/R/bootSel.R). I recently noticed that the parallelization with snow wasn't working on Windows, so I'm trying to fix that and simultaneously update to match the more recent version of `bootMer`. The new version of `bootMer` uses the function `factory` which [looks like it was intended to be exported](https://github.com/lme4/lme4/blob/3d88fcf804a3802e531d628b566ae11252ddb728/R/error_factory.R#L11), but it isn't exported in the namespace. 
 
The new `bootMer` also uses `initialize.parallel` which is an expression. I wondered if it might make sense to export that also. I don't have an opinion. It's just as easy for me to copy the code over to my package.

Edit: as a side note, I found in #435 that `clusterExport` solves my problem with `snow`.

**Comment by bbolker** [comment]
I don't think we'll bother for now.
