### ISSUE TITLE
glmer.nb: extra argument(s) ‘nb.control’ disregarded

### ISSUE THREAD

**Issue by Kodiologist** [lme4/lme4#556]
`nb.control` is documented as a parameter for `glmer.nb`, but trying to set it yields the warning "extra argument(s) ‘nb.control’ disregarded". Apparently, the argument has to be called `control` instead; see https://stackoverflow.com/questions/46533903.

**Comment by Kodiologist** [comment]
The same goes for `initCtrl`.

**Comment by bbolker** [comment]
Think this is resolved (I couldn't replicate a problem with `initCtrl`); can you install devel version `remotes::install_github("lme4/lme4")` and check?

**Comment by Kodiologist** [comment]
I don't have an example handy right now, sorry. If you can see that the behavior of the function is changed as requested when `nb.control` and `initCtrl` are set, then everything should be good.

**Comment by bbolker** [comment]
I think so ... closing for now, feel free to re-open if necessary.
