### ISSUE TITLE
gcc 10 error: symbol `fun' is already defined

### ISSUE THREAD

**Issue by Enchufa2** [lme4/lme4#558]
I don't know what's going on here, because I don't see any symbol "fun" around, but the thing is that `lme4` fails to build with gcc 10 with this odd error message. Here's the log: https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-rawhide-x86_64/01217366-R-CRAN-lme4/builder-live.log.gz. Any ideas?

**Comment by bbolker** [comment]
No, no idea.  https://github.com/Rdatatable/data.table/issues/4091 looks related, but not close enough to be useful.  Are you able to install RcppEigen/other packages that use RcppEigen ... ??

**Comment by Enchufa2** [comment]
>
> No, no idea. Rdatatable/data.table#4091
> <https://github.com/Rdatatable/data.table/issues/4091> looks related, but
> not close enough to be useful.
>
That's different, that's a linker error due to missing extern declarations
in C, and it's documented in the porting guide. This, on the other hand,
comes from the C++ compiler, apparently.

> Are you able to install RcppEigen/other packages that use RcppEigen ... ??
>
RcppEigen compiles correctly. I believe that other packages depending on
Eigen do to (I have to check though). This is the only package on CRAN with
this error AFAIK.

>

**Comment by Enchufa2** [comment]
Checked: other packages using RcppEigen are fine.

**Comment by Enchufa2** [comment]
Ok, it seems that the error arises from the `lme4CholmodDecomposition.h` header. If I generate a package skeleton with `RcppEigen::RcppEigen.package.skeleton`, then copy that header into this package and just instantiate an object of type `lme4::lme4CholmodDecomposition<SpMatrixd>` there, then I obtain the same error.

**Comment by Enchufa2** [comment]
It seems to be a bug either in RcppEigen or gcc 10 (see [this thread](http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2020-February/010397.html)).
