### ISSUE TITLE
R-devel (-> R 4.0.0) check failures for `lme4`

### ISSUE THREAD

**Issue by mmaechler** [lme4/lme4#560]
There are several failures (and of all versions of R-devel that are recent enough);  see
     [CRAN lme4 checks](https://cran.r-project.org/web/checks/check_results_lme4.html)

I'll start looking at them now.

I'm almost sure they are entirely related to the new `stringsAsFactors = FALSE` setting,
see Kurt Hornik's blog about this on **the** [R Blog](https://developer.r-project.org/Blog/public/) :
 <https://developer.r-project.org/Blog/public/2020/02/16/stringsasfactors/index.html>

**Comment by bbolker** [comment]
I'm pretty sure I fixed these in 6ec1db2c0795659aa .  Testing with up-to-the-minute r-devel now ...

As with glmmTMB there's a 20-03-2020 deadline for submitting the fixes to CRAN.

Raises the more general question of which other issues we want to try to address before release (there are quite a few recent issues that might reasonably be addressed)

**Comment by mmaechler** [comment]
Well, it seems that  your  `LME4_TEST_LEVEL=2`  setting in `travis.yml` has no effect anymore.. (which may be fine; as you know I hate "CI" which builds on burning trees (or much worse) producing electricity to run considerable fractions of hours of CPU for every commit)

My standard testing always uses  test level at least 2, and finds two more problems, .. one of them almost identical  to the one you fixed...

**Comment by mmaechler** [comment]
fixed with      9953e1ee3627cf423525802f953f789f39a38158
