### ISSUE TITLE
rchk/PROTECT/UNPROTECT

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#563]
Tomas Kalibera's `rchk` package turns up a number of potential allocation issues in `glmFamily.cpp`, i.e. see [here](https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/lme4.out) (all variations on the theme of `calling allocating function Rf_{eval,asReal} with argument allocated using {Rf_lang2, Rf_lang4, Rf_lang6, Rf_eval}`). I tried to fix this in ea8e5c867 and  ae55f4f but don't know if I succeeded; setting up the `rchk` machinery [seems a little complicated](https://github.com/kalibera/rchk/blob/master/README.md) ... also, I broke something (maybe by removing the "unnecessary" PROTECTs?), dumping core somewhere in the testing process ....

**Comment by mmaechler** [comment]
Well, I did propose/offer  I'd do  PROTECT / UNPROTECT .. because I think I know how to do them
(and was waiting for your "yes").
*Dropping*  them was not going to be helpful...  but indeed, at the places where you / we had them,
they look to me as having been done wrongly anyway.  You cannot just wrap them around expressions the evaluation order of which is compiler/optimizer/....  dependent.

You need to protect variables, often time introducing new temporary variables.

**Comment by bbolker** [comment]
Sorry, Martin ... I thought I knew what to do on the basis of the r-devel conversation (but apparently was wrong), and was trying to save you the trouble. I can take another shot at fixing this, on the assumption that instead of  `type1 var1=PROTECT(PROTECT(...))` I need `type1 varl type2 var2; var2= PROTECT(...); var1=PROTECT(var2)`.  Or I'm happy for you to do it.

(I'm not sure what "dropping them" means in the second sentence.)

**Comment by bbolker** [comment]
@mmaechler , do you think you'll be able to get to this before April 5?  (I don't know how annoyed CRAN-maintainers will be if we submit without resolving these - we haven't had *official* complaints about them yet ...)  I'm also willing to try again if you're too busy (although I'm pretty busy!)

**Comment by bbolker** [comment]
I'm going to give this a shot now (deadline is *today*); if I can't get something that compiles and passes local tests I'll revert the PROTECT fixes for this submission and we can do it next time around ...

**Comment by mmaechler** [comment]
(I'm sorry I was busy in several ways..

**Comment by bbolker** [comment]
I'm going to close this since the "rchk" link has apparently disappeared from the CRAN checks (which implies that it's fixed now in their new round of tests)

**Comment by mmaechler** [comment]
(AFAIK rchk don't run automatically continuously... they have been too expensive and brittle IIRC, and needed human inspection because of false positives ... so the non re-emerging within one day would not mean so much)

**Comment by bbolker** [comment]
OK.  I took hope since they had disappeared: don't know if they're cleared automatically when a new version appears on CRAN. (Versions of the more standard tests that are run on older versions persist until the new tests are run ...)  Anyway, fingers crossed, we can always re-open this when we know that there's a problem (feel free to re-open this if you think it should be open by default until we know that it's OK rather than closed until we think it's not OK).
