### ISSUE TITLE
Saving memory for objects with same design 

### ISSUE THREAD

**Issue by ilyakorsunsky** [lme4/lme4#568]
Dear team, 

I am fitting ~20,000 glmer models (with the same design matrix) and would like to save them for doing prediction on new data later. I'm using the refit function to estimate each new model, so that's great for time efficiency! Unfortunately, each object is too large to save. Is there any way to do this in a memory efficient way? For instance, is it possible to keep the results from both models when I fit and refit to a new response? 

Thanks for an amazing tool!

**Comment by bbolker** [comment]
This is a great question, to which I don't have an immediate and simple answer. The [butcher](https://tidymodels.github.io/butcher/) package is supposed to help with this, by saving trimmed-down model objects that are still useful for post-fitting jobs like prediction; I don't know if a method exists for `merMod` objects or not.

If not, a more "bespoke" method would be to do the predictions yourself, by saving just the coefficients and formulae.  The disadvantage here is that you'd have write the stuff yourself, and it might not be as robust or thoroughly tested as the built-in prediction machinery.

If you give a small reproducible example of what you want to do we might be able to provide some code.

**Comment by ilyakorsunsky** [comment]
Thanks for the quick reply @bbolker! I took your advice and wrote functions to save the coefficients in a matrix and vectorize the predictions.
