### ISSUE TITLE
Comparing Models

### ISSUE THREAD

**Issue by jsraadt** [lme4/lme4#571]
I know you can compare models using `anova()`, but I learned that you can check the change in variance explained by random effects to compare models too.

What do you think of this function? It could be more efficient probably and have more arguments to make it more customizeable, but it works for me! I think it would be neat if this could be added to the package.

```
prop_inc=function(m1,m2){
  my_merge=merge(data.frame(VarCorr(m2)),data.frame(VarCorr(m1)),by=1:3,all=T)
  prop_increase=round(((my_merge[,4]-my_merge[,6])/my_merge[,6]),6)*100
  return(list(cbind(my_merge[,1:3],prop_increase),anova(m1,m2)))
}
```

**Comment by bbolker** [comment]
Thanks! This is a good idea, but we're pretty conservative about adding material to the package.  Most diagnostics, model comparison, etc. tools have ended up in downstream packages such as `sjstats`, `DHARMa`, `merTools`, `LMERConvenienceFunctions`, etc ... you might see if this function fits well into one of those frameworks ... (maybe someone on `r-sig-mixed-models@r-project.org` will have an idea or an opinion about that ...)
