### ISSUE TITLE
LRT for testing significance of fixed effects in GLMM Poisson and NB

### ISSUE THREAD

**Issue by cdcoliveira** [lme4/lme4#572]
I am running GLMM Poisson and NB and I have count variables as response variables. I am testing the fixed effects "treatment", "year" and "treatment* year", and I want to show the Likelihood Ratio test results for each of them. I am using drop 1, but just results for the interaction are presented. What am I doing wrong? What should I do to get results for "year" and "treatment"?

@dmbates , @bbolker 

`drop1(GLMM.AM,  scope = ~ treatment + year + treatment*year, test = "Chisq")
Single term deletions

Model:
abund_m ~ treatment + year + treatment * year + (1 | plot) + 
    offset(log(abund_m_2011))
               npar    AIC    LRT Pr(Chi)  
<none>              95.826                 
treatment         0 95.826  0.000          
year              0 95.826  0.000          
treatment:year    4 99.032 11.206 0.02435 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1`

**Comment by bbolker** [comment]
This is more appropriate for `r-sig-mixed-models@r-project.org`; could you please ask there?
