### ISSUE TITLE
[QUESTION] Is it possible to fit MMRM GLM model with lme4 (or glmmTMB)?

### ISSUE THREAD

**Issue by Generalized** [lme4/lme4#574]
Dear Authors,
I'm writing here my question, as you're the most competent people in the R  community to answer it.

I need to reproduce SAS analysis, using the MMRM model on binomial data.

**MMRM** stands for _Mixed-Effect Model Repeated Measure._ It isn't a real mixed-effects model, that's just a tricky name. Actually, it's a "_mixed model without random part_", only the residual part (repeated data pattern) is used. 

For Gaussian models it's nothing but the GLS (nlme::gls) estimation of a linear model. I can fit that this way. By using additional packages, like emmeans, I can calculate the Sattherthwaite degrees of freedom. Sadly, there seems to be no Kenward-Roger implementation of that for nlme.

But here I need to employ GLM on repeated observations. I noticed two packages able to do that: lme4 and glmmTMB. Both handle GLM. lme4 seems to handle the Kenward-Roger degrees of freedom (via external package), which is the most relevant for me. But I'm not sure if I can skip the random effects part?

BUT, I have read, that by specifying both random slopes and intercepts, I can mimic the unstructured covariance structure of the residuals. Then I read, that lme4 adds identity matrix on the residual part. But maybe lme4 recognizes what I do and fits the true effective (random effects + residuals covariance) unstructured covariance?

How about glmmTMB? I have read, that I can zero the residual covariance by using dispformula=~0. Then, if I specify the random slope and intercept model, will this be effectively equivalent to MMRM with unstructured covariance of the residuals? And if so, can I use the glmmTMB results to get Kenward-Roger degrees of freedom?

Or maybe there is any other way to get the MMRM for logistic model with Kenward-Roger or Satterthwaite in R?

**Comment by bbolker** [comment]
Can you please post this on `r-sig-mixed-models@r-project.org`?  That would be a better venue.  (Don't forget to subscribe first so that your message doesn't need moderation to get onto the list.)

(By the way, you say "logistic model" in the last sentence, which changes a lot - did you mean that, or are you happy with an assumption of a Gaussian conditional distribution?)
