### ISSUE TITLE
Error in lme4 output

### ISSUE THREAD

**Issue by vasishth** [lme4/lme4#577]
One of my students has noticed that the number of parameters in this model below is wrong if one uses contr.sum(2) to set up the contrast  coding for the two-level predictor Condition. If one uses a hand-coded (sum-coded) vector cond, then one gets the correct number of parameters in the model. Is this a bug or is this intentional? Probably this is a known issue to everyone except me :), in which case my apologies for bringing this up.

```
library(languageR)
data(primingHeid)

## Sum coding for the factor Condition:
levels(primingHeid$Condition)
contrasts(primingHeid$Condition) <- contr.sum(2) 
contrasts(primingHeid$Condition) 

## alternative way of defining your own contrast vector:
primingHeid$cond<-ifelse(primingHeid$Condition=="baseheid",-1,1)

## center frequency:
primingHeid$BaseFrequency <- scale(primingHeid$BaseFrequency, scale = FALSE)

library(lme4)
```

## Using internal contr.sum coding: 7 parameters

```
null.freq1 <- lmer(
  RT ~ 1+Condition +  Condition:BaseFrequency +
    (1 | Word) + (1 | Subject), data = primingHeid,
  control = lmerControl(
    optimizer ="bobyqa",
    optCtrl = list(maxfun = 90000) ),
  REML = FALSE )
```

**Incorrect number of parameters:**

```
summary(null.freq1)
Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: 
RT ~ 1 + Condition + Condition:BaseFrequency + (1 | Word) + (1 |  
    Subject)
   Data: primingHeid
Control: 
lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 90000))

     AIC      BIC   logLik deviance df.resid 
  -106.7    -73.6     60.3   -120.7      825 

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-2.332 -0.682 -0.127  0.606  4.153 

Random effects:
 Groups   Name        Variance Std.Dev.
 Word     (Intercept) 0.00248  0.0498  
 Subject  (Intercept) 0.03900  0.1975  
 Residual             0.04404  0.2099  
Number of obs: 832, groups:  Word, 40; Subject, 26

Fixed effects:
                                Estimate Std. Error t value
(Intercept)                      6.61800    0.04033  164.09
Condition1                      -0.01567    0.00733   -2.14
**Conditionbaseheid:BaseFrequency** -0.01397    0.00633   -2.21
**Conditionheid:BaseFrequency**     -0.01487    0.00621   -2.40

Correlation of Fixed Effects:
            (Intr) Cndtn1 Cndtnb:BF
Condition1   0.003                 
Cndtnbsh:BF -0.002 -0.008          
Cndtnhd:BsF  0.001 -0.006  0.370   
```

**Using hand-coded contrast vector: 6 parameters**:

```
null.freq2 <- lmer(
  RT ~ 1+cond +  cond:BaseFrequency +
    (1 | Word) + (1 | Subject), data = primingHeid,
  control = lmerControl(
    optimizer ="bobyqa",
    optCtrl = list(maxfun = 90000) ),
  REML = FALSE )
```

**Correct number of parameters**:

```
summary(null.freq2)
Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: 
RT ~ 1 + cond + cond:BaseFrequency + (1 | Word) + (1 | Subject)
   Data: primingHeid
Control: 
lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 90000))

     AIC      BIC   logLik deviance df.resid 
  -101.6    -73.2     56.8   -113.6      826 

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-2.363 -0.689 -0.133  0.590  4.253 

Random effects:
 Groups   Name        Variance Std.Dev.
 Word     (Intercept) 0.00339  0.0583  
 Subject  (Intercept) 0.03926  0.1981  
 Residual             0.04403  0.2098  
Number of obs: 832, groups:  Word, 40; Subject, 26

Fixed effects:
                    Estimate Std. Error t value
(Intercept)         6.618484   0.040737  162.47
cond                0.015638   0.007331    2.13
cond:BaseFrequency -0.000601   0.003519   -0.17

Correlation of Fixed Effects:
            (Intr) cond  
cond        -0.003       
cnd:BsFrqnc  0.002 -0.002
```

**Comment by bbolker** [comment]
I'll take a look.  This is a little surprising since all we're doing (IIRC) is counting the number of columns of the model matrix ... ???

**Comment by bbolker** [comment]
This has not much to do with `lme4`.  It is a fundamental constraint/aspect/infelicity of the way that `model.matrix()` works: there is no easy way (that I know of) to get the second model you're looking for without hand-coding it.

```
X <-  model.matrix(~1 + Condition + Condition:BaseFrequency,
                   data=primingHeid)
colnames(X)
## [1] "(Intercept)"                     "Condition1"                     
## [3] "Conditionbaseheid:BaseFrequency" "Conditionheid:BaseFrequency"    

X2 <- model.matrix(~1+cond +  cond:BaseFrequency,
                   data=primingHeid)
colnames(X2)
## [1] "(Intercept)"        "cond"               "cond:BaseFrequency"
```

**Comment by dmbates** [comment]
I agree with Ben that this is an issue with the `model.matrix` function itself.  You would get the same model matrix and coefficient vector for an `lm` or `glm` call.  It is an unusual set of parameters for `BaseFrequency` that you want in that you have an interaction without a main effect.  That is always a tricky situation for the formula language.  Do you expect that the slope w.r.t. `BaseFrequency` will be exactly the negative under `baseheid` that it is under `heid`?

**Comment by bbolker** [comment]
@dmbates: I agree it's rare, but I have encountered situations where I think it actually made sense to try to construct models of this form.

**Comment by dmbates** [comment]
@bbolker The most common situations I have seen in which interactions without main effects are the "zero dose" cases where a categorical condition (e.g. treatment/control) and a continuous covariate (e.g. dose) on a proportional scale with a meaningful zero - so that zero dose of the treatment is the same as zero dose of the control - are combined as `response ~ 1 + dose + dose:treatment`.  The model for the early childhood cognitive study is such an example if you change the time scale from `age` to `age - 0.5`, which is time-on-study.  In this case the term that is dropped is the main effect for the numeric covariate, `BaseFrequency`, which is more difficult to interpret.
