### ISSUE TITLE
PIRLS step-halvings failed to reduce deviance in pwrssUpdate with binomial glmer

### ISSUE THREAD

**Issue by tiantiy** [lme4/lme4#579]
Hi I am using the **glmer** function with **binomial** family in **lme4** for my simulated datasets. However, one of the simulated data causes the following error message.  
 
![image](https://user-images.githubusercontent.com/25966997/88246460-99f72f00-cc68-11ea-9ca5-30c21b68f98e.png)

I checked the dataset and there is no complete separation issue. I am wondering if anyone can help me figure out what causes the error. The dataset is attached.

[data.xlsx](https://github.com/lme4/lme4/files/4963544/data.xlsx)

Thanks a lot!

**Comment by bbolker** [comment]
You have a very small sample size per group (6 groups with one binary observation, 10 with 2, 7 with 3, and 7 with 4), so the Laplace approximation breaks down.  Setting `nAGQ=20` seems to work fine. You could try larger values to confirm that 20 is large enough.

```
library(readxl)
dd <- read_excel("lme4_GH579.xlsx")
with(dd,table(table(group)))

library(lme4)
try(glmer(y ~ 1 + x1 + x2 + (1|group), data=dd, family=binomial))

m2 <- glmer(y ~ 1 + x1 + x2 + (1|group), data=dd, family=binomial, nAGQ=20)
library(DHARMa)
simulateResiduals(m2, plot=TRUE)
```

**Comment by tiantiy** [comment]
Thanks, Dr. Bolker. Here I still have two questions.

1. I tried several different values of **nAGQ**. It works even when **nAGQ=2**.  I am wondering if it is necessary to set a larger value or not. I can see that the outputs are different for different values of nAGQ.  

2. I have another simulated dataset ([data2.xlsx](https://github.com/lme4/lme4/files/4963764/data2.xlsx)), which has the exact same values for **y** and **group** and different values for **x1** and **x2** compared with the previous attached dataset. However, when running the **glmer** function, it only produces some warnings but no error message. 
![image](https://user-images.githubusercontent.com/25966997/88250669-42f85680-cc76-11ea-9c3d-4727d3e21588.png)

By the way, is it also preferred to set the value of nAGQ >1 here?

Thanks again!

**Comment by tiantiy** [comment]
> You have a very small sample size per group (6 groups with one binary observation, 10 with 2, 7 with 3, and 7 with 4), so the Laplace approximation breaks down. Setting `nAGQ=20` seems to work fine. You could try larger values to confirm that 20 is large enough.
> 
> ```
> library(readxl)
> dd <- read_excel("lme4_GH579.xlsx")
> with(dd,table(table(group)))
> 
> library(lme4)
> try(glmer(y ~ 1 + x1 + x2 + (1|group), data=dd, family=binomial))
> 
> m2 <- glmer(y ~ 1 + x1 + x2 + (1|group), data=dd, family=binomial, nAGQ=20)
> library(DHARMa)
> simulateResiduals(m2, plot=TRUE)
> ```


Hi Dr. Bolker, thanks so much for your help! Could you please help me figure out my new questions above?

**Comment by bbolker** [comment]
1. in general you should set `nAGQ` large enough that the answers do not differ much (I would say "significantly", but I don't mean statistical significance ...) for further increases in `nAGQ`. There's a tradeoff between computational cost and accuracy. Higher values of `nAGQ` are always more accurate - if `nAGQ=2` and `nAGQ=10` give different answers but there is little difference between 10 and 20, you should use `nAGQ=10`.

2. It will always be good practice to use the most accurate method that is available and computationally feasible. In your case, this means you should always use a larger value of `nAGQ`. Convergence warnings may go away if you use larger values of `nAGQ`. If convergence warnings persist, see the `?lme4::convergence` help page.

Please send follow-up questions to `r-sig-mixed-models@r-project.org` (see https://github.com/lme4/lme4/blob/master/README.md#where-to-get-help)

**Comment by tiantiy** [comment]
Thanks so much, Dr. Bolker. You helped me a lot!
