### ISSUE TITLE
How to specify missing values for lmer4 using REML

### ISSUE THREAD

**Issue by zhengchencai** [lme4/lme4#581]
Hi there,

I was playing lmer4 using REML to perform variance analysis.  The data set consists of 96 observations collected from 16 subjects (ID), 3 conditions (Condition) and 2 time points (Time).  There were few data points missing so in total I have 80 observations. I fit a model as following to estimate the fixed effects of the condition, time and their interaction, plus a random effect for each specific subject. I got the error saying observation is less than the number of random effects, is this normal? I thought with REML the model should have handled the missing values? Do I have to mark the missing data as NA? 

fit1 <- lmer(Mean ~ Condition* Time + (1+Condition* Time|ID), data = dat)
Error: number of observations (=80) <= number of random effects (=96) for term (1 + Condition* Time | ID); the random-effects parameters and the residual variance (or scale parameter) are probably unidentifiable

Thanks,
ZC

**Comment by bbolker** [comment]
It's possible that the model actually is identifiable (I haven't thought about it too closely), in which case you can override the error by appropriate use of `control=lmerControl(...)` (see `?lmerControl` for details).  (You may already know this, but fitting a 6 x 6 covariance matrix from 16 subjects/80 observations is extremely optimistic, even if it's theoretically identifiable...)

If you have further questions can you please ask them on `r-sig-mixed-models@r-project.org` (see the ["where to get help" section of the README](https://github.com/lme4/lme4#where-to-get-help); the issues list is primarily for bugs or feature requests ...
