### ISSUE TITLE
Gamma for discrete data and PIRLS step-halvings failed

### ISSUE THREAD

**Issue by adrianacravo** [lme4/lme4#582]
Hello,
I'm relatively new to glmm world and I've been having some issues to fit the correct distribution to my data. 
Attached you can find the structure of my data (I changed the column names, but the values and qualitative data are original). 
[troubleshooting_data.txt](https://github.com/lme4/lme4/files/5041455/troubleshooting_data.txt)
The response variable is the column "number", so I tried to find out which distribution would the the best one. Since it is a discrete variable, I should not use Gamma/lognormal, but Poisson or negative binomial. However, the data is really far from the theoretical distribution, according to the plots below:

Poisson
![image](https://user-images.githubusercontent.com/47452445/89657194-f72beb00-d8cc-11ea-8ee4-18999be6f0b3.png)

Negative binomial
![image](https://user-images.githubusercontent.com/47452445/89657497-75888d00-d8cd-11ea-8729-3d42375f3db4.png)

So, I tried with Gamma, even if I shouldn't, to have an idea of how it would look like and the data seems to fit the distribution quite well 
![plot_fit-gamma_obsASVs](https://user-images.githubusercontent.com/47452445/89657787-e9c33080-d8cd-11ea-9bb5-496889df61b3.png)
So, here comes my first question. **Can I use gamma distribution with discrete data? Or is it restricted to continuous data?** I wouldn't like to transform my data to log, e.g., so I would prefer to stick with Gamma if that is allowed. I also saw that **quasi Poisson** could be an option when variance and mean are not similar for a Poisson distribution, which is the case, but apparently I cannot check it with `fitdist()` or other tools used to do so. 

My second question comes when I try to fit a model to my response and possible explanatory data. 

`model1 <- glmer(number ~ date + name + total +index1 + height + index3 + length + simpleindex + (1|site), data = troubleshooting_data, family=Gamma(link = "inverse"))`
Since the Gamma distribution seemed to fit the shape of the data, I tried with it anyway, but got the following error message:
`Error in pwrssUpdate(pp, resp, tol = tolPwrss, GQmat = GQmat, compDev = compDev, : (maxstephalfit) PIRLS step-halvings failed to reduce deviance in pwrssUpdate` - so apparently there is a complete separation of data.. but it is not binomial. When I scale all the numerical values, I get the same error.
So I checked here https://github.com/lme4/lme4/issues/179#issuecomment-40123184 and tried to change from `link=inverse` to `link=log`, still with Gamma. It kind of work, but then I get the warning messages (with both scaled and not scaled data): 
```
Model failed to converge with max|grad| = 0.00276352 (tol = 0.001, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?;Model is nearly unidentifiable: large eigenvalue ratio
 - Rescale variables?
```
Since the variables are also scaled, I wondered if that problem came from the Gamma distribution or if it doesn't have a huge influence on the ouput. I checked other forums and could not get to a final conclusion, considering the possible distribution problem that I have.  I tried with more simple models and got the same problem. 

(I'm using the package version 2.1.21 in RStudio and I can send the original dataset if necessary)

I'm happy with any input or suggestion!
Thanks a lot,
Adriana

**Comment by bbolker** [comment]
This is really a request for general statistical modeling help, and as such belongs on another forum (`r-sig-mixed-models` or CrossValidated: see https://github.com/lme4/lme4#where-to-get-help ; please follow up elsewhere ...

I've posted some exploratory stuff below that may help you.

Some general points:

- don't ever worry about the *marginal* distribution of your response variable (i.e. what you get from a histogram or density plot); you need to think about the *conditional* distribution, i.e. look at residuals, Q-Q plots, etc.
- you should generally pick your distribution on theoretical/*a priori* grounds
- matching the exact conditional distribution is probably the *least* important aspect of model fitting; the other assumptions (linearity, homoscedasticity, lack of outliers) are all more important
- the DHARMa package is useful (see below), and especially its vignettes
- fitting continuous distributions to discrete data *can* be OK, especially if the discrete counts are large, but exploration below suggests it doesn't work well
- Gamma with the default (inverse) link is often computationally fragile; the log link usually works better



```
troubleshooting_data <- read.table("lme4_GH582.txt", header=TRUE)

nrow(troubleshooting_data)
library(lme4)
summary(troubleshooting_data)
sapply(troubleshooting_data,sd)
## scaling variables with large SD gets rid of warning messages
model1 <- glmer(number ~ scale(date) + name + total +index1 + scale(height) + index3 + scale(length) + simpleindex + (1|site),
                data = troubleshooting_data,
                family=poisson)
attr(logLik(model1),"df") ## 10 parameters

model2 <- update(model1, family=Gamma(link="log"))

library(GGally)
ggpairs(troubleshooting_data)
library(DHARMa)
plot(simulateResiduals(model1))
lattice::qqmath(model1)  ## alternative qq
plot(model1,type=c("p","smooth"),col=1,col.line="red")
plot(simulateResiduals(model2))
```
