### ISSUE TITLE
PIRLS step-halvings failed to reduce deviance in pwrssUpdate in Gaussian (log link) model

### ISSUE THREAD

**Issue by leorjorge** [lme4/lme4#585]
I am trying to fit a glmm with a Gaussian distribution and log link, and I'm getting this error message, which according to https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#other-problemslme4-error-messages should show up when the link function creates values that are not defined for the distribution chosen. Given this case is the opposite (negative values are acceptable in a gaussian, but will never be generated on the log scale), I wouldn't expect this to be an issue. 
This is a quite simple model, with just 1 random factor, and two categorical fixed effects with 2 and 3 levels respectively. I'm getting this error even when trying to fit a null model only with the random factor, so I'm puzzled on what could be causing this.

**Comment by bbolker** [comment]
Can you provide a reproducible example ... ?

**Comment by leorjorge** [comment]
Thank you very much in advance, and sorry for the lack of the example. 
It follows in the link:
https://www.dropbox.com/sh/1rgvlswlql3ldya/AAB4Fz6luXK5ZMMRLECNEgrNa?dl=0

**Comment by bbolker** [comment]
I can get things to run by providing a better `etastart` (GLMs are very difficult to run on this model as well: I'm not sure what makes it so hard, some combination of the very large scale of the response and the non-standard link ...)  It's still a bit unstable, but I think the results are pretty reliable (also, the differences among groups are very large)

https://gist.github.com/bbolker/ea8ed558d9fe0a4a1a6909039242eb87

**Comment by leorjorge** [comment]
Thank you very much for your time and really fast response! I think this sorts it, hopefully also for the other datasets we have. 

I understand this is difficult data to deal with, we went for the log link both because the response we are interested in makes more sense in a logarithmic scale, and also to avoid negative predictions in the model. 

By the way, I was wondering if it is by design that the mustart values are required when building a log-link gaussian model? That's something quite hard to figure out as well.
