### ISSUE TITLE
GQdk causes system meltdown

### ISSUE THREAD

**Issue by mpadge** [lme4/lme4#588]
With due acknowledgement that `GQdk` is "currently unused", it is nevertheless exported, and on my machine at least causes a complete crash of the R session. It happens because there is no check on allocation in these lines:

https://github.com/lme4/lme4/blob/f07c1b091132559f20348a8e717dec4111ea744f/src/external.cpp#L59-L61

But you know the size of the vector beforehand (`factorial(length(v_))`, at least for all cases called within `GQdk`, which is the only place that function is called), so you can easily pre-allocate and thereby simply trigger a `bad_alloc` rather than system meltdown. You'll also avoid all the dynamic `push_back` calls.

----

@bbolker This came up as part of the development of [`autotest`](https://github.com/mpadge/autotest) for the rOpenSci Statistical Software Review project. `GQdk` has an example, and mutating/fuzzing that in current form (by varying `d`) leads to the above meltdown. Most packages fail `autotest` checks in a variety of ways (which is fine, because that's the point of it), but complete meltdowns can not of course be processed or dealt with, so it'd be good to fix or remove that one. Thanks!

**Comment by bbolker** [comment]
OK, will take a look....

**Comment by bbolker** [comment]
There are a few ways to handle this:

1. fix the C++ code [*resolves the root issue*]
2. remove the examples of `GQdk` and/or the function itself and/or the C++ code that supports it, since we're really not using it anyway [*takes care of the problem, removes unused clutter*]
3. use `combinat::permn()` instead [*unclear what the advantage of C++ is in this case; as far as I can tell this step isn't a performance bottleneck under any normal circumstances*]
4. write our own little bit of code for generation permutations, e.g. as [here](https://blog.ephorie.de/learning-r-permutations-and-combinations-with-base-r) [*this solution is even less performant, and might not return values in a minimum-change sequence, but I doubt either of those points matters; it avoids the minor dependency burden of `combinat` (which is old and stable)*]

This commit f426fa2 applies solution 3.  Would you be willing to test this and/or send along a dangerous example to include in our test suite?

**Comment by mpadge** [comment]
The above-reference PR fixes the C++ code, and removes need to introduce extra package import (`combinat`). (The C++ code is also around 3-5 times faster than `combinat`, so good to keep, I'd say.) That PR will now give you something like this:
``` r
devtools::load_all (export_all = FALSE)
#> Loading lme4
#> Loading required package: Matrix
#library (lme4)
x <- GQdk (d = 15L, k = 2L)
#> Error in GQdk(d = 15L, k = 2L): Can not allocate a vector that large
```
<sup>Created on 2020-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But, interestingly and frighteningly, that does not made the code safe. Try this at your own peril:
``` r
devtools::load_all(export_all = TRUE)
#> Loading lme4
#> Loading required package: Matrix
d <- 10L # suffices for me
k <- 2L
GQNd <- GQN[[d]]
tmat <- t(GQNd[[k]])
perms <- .Call(allPerm_int, seq_len(d) + 1L, as.integer(factorial(d))) # okay here
rperms <- lapply(perms, function(v) c(1L, v))
dd <- unname(as.matrix(do.call(expand.grid, c(rep.int(list(c(-1,1)), d), KEEP.OUT.ATTRS=FALSE))))
# ## DO NOT TRY THIS!!!
#ret <- unname(unique(t(do.call(cbind,
#                            lapply(as.data.frame(t(cbind(1, dd))),
#                                   "*", e2=do.call(cbind, lapply(rperms, function(ind) tmat[ind,])))))))
e2=do.call(cbind, lapply(rperms, function(ind) tmat[ind,]))
dim(e2)
#> [1]      11 7257600
# x <- lapply(as.data.frame(t(cbind(1, dd))),"*",e2) # DO NOT TRY THIS EITHER!!
ddf <- as.data.frame(t(cbind(1,dd)))
dim(ddf)
#> [1]   11 1024
#x <- lapply (ddf, "*", e2) # This is where things go awry
#length(x)
#ret <- unname (unique (t (do.call (cbind, x))))
```

<sup>Created on 2020-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And an `lapply` call causes R session to crash. I have no idea how to safely catch that!

---

Note also at the very least that in your original code (the 3 commented-out `ret <-` lines above) you're calculating an effectively constant value of `e2` for every single column of the `as.data.frame` object, which ought at least be avoided by pre-calculating `e2` as above.

**Comment by bbolker** [comment]
I've spent a while flailing around with this; I haven't really approached it properly (i.e. really sitting down and thinking hard about the dimensionality of these Gauss-Hermite grids, and how the required size scales with `d` and `k`, and where the memory bottleneck is ...)   I could spend some more time thinking about imposing a sensible limit.

**on the other hand**: I think the proximal problem, which is that R on Linux will by default grab all the memory it wants until the system kills the process to stop it from compromising the stability of the entire OS, forcing the OS to kill it, can be overcome.  For example, running `ulimit -Sv 5000000` (S is for soft limit, v for max virtual memory, units are in Kb (2^10 bytes), so this is approx 5 Gb; see `man bash`) changes the outcome of running out of memory from killing the entire process to instead throwing an error

> Error: memory exhausted (limit reached?)
 
(which is indeed an R error, not an OS error)

Hope that's sufficiently resolved to let you proceed with testing etc ...

**Comment by mpadge** [comment]
Yeah, it definitely is not, or should not, be directly caused by the code as written. On the other hand, since the huge list of potentially huge matrices is ultimately reduced by a single `unique` call, the whole problem could be avoided by apply `unique` within each step of the `lapply`. Basically just a rearrangement of the sequence of calls in current expression. The only memory limit should be the one fixed by the [previous PR](https://github.com/lme4/lme4/pull/590), and condensing the mega-matrix list at each iteration would obviate problems with the remaining code. Happy to PR that if you want?

**Comment by bbolker** [comment]
Sure!  I feel bad that you're doing all this work, but not so bad that I won't accept your help :-)

**Comment by bbolker** [comment]
I think this is a running-out-of-memory issue; as far as I can tell, it's the [Linux out-of-memory killer](https://stackoverflow.com/questions/3426356/what-causes-an-r-script-to-get-killed) operating ... (see also comments on the bugzilla report).  I will happily accept another PR that reduces the memory load.
