### ISSUE TITLE
Help to fit a GLMM model (on Cytometry data)

### ISSUE THREAD

**Issue by DomenicoSkyWalker89** [lme4/lme4#591]
Hi Team,

I would like to fit a GLMM model on my data (below) to anderstand if ther is a statistical significance within a population beetween the two type of response (NR, R).
![image](https://user-images.githubusercontent.com/53559811/92126183-25cfaf80-ee00-11ea-982c-001f95fe5cd4.png)
 
I tryed to use this formula (mod1 = **glmer(formula = count ~  (response * population) + ( 1 | sample),
             family = poisson(link = "log"), data = count.long))**.

It's correct for what I want to do? how can i have a p-value for each different population comparing NR vs R?
![image](https://user-images.githubusercontent.com/53559811/92128249-8233ce80-ee02-11ea-99a8-03d96faee49e.png)

![image](https://user-images.githubusercontent.com/53559811/92128311-9081ea80-ee02-11ea-8245-ef3474351de4.png)

thanks a lot,
best Domenico

**Comment by bbolker** [comment]
Can you please take a look at https://github.com/lme4/lme4/#where-to-get-help ? This looks more appropriate for `r-sig-mixed-models@r-project.org` or https://stats.stackexchange.com ...
