### ISSUE TITLE
Issue with simr model 

### ISSUE THREAD

**Issue by gbate** [lme4/lme4#593]
Hi everyone

I'm having an issue specifying specifying a model when trying to do a power (sensitivity) analysis by effect size using simr. We have 85 participants and my model has 3 predictors (measured once per day for 3 days) and, therefore, there are 3 different means, SDs, and effect sizes I need to specify (one for each predictor). However, when I try to run the model, I get the error message: Error in setParams(object, newparams) : length mismatch in beta (6!=4). I've messed around with the fixef line several ways, but the only way I can get the model to run is by only have 1 predictor, which I do not want to do. Can anyone help out with this? Thank you! I'm including my syntax below

Observation <- as.factor(rep(1:3)) ##both DV and IVs measured 3 times
Subject <- as.factor(rep(1:85)) #85 participants
CAR<- rnorm(255, 119.06, 106.39) #mean and SD of CAR
Slope<- rnorm(255, -.74, .24) #mean and SD of Slope
Total<- rnorm(255, 72.15, 60.93) #mean and SD of Total
dataset <- expand.grid(Observation, Subject) #creating data set of Observations x Subject
dataset<-cbind(dataset,CAR,Total,Slope) #bringing the predictors into the data set
names(dataset)[1]<-  "Observation"
names(dataset)[2]<-  "Subject"
names(dataset)[3]<-  "CAR"
names(dataset)[4]<-  "Total"
names(dataset)[5]<-  "Slope"
dataset #looking at the dataset
b1 <-c(0, -2.76) #plugging in effect sizes
b2 <-c(0,.24)
b3 <-c(0,-0.87)
V1 <- 192.92
s <- 18.95 #residual SD
model1 <- makeLmer(y ~ CAR + Total + Slope + (1|Subject), fixef=fixed, VarCorr=V1, sigma=s, data=dataset)

**Comment by pitakakariki** [comment]
Your model has four fixed effects: Intercept, CAR, Total, and Slope. So something like `b <- c(0, -2.76, 0.24, -0.87)` will work if you use `fixef=b`.

**Comment by pitakakariki** [comment]
@bbolker if you give me admin access I can move issues like this over to the simr repository. Alternatively I could give you admin access over there if you'd prefer to move them yourself.

**Comment by gbate** [comment]
Thank you so much for your help with this! I'm unfamiliar with how to grant admin access. Is there an easy way to do that? Sorry about the trouble.

Now the model runs, but when when I try to run the sensitivity analysis with the syntax I depicted below, with all 3 predictors, I get an error message again. Any advice? Thanks again, truly appreciate it.

pc2 <- powerCurve(model1, along="CAR", "Total", "Slope")
plot(pc2)
summary(pc2)
print(pc2)

**Comment by pitakakariki** [comment]
Only works along one axis at a time. Try `powerCurve(model1, along="Subject")`
