### ISSUE TITLE
Categorical response variable

### ISSUE THREAD

**Issue by polvanrijn** [lme4/lme4#594]
Dear developers of lme4,

I would like to fit a multinomial multilevel model with discrete (so unordered) categories to some predictor variables. So let's say I want to predict music style (`style`) using three styles: `rock`, `classic` and `blues`. To predict the music style we could take predictors like `beats_per_minute` or `number_of_instruments`. There are also some variables that should not have an effect, like `country_of_recording`. Each row represents a single piece. Now I would like to do something like:
```
model = glmer(style ~ beats_per_minute + number_of_instruments + (1|country_of_recording), data = df, family=categorical( link = "logit"))
```

As far as I know, such a categorical family is not yet implemented. I know the `family = binomial`, but this does not work for more than 2 categories.

The same question has been asked before ([1](https://stats.stackexchange.com/questions/319427/mixed-model-with-categorical-response-variable), [2](https://stats.stackexchange.com/questions/372143/r-glm-with-a-categorical-response-variable), [3](https://stats.stackexchange.com/questions/389918/which-family-to-use-for-glmm-with-3-level-categorical-response-variable-in-r) and [4](https://stats.stackexchange.com/questions/280423/is-it-currently-possible-to-run-a-multinomial-logistic-regression-with-random-su)) but was never really answered. The only workaround was to use `brms` ([this question](https://discourse.mc-stan.org/t/understanding-output-of-multinomial-multilevel-model-using-brms-package/7517) seems related too). 

So my question is, is it possible to fit a lme4-model to discrete categories? If so, could you maybe tell me where to look for an answer? If not, is such feature planned? If not such a feature is planned or developed, I would be willing to implement it myself. But would be very happy to get some advice on how to go about implementing it.

Thanks for your time reading and replying to the question.

All the best,
Pol van Rijn

**Comment by bbolker** [comment]
The short answer is "no, not really". As far as I remember, multinomial models can be implemented as a series of appropriately "stacked" binomial models (e.g. category N vs category 1, category N vs category 2 ...), e.g. see https://data.princeton.edu/wws509/notes/c6.pdf . Really the "only" difficulty is bookkeeping, i.e. deciding how you're going to organize all of the different fits.  If you wanted I could try to cook up a short example.

**Comment by polvanrijn** [comment]
Thank you for your fast reply. It would be great if we could set up a small example. Maybe it would make sense to use datasets that are commonly used in regular multinomial logistic regression? 

One commonly used dataset is the hsbdemo data set. It contains 200 observations each of a single student. The outcome variable is program type (`prog`), which can either be `general`, `academic` or `vocation`. As predictor variables we could use:
- social economic status (`ses`), which is either `low`, `middle` or `high` and
- writing score (`write`), indicating writing abilities

As a random effect we could use the student ID or maybe gender?

```
df <- foreign::read.dta("https://stats.idre.ucla.edu/stat/data/hsbdemo.dta")
```

**Comment by bbolker** [comment]
Looked a little bit more at Rodríguez's WWS509 notes (linked above), and this is a *little* harder than I thought - there are two different not entirely equivalent ways to set up the model ("log-linear" and "hierarchical logit") ... (this "slightly harder than I thought" probably explains why I still haven't gotten around to it ...)

**Comment by polvanrijn** [comment]
Thanks for the reply. I had a better look at Rodríguez's notes. Are there reasons to either favour the log-linear over the hierarchical logit or vice versa (e.g. pragmatical reasons, like on approach can more easily be integrated into the `lme4` package)? Maybe it is helpful to have a look at commonly used packages for multinomial logistic regression like [`nnet`](https://github.com/cran/nnet/blob/master/R/multinom.R). What do you think?

**Comment by cvoeten** [comment]
While it would of course be convenient if a family like `multinom` (e.g. as in `mgcv`) could be added to `lme4`, multinomial mixed models can already be fitted in `lme4` using the "Poisson trick" to reformulate the multinomial log-likelihood as an equivalent Poisson log-likelihood. [This paper](https://arxiv.org/pdf/1707.08538.pdf) seems to cover the approach quite comprehensively. Maybe that could help you out right now?

**Comment by polvanrijn** [comment]
@cvoeten, thanks for the reply. For now, I decided to go with `brms`, which also works well for my research question. It would be amazing if the `multinom` option could be added in the future.
