### ISSUE TITLE
Issues with reverse import package lmerconveniencefunctions

### ISSUE THREAD

**Issue by JonathanDKim** [lme4/lme4#597]
Hi all,

Sometime after lme4 version EDIT: 1.1-21 (have gotten that far, but haven't been able to check further due to my computer not wanting to change between versions of lme4 very well), something happened that stops certain functions of 'lmerconveniencefunctions' from working properly with lme4. I am aware that this should be something for those behind lmerconveniencefunctions to fix, but since it seems nothing has been done on that package in half a decade I was hoping for some guidance here.

Specifically, the bfFixefLMER_F.fnc (backfitting of fixed effects in LMER models) and pamer.fnc (compute upper- and lower-bound p-values for the analysis of variance or deviance) give the error "Error in pf(anova.table[term, "F value"], anova.table[term, "Df"], nrow(model@frame) - : Non-numeric argument to mathematical function". I have suspicions that the same would be found for ffRanefLMER.fnc, but my models haven't run far enough for me to check that since bfFixefLMER_F.fnc throws up the error. 

I have found the same result on both my home computer and my work computer, and regardless of data set. I found that this has previously been an issue in 2014, although at that point at least the coders for lmerconveniencefunctions were still active (https://stat.ethz.ch/pipermail/r-sig-mixed-models/2014q2/022264.html)

I recognise that this might not be the best place to discuss this, but since you all have the best understanding of lme4 I thought it was worth asking whether you had any insight into how to fix this? Even if it's just a fix on my end?

**Comment by JonathanDKim** [comment]
I should note, this issue happens in R versions 3.6.2 and 4.0, which is why I think the disconnect comes from a change to lme4

**Comment by bbolker** [comment]
This is fairly easy to understand.  Commit 98d8c8a8d894d20 (released in version 1.1-23, 6 March 2020) changed the names of the table produced by `anova()`, for reasons explained in #528. If `LMERConvenienceFunctions` had any tests this would have been caught during reverse dependency checks ... It should (?) be fairly easy to fix by finding the place in the code where it is looking for columns "Chi Df" or "Df" and change these to "Df" and "npar" respectively ... It would be a good idea to contact the package maintainer (`maintainer("LMERConvenienceFunctions")`) and ask them if they can fix the CRAN version of the package ...

**Comment by JonathanDKim** [comment]
Excellent; thank you for the advice :) I will try my hand at updating the code for my own use, and I will try to contact the package maintainer as you suggest :)

**Comment by JonathanDKim** [comment]
For anyone looking at this in the future, I looked into the code; pamer.fnc needs to a code change from Df to npar in two places, while bfFixefLMER_F.fnc calls to pamer.fnc, meaning that changing the code for pamer.fnc fixes the problem for both.

**Comment by bbolker** [comment]
Great. You should definitely contact the package maintainer and ask them to implement this fix ...

**Comment by JonathanDKim** [comment]
I sent him a message when you first suggested it; no reply yet, but we live in hope.
