### ISSUE TITLE
1.1-26 (!@%@#$) release checklist

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#604]
- `lmerTest`: chisq test 0/1 change (pull request submitted to `runehaubo/lmerTestR`)
- `simr`: logical value for LHS of formula (fixed)
- `panelr` ?  tries to pass args `terms` and `type` to `simulate.merMod`, these unused args end up in `...`, which triggers a warning which in turn fails tests (`expect_silent(simulate(mod))`).

**Comment by pitakakariki** [comment]
Uh-oh what did simr do wrong now?

**Comment by bbolker** [comment]
Not simr's fault.  I'm just mad because stuff keeps slipping through the cracks of my testing setup..


*** Changes to worse in reverse dependencies ***
Debian: <https://win-builder.r-project.org/incoming_pretest/lme4_1.1-25_20201014_022810/reverseDependencies/summary.txt>
 
Log dir: <https://win-builder.r-project.org/incoming_pretest/lme4_1.1-25_20201014_022810/>
The files will be removed after roughly 7 days.

**Comment by pitakakariki** [comment]
Does fixed refer to fixed effects or is the problem already solved?

**Comment by bbolker** [comment]
should be solved in 66579b0 (not tested yet though)

**Comment by bbolker** [comment]
@pitakakariki : I've fixed the problem  (in 85c180885658c), but in order to avoid submitting a new version of `lme4` I wonder if it might be possible for you to add

```r
   simulate.formula_lhs_ <- function(object, nsim = 1, seed = NULL, newdata, ...) {
            .simulateFun(formula=object, nsim=nsim, seed=seed, newdata=newdata, ...)
        }
```
(and export it in your `NAMESPACE`) as a stopgap?  Or, I could suck it up and do the right thing and bump the version number and re-submit with the fix ...

**Comment by pitakakariki** [comment]
CRAN are getting a bit nervous, would you like a hand?

**Comment by bbolker** [comment]
No thanks.  I think I can just package what I've got and submit it (after a little tiny bit of fussing with `NEWS` etc.). All three of the issues listed above should be resolved.
