### ISSUE TITLE
Error with predict.merMod and newdata

### ISSUE THREAD

**Issue by Fatjetaa** [lme4/lme4#605]
I have build a model:

```r
def_model <- glmer(VSV ~ leeftijd + geslacht + niveau + 
        leerweg + `al Mondriaan` + apcg + aantal1415  + 
            (1 | BSN) + (1|schoolnieuw), data = defVSV, 
                   family = binomial(link = "logit"), control = glmerControl(optimizer = "bobyqa"))
```

And tried to predict VSV on newdata with function:

```r
predict(def_model, newdata = VSV_17_18, type = "response")
```

but I got the following error:

> Error in `[.data.frame`(fr, vars) : undefined columns selected

The `newdata` is a data frame with the same variables as in the data, which is used to build the model. I am getting the same error with:

```
predict(def_model, newdata = model.frame(def_model))
```

Used packages:

```
readxl
tidyverse
ggplot2
GGally)
reshape2
compiler
parallel
boot
lattice
broom
gridExtra
lme4
```

**Comment by bbolker** [comment]
Is there any chance we can have a reproducible example?  I don't know what's going on but my first guess would be the variable with a space in its name ...

**Comment by bbolker** [comment]
Reproducible example:

```r
library(lme4)
cbpp$`silly period` <- cbpp$period
m <- glmer(cbind(incidence,size-incidence) ~ `silly period` + (1|herd),
           family=binomial, data=cbpp)

predict(m)
predict(m,newdata=cbpp)
```

>  Error in `[.data.frame`(fr, vars) : undefined columns selected

**Comment by Fatjetaa** [comment]
That is indeed the case. It worked. Thank you very much!

**Comment by bbolker** [comment]
for what it's worth, this should work now even if the variable names have spaces in them ...
