### ISSUE TITLE
Add in QQ plots glmers

### ISSUE THREAD

**Issue by anthonycrane** [lme4/lme4#608]
Hello lme4 developers!  I've been wondering for a while if QQ plots were going to be made available for glmers and just stumbled across this comment. I've been playing around with implementing QQ-plots for various count regression glmers using code borrowed from the countreg package here: https://rdrr.io/rforge/countreg/src/R/qresiduals.R, but would happy to also take a look at the implementation in qq.gam. Is this a priority for your team? I'm not sure how to get started as a contributor here but would be happy to try and tackle this.

https://github.com/lme4/lme4/blob/b2de8ee3e6a48c3dbe95693f8e612a7a7615a5b9/R/plot.R#L428

**Comment by anthonycrane** [comment]
The DHARma package seems to cover this: https://cran.r-project.org/web/packages/DHARMa/index.html

**Comment by bbolker** [comment]
Yes, I was going to say that.  The other point is that "plain" QQ plots have been part of `lme4` for a long time (albeit by the somewhat obscure title of `qqmath`: there is also a `qqmath` method for random effects. But I agree that the `DHARMa` randomized quantile residuals are more useful in less-straightforward cases.

```
library(lme4)
m1 <- glmer(cbind(incidence,size-incidence)~period+(1|herd), data=cbpp, family=binomial)
library(lattice)
qqmath(m1)
qqmath(ranef(m1))
```
