### ISSUE TITLE
FR: add information on getME(merMod,"lower") and `boundary (singular) fit: see ?isSingular` 

### ISSUE THREAD

**Issue by iago-pssjd** [lme4/lme4#609]
I would like to automatize the update of a model when I get a warning. I am trying it through `tryCatch` (but for the moment I have some issues about which I have already asked [here](https://stackoverflow.com/questions/65035226/is-there-a-way-to-use-trycatch-or-similar-in-r-as-a-loop-or-to-manipulate-the)).

The problem was that I knew that with `tryCatch` or similar I could handle warnings and errors, but I didn't know that I also can handle simple messages as `boundary (singular) fit: see ?isSingular`. This led me to the question, why is this message not a warning as are convergence fails?

**Comment by iago-pssjd** [comment]
Related, so the issue could be thought as a double FR. In `?getME` I can read:
```
"lower":
lower bounds on model parameters (random effects parameters only).
```
So on one side, a documentation FR: Can you extend on this?
And on the other side, if I run `getME(model,"lower")` I get a numeric vector without more information, so I do not know what to check with it. Here, the 2nd FR: Could the values of this numeric vector having informative names?

Thank you!

**Comment by bbolker** [comment]
1. If you like you can control the behaviour of singular models by saying (e.g.) `control=lmerControl(check.conv.singular=.makeCC(action="warning", tol))` (where `tol` is a tolerance). Your choices are "ignore", "message", "warning", or "stop" (see `?lmerControl`)

2. Making the default action "message" was chosen initially in version 1.1-19 (2018) because we didn't suddenly want lots of warnings showing up in everybody's output. I think there's a reasonable argument to be made for either "message" or "warning" - it doesn't necessarily indicate that there's actually anything *wrong* with the model (-> message), but it does suggest that something might need attention (-> warning)

more later ...

**Comment by bbolker** [comment]
This should be fixed now.  This is what I wrote for the expanded documentation:

> ‘"lower"’: lower bounds on random-effects model parameters (i.e, "theta" parameters). In order to constrain random  effects covariance matrices to be semi-positive-definite,  this vector is equal to 0 for elements of the ‘theta’ vector corresponding to diagonal elements of the Cholesky   factor, ‘-Inf’ otherwise. (‘getME(.,"lower")==0’ can be   used as a test to identify diagonal elements, as in ‘isSingular’.)

Feel free to suggest improvements.

**Comment by iago-pssjd** [comment]
Thank you Ben!,

A few later than I introduced the issue I got those diagonal elements that you refer by `getME(.,"theta")[getME(.,"lower")==0]`. For all what I have found, I understand that these elements are related to the variances of random effects, but I don't see how. Despite that, I see now that it is described in https://cran.r-project.org/web//packages/lme4/vignettes/lmer.pdf around equation (18), so maybe the vignette could be referred.

**Comment by bbolker** [comment]
Maybe. On the other hand, most of the content of `?getME` is pretty technical already: I feel like anyone who's calling `getME()` either already knows what they're doing or should know to look in the vignette ...  FWIW the relationship between the diagonal elements of the Cholesky factors and the variances is complicated unless the Cholesky factor is actually diagonal (in which case the covariance matrix will be diagonal, and the `theta` values will be exactly the standard deviations of the corresponding variance term). For example, for a 3x3 unstructured matrix (i.e. all off-diagonal elements non-zero), the variances are `{ theta1^2, theta2^2 + theta4^2, theta3^2 + theta5^2 + theta6^2 }`, where `[theta1, theta4, theta6]` are the diagonal elements. So you can say that the diagonal elements represent a *lower bound* for the standard deviations, but not much more than that ...
