### ISSUE TITLE
lme4 not installing

### ISSUE THREAD

**Issue by doublemd3** [lme4/lme4#610]
Hello, 

The lme4 package is not installing. Below are the issues reported before exit: 

`libtool: link: ERROR: no information for variable 'AR' cru .libs/libutil.a .libs/mt19937ar.o .libs/sobolseq.o .libs/timer.o .libs/stop.o .libs/redblack.o .libs/qsort_r.o .libs/rescale.o 
../libtool: line 1102: ERROR:: command not found
Makefile:371: recipe for target 'libutil.la' failed
make[2]: Leaving directory '/tmp/RtmppGdVcH/R.INSTALL6a2d1a7f7173/nloptr/src/nlopt_src/util'
make[2]: *** [libutil.la] Error 127
Makefile:574: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/tmp/RtmppGdVcH/R.INSTALL6a2d1a7f7173/nloptr/src/nlopt_src'
Makefile:438: recipe for target 'all' failed
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
ERROR: configuration failed for package ‘nloptr’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.6/nloptr’
Warning in install.packages :
  installation of package ‘nloptr’ had non-zero exit status
ERROR: dependency ‘nloptr’ is not available for package ‘lme4’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.6/lme4’
Warning in install.packages :
  installation of package ‘lme4’ had non-zero exit status`

**Comment by bbolker** [comment]
Can you try `install.packages("nloptr")` and see if you get similar errors?

**Comment by doublemd3** [comment]
Yes, exact same errors: 

> libtool: link: ERROR: no information for variable 'AR' cru .libs/libutil.a .libs/mt19937ar.o .libs/sobolseq.o .libs/timer.o .libs/stop.o .libs/redblack.o .libs/qsort_r.o .libs/rescale.o 
../libtool: line 1102: ERROR:: command not found
Makefile:371: recipe for target 'libutil.la' failed
make[2]: Leaving directory '/tmp/RtmpKzEp2D/R.INSTALL5013262c1e1/nloptr/src/nlopt_src/util'
make[2]: *** [libutil.la] Error 127
Makefile:574: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/tmp/RtmpKzEp2D/R.INSTALL5013262c1e1/nloptr/src/nlopt_src'
Makefile:438: recipe for target 'all' failed
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
ERROR: configuration failed for package ‘nloptr’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.6/nloptr’
Warning in install.packages :

**Comment by bbolker** [comment]
OK then, this is an `nloptr` issue - not really something we can fix. It looks like [CRAN nloptr needs R >= 4.0.x, you can install an older version if you need to stick with R 3.x](https://stackoverflow.com/questions/62900525/install-lme4-from-cran-on-ubuntu)
