### ISSUE TITLE
GLMMs: fitting only betas with fixed covariance

### ISSUE THREAD

**Issue by ilyakorsunsky** [lme4/lme4#614]
Dear Authors, 

Is it possible to run glmer in a modular fashion such that the covariance parameters are fixed and only the betas are estimated during optimization? For instance, I want to shrink one effect with one diagonal covariance and a different effect with a separate covariance matrix. 

Thanks! 

Ilya

**Comment by bbolker** [comment]
Yes, if I understand you correctly, but there will be a certain "do-it-yourself"/hackish quality.   See `?modular`.

For example

```
library(lme4)
## regular fit
gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
                data = cbpp, family = binomial)
getME(gm1,"beta")

## modular fit with fixed theta
gf <- glFormula(cbind(incidence, size - incidence) ~ period + (1 | herd),
                data = cbpp, family = binomial)
devfun <- do.call(mkGlmerDevfun, gf)
## run first step to get all the bits in the right place
optimizeGlmer(devfun)
devfun <- updateGlmerDevfun(devfun, gf$reTrms)
ee <- environment(devfun)
ls(env=ee)
ee$lower
theta_fix  <- 1
optfun <- function(beta) {
    devfun(c(theta_fix,beta))
}
opt2 <- nloptwrap(rep(0,4),fn=optfun,lower=rep(-Inf,4),
          upper=rep(Inf,4))
opt2$par
## this doesn't quite work
res <- mkMerMod(ee, opt2, gf$reTrms, fr=gf$fr)
```




This question is probably more suited to `r-sig-mixed-modesl@r-project.org`, see [where to ask?](https://github.com/lme4/lme4/#where-to-get-help); please send follow-ups there.
