### ISSUE TITLE
convergence issues with continuous variables in model

### ISSUE THREAD

**Issue by psher23** [lme4/lme4#618]
Running logistic or poisson in glmer with any random effect does not converge if there is a continuous variable in the model. Rescaling the continuous variables does not resolve the error. The model runs as expected in coxme or other mixed effects models.

m1 <- glmer(OUTCOME_DEAD~ AGE + (1|ZIP), family=binomial, data=d2)

Warning messages:
1: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.0216585 (tol = 0.002, component 1)
2: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?

**Comment by bbolker** [comment]
Could we have a reproducible example please?  Do you have complete or near-complete separation?

**Comment by psher23** [comment]
There is no complete or near complete separation.

The format of the data is binary outcome, continuous exposure, and categorical random effect. See sample data:

[dat_sample.txt](https://github.com/lme4/lme4/files/5882731/dat_sample.txt)

```
m1<- glmer(outcome_dead ~ AGE + (1|ZIP), family=binomial, data=dat_sample)
summary(m1)
```

**Comment by bbolker** [comment]
When I run this I don't get the convergence warning. Scaling the age variable makes the large-eigenvalue warning go away.

The only thing I see about this data that looks at all problematic is that the cluster sizes are very small:

```
summary(as.numeric(table(dd$ZIP)))
##   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  1.000   1.000   1.000   1.629   2.000   7.000 
```
i.e. mean samples per cluster is only  more than half of the clusters have n==1, more than 75% have n<=2, max value is 7

This means it would be wise to use Gauss-Hermite quadrature (i.e. `nAGQ` > 1); I tried that, in this case it had barely any effect on the point estimates *or* the confidence intervals.

What results did you get?

```r
  group term            estimate std.error conf.low conf.high
1 NA    (Intercept)        1.61     0.136     1.37      1.91 
2 NA    scale(AGE)         0.345    0.0850    0.180     0.516
3 ZIP   sd__(Intercept)    0.583   NA         0         1.07 
```

When in doubt, try `allFit(m1)`. I got:

```r
aa <- allFit(m1)
ss <- summary(aa)
 ss$msgs[!sapply(ss$msgs,is.null)
## $nlminbwrap
## [1] "boundary (singular) fit: see ?isSingular"
## $nmkbw
## [1] "Model failed to converge with max|grad| = 0.0037293 (tol = 0.002, component 1)"
```

Looking at `ss$fixef`, `ss$theta`, `ss$llik`, it seems that `nlminbwrap` got stuck at a singular fit for some reason, but the rest of the estimates are OK (`nkmbw` finds a fit that is a tiny bit worse than the other optimizers).

**Comment by psher23** [comment]
Yes the cluster size is a result of the sampled dataset - the full dataset has 200k obs. I have attached a slightly larger sample here that throws the convergence warnings. I tried allFit - I do not get the nlminbwrap singular fit warning for the full dataset.

[dat_sample.txt](https://github.com/lme4/lme4/files/5883908/dat_sample.txt)


```
gm_all <- allFit(m1)
bobyqa : [OK]
Nelder_Mead : [OK]
nlminbwrap : [OK]
nmkbw : [OK]
optimx.L-BFGS-B : [OK]
nloptwrap.NLOPT_LN_NELDERMEAD : [OK]
nloptwrap.NLOPT_LN_BOBYQA : [OK]
Warning messages:
1: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.111155 (tol = 0.002, component 1)
2: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?
3: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.00709144 (tol = 0.002, component 1)
4: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?
5: In optwrap(optimizer, devfun, start, rho$lower, control = control,  :
  convergence code 9999 from optimx: none
6: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.0124928 (tol = 0.002, component 1)
7: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?
8: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.0945225 (tol = 0.002, component 1)
9: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?
```

**Comment by bbolker** [comment]
Huh.  Scaling age (which gets rid of all of the distracting "very large eigenvalue" warnings) and using `nAGQ=20` I get no problems with *any* of the optimizers with this data set.

```r
m3 <- glmer(outcome_dead ~ scale(AGE) + (1|ZIP), family=binomial, data=dd2,
            nAGQ=20)
aa <- allFit(m3)
ss <- summary(aa)
ss$msgs
```

In any case, `allFit()` should tell you everything you need to know. From `?convergence`:

>  use ‘allFit’ to try the fit with all available optimizers (e.g. several different implementations of BOBYQA and Nelder-Mead, L-BFGS-B from ‘optim’, ‘nlminb’, ...).  While this will of course be slow for large fits, we consider it the gold standard; if all optimizers converge to values that are practically equivalent, then we would consider the convergence warnings to be false positives.

**Comment by bbolker** [comment]
I'm going to close this for now: feel free to re-open if you have further questions/new information ...
