### ISSUE TITLE
Trying to install lme4 and lmer

### ISSUE THREAD

**Issue by pleasehelp1234** [lme4/lme4#620]
every time I try to install this package this is what I get:

Warning in install.packages :   package ‘lm4’ is not available (for R version 4.0.2)

**Comment by pleasehelp1234** [comment]
Now i am getting the same message for drop1.merMod

**Comment by bbolker** [comment]
You should try `install.packages("lme4")` (if you don't spell it correctly, R doesn't know what it means ...)

**Comment by bbolker** [comment]
Closing this (feel free to re-open if you are still having problems and can give more information)
