### ISSUE TITLE
Estimates by lmer changes due to permutation of rows

### ISSUE THREAD

**Issue by soumyasahu** [lme4/lme4#630]
Hi lme4 Team,

I am having a strange problem. I am using the following model on the data (I am sharing the first 18 rows i.e. data of patient 1).

## Model
```{r}
model <- lmer(response ~ 0 + rater1 + rater2 + rater3 + rater1timept + rater2timept + rater3timept
                 + (0 + rater1 + rater2 + rater3 | patient) + (0 + rater1 + rater2 + rater3 | patient:timept),
                 data = newdata, REML = T)
```

## Data
```{r}
   rater patient timept obs_no response rater1 rater2 rater3
2      1       1      1      1 5.315988      1      0      0
3      1       1      1      2 5.486210      1      0      0
4      1       1      2      1 3.368949      1      0      0
5      1       1      2      2 3.829588      1      0      0
6      1       1      3      1 2.692542      1      0      0
7      1       1      3      2 3.993876      1      0      0
8      2       1      1      1 5.445650      0      1      0
9      2       1      1      2 7.017736      0      1      0
10     2       1      2      1 3.195931      0      1      0
11     2       1      2      2 3.232998      0      1      0
12     2       1      3      1 3.200544      0      1      0
13     2       1      3      2 3.350447      0      1      0
14     3       1      1      1 5.692071      0      0      1
15     3       1      1      2 6.527657      0      0      1
16     3       1      2      1 3.133882      0      0      1
17     3       1      2      2 3.330115      0      0      1
18     3       1      3      1 2.571569      0      0      1
19     3       1      3      2 2.948904      0      0      1
````
## Estimates of fixed and random effects

````{r}
c(getME(model, "fixef"), as.data.frame(VarCorr(model))[, "vcov"])

      rater1       rater2       rater3 rater1timept rater2timept rater3timept              
  3.68452161   4.11748456   3.97399862  -0.05746881  -0.16188797  -0.10450828   1.33642021 
                                                                                           
  1.30546422   1.05245295   1.19503701   1.05410633   1.06959196   0.15045522   0.10943759 
                                                                 
  0.17248444   0.10640661   0.09153883   0.08890000   0.15760252 
````

Now I am permuting the data so that time points are in increasing order for each patient (for example I am showing for the first patient).

## Permuted data

````{r}
   rater patient timept obs_no response rater1 rater2 rater3
2      1       1      1      1 5.315988      1      0      0
3      1       1      1      2 5.486210      1      0      0
8      2       1      1      1 5.445650      0      1      0
9      2       1      1      2 7.017736      0      1      0
14     3       1      1      1 5.692071      0      0      1
15     3       1      1      2 6.527657      0      0      1
4      1       1      2      1 3.368949      1      0      0
5      1       1      2      2 3.829588      1      0      0
10     2       1      2      1 3.195931      0      1      0
11     2       1      2      2 3.232998      0      1      0
16     3       1      2      1 3.133882      0      0      1
17     3       1      2      2 3.330115      0      0      1
6      1       1      3      1 2.692542      1      0      0
7      1       1      3      2 3.993876      1      0      0
12     2       1      3      1 3.200544      0      1      0
13     2       1      3      2 3.350447      0      1      0
18     3       1      3      1 2.571569      0      0      1
19     3       1      3      2 2.948904      0      0      1
````

Now If I use the same model on this data, the estimates are,

```{r}
  rater1       rater2       rater3 rater1timept rater2timept rater3timept              
  3.68452161   4.11748456   3.97399862  -0.05746881  -0.16188797  -0.10450828   1.33644709 
                                                                                           
  1.30547442   1.05245081   1.19505798   1.05412510   1.06959855   0.15047718   0.10943729 
                                                                 
  0.17252346   0.10641505   0.09155549   0.08891764   0.15760193 
```

Although the fixed effects are the exact same, the estimates of random effects differ a little. Interestingly REML criterion at convergence are exactly the same.

This is a simulation study. In this example model for both data converges. But in some simulations, I have seen the model for first data converge but the model for the permuted data is not. I am confused why this is happening.

In our research, we are studying the large sample properties of these estimates and we have progressed well but suddenly I found out this which I am not able to explain. Kindly take a look on this issue.

Thanks,
Soumya.

**Comment by bbolker** [comment]
This may be the same as [this issue](https://github.com/lme4/lme4/issues/449).

The short answer is that (1) unfortunately the linear algebra is not always perfectly independent of the structure of the Z matrix: (2) the maximum deviation between these estimates is of the order of 0.0002 (i.e., 0.02%). Is this an important difference for your use case?

I can understand that you would be worried about this difference, but the bottom line is that we have seen it before and fixing it would be very challenging.

Also see the notes in the previous issue about what "converged" vs "non-converged" means; basically, only that the magnitude of certain computed values was above or below a specified threshold.

Feel free to clarify further.

```r
nm <- c("rater1","rater2","rater3","rater1timept","rater2timept","rater3timept")
x1 <- c(3.68452161,4.11748456,3.97399862,-0.05746881,-0.16188797,-0.10450828,1.33642021,
  1.30546422,1.05245295,1.19503701,1.05410633,1.06959196,0.15045522,0.10943759,
  0.17248444,0.10640661,0.09153883,0.08890000,0.15760252)

x2 <- c(3.68452161,4.11748456,3.97399862,-0.05746881,-0.16188797,-0.10450828,1.33644709,
        1.30547442,1.05245081,1.19505798,1.05412510,1.06959855,0.15047718,0.10943729,
        0.17252346,0.10641505,0.09155549,0.08891764,0.15760193)

all.equal(x1,x2)
max(abs(x1-x2)/((x1+x2)/2))
```

**Comment by bbolker** [comment]
Any further comments on this?

**Comment by soumyasahu** [comment]
Hi Dr. Ben,

Thanks a lot for your quick reply and sorry for my delay in replying to your commemt.
I see the difference is very little and I don't think it will put any effect on the distributions of the estimates.
My goal in raising this issue is to understand why this is happening as I have checked 'X' and 'Z' matrices are perfectly fine. In that context, I don't quite understand your comment, _'unfortunately the linear algebra is not always perfectly independent of the structure of the Z matrix:'_  Can you give me a little more explanation? I don't need a detailed explanation. An intuition is fine for me.

**Comment by bbolker** [comment]
I meant to say that **computationally** the linear algebra is not invariant to permutation of rows and columns, although **mathematically** it is.

I commented in the other that thread that addition/subtraction are not (necessarily) associative in floating-point math:

```r
((1/3 + 1/4) - 1/5) - (1/3 + (1/4 - 1/5))  ##  -5.551115e-17
```

Here's a simple example that even basic matrix multiplication is not invariant to permutation of rows and columns:

```r
set.seed(101)
m <- matrix(rnorm(9), 3, 3)
r1 <- m %*% m
perm <- sample(3)
iperm <- match(1:3, perm)  ## inverse permutation
## permute rows & cols, multiply, permute back
r2 <- (m[perm, perm] %*% m[perm, perm])[iperm, iperm]
r1-r2
##              [,1]         [,2]          [,3]
##  [1,] 5.551115e-17 0.000000e+00  5.551115e-17
##  [2,] 0.000000e+00 1.387779e-17 -2.775558e-17
##  [3,] 0.000000e+00 0.000000e+00  0.000000e+00
```

For simple calculations the floating-point errors are normally of the order of `.Machine$double.eps`, but in complex (or numerically unstable) computations these floating-point errors can be magnified considerably ..

**Comment by bbolker** [comment]
I'm going to close this; feel free to re-open it if there's a reason.
