### ISSUE TITLE
ranef extremely slow

### ISSUE THREAD

**Issue by humana** [lme4/lme4#637]
This might be related to this issue https://github.com/lme4/lme4/issues/636

But when I am using predictInterval from merTools, it takes extremely long (more than a minute) and from profiling, 99% of the time is spent in the ranef() call, which seems to come from the lme4 package.  Once again, this is a quite large model, with a lot of nested groups and interaction terms.  As in the issue mentioned above, I have already performed the optimizations to manually create the interactions.

**Comment by bbolker** [comment]
I haven't dug into the guts of predictInterval (yet). If you've already created the interactions manually as described in #636 (or, if you've installed the development version from GitHub), then the interaction machinery is presumably not the problem. The only general issue that occurs to me is that computing conditional variances can be slow - *if* they're not needed for the computation then `ranef(., condVar = FALSE)` will be faster. 

Beyond that, we would need a reproducible example to get any farther ...

**Comment by humana** [comment]
Attached is an example re-creating the issue.  

[ranef_slow_test.zip](https://github.com/lme4/lme4/files/7015813/ranef_slow_test.zip)

As you mentioned, predictInterval unnecessarily calls it multiple times.  I actually took their code and pulled the ranef calls outside and created my own predictInterval, so that I can pass it through on subsequent calls.  But it would be nice if we could determine what causes the slowness:

```
ranef_cached <- ranef(model)
ranef_condvar_cached <- ranef(model, condVar = TRUE)
myPredictInterval(model, X, ranef_cached, ranef_condvar_cached, n.sims=1000, which="full")
```

**Comment by bbolker** [comment]
I'm afraid you may be out of luck.

The slow part is indeed computing the conditional variances (see below), and these computations are already coded by Doug Bates in C++, in what is presumably a pretty efficient way. The relevant code is [here](https://github.com/lme4/lme4/blob/8ca6f33939e14821979dc86126bbf0718f9f7531/src/predModule.cpp#L93-L131); the corresponding math is expressed in equation 57 of the [lme4 vignette](https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf). It's *conceivable* that some very careful examination  and profiling of the implementation could find ways to speed things up, but there definitely doesn't seem to be any low-hanging fruit here ...

The only speedup I can see is in `predictInterval` (not calling `ranef()` more times than necessary, especially not with `condVar = TRUE`).

My version of `slow.R` (exploration):

```
library(lme4)
data <- read.csv(file = 'data.csv')
## convert chars to factors so we investigate number of levels (double-check that 
## construction of interactions etc. really isn't what's messing us up)
dd <- as.data.frame(lapply(data,
                           function(x) if (is.character(x)) factor(x) else x))
sapply(dd, function(x) if (is.factor(x)) length(levels(x)) else 1)
summary(dd)
## conclusion: no. no interactions to expand in the grouping variables, and no factors with unreasonable
## numbers of levels in the RE terms

## fitting:
## 1043 operations, 163 seconds (laptop)
t0 <- system.time(pred.model <- lmer(y ~ x1*x2 +  x1*x2*x3 +  x1*x4 + x5 + x6 +  x7*x8 + x9 + (1+x2 + x2*x3|mm_ry) + (1+x2 + x2*x3|int_mm_ry_mmv_ry), data=data,
                   verbose=TRUE,
                   control = lmerControl(calc.derivs = FALSE)))

t1 <- system.time(r1 <- ranef(pred.model, condVar = TRUE )) ## 34 seconds
## debugging through this with debug(lme4:::ranef.merMod), we see that the only particularly slow line is:
##      vv <- .Call(merPredDcondVar, object@pp$ptr(), as.environment(rp)) -- direct call to C++, reference above
t2 <- system.time(r2 <- ranef(pred.model, condVar = FALSE)) ## 0.003 seconds
```

**Comment by humana** [comment]
> The only speedup I can see is in predictInterval (not calling ranef() more times than necessary, especially not with condVar = TRUE).

Agreed. Thanks for the detailed write up. I hope it will help someone in the future too.
