### ISSUE TITLE
Convergence Issue

### ISSUE THREAD

**Issue by delucalab** [lme4/lme4#639]
Dear All,

I have a dataset with 119 individuals with information on the presence of lesions of various types (1,2,3) at various levels (1,2,3) and want to understand the effect of type and location on lesion presence. Therefore, I ran the following:

glmer.model<-glmer(LesionPresence ~ Location*Type + (1 | ID), data=lesion_proportion_staged_level, family="binomial")

Unfortunately, I ran into the following warning:

In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.048092 (tol = 0.002, component 1)

I'm quite new to running mixed models and even with some googling am still unsure why I am running into this issue? Any insight would be much appreciated. I am attaching the model output below and the input data in case that is helpful:

Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) [
glmerMod]
 Family: binomial  ( logit )
Formula: LesionPresence ~ Level * LesionType + (1 | ID)
   Data: lesion_proportion_staged_level

     AIC      BIC   logLik deviance df.resid 
  1080.4   1129.2   -530.2   1060.4      962 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.6875 -0.5649 -0.3291  0.7170  4.2816 

Random effects:
 Groups Name        Variance Std.Dev.
 ID     (Intercept) 1.519    1.232   
Number of obs: 972, groups:  ID, 119

Fixed effects:
                   Estimate Std. Error z value Pr(>|z|)    
(Intercept)         -1.6081     0.2966  -5.423 5.87e-08 ***
Level1              -0.6006     0.3900  -1.540 0.123600    
Level2              -0.7270     0.4094  -1.776 0.075782 .  
LesionType1          1.6362     0.3538   4.624 3.76e-06 ***
LesionType2          1.1659     0.3524   3.309 0.000938 ***
Level1:LesionType1  -0.3568     0.5022  -0.711 0.477379    
Level2:LesionType1  -0.2015     0.5211  -0.387 0.698986    
Level1:LesionType2   0.4030     0.5004   0.805 0.420607    
Level2:LesionType2   0.1608     0.5229   0.308 0.758387    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) Level1 Level2 LsnTy1 LsnTy2 L1:LT1 L2:LT1 L1:LT2
Level1      -0.603                                                 
Level2      -0.574  0.447                                          
LesionType1 -0.703  0.498  0.475                                   
LesionType2 -0.694  0.503  0.479  0.582                            
Lvl1:LsnTy1  0.480 -0.766 -0.339 -0.691 -0.400                     
Lvl2:LsnTy1  0.461 -0.344 -0.775 -0.665 -0.385  0.466              
Lvl1:LsnTy2  0.468 -0.772 -0.344 -0.392 -0.692  0.598  0.268       
Lvl2:LsnTy2  0.453 -0.344 -0.773 -0.379 -0.665  0.267  0.607  0.468
optimizer (Nelder_Mead) convergence code: 0 (OK)
Model failed to converge with max|grad| = 0.048092 (tol = 0.002, component 1)

**Comment by bbolker** [comment]
Can you please post this to `r-sig-mixed-models@r-project.org` (subscribe first: you can find the info/subscription page by web-searching ...) See https://github.com/lme4/lme4#where-to-get-help
