### ISSUE TITLE
Rcpp version in DESCRIPTION is too old

### ISSUE THREAD

**Issue by NikNakk** [lme4/lme4#641]
I've just run into an issue with a missing function in Rcpp because the version required by lme4 is older than is actually supported. `Rcpp_precious_remove` wasn't introduced until Rcpp 1.0.6, so I would suggest updating the required version in DESCRIPTION at least to that (or to 1.0.7 if you're not planning to test lme4 with the previous release).

**Comment by bbolker** [comment]
My guess is that you have slightly misdiagnosed the problem. See [here](https://stackoverflow.com/questions/68416435/rcpp-package-doesnt-include-rcpp-precious-remove): My diagnosis is that `lme4` **will** work with earlier versions of Rcpp, but that there is a mismatch somewhere in the *binary installations* of the package stack that `lme4` uses: in other words, my guess is that `RcppEigen` (last CRAN update 2020-12-17) was built with an older version of `Rcpp` than `lme4` (last CRAN update 2021-06-22). 

Testing my hypothesis:

```r
remotes::install_version("Rcpp", "1.0.6")  # install from 
install.packages("RcppEigen", type = "source")
install.packages("lme4", type = "source")
library(lme4)
example(lmer)
```

This seems to work fine, at least on my system.

**Comment by bbolker** [comment]
The best way to deal with this is an open question: `glmmTMB` frequently has this problem with the `TMB`, `Matrix` packages. I [wrote some experimental code](https://github.com/glmmTMB/glmmTMB/blob/081015febcbf17fc350e122a3bd3c046e0772b3b/glmmTMB/R/utils.R#L735-L761) to try to diagnose/warn about these problems ...

**Comment by NikNakk** [comment]
Thanks for the rapid feedback. However, what you’ve done is to test it works with 1.0.6 which is the version when that function was introduced. I’ve just tested your exact code substituting 1.0.5 for 1.0.6 and I get the error again.

You can make the minimum version 1.0.6 if you like, but my principal is that I’ll try where possible to put the minimum version of a dependency that I’ve confirmed is compatible.

**Comment by bbolker** [comment]
Oops.  I misread your point about versions. I'm still confused about/trying to understand the root cause, as `Rcpp_precious_remove` doesn't actually appear in the source code for `lme4` ...

I just ran 

```r
remotes::install_version("Rcpp", "1.0.5")
install.packages("RcppEigen", type = "source")
install.packages("lme4", type = "source")
example(lmer)
library(lme4)
example(lmer)
```

from a **clean** R session (you may need a clean R session in order to make sure that DLLs are properly unloaded) and it seems to work for me? (I'm assuming that `example("lmer")` is sufficient to replicate the problem if it exists?)

```
> packageVersion("RcppEigen")
[1] ‘0.3.3.9.1’
> packageVersion("Rcpp")
[1] ‘1.0.5’
> packageVersion("lme4")
[1] ‘1.1.27.1’
```

**Comment by bbolker** [comment]
Just curious if there are any further updates from your side? (I know, it's the weekend)

**Comment by NikNakk** [comment]
Quite right. I was testing things out on rstudio.cloud, but that was install RcppEigen and lme4 from binaries despite passing the type as source. The issue, as you pointed out, is that if lme4 (and RcppEigen) are compiled using a newer version of Rcpp, they use newer Rcpp functionality and so the error I've identified results. I'm not sure what the best option is here. Increasing the version required of Rcpp might cause a problem for people compiling from source who want to keep an earlier version of Rcpp around for other reasons, whereas the current situation means that lme4 fails unexpectedly for those installing it from CRAN as a binary and who expect the R package dependency system to ensure any dependencies are on the appropriate minimum versions. 

I haven't tested your experimental code yet, but that looks like a sensible approach. Do you think it's worth raising this with the RcppCore team since it may apply to any packages built using Rcpp that are released as binaries on CRAN?

**Comment by bbolker** [comment]
Did you ever have a chance to test my experimental code?
