### ISSUE TITLE
Avoid/Circumvent stop("No random effects terms specified in formula")

### ISSUE THREAD

**Issue by SchmidtPaul** [lme4/lme4#648]
I want to use the `update()` function to fit different `lmer` mixed models - all with random effects - but the base model that would be *updated* does not have any random effects. This throws an error due to the [`stop()` function here](https://github.com/lme4/lme4/blob/23abf93e99ba91b1f5584ab62397315aa953e3bb/R/utilities.R#L194). What would be the most efficient way to circumvent this problem / approach my situation?

``` r
library(dplyr)
dat <- mtcars %>% mutate_at(vars(vs:carb), as.factor)

library(lme4) # it does not work with lmer
base.model <- lmer(mpg ~ vs, dat)
#> Error: No random effects terms specified in formula
base.model %>% update(. ~ . + (1|am)) %>% AIC()
#> Error [...]
base.model %>% update(. ~ . + (1|carb)) %>% AIC()
#> Error [...]

# Bonus: it works for glmmTMB
library(glmmTMB)
base.model <- glmmTMB(mpg ~ vs, dat, REML=TRUE)
base.model %>% update(. ~ . + (1|am)) %>% AIC()
#> [1] 176.8022
base.model %>% update(. ~ . + (1|carb)) %>% AIC()
#> [1] 188.9686
```
<sup>Created on 2021-10-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bbolker** [comment]
This is unfortunately just not possible without a radical change in architecture.  It would probably be (much) easier to adapt `semEff` to know about `negbin` objects (produced by `MASS::glm.nb`) than to adapt `glmer.nb` to work without random effects. Do you have a minimal reproducible example of what you want to do with `semEff` + `glm.nb` ?
