### ISSUE TITLE
fixing the covariance matrix to pre-defined values

### ISSUE THREAD

**Issue by AlexiaJM** [lme4/lme4#650]
Hi @bbolker and @dmbates, this is a follow-up on a recent email about fixing the covariance matrix in a lmer or glmer model. Thank you for the email response. I tried using the modular approach but ran into problems.

The problem is if I don't do non-linear optimization, I get a constant random effect. What we actually need is to 1) run model A with fixed and random effects and 2) then run model B (which has the same formula as model A, but the values of the variables are slightly different) while fixing the random effects to values found in model A. I made a simple example below. I am unable to transfer the random effects of model A to model B without also transferring the fixed-effects. 

```
library(lme4)

sleepstudy_ = sleepstudy
sleepstudy_$Days[1:50] = sleepstudy_$Days[1:50]*100 + 5 # Modifying the variable Days in sleepstudy_


### model with data="sleepstudy"

# 1.  Parse the data and formula:
lmod <- lFormula(Reaction ~ Days + (Days|Subject), sleepstudy)
names(lmod)
# 2.  Create the deviance function to be optimized:
(devfun <- do.call(mkLmerDevfun, lmod))
ls(environment(devfun)) # the environment of 'devfun' contains objects
                        # required for its evaluation
# 3.  Optimize the deviance function:
opt <- optimizeLmer(devfun)
opt[1:3]
# 4.  Package up the results:
fit1 = mkMerMod(environment(devfun), opt, lmod$reTrms, fr = lmod$fr)
# Saving the parameters for reusing later
opt_1 = opt
rand_1 = lmod$reTrms
devfun_1 = environment(devfun)
fr_1 = lmod$fr


### model with data="sleepstudy_"

# 1.  Parse the data and formula:
lmod <- lFormula(Reaction ~ Days + (Days|Subject), sleepstudy_)
names(lmod)
# 2.  Create the deviance function to be optimized:
(devfun <- do.call(mkLmerDevfun, lmod))
ls(environment(devfun)) # the environment of 'devfun' contains objects
                        # required for its evaluation
# 3.  Optimize the deviance function:
opt <- optimizeLmer(devfun)
opt[1:3]
# 4.  Package up the results:
fit2 = mkMerMod(environment(devfun), opt, lmod$reTrms, fr = lmod$fr)


### Model with data="sleepstudy_" but with the random effects obtained with data="sleepstudy"

# 1.  Parse the data and formula:
lmod <- lFormula(Reaction ~ Days + (Days|Subject), sleepstudy_)
names(lmod)
# 2.  Create the deviance function to be optimized:
(devfun <- do.call(mkLmerDevfun, lmod))
ls(environment(devfun)) # the environment of 'devfun' contains objects
                        # required for its evaluation
## We don't want to optimize, but if we don't the random effect is a constant everywhere
## We want to restore the random effects from fit1, but not the fixed-effects
# names(environment(devfun)) =  "lower"         "resp"          "pp"            "lmer_Deviance"; only pp seems to contain random effects
environment(devfun)$pp = devfun_1$pp # (PROBLEM HERE I THINK) this contains both fixed and random effects and trying to change only one thing lead to read-only errors: "environment(devfun)$pp$theta = devfun_1$pp$theta" leads to error
# do not touch environment(devfun)$resp as I think that this is fixed-effect stuff, but I am unsure?
lmod$reTrms = rand_1 # must replace the random terms
opt = opt_1 # must replace the random effects optimization
# do not touch lmod$fr since its the variables

# 4.  Package up the results:
fit2_rand1 = mkMerMod(environment(devfun), opt, lmod$reTrms, fr = lmod$fr)


fit1
fit2
fit2_rand1

# fit2_rand1 now has the same fixed effects as fit1, so we failed. It's because of that environment(devfun)$pp
# commenting out the pp line leads to the random effects being constant everywhere

```

**Comment by bbolker** [comment]
Does this do what you want?

```r
library(lme4)

sleepstudy_ = sleepstudy
sleepstudy_$Days[1:50] = sleepstudy_$Days[1:50]*100 + 5 # Modifying the variable Days in sleepstudy_

## model with 'sleepstudy'
fit1 <- lmer(Reaction ~ Days + (Days|Subject), sleepstudy)

## get top-level parameters (scaled Cholesky factor of RE cov matrix)
th_1 <- getME(fit1, "theta")

## model with 'sleepstudy_'
fit2 <- update(fit1, data = sleepstudy_)

## modular model with sleepstudy_
lmod <- lFormula(Reaction ~ Days + (Days|Subject), sleepstudy_)
devfun <- do.call(mkLmerDevfun, lmod)
## dummy optimization, so we can get the right object
opt <- optimizeLmer(devfun, control = lmerControl(optCtrl = list(maxfun=0)))
## evaluate the deviance function
## with the top-level parameters from fit1
## This updates the environment of devfun
devfun(th_1)
## package
fit2_rand1 <- mkMerMod(environment(devfun), opt, lmod$reTrms, fr = lmod$fr)

fixef(fit1)
fixef(fit2)
fixef(fit2_rand1)
```

**Comment by AlexiaJM** [comment]
Hi Ben, thanks for the quick response.

Your approach seems to give similar fixed effects between fit2 and fit2_rand1, but the random effects of fit2_rand1 are still not the random effects of fit. See
```
ranef(fit1)
ranef(fit2)
ranef(fit2_rand1)
```

However, I do get the exact same theta parameters:
```
getME(fit1, "theta")
getME(fit2_rand1, "theta")
```

I am right to understand that the only model parameters are 'theta' and 'beta', so your approach is indeed only changing beta. And then the ranef correspond to prediction made from the data with that same theta, so it changes only due to the data? I just want to be sure as my knowledge of random effects is rusty.


Alexia

**Comment by bbolker** [comment]
Hmm, I'm having a little trouble understanding what you need here. In lme4-world, both the fixed effects and the random effects (BLUPs/conditional modes) are computed directly, via fancy linear algebra, conditional on the data and on (a) specified covariance matrix (matrices) for the random effect(s).  So it's not super-easy to say "fix the covariance matrix *and* the fixed-effect parameters to specified values and find the corresponding random effects" **or** "fix the covariance matrix and the random effects to a specified value and solve for the fixed effects".  In fact, if you really want to hold the random effects fixed, shouldn't you be able to add an offset for the random effects and then solve the linear model? i.e. something like this:

```r
## effects of RE only; compute full predictions (including all RE) minus
##   population-level RE (including no RE)
## this could be done more efficiently ...
RE_preds <- function(model, newdata) {
  predict(model, newdata, re.form = NULL) -
    predict(model, newdata, re.form = NA)
}

head(rr <- RE_preds(fit1, sleepstudy_))
lm(update(formula(fit1, fixed.only = TRUE), . ~ . + offset(rr)),
   data = sleepstudy_)
```

**Comment by AlexiaJM** [comment]
Hi Ben,

We are really just trying to do alternating optimization in a mixed-effect model: i.e. 
1) learn beta_1, theta while fixing beta_2, beta_3 (mixed model)
2) learn beta_2 while fixing beta_2, beta_3, theta (learning fixed-effects only)
3) learn beta_3 while fixing beta_2, beta_3, theta   (learning fixed-effects only)

I think the approach in https://github.com/lme4/lme4/issues/650#issuecomment-979544722 would do that, but maybe your latest suggestion make more sense as it fixes parts of the actually model formula and I do actually make use of a similar offset in the alternating optimization for fixed-effect models.

Thanks a lot for your help, I will try both approaches and see which one converges properly the LEGIT alternating optimization.

Alexia

**Comment by bbolker** [comment]
I'm not really sure what all the different beta vectors are in your comment above &mdash; but I guess either one of these approaches will do what you want, or you'll come back and give us more details ...
