### ISSUE TITLE
'reOnly(f)' does not preserve 'environment(f)'

### ISSUE THREAD

**Issue by jaganmn** [lme4/lme4#654]
This minor bug affects the result of `formula(<merMod>, random.only = TRUE)`:

```r
packageVersion("lme4") # 1.1.27.1

f <- Reaction ~ Days + (1 | Subject)
e <- environment(f)
m <- lmer(f, data = sleepstudy)

identical(environment(formula(m)), e) # TRUE
identical(environment(formula(m, fixed.only = TRUE)), e) # TRUE
identical(ee <- environment(formula(m, random.only = TRUE)), e) # FALSE

as.list(ee)
```
```none
$f
Reaction ~ Days + (1 | Subject)

$response
[1] TRUE
```

`ee` should be identical to `e`; instead it is the frame of the `reOnly` call inside of `formula.merMod`. The issue is that `reOnly` does not pass `env = environment(f)` to `reformulate`:

https://github.com/lme4/lme4/blob/1fbf0afea36782cca7c58e3d5338ea88eebf4b9c/R/predict.R#L17-L21

**Comment by bbolker** [comment]
fixed, thanks. (What are you doing/how are you exercising the package to discover issues like this??)

**Comment by jaganmn** [comment]
I'm not, really - I only noticed in the process of answering this question:

https://stackoverflow.com/questions/70661745/
