### ISSUE TITLE
Issues installing lme4 package, problem with nloptr dependency

### ISSUE THREAD

**Issue by amepham** [lme4/lme4#656]
I am working on Databricks through my company's subscription and need to install R packages each time I open my cluster. 

Trying to install `lme4` today has repeated issues, specifically with installing the dependency `nloptr`.

`ERROR: compilation failed for package ‘nloptr’`
`* removing ‘/home/[email_removed]/x86_64-pc-linux-gnu-library/4.0/nloptr’`
`Warning in install.packages :`
`  installation of package ‘nloptr’ had non-zero exit status`
`ERROR: dependency ‘nloptr’ is not available for package ‘lme4’`
`* removing ‘/home/[email_removed]/R/x86_64-pc-linux-gnu-library/4.0/lme4’`
`Warning in install.packages :`
`  installation of package ‘lme4’ had non-zero exit status`

Unsure if this is an `lme4` bug or not. Seeking advice how best to proceed.

Thanks and regards,
Alex

**Comment by amepham** [comment]
Also, other members of my team are experiencing the same issues/error messages.

**Comment by mmaechler** [comment]
No, it's an `nloptr` issue only.
The `nloptr` package is about to be updated on CRAN, notably as there will have been a maintainer change from Jelmer Ypma to Aymeric Stamm.
You and your team may *temporarily* (!) consider installing `nloptr`  from its development website, i.e., the new maintainer's github, at  https://github.com/astamm/nloptr  

Once you've installed `nloptr` , installation of `lme4` should be seemless.

**Comment by devarops** [comment]
@amepham:
This worked for us:

```
devtools::install_github('cran/nloptr@1.2.2.3')
install.packages('lme4')
```

**Comment by bbolker** [comment]
Is there any particular reason you went with the old/current CRAN version rather than installing the new version (`remotes::install_github("astamm/nloptr")`), which will be up on CRAN shortly?

**Comment by devarops** [comment]
@bbolker:
I tried to install that `install_github("astamm/nloptr")` first, but it didn't work for me.
I'm unable to install the version 2.0.0 of `nloptr`.
The version 1.2.2.3 is the newest version that I was able to install.

**Comment by bbolker** [comment]
It would help a lot if you could go over to https://github.com/astamm/nloptr/issues and post some details of your problems with installation ...

**Comment by devarops** [comment]
It seems that version 2.0.0 of `nloptr` requires CMake.
But I was able to install version 1.2.2.3 without installing CMake first.

After installing CMake, this worked:

```
remotes::install_github("astamm/nloptr")
install.packages('lme4')
```

**Comment by bbolker** [comment]
was there a clear error message that guided you about what to do? (I think I've seen examples where the failed install said something like `the [xxx] system library is required; please install it, e.g. `sudo apt-get install [xxx]; yum [....]; or brew install [xxx]` (maybe `nloptr` already does this?)

**Comment by devarops** [comment]
I can't imagine a clearer error message 😅

![image](https://user-images.githubusercontent.com/3461018/151427437-0210d327-845f-49b1-91be-280ecb8277b6.png)

**Comment by amepham** [comment]
Thanks everyone for all your comments. Myself and my team have been able to use lme4 while ownerships are changing over using the different solutions supplied here. Thanks again, everyone!
