### ISSUE TITLE
Should the singularity check occur before bailing for empty derivatives?

### ISSUE THREAD

**Issue by palday** [lme4/lme4#659]
At the beginning of `checkConv`, we have:

https://github.com/lme4/lme4/blob/67f57e2a2d3835278c6f716d4b162d1825ac336f/R/checkConv.R#L17

and then later:

https://github.com/lme4/lme4/blob/67f57e2a2d3835278c6f716d4b162d1825ac336f/R/checkConv.R#L24-L46

It's not quite as unconditional as the comment indicates: if `calc.derivs=FALSE` is set, then no singularity check is performed, regardless of the value for `check.conv.singular`.

Should the block for singularity be moved to the top of the function? I'm happy to write the trivial PR but wanted to see if others found this desirable.

**Comment by bbolker** [comment]
Yes please.
