### ISSUE TITLE
Incorrect Supported R Versions

### ISSUE THREAD

**Issue by ddsjoberg** [lme4/lme4#664]
Hello! Thank you for the wonderful modeling package!

I wanted to let you know that the DESCRIPTION file indicates that R >= 3.2.0 is currently supported by the lme4 package. However, the package uses the `reformulate(env=)` argument, which was added in R 3.6. This line was added about 3 weeks ago.
 https://github.com/lme4/lme4/blob/fa75e54a118e2b92ef38381d665978589437756f/R/predict.R#L18
```r
reOnly <- function(f, response=FALSE) {
    reformulate(paste0("(", vapply(findbars(f), deparse1, ""), ")"),
                response = if(response && length(f)==3L) f[[2]],
                env = environment(f))
}
```
(This nice shiny app makes it easy to see the history of a function https://hughjonesd.shinyapps.io/rcheology/)

The issue that I am seeing is that lme4 is able to be installed on R 3.5 (for example), but when scripts are run, we get an error because the `env=` argument doesn't yet exist in the older version of R.

**Comment by bbolker** [comment]
OK.  We've put a lot of work into maintaining backward compatibility ([hooks.R](https://github.com/lme4/lme4/blob/master/R/hooks.R) contains an entire catalog of back-compatibility functions), so I guess we'll add this one to the list ...

**Comment by ddsjoberg** [comment]
Thank you so much!

**Comment by bbolker** [comment]
pushed something that makes sense on the face of it but might be terrible (failing tests now!)

**Comment by bbolker** [comment]
if you have  a convenient test platform for R < 3.6.0 could you test the current HEAD version?

**Comment by ddsjoberg** [comment]
thank you @bbolker !

I ran checks on the dev version of lme4, and everything works properly (https://github.com/larmarange/broom.helpers/pull/149)

I know you made a CRAN release recently. Do you have an estimated timeline for the next release?

**Comment by bbolker** [comment]
I wouldn't really want to transgress the “no more than every 1–2 months" CRAN update rule (esp since changes so far are minor - I realize that this is messing up your checks but it does seem to be a fairly minor edge case [do you know if there are any stats on versions of R currently in use in the wild?]).

I guess we could aim for March 20 or so ... ?  If there were a strong case for accelerating the release I think CRAN would probably not give us much pushback ...

**Comment by ddsjoberg** [comment]
No rush from my end. You're exactly right...for me, it's a very minor "inconvenience" (if you could even call it that). I've just commented out the older R version checks for my packages that include lme4 for the time being. I'll watch for the release and re-activate when the next version is on CRAN.

Thanks again for looking into it so quickly! 

PS Your posts all over the internet the last few years have been extremely helpful. Thank you for all the help you've given the community (and me)!
