### ISSUE TITLE
Request on the order of `merMod@cnms`

### ISSUE THREAD

**Issue by iago-pssjd** [lme4/lme4#679]
I get an issue because `findbars` returns the random effects expressions ordered possibly different of the order in the `merMod` slot `cnms`. Indeed, considering the example in https://www.rpubs.com/bbolker/lme4trouble1
```r
source("SO_23478792_dat.R")
df$SUR.ID <- factor(df$SUR.ID)
df$replicate <- factor(df$replicate)
Rdet <- cbind(df$ValidDetections,df$FalseDetections)
Unit <- factor(1:length(df$ValidDetections))
m1 <- glmer(Rdet ~ tm:Area + tm:c.distance +
            c.distance:Area + c.tm.depth:Area +
            c.receiver.depth:Area + c.temp:Area +
            c.wind:Area +
            c.tm.depth + c.receiver.depth +
            c.temp +c.wind + tm + c.distance + Area +
            replicate +
            (1|SUR.ID) + (1|Day) + (1|Unit) ,
            data = df, family = binomial(link="logit"))
findbars(m1@call)
[[1]]
1 | SUR.ID

[[2]]
1 | Day

[[3]]
1 | Unit
# while
m1@cnms
$Unit
[1] "(Intercept)"

$Day
[1] "(Intercept)"

$SUR.ID
[1] "(Intercept)"

```
Is there any way to get both orders matched (not changing the call to `lmer`)??

Otherwise, in order to solve this issue, I ask you if there is any chance to get some of the following:

-  would it be possible allowing to give the `mkReTrms`-argument `reorder.terms` to `lmer`/`glmer`? Does it have sense? Why is the default option `reorder.terms=TRUE` and why is it the one used in `lFormula` (line 389)?
- would you mind to export the function `mkBlist`, so it would allow to compute again the order permutation of the terms? (Of course, I know I can do `lme4:::mkBlist`, but it is not recommended in https://cran.r-project.org/doc/manuals/R-exts.html#Specifying-imports-and-exports)
- ~~alternatively, may the output of the function `mkReTrms` include the element `nl` as another component?~~

Thank you for considering the suggestion!

**Comment by iago-pssjd** [comment]
Thanks @bbolker . Both options, returning `nl` as part of `mkReTrms` or exporting `mkBlist` are fine for me and any of them is enough.  May close the issue if the commit regarding to it is definitive.

**Comment by bbolker** [comment]
The commit was to the master branch, so it will presumptively end up in the next CRAN release. (If it breaks something in a downstream package we'll probably ask the package maintainer to adapt rather than reverting this ...)

**Comment by iago-pssjd** [comment]
Dear @bbolker. I've just realized that `nl` is not informative as I thought, so I would prefer `mkBlist` exported if possible (or other alternative below). Indeed, I was thinking in `nl` as produced by 
```r
nl <- vapply(blist, `[[`, 0L, "nl")  # line 179 R/utilities.R
```
so I could obtain the output
```r
ord <- rev(order(nl)) # line 185 of R/utilities.R
```
but now I've realized that `nl` is reordered later in
```r
nl         <- nl        [ord] # line 187 of R/utilities.R
```
so I cannot reproduce the `ord` object.

Other option would be return `ord` as part of `mkReTrms`, when it exists or generate a default one even when `reorder.terms=FALSE` and return it always. 

Sorry for this and thanks again.

**Comment by iago-pssjd** [comment]
Thanks @bbolker.
My case is a function in which I need to reorder the output of `findbars(m1@call)` as it is so  that it matches that in `m1@cnms`. That is, I would do
```r
bars <- findbars(m1@call)
bars <- bars[ord] # without applying deparse(x[[3]]) or similar
``` 

The function updates the original formula to do later `update(m1, .~.  - some bar terms + some others)` (you know, https://stackoverflow.com/a/45188154). 

My issue is because I loop through `getME(m1, "theta")` output (and so, the order in `m1@cnms`), but I want to modify using the corresponding `findbars(m1)` output

**Comment by bbolker** [comment]
Again, just trying to understand the problem dimensions: What's wrong with doing `deparse(x[[3]])` etc. ? (Other than the generic "code smell" of using `deparse()` anywhere?)

In fact, I realize this is exactly how things are implemented in `lme4:::barnames()` (`deparse1()` is a "safe" version of deparse that was introduced in R 4.0.0; `R/hooks.R` has back-compatibility code defining the function for earlier versions of R)

```r
## repeat definition of lme4:::barnames()
barnames <- function(bars) vapply(bars, function(x) deparse1(x[[3]]), "")
res <- suppressWarnings(list(
    lmer(angle ~ recipe + temperature + (1|replicate) + (1|recipe), cake),
    lmer(angle ~ recipe + temperature + (1|recipe) + (1|replicate), cake)
 )
)
t(sapply(res, function(x) barnames(findbars(formula(x)))))
##      [,1]        [,2]       
## [1,] "replicate" "recipe"   
## [2,] "recipe"    "replicate"
t(sapply(res, function(x) names(getME(x, "cnms"))))
##      [,1]        [,2]    
## [1,] "replicate" "recipe"
## [2,] "replicate" "recipe"
```

**Comment by iago-pssjd** [comment]
> What's wrong with doing deparse(x[[3]]) etc. ? 

My answer is exactly what you say below:

>  I'm not quite sure what will happen in a case of repeated grouping variables like
```r
lmer(angle ~ recipe + temperature + (1|replicate) + (0+temperature|replicate), cake)
```
Or even more complex groupings. I think sorting `ff` depending on `barnames(ff)` is not safe in these cases. It is exactly because of this that I do not want to simplify (`deparse`) the output of `findbars`.

> PS I think using `formula()` is safer than accessing `@call` (it's not an internal S4 slot, and it is less likely to be screwed up by indirect references to formulas).

Thanks! I will take this into account.

**Comment by bbolker** [comment]
I appreciate the concern for safety (and it's hard to consider all the possible test cases), but I think the fact that the `barnames` as implemented here **is used internally within lme4** strongly suggests that it could be fine ...

**Comment by iago-pssjd** [comment]
Dear @bbolker. Sorry for the late answer.

Finally, if `mkBlist` is not exported, I reproduced the part which I need in my package and it seems to work fine, so I think we can close this issue.

Beyond that, you can revert the inclusion of `nl` in the output of `mkReTrms`. Otherwise, note that `nl` are the number of levels of the grouping factors. I say this because of (**warning!**):
https://github.com/lme4/lme4/blob/2b0b293e058052fe9be3fdc406a6efc429234383/inst/NEWS.Rd#L10-L11
and
https://github.com/lme4/lme4/blob/2b0b293e058052fe9be3fdc406a6efc429234383/man/mkReTrms.Rd#L63-L64
