### ISSUE TITLE
whether the data can include participants compelete the questionnaire on only one accasion

### ISSUE THREAD

**Issue by yanminwang576** [lme4/lme4#683]
it is known that linear mixed model is suitable for repeated measure. my longitudinal data is unbalanced, and many  participants compelete the questionnaire on only one accasion. can i include these participants?
any help is appeciated!

**Comment by bbolker** [comment]
Can you please ask this question on `r-sig-mixed-models@r-project.org` or [CrossValidated](https://stats.stackexchange.com)? See https://github.com/lme4/lme4/blob/master/README.md#where-to-get-help ...
