### ISSUE TITLE
can lmer be fitted to the longitudinal data that some units only have one observation?

### ISSUE THREAD

**Issue by yanminwang576** [lme4/lme4#684]
it is known that linear mixed model can be used to repeated measurement. my data is longitudinal, however, half of units only have one observation. can  this data be fitted with linear mixed model?

**Comment by yanminwang576** [comment]
some units only one observation

**Comment by bbolker** [comment]
You already asked this question [here](https://github.com/lme4/lme4/issues/683). In my response, I suggested that it would be more appropriate to post the question somewhere else, specifically to read [this link](https://github.com/lme4/lme4/blob/master/README.md#where-to-get-help) and go to the [r-sig-mixed-models mailing list](https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models) to ask for help there.

 sincerely
   Ben Bolker
