### ISSUE TITLE
partial match of 'eta' to 'etastart' when warnPartialMatchDollar = TRUE

### ISSUE THREAD

**Issue by EmilHvitfeldt** [lme4/lme4#686]
As the title says, when you set `options(warnPartialMatchDollar = TRUE)`, you get a partial match warning, which I believe is happening right here: https://github.com/lme4/lme4/blob/master/R/AllClass.R#L378

Distilled from https://github.com/tidymodels/recipes/issues/1002.

### Reprex

``` r
options(warnPartialMatchDollar = TRUE)

dat <- data.frame(
  value = factor(sample(letters, 1000, TRUE)),
  y = factor(sample(c(0, 1), 1000, TRUE))
)

lme4::glmer(y ~ 1 + (1 | value), 
            data = dat, 
            na.action = na.omit, 
            family = stats::binomial)
#> Warning in ll$eta: partial match of 'eta' to 'etastart'
#> boundary (singular) fit: see help('isSingular')
#> Generalized linear mixed model fit by maximum likelihood (Laplace
#>   Approximation) [glmerMod]
#>  Family: binomial  ( logit )
#> Formula: y ~ 1 + (1 | value)
#>    Data: dat
#>       AIC       BIC    logLik  deviance  df.resid 
#> 1389.2702 1399.0857 -692.6351 1385.2702       998 
#> Random effects:
#>  Groups Name        Std.Dev.
#>  value  (Intercept) 0       
#> Number of obs: 1000, groups:  value, 26
#> Fixed Effects:
#> (Intercept)  
#>    -0.06402  
#> optimizer (Nelder_Mead) convergence code: 0 (OK) ; 0 optimizer warnings; 1 lme4 warnings
```

<sup>Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bbolker** [comment]
OK, I am 99% sure that this line should be

```r
eta <<- if (!is.null(ll[["etastart"]])) as.numeric(ll[["etastart"]]) else numeric(length(y))
```

(This is almost but not quite a candidate for the `rlang`-style `%||%` operator; it's awkward because the `as.numeric` conversion doesn't fit smoothly, can't say `as.numeric(eta) %||% numeric(length(y))` &mdash; only if we defined `%||%` more generally as `if (length(x) == 0) y else x` (rather than `if (is.null(x))`) ...)
