### ISSUE TITLE
Error in callinf summary() of a glmerMod object from glmer.nb

### ISSUE THREAD

**Issue by tardipede** [lme4/lme4#688]
Hi,
I run a NB GLMM with glmer.nb, however when I try to use summary() it gets the following error:

```{r}
library(lme4) # Version 1.1-29
set.seed(101)
# R version 4.1.3
# merDeriv v. 0.2-4
data(Arabidopsis)

mod = glmer.nb(total.fruits~status+nutrient+(1|gen), data=Arabidopsis)
summary(mod)
## Error in vcov.glmerMod(object, use.hessian = use.hessian):  family has to be binomial or poisson
report::report(mod)
## Error in vcov.glmerMod(object, use.hessian = use.hessian):  family has to be binomial or poisson

mod@resp$family$family[1] 
## [1] "Negative Binomial(0.6105)"
```

Thanks, 
M.

**Comment by bbolker** [comment]
This is a limitation of the `merDeriv` package. Loading the `report()` package adds a `vcov.glmerMod` method that doesn't work with NB models. Compare `lme4:::vcov.merMod(mod)` (which works) with `merDeriv:::vcov.glmerMod(mod)`, which returns the warning.  We can probably harden the `summary.merMod` method to avoid this, but in the meantime you can get a summary of the `glmer.nb` method by **not** loading the `report` package (I don't think there's any way to avoid the overriding of the `vcov()` method once the `report` package has been loaded, even if it's subsequently detached).

You might want to raise an issue with the `merDeriv` maintainers about this as well ...
