### ISSUE TITLE
fixed-effect model matrix is rank deficient so dropping 1 column / coefficient

### ISSUE THREAD

**Issue by jhaltiga** [lme4/lme4#689]
Running a random-effects mixed model where the fixed portion has a control variable that is essentially a dummy indicating a village pair (it's an RCT). When I run the model as:

`lme4_4_B = lmer(posXsymp~treat_surg+treat_cloth+ pairID + (1 | union), data = bdata.raw1)`

The desire results are returned. However, when I treat 'pairID' as i(pairID) as in the following code the subject-title warning is returned and the results are slightly different. Is there a way to suppress the dropping of the coefficient even if the model matrix is rank deficient? 

`lme4_4_C = lmer(posXsymp~treat_surg+treat_cloth+ i(pairID) + (1 | union), data = bdata.raw1)`

**Comment by bbolker** [comment]
Yes, this is (obscurely) documented in `?lmerControl`:

> check.rankX = c("message+drop.cols", "silent.drop.cols", "warn+drop.cols",
                         "stop.deficient", "ignore"),

> check.rankX: character - specifying if ‘rankMatrix(X)’ should be
          compared with ‘ncol(X)’ and if columns from the design matrix
          should possibly be dropped to ensure that it has full rank.
          Sometimes needed to make the model identifiable.  The options
          can be abbreviated; the three ‘"*.drop.cols"’ options all do
          drop columns, ‘"stop.deficient"’ gives an error when the rank
          is smaller than the number of columns where ‘"ignore"’ does
          no rank computation, and will typically lead to less easily
          understandable errors, later.

so `control = lmerControl(check.rankX = "ignore")`

**Comment by jhaltiga** [comment]
the pairID variable is a matrix of 'dummy' variables such that in the run with i(pairID) as:

`lme4_4_C = lmer(posXsymp~treat_surg+treat_cloth+ i(pairID) + (1 | union), data = bdata.raw1)#lme4 package`

the results returned are of the form: 

```
Fixed effects:
                     Estimate       Std. Error  t value
(Intercept)   0.0004293125887  0.0038873457268  0.11044
treat_surg   -0.0008265679202  0.0005851967993 -1.41246
treat_cloth  -0.0004662459435  0.0008208982553 -0.56797
i(pairID)2    0.0027139134991  0.0054980005516  0.49362
i(pairID)3    0.0017492365217  0.0055985082814  0.31245
i(pairID)4    0.0077384031619  0.0056618102495  1.36677
i(pairID)5    0.0236874825370  0.0054770868053  4.32483
i(pairID)6    0.0117726645798  0.0054251462150  2.17002
i(pairID)7    0.0121387410706  0.0055350299311  2.19308
i(pairID)11   0.0027937979992  0.0056057768103  0.49838................k for 300 pairs.
```

ending of course with the rank deficient warning.

But when I run the model as: 

`lme4_4_B = lmer(posXsymp~treat_surg+treat_cloth+ pairID + (1 | union), data = bdata.raw1)#lme4 package`

I don't get any warnings in the results. I believe that both ways of treating i(pairID) should provide identical results for the fixed effects if not mistaken.

Re: results: for the first model:

```
Fixed effects:
                   Estimate      Std. Error  t value
(Intercept)  0.006388015539  0.000699189687  9.13631
treat_surg  -0.000449693362  0.000693399279 -0.64853
treat_cloth -0.001309650928  0.000870925219 -1.50375
pairID       0.000008816780  0.000003617534  2.43723
```

for the model treating pairID as i(pairID) as above:

```
Fixed effects:
                     Estimate       Std. Error  t value
(Intercept)   0.0004293125887  0.0038873457268  0.11044
treat_surg   -0.0008265679202  0.0005851967993 -1.41246
treat_cloth  -0.0004662459435  0.0008208982553 -0.56797
```

**Comment by jhaltiga** [comment]
> Yes, this is (obscurely) documented in `?lmerControl`:
> 
 
> so `control = lmerControl(check.rankX = "ignore")`

would this get directly added into my model code as:

`lme4_4_C = lmer(posXsymp~treat_surg+treat_cloth+ i(pairID) + (1 | union), control = lmerControl(check.rankX = "ignore"), data = bdata.raw1)#lme4 package`

**Comment by jhaltiga** [comment]
> > Yes, this is (obscurely) documented in `?lmerControl`:
> 
> > so `control = lmerControl(check.rankX = "ignore")`
> 
> would this get directly added into my model code as:
> 
> `lme4_4_C = lmer(posXsymp~treat_surg+treat_cloth+ i(pairID) + (1 | union), control = lmerControl(check.rankX = "ignore"), data = bdata.raw1)#lme4 package`

Updating that this code worked, but yielded the error:

`#Error in devfun(rho$pp$theta) : Downdated VtV is not positive definite`

which likely relates to my edited post preceding this quoted post where I present output from two models in greater detail.

**Comment by bbolker** [comment]
Can you please repost this question (in its entirety) to `r-sig-mixed-models@r-project.org`? See https://github.com/lme4/lme4/blob/master/README.md#where-to-get-help

It would help to see the results of `str(bdata.raw1)`

**Comment by jhaltiga** [comment]
> Can you please repost this question (in its entirety) to `r-sig-mixed-models@r-project.org`? See https://github.com/lme4/lme4/blob/master/README.md#where-to-get-help
> 
> It would help to see the results of `str(bdata.raw1)`
> 
> PS is there a reason you're not using `(1|pairID)`, which would make the most sense to me?

Will do, thank you for your time. Using `(1|pairID)` would make pairID as a random effect and per my replication of the analyses I am concerned with, pairID was used as a control variable. It is nested within cluster, which is what I have parameterized as a random effect in the model.

**Comment by jhaltiga** [comment]
I know this issue is closed, but wanted to return to ask: 

In the case of a fixed effect in lmer, if the variable "pairID" is specified simply as 'pairID' [rather than i(pairID)] in the fixed effects part of the equation, does the fixed effect estimate simply aggregate across the levels of that variable? 

I am trying to more clearly ascertain whether this is similar to the case in STATA where absorb(pairID) and i.pairID are the same parameterization, but the former is faster as 'absorb' does not return estimates for each level of the factor variable. E.g.,

![image](https://user-images.githubusercontent.com/38481807/179315967-a0783a85-12b5-4ad4-b17f-59388a841931.png)
![image](https://user-images.githubusercontent.com/38481807/179315987-fde904c6-4dc7-4943-9b4b-593b53a930e9.png)

**Comment by bbolker** [comment]
I don't really understand the question. `i(pairID)` isn't R syntax at all (as far as I know), and `I(pairID)` (with a capital "i") shouldn't change the model at all. The text you're quoting here discusses clustered standard errors, which aren't part of `lme4` at all (although you can get them via `clubSandwich` or `merDeriv`, see [StackOverflow](https://stackoverflow.com/questions/26412581/robust-standard-errors-for-mixed-effects-models-in-lme4-package-of-r))

It would be better to ask this on `r-sig-mixed-models@r-project.org` ...

**Comment by jhaltiga** [comment]
OK, thanks for your time. I should add:

[As noted in the above post](https://github.com/lme4/lme4/issues/689#issuecomment-1171669368), for the variable '`pairID`', if I use `i(pairID)` it just returns estimates for each pair whereas if I simply just specify `pairID`, it provides only 1 estimate for the variable. What is the material difference between those two specifications other than one provides multiple estimates for each '`pairID`' factor level?

so it would seem it is safe to say whether small or capital i, the variable is thus treated as a factor.

**Comment by bbolker** [comment]
It sounds like `pairID` alone is being treated as numeric (which is silly) if you don't specify `i()`. Still, I'm surprised by this effect of `i()` (or `I()`) -- it's new to me. (Best practice would generally be to convert anything that's supposed to be categorical to a factor upstream ...)

I'm still trying to reconcile with this simplified example:

```r
> dd <- data.frame(y = rnorm(20), x= rep(1:4,5))
> coef(lm(y ~ x, dd))
(Intercept)           x 
-0.27850226  0.04911911 
> coef(lm(y ~ I(x), dd))
(Intercept)        I(x) 
-0.27850226  0.04911911 
> coef(lm(y ~ i(x), dd))
Error in i(x) : could not find function "i"
```

What does `find("i")` return?

**Comment by jhaltiga** [comment]
Yes, I do have the fixest package loaded, but was using the 'i' in the lmer function with lme4.

Agreed re: how pairID is being treated if not specified as a factor (i.e., as numeric). It's all starting to make some sense now.

**Comment by bbolker** [comment]
But the `i` **is not coming from lme4**, it's coming from `fixest` (try running your model without `fixest` loaded and see what happens).

**Comment by jhaltiga** [comment]
> 

Making sense now. Thanks. I imagine without fixest loaded, i() is not going to work (as should be the case) in lme4.

**Comment by jhaltiga** [comment]
> I don't really understand the question. `i(pairID)` isn't R syntax at all (as far as I know), and `I(pairID)` (with a capital "i") shouldn't change the model at all. The text you're quoting here discusses clustered standard errors, which aren't part of `lme4` at all (although you can get them via `clubSandwich` or `merDeriv`, see [StackOverflow](https://stackoverflow.com/questions/26412581/robust-standard-errors-for-mixed-effects-models-in-lme4-package-of-r))
> 
> It would be better to ask this on `r-sig-mixed-models@r-project.org` ...

Thanks, this is what I was trying to convey re: STATA's 'absorb' command but failed to do. [https://stackoverflow.com/questions/49639238/r-equivalent-of-statas-absorb](url) 

So, in STATA, absorb basically just aggregates estimates it seems across the factor variable. I have now changed the `pairID` variable upstream to a factor class which results in estimates for all 300 pairIDs. Is there something similar to STATA's absorb in lme4? Or would it simply be `| pairID` in the formula even if the original factor '`pairID`' with all 300 estimates were 'fixed effects.'

**Comment by bbolker** [comment]
please ask on `r-sig-mixed-models@r-project.org`

**Comment by jhaltiga** [comment]
> please ask on `r-sig-mixed-models@r-project.org`

Thanks, will begrudgingly join another listserv :)
