### ISSUE TITLE
No way to compute normalized model residuals

### ISSUE THREAD

**Issue by DexterGlass** [lme4/lme4#697]
Definition of "normalized residuals": the normalized residuals=resid(x,type='normalized')= (standardized residuals pre-multiplied by the inverse square-root factor of the estimated error correlation matrix) are used source: nlme documentation.

**Comment by bbolker** [comment]
As I explained [here](https://stackoverflow.com/questions/73459709/how-does-one-compute-the-normalized-model-residuals-based-via-lme4-mermod-in-r), it doesn't really make any sense to compute normalized residuals when the residuals have no correlation structure (using `scaled = TRUE` will scale the residuals by the residual standard deviation)
