### ISSUE TITLE
No feature to model heteroskedasticity

### ISSUE THREAD

**Issue by DexterGlass** [lme4/lme4#698]
nlme has a feature to model heteroskedasticity

**Comment by bbolker** [comment]
This is true. This is more or less a "WONTFIX" item; it would take considerable development effort to add this feature for lme4, that's not going to happen unless there are suddenly a lot more resources available for doing this. 

See https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#spatial-and-temporal-correlation-models-heteroscedasticity-r-side-models

This list doesn't mention `glmmTMB`, which is a relatively new option.
