### ISSUE TITLE
`glmer` segfaults for small `rhoend`

### ISSUE THREAD

**Issue by Kodiologist** [lme4/lme4#703]
```
R version 4.1.2 (2021-11-01) -- "Bird Hippie" -- x86_64-pc-linux-gnu
> library(lme4)
> packageVersion("lme4")
[1] ‘1.1.30’
> gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd), data = cbpp, family = binomial)
> gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd), data = cbpp, family = binomial, control = glmerControl(optCtrl = list(rhoend = 1e-8)))
Warning message:
In (function (iprint = 0L, maxfun = 10000L, FtolAbs = 1e-05, FtolRel = 1e-15,  :
  unused control arguments ignored
> gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd), data = cbpp, family = binomial, control = glmerControl(optCtrl = list(rhoend = 1e-80)))

 *** caught segfault ***
address 0x55c537c5a1b8, cause 'memory not mapped'

Traceback:
 1: (function (par, fn, lower = -Inf, upper = Inf, control = list(),     ...) [snip]
 2: do.call(optfun, arglist)
 3: withCallingHandlers(do.call(optfun, arglist), warning = function(w) {    curWarnings <<- append(curWarnings, list(w$message))})
 4: optwrap(optimizer, devfun, start, rho$lower, control = control,     adj = adj, verbose = verbose, ...)
 5: optimizeGlmer(devfun, [snip]
 6: glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),     data = cbpp, family = binomial, control = glmerControl(optCtrl = list(rhoend = 1e-80)))

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

Notice also, although probably unrelated, that a bogus warning "unused control arguments ignored" is produced.

**Comment by bbolker** [comment]
Replicated.  I wonder if we can come up with an example that calls `bobyqa` directly ...

**Comment by bbolker** [comment]
This is a `minqa::bobyqa()` bug.

```r
library(minqa)
trivial_fun <- function(p) p^2
bobyqa(2, trivial_fun)
bobyqa(2, trivial_fun, control =list(rhoend = 1e-8))
bobyqa(2, trivial_fun, control =list(rhoend = 1e-80))  ## boom
```
There's a bug tracker [here](https://r-forge.r-project.org/tracker/?group_id=395), but we should probably start by e-mailing the maintainer (`maintainer("minqa")`).  Will you do that or shall I?

**Comment by Kodiologist** [comment]
> Will you do that or shall I?

Go for it. You know a lot more about what's going on here than I do.

**Comment by bbolker** [comment]
Is there an actual case for wanting to set `rhoend` so small, or would it be sufficient to "fix" the bug by disallowing `rhoend` values small enough to trigger the problem?

**Comment by Kodiologist** [comment]
`?convergence` suggests (in an indirect fashion) that you can help a GLMM converge by shrinking `rhoend`. It doesn't say at what point you should stop shrinking, nor does it give you a sense of what scale the parameter is on. So I kept shrinking `rhoend` for a model that wasn't converging, and I tripped this segfault.

**Comment by Kodiologist** [comment]
In other words, I have no idea what the smallest reasonable value of `rhoend` is.

**Comment by bbolker** [comment]
The parameter scales are (fixed effect) logit scale (i.e., link scale: for binomial models this is logit by default) and (random effect) essentially standard-deviation scale of random effects. So 1e-80 is small!

For comparison, from a [NAG (Nottingham Algorithms Group) web page](https://www.nag.com/numeric/nl/nagdoc_latest/clhtml/e04/e04jcc.html):

Suggested value: [rhoend](https://www.nag.com/numeric/nl/nagdoc_latest/clhtml/e04/e04jcc.html#rhoend) should indicate the absolute accuracy that is required in the final values of the variables.
Constraint: rhoend≥macheps, where macheps=nag_machine_precision, the machine precision.

This is apparently something like `2^(-53)` (approx 1e-16).

**Comment by bbolker** [comment]
Closing this now since I have contacted the `minqa` maintainer ...

**Comment by Kodiologist** [comment]
Thanks for the explanation. It sounds like 1e-20 should be more than small enough for any practical problem.
