### ISSUE TITLE
Compute logLik with REML=FALSE - a small difference

### ISSUE THREAD

**Issue by hojsgaard** [lme4/lme4#708]
Please see this:

> fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
> logLik(fm1)
'log Lik.' -871.8141 (df=6)
> logLik(fm1, REML=FALSE)
'log Lik.' -875.9929 (df=6)
> logLik(update(fm1, REML=FALSE))
'log Lik.' -875.9697 (df=6)

I would intuitively have expected the last two calls to logLik() to produce identical results, but maybe I am wrong?

**Comment by bbolker** [comment]
These are doing the following calculations:

- `fm1 <- lmer(...)`: fit the model by REML (let's call the parameter estimates of the RE component, which are the only 'real' parameters [the fixed effects are profiled out] `theta_REML`)
- `logLik(fm1)`: equivalent to `logLik(fm1, REML=TRUE)` or `-1*lme4:::devCrit(fm1, REML = TRUE)/2`: compute the REML criterion, `REML(theta_REML)`
- `logLik(fm1, REML = FALSE)`: compute the log-likelihood of `theta_REML`, `logLik(theta_REML)`
- `fm2 <- update(fm1, REML = FALSE)`: refit the model by ML (estimates `theta_ML`)
- `logLik(fm2, REML = FALSE)` (== `logLik(fm2)`): compute `logLik(theta_ML)`

You can check `getME(fm1, "theta")` vs `getME(fm2, "theta")` or `VarCorr(fm1)` vs `VarCorr(fm2)` to see that these models have two different sets of parameter estimates.

**Comment by bbolker** [comment]
Søren, did this address your question?

**Comment by hojsgaard** [comment]
Thanks for you reply and sorry for not responding earlier. Yes, I believe so: My reading is that the difference in log likelihood between two models (for constructing a chi-square-statistic) is to be computed as:

logLik(update(fm1, REML=FALSE)) - logLik(update(fm2, REML=FALSE))

Do you agree?

**Comment by bbolker** [comment]
Yes, but `refitML()` is a more computationally efficient way to do the same thing (`update()` just re-evaluates the entire call, i.e. refits the model from scratch), so `logLik(refitML(fm1), refitML(fm2))`  (this is what the `lme4:::anova.merMod()` function does when necessary)
