### ISSUE TITLE
add informative warning for 'family' argument provided to 'lmer' ?

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#712]

**Comment by bbolker** [comment]
I think this isn't really possible unless we specifically *re-add* the argument to the function just so we can say it's not used (which feels like a step backwards).

**Comment by jaganmn** [comment]
You could add `...` as an argument then call Martin's `base::chkDots` (added in R 3.3.0) to catch _any_ arguments matching `...` and warn about them.  But then you'll have to document that `...` isn't used ...

**Comment by bbolker** [comment]
The point of this exercise would be to have an error message that was more informative than "'family' isn't used", i.e. something like "family isn't used: use glmer() if you want to model non-Gaussian responses" ...

**Comment by jaganmn** [comment]
```r
chkDots2 <- function(..., which.call = -1, allowed = character(0)) {
    if (nx <- ...length()) {
        nms <- ...names()
        if (any(nms == "family")) {
            nms <- nms[nms != "family"]
            nx <- nx - 1L
            warning(<blah blah blah>)
        }
        if (nx) {
            warning(sprintf(ngettext(nx, 
                                     "In %s :\n extra argument %s will be disregarded", 
                                     "In %s :\n extra arguments %s will be disregarded"), 
                            paste(deparse(sys.call(which.call), control = c()), 
                                  collapse = "\n"), 
                            paste(sQuote(nms), collapse = ", ")), 
                    call. = FALSE, domain = NA)
        }
    }
}
```
