### ISSUE TITLE
Error in lmer / optimizeLmer: Error in if (any(bgrad < 0)) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by MathiasAmbuehl** [lme4/lme4#719]
I ran into an error when fitting a linear mixed effects model with `lmer()`. Execution stops with an error message
`Error in if (any(bgrad < 0)) { : missing value where TRUE/FALSE needed`. Unfortunately, I can not include a reproducible example here, as my data set is large and I did not succeed in provoking the error with simulated data.

The error is triggered in `optimizeLmer()`, where a vector `bgrad` is created and some code is executed conditional on `if (any(bgrad < 0))`, see [here](https://github.com/lme4/lme4/blob/9c673edb76ae19165ffe0a45b375737bb02f1fc3/R/modular.R#L615). In my case, all elements of bgrad are `NA` or `NaN`, such that `any(bgrad < 0)` evaluates to `NA`. 
The error has been reported before [on stackoverflow](https://stackoverflow.com/questions/72278210/lme4lmer-error-in-if-anybgrad-0-when-using-random-slopes). In my example, the random part of the model is rather complex. It's of the form `(1+x|A)+(1+x|B)+(1+x|C)+(1+x|D)`, with A, B, C, D being nested factors.

Note that the issue can be avoided by stating `lmerControl(restart_edge=FALSE)`, such that the if clause is not evaluated.

**Comment by bbolker** [comment]
It's easy enough to fix this, but ... what should the proper response be if `bgrad` contains `NA` values? Presumably we don't want to check at the boundary in this case, but should we issue a warning?

**Comment by MathiasAmbuehl** [comment]
Thanks @bbolker for your answer. IMO, it would be helpful to have a more informative result in this situation, either an error message stating that the algorithm did not converge to a meaningful model, or the actual fitted model supplemented with a warning about the questionable nature of the fit.

**Comment by bbolker** [comment]
This is fixed (I think) in 771498cbdb (it would give a warning "some gradient components are NA near boundaries, skipping boundary check"), but it's not tested because it's hard to come up with a test case ... can you test it on your data?  (`remotes::install_github("lme4/lme4")` to install the development version)
