### ISSUE TITLE
FR: some suggestions for `dotplot.ranef.mer` method

### ISSUE THREAD

**Issue by iago-pssjd** [lme4/lme4#722]
First, it is not possible to modified the dot colour as is coded. Next a minimal reprex:

# Loading and default attempt

``` r
library(lattice)
library(lme4)
#> Loading required package: Matrix
fm1 <- lmer(Reaction ~ Days + (Days|Subject), sleepstudy)
rr1 <- ranef(fm1)
dotplot(rr1, col = "green")[["Subject"]]
```

![unnamed-chunk-3-1](https://user-images.githubusercontent.com/40892925/227870626-82bd84f0-2f9f-4634-8e47-22c3c039211f.png)

# Modified attempt
 Adding `col=col` to `panel.xyplot`

``` r
dotplot.ranef.mer <- function(x, data, main = TRUE, transf=I, ...)
{
    prepanel.ci <- function(x, y, se, subscripts, ...) {
        if (is.null(se)) return(list())
        x <- as.numeric(x)
        hw <- 1.96 * as.numeric(se[subscripts])
        list(xlim = range(transf(x - hw), transf(x + hw), finite = TRUE))
    }
    panel.ci <- function(x, y, se, subscripts, pch = 16,
                         horizontal = TRUE, col = dot.symbol$col, 
                         lty = dot.line$lty, lwd = dot.line$lwd,
                         col.line = dot.line$col, levels.fos = unique(y),
                         groups = NULL, ...)
    {
        x <- as.numeric(x)
        y <- as.numeric(y)
        dot.line <- trellis.par.get("dot.line")
        dot.symbol <- trellis.par.get("dot.symbol")
        sup.symbol <- trellis.par.get("superpose.symbol")
        panel.abline(h = levels.fos, col = col.line, lty = lty, lwd = lwd)
        panel.abline(v = 0, col = col.line, lty = lty, lwd = lwd)
        if (!is.null(se)) {
            se <- as.numeric(se[subscripts])
            panel.segments( transf(x - 1.96 * se), y,
                            transf(x + 1.96 * se), y, col = 'black')
        }
        panel.xyplot(transf(x), y, pch = pch, col = col, ...)
    }
    f <- function(nx, ...) {
        ss <- lme4:::asDf0(x,nx)
        mtit <- if(main) nx 
        dotplot(.nn ~ values | ind, ss, se = ss$se,
                prepanel = prepanel.ci, panel = panel.ci,
                xlab = NULL, main = mtit, ...)
    }
    setNames(lapply(names(x), f, ...), names(x))
}

dotplot(rr1, col = "green")[["Subject"]]
```

![unnamed-chunk-4-1](https://user-images.githubusercontent.com/40892925/227870848-4d2e93a4-ca9c-4d6b-8c53-9fc40eaafa5e.png)

<sup>Created on 2023-03-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by iago-pssjd** [comment]
Second, it would be great to have the chance of modifying vertical and horizontal lines separately. Next, a minimal reprex comparing default and modified function:

# Loading and default attempt
``` r
library(lattice)
library(lme4)
#> Loading required package: Matrix
fm1 <- lmer(Reaction ~ Days + (Days|Subject), sleepstudy)
rr1 <- ranef(fm1)
dotplot(rr1, lty = 3, lwd = 2, col.line = 'purple')[["Subject"]]
```

![unnamed-chunk-3-1](https://user-images.githubusercontent.com/40892925/227873022-0362e72d-7e58-4db7-b17b-0a4969492825.png)

# Modified attempt

Replacing `col.line`, `lty` and `lwd` with `col.line.v`, `lty.v`, `lwd.v` and `col.line.h`, `lty.h`, `lwd.h` respectively (duplicate these arguments on `panel.ci` and replace on `panel.abline` calls)

``` r
dotplot.ranef.mer <- function(x, data, main = TRUE, transf=I, ...)
{
    prepanel.ci <- function(x, y, se, subscripts, ...) {
        if (is.null(se)) return(list())
        x <- as.numeric(x)
        hw <- 1.96 * as.numeric(se[subscripts])
        list(xlim = range(transf(x - hw), transf(x + hw), finite = TRUE))
    }
    panel.ci <- function(x, y, se, subscripts, pch = 16,
                         horizontal = TRUE, col = dot.symbol$col, 
                         lty.h = dot.line$lty, lty.v = dot.line$lty, 
                         lwd.h = dot.line$lwd, lwd.v = dot.line$lwd, 
                         col.line.h = dot.line$col, col.line.v = dot.line$col, 
                         levels.fos = unique(y),
                         groups = NULL, ...)
    {
        x <- as.numeric(x)
        y <- as.numeric(y)
        dot.line <- trellis.par.get("dot.line")
        dot.symbol <- trellis.par.get("dot.symbol")
        sup.symbol <- trellis.par.get("superpose.symbol")
        panel.abline(h = levels.fos, col = col.line.h, lty = lty.h, lwd = lwd.h)
        panel.abline(v = 0, col = col.line.v, lty = lty.v, lwd = lwd.v)
        if (!is.null(se)) {
            se <- as.numeric(se[subscripts])
            panel.segments( transf(x - 1.96 * se), y,
                            transf(x + 1.96 * se), y, col = 'black')
        }
        panel.xyplot(transf(x), y, pch = pch, col = col, ...)
    }
    f <- function(nx, ...) {
        ss <- lme4:::asDf0(x,nx)
        mtit <- if(main) nx 
        dotplot(.nn ~ values | ind, ss, se = ss$se,
                prepanel = prepanel.ci, panel = panel.ci,
                xlab = NULL, main = mtit, ...)
    }
    setNames(lapply(names(x), f, ...), names(x))
}

dotplot(rr1, lty.v = 3, lwd.v = 2, col.line.v = 'purple')[["Subject"]]
```

![unnamed-chunk-4-1](https://user-images.githubusercontent.com/40892925/227873538-f2dd068f-aa4c-4d4c-9543-14f6876e4cd0.png)

<sup>Created on 2023-03-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by iago-pssjd** [comment]
Finally, ideally there would be a `dotplot.coef.mer` method producing the equivalent plot, but centered at fixed effects instead of zero. For this, it would be necessary that the output of `coef.merMod` include the same `postVar` attribute as `ranef.merMod` when `condVar = TRUE`.

At this point, just for my need, I coded a `dotplot.lmerMod` method which calls to `ranef.merMod` and modifies the data.frame(s) to save the output of `coef.merMod` with the  `postVar` attribute. Then, it is necessary to modify again the `dotplot.ranef.mer` method so it can print a distinct vertical line for each panel.  My way to do this is

1. adding the default argument `v = 0` to `panel.ci` instead of including it in `panel.abline`
2. replacing `panel.abline(v = 0, col = col.line.v, lty = lty.v, lwd = lwd.v)` with
```r
if(length(v) == 1){
	  panel.abline(v = v, col = col.line.v, lty = lty.v, lwd = lwd.v)
}else{
	  panel.abline(v = v[panel.number()], col = col.line.v, lty = lty.v, lwd = lwd.v) 
}
```

Please, beyond attending or not the suggestion of adding the new method, let me know if there is a better way to code these goals.

Thank you!

**Comment by bbolker** [comment]
Almost all of this seems fine, and I'd be happy to include your augmented `dotplot.coef.mer` method (it's completely back-compatible, right?) in the package. (You could also submit a pull request.)  About `dotplot.coef.mer`, are you proposing that the error bars only include the uncertainty in the BLUPs/conditional modes?

---
There's a statistical issue here &mdash; in a frequentist context, it's difficult to rigorously define the confidence intervals for a sum of a parameter estimate (fixed effect) and a random variable (conditional mode/BLUP). When plotting do we ignore the uncertainty of the fixed effect? Pretend the fixed effects and conditional modes are independent (which is frequently done by downstream packages)?  (This is discussed in the GLMM FAQ.)

**Comment by iago-pssjd** [comment]
Thanks for your answer @bbolker, particularly because I had not read the discussion in GLMM FAQ you cite. Indeed, I was 'drawing' error bars which only included the uncertainty in the BLUPs/conditional modes through a `dotplot.lmerMod` (not `dotplot.coef.mer`) method. Then, it seems this point should be fully forgetted and removed from my suggestions.

**Comment by bbolker** [comment]
Just getting back to this/clarifying: do you think the `dotplot.ranef.mer()` [above](https://github.com/lme4/lme4/issues/722#issuecomment-1484655181) is ready as a drop-in replacement for the existing function?

**Comment by iago-pssjd** [comment]
@bbolker yes, I think it is.

**Comment by bbolker** [comment]
In lme4 now, please try the latest version with your examples and confirm.  Would you like to be listed as a contributor?  (If you have an ORCID id and want it included, let me know.)
