### ISSUE TITLE
Error in reformulate

### ISSUE THREAD

**Issue by chungsaihotony** [lme4/lme4#734]
I have just installed lme4 1.1.28. My R version is 3.5.1. I tried to run a standard example to test if it is ok. I got "Error in reformulate(paste0("(", vapply(findbars(f), deparsel, ""),")"), : unused arguement (env= environment(f))) ". Any advice? Million thanks.

**Comment by bbolker** [comment]
This is a very old version of R (3.5.1 is 5 years old) and a slightly old version of lme4 (1.1.28 is 18 months old). We have back-compatibility code that handles this change in reformulate, but it wasn't added until version 1.1.29 ... is there any chance you can update either to R>3.6 or lme4 >= 1.1.29? (In general unless you have a strong reason to use old versions it's best to update both R and all packages to the latest versions ...

**Comment by chungsaihotony** [comment]
I can't change the version of R 3.5.1. Which version of lme4 would you recommend ? Many thanks.

**Comment by bbolker** [comment]
Any version after 1.1.29 should work.  I can't think of any reason not to update to the latest version. (Out of curiosity, why are you stuck on R 3.5.1?)

**Comment by chungsaihotony** [comment]
I can't change the R version. I have tried to install lme4 1.1.29 and got errors during installation (glmFamily.cpp:55:40: error: .....). Many glmFamily  related errors were generated. It seems it comes from RcppEigen.

**Comment by bbolker** [comment]
Again, I would be curious what is stopping you from updating R (I'm not arguing, just curious).

I think trying to sort out RcppEigen compatibility problems is just going to be going farther down the rabbit hole.

Here's what I would try next; I'm assuming that you have development tools (compilers etc.).

* download the [source tarball for lme4 1.1.28](https://cran.r-project.org/src/contrib/Archive/lme4/lme4_1.1-28.tar.gz)
* unpack it 
* replace the `R/hooks.R` file with [this file](https://raw.githubusercontent.com/lme4/lme4/master/R/hooks.R), which adds the little bit of code that will avoid the problem with `reformulate`
* `R CMD INSTALL` from this directory

**Comment by chungsaihotony** [comment]
Thank you very much for your help and prompt replies. 

Besides, I am working in a closed environment which I have no right to amend it. ^0^

**Comment by bbolker** [comment]
I'm going to assume that the last suggestion worked, but feel free to re-open if you need to.
