### ISSUE TITLE
When NAs are present, re.form=NULL leads to an error in simulate

### ISSUE THREAD

**Issue by frousseu** [lme4/lme4#737]
Hi! 

When NAs are in the response variable, `simulate` does not seem to adapt to the fact that values are missing when `re.form = NULL` and generates a value for the missing responses contrary to when `re.form = NA`.

```r
library(lme4)

fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
simulate(fm1,re.form=NA)
simulate(fm1,re.form=NULL)

d<-sleepstudy
d$Reaction[1] <- NA
fm1 <- lmer(Reaction ~ Days + (Days | Subject), d)
simulate(fm1, re.form = NA)
simulate(fm1, re.form = NULL)
##  Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
##  In addition: Warning message:
##  In pred + REvals :
##   longer object length is not a multiple of shorter object length
```

The simulated `x` object seem to have the same length as the original `data` without the NAs removed while the `value` object has the row names of the lines with non-missing response values. This is with lme4_1.1-34.

Thanks!
François

**Comment by bbolker** [comment]
Confirmed ....

**Comment by bbolker** [comment]
fixed now.
