### ISSUE TITLE
LME4 Not Working, Potentially Also Corrupted Device?

### ISSUE THREAD

**Issue by GMarkovich** [lme4/lme4#740]
Hey, 
Not sure if anyone else has had this. Had an rstudio file working great, was going through lme analysis using this and lmerTest. Overnight, the values changed though the command still ran. Went from a p = .001 to a p = .6 value. I had record of what it was before and set to trying to figure out what happened. I can only guess that my computer got corrupted by something because fresh installs of everything didn't have an effect on this and neither did using a new data file. I'd also written some fresh code using it and got the same result. Only solution was to completely wipe my computer and reinstall the OS - but the computer wasn't even able to recognize its own hard drive at the time. Posting this here because I got the fresh install about 48 hours ago and it fixed it, but now I'm having to do it again. I don't know if this is an lme4 thing, an lmerTest thing, or maybe even just a base Rstudio thing but I figured I'd put it out there just in case. Hopefully nobody has had a similar experience!

**Comment by bbolker** [comment]
This is obviously painful for you but I don't think there's anything we can do about it -- sorry. It's hard to see how we could ever replicate the problem to see what's happening, and it's hard to imagine  how R packages could get corrupted in this way ... (also hard to imagine how going beyond a fresh install of RStudio + R + packages, i.e. going all the way to an OS reinstall, could be necessary ...)

**Comment by bbolker** [comment]
Closing.
