### ISSUE TITLE
use headers from Matrix, not RcppEigen

### ISSUE THREAD

**Issue by jaganmn** [lme4/lme4#745]
I was quite surprised to learn that **RcppEigen** contains static, now somewhat stale copies of the **Matrix** headers, and that those copies are included in `RcppEigen.h`.  A corollary is that the following list of the reverse LinkingTo of **Matrix**,

```
> rrLT <- function(p) unique(unlist(tools::package_dependencies(p, which = "LinkingTo", reverse = TRUE, recursive = TRUE), FALSE, FALSE))
> length(p1 <- rrLT("Matrix"))
[1] 36
```

is incomplete: we actually need to look at a much longer list,

```
> length(p2 <- rrLT(c("Matrix", "RcppEigen")))
[1] 449
```

when testing the effect of changes to the Matrix C API in package space.  A static analysis of the packages in `setdiff(p2, p1)` reveals that **lme4** is the _only_ package making use of the **RcppEigen** copies of the headers.  So I am creating this issue partly to ask: why?

It seems wrong to me that **Matrix** should have these "hidden" 413 reverse LinkingTo.  Shouldn't **lme4** change to accessing CHOLMOD via **Matrix** instead of **RcppEigen**?  Then eventually **RcppEigen** could stop packaging the headers, which have been liable to become stale and have created this weird situation beneficial (if you can call it that) seemingly only to **lme4**.

Edit: Well, I see now that the headers are there to support Eigen's CHOLMOD module.  It is possible that packages are using the module without calling any of the functions declared in the copies of our headers.  Still, I think that the situation can be improved ...

**Comment by bbolker** [comment]
I don't know. Doug Bates would probably have the clearest idea of the relationships among lme4, Eigen/RcppEigen, Matrix, and CHOLMOD ...

**Comment by jaganmn** [comment]
@mmaechler @dmbates Can either of you comment on the initial motivation for packaging copies of our headers with **RcppEigen**, namely these:

https://github.com/RcppCore/RcppEigen/blob/master/inst/include/RcppEigenCholmod.h
https://github.com/RcppCore/RcppEigen/blob/master/inst/include/RcppEigenStubs.h

last modified 6 and 12 years ago, respectively ...

**Comment by mmaechler** [comment]
Hmm... I vaguely remember that Doug had found that lme4 should start using  RcppEigen  in addition to Matrix *and* 
that RcppEigen should start "doing" more things (than originally) in Matrix-compatible ways, notably should use Matrix' C-level API.  
I would have thought that  RcppEigen  would have been   `LinkingTo: Matrix`  originally, but then it seems dropped that explicit dependency ("for convenience" ?)  and just copied the headers  ... which of course is a maintenance "nightmare"..

**Comment by dmbates** [comment]
My apologies for this long-standing infelicity.  I have only vague
recollections of the sequence of events, which I think may have been in
response to a CRAN maintainer ultimatum.  In any case, yes there was an
instance where RcppEigen had to abandon LinkingTo: Matrix and yes it would
have been better to seek a long-term solution rather than a stop-gap.
Having now been out of the business of trying to reconcile S4 classes and
methods with object-oriented programming in C++ for several years I'm
afraid I have neither the skills nor the inclination to try to resolve the
problem.

**Comment by jaganmn** [comment]
Thanks all ... I've started on a patch for both **lme4** and **RcppEigen** that I hope will rectify things things without requiring any rev. dep. to change.  But maybe I should confirm whether @eddelbuettel would welcome such a patch in the first place ... ?

**Comment by eddelbuettel** [comment]
@jaganmn  We do.  As you note, I am mostly a placeholder maintainer here keeping the RcppEigen machinery on. I made one attempt at updating the a newer upstream, it got stuck by possibly upsetting too many other packages.  [1]

I am of course if favour of cleanup and can test them too via reverse depends checking.  We should strive for a minimal patch against the main branch aka CRAN version.

[1] I have a similar issue in RcppArmadillo but plan to forge ahead there, see its three related issue tickets.
