### ISSUE TITLE
bug in bobyqa

### ISSUE THREAD

**Issue by JacobGry** [lme4/lme4#749]
I discovered a bug in the code of bobyqa, which can be obtained by calling `getOptfun(optimizer = "bobyqa")`. If the start value is not between lower and upper and should be corrected:

```
if (any(par < lower | par > upper)) {
  if (ctrl$obstop) 
    stop("Starting values violate bounds")
  else {
    par <- pmax(lower, pmax(par, upper))
    warning("Some parameters adjusted to nearest bound")
  }
}
```
These are lines 22 - 29. In line 27, the start values that are outside the interval should be set to the next boundary. For this, however, the second `pmax` must be a `pmin`.

**Comment by bbolker** [comment]
Thanks. `bobyqa` is actually from the `minqua` package, which is maintained by Katharine Mullen <katharine.mullen@stat.ucla.edu>. The package DESCRIPTION links [here](https://r-forge.r-project.org/projects/optimizer/), where there is a bug tracker, but it looks unused - we should probably contact the maintainer by e-mail.
