### ISSUE TITLE
R aborts and terminates session when trying to run lmer

### ISSUE THREAD

**Issue by njmorris** [lme4/lme4#757]
Hi! I am a beginner trying to calculate microbiome alpha diversity in Rstudio, and have been stuck, as every time I try to run the lmer function, R aborts and terminates my session. I have tried updating R, updating packages, removing and re-installing packages, and detaching packages that may mask the function, with no luck. 

I have tried running the example code on the R help documentation, and that also aborts, as well as when I try to run code using 'lmer' from online tutorials and old code that worked in the past. 

I have R 4.3.2 and ‘lme4’ version 1.1-35.1, and am working on a Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz with Windows 11. 

I am wondering what else I can do to troubleshoot, thanks! :)

**Comment by bbolker** [comment]
Yikes. Can you try running this in a clean R *console* session (i.e., outside of RStudio, [on the command line](https://stackoverflow.com/questions/66197563/running-r-script-using-command-line-on-windows), just to rule out the possibility that `RStudio` is involved?

```r
library("lme4")
sessionInfo()
lmer(Reaction ~ Days + (1|Study), sleepstudy)
```

If this fails, please post your `sessionInfo()`.

Another thing to try is to to revert to an earlier version of `lme4` (you'll also need to revert `RcppEigen`, and you will need to have [development tools](https://cran.r-project.org/bin/windows/Rtools/rtools43/rtools.html) installed)

```r
remove.packages("lme4")
remove.packages("RcppEigen")
remotes::install_version("RcppEigen", "0.3.9.9.3")
remotes::install_version("lme4", "1.1-34")
```

**Comment by bbolker** [comment]
Also, out of curiosity, how are you using `lme4` to compute alpha diversity?  It's not immediately obvious to me ...

**Comment by njmorris** [comment]
In the console, it didn't crash but gave me the following error message "Error in eval(predvars, data, env) : object 'Study' not found." I tried it in Rstudio as well, and got the same error message. 

Also, I meant to say that I am using lme4 to model alpha diversity, I have already done the alpha diversity calculations!

Here's my session info:

"R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8
[2] LC_CTYPE=English_United States.utf8
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.utf8

time zone: Europe/Budapest
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] lme4_1.1-35.1  Matrix_1.6-1.1

loaded via a namespace (and not attached):
 [1] minqa_1.2.6    MASS_7.3-60    compiler_4.3.2 Rcpp_1.0.11    splines_4.3.2
 [6] nlme_3.1-163   grid_4.3.2     nloptr_2.0.3   boot_1.3-28.1  lattice_0.21-9"

**Comment by bbolker** [comment]
Oops!  I meant `Reaction ~ Days + (1|Subject)`.  Try that instead?

**Comment by bbolker** [comment]
And can you also tell me the output of `packageVersion("RcppEigen")` ?

**Comment by njmorris** [comment]
When I tried Reaction ~ Days + (1|Subject) in command line, it worked! 
But, when I tried in Rstudio, it aborted  :/
The output for packageVersion("RcppEigen") is ‘0.3.3.9.4’

**Comment by bbolker** [comment]
Hmm, that's unfortunate.  Can you possibly raise this on the RStudio forums, where there will be more expertise?  I just tried it in my version of RStudio (Linux, 2023.06.1 Build 524) without a problem ...

**Comment by njmorris** [comment]
Will do, thank you so much for your help! :)

**Comment by bbolker** [comment]
PS also OK for me with

```
RStudio 2023.09.1+494 "Desert Sunflower" Release (cd7011dce393115d3a7c3db799dda4b1c7e88711, 2023-10-16) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.09.1+494 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
```

**Comment by RachBioHaz** [comment]
Just to give you a heads up - this also happens using ANCOM-BC when trying to populate the Random file which uses lme4.  It is not a phyloseq issue which was the original thought but seems to be related to the lme4 functionality. 
see https://github.com/FrederickHuangLin/ANCOMBC/issues/217

**Comment by bbolker** [comment]
(1) Is it also RStudio-specific?  (2) I can imagine it is somehow related to https://github.com/lme4/lme4/issues/756 (version mismatches due to recent `Matrix`/`lme4`/`RcppEigen` updates)

**Comment by bbolker** [comment]
Is there any more input on this?

**Comment by RachBioHaz** [comment]
Tried it directly in R, and R crashed as well .  What additional information do you need me to provide? I have added the session info to the two issues listed below.  
At this stage, I am using the ANCOM-BC package and it crashes. I have contacted the author and he states it is a lmer issue. This issue has cropped up since the R update (R version 4.3.1) and has been happening with other packages that are using lmer functionality, like ANCOM-BC https://github.com/FrederickHuangLin/ANCOMBC/issues/217#top,  and LinDA https://github.com/zhouhj1994/LinDA/issues/15#top .

**Comment by njmorris** [comment]
> PS did you try reverting to the previous package versions (with the `remotes::install_version()` example above) and then attempting in RStudio again? It would be useful for information for anyone trying to debug this.

I did try this and still had the same issue in RStudio. After that, I tried uninstalling and re-installing R & RStudio again, and still had the same issue at first. 

However, when I tried again in a completely new tab and new file of RStudio, the example worked... I copied a portion (after alpha diversity was calculated) of my code into the new tab/file and that also worked. 

I am wondering if something about my original file's history (even though the session was terminated and restarted, packages un-libraried, environment/console cleared, tab closed and re-opened, computer re-started, R uninstalled and re-installed...) was blocking the function. I originally had the following packages libraried: 
`pacman::p_load("ggplot2", "grid", "gridExtra", "lme4", "lmerTest", "emmeans", "phyloseq",
               "vegan", "devtools", "sjPlot", "here", "ape", "philr", "pairwiseAdonis",
               "ggordiplots", "BiodiversityR", "dplyr", "tidyr")`
`library(decontam)`
`library(biomformat);packageVersion("biomformat")`
`library(picante)`

**Comment by SJohnsonMayo** [comment]
I'm able to replicate this error in R directly as well. 

What works:
-loading only lme4

What doesn't work:
-loading phyloseq and lme4 (order doesn't matter)
-detaching phyloseq (either before or after loading lme4)


```
> library(phyloseq)
> library(lme4)
Loading required package: Matrix
> (fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy))

 *** caught segfault ***
address 0x1, cause 'memory not mapped'

Traceback:
 1: t(do.call(sparseMatrix, do.call(rbind, lapply(seq_along(blist),     function(i) {        mm <- matrix(seq_len(nb[i]), ncol = nc[i], byrow = TRUE)        dd <- diag(nc[i])        ltri <- lower.tri(dd, diag = TRUE)        ii <- row(dd)[ltri]        jj <- col(dd)[ltri]        data.frame(i = as.vector(mm[, ii]) + boff[i], j = as.vector(mm[,             jj]) + boff[i], x = as.double(rep.int(seq_along(ii),             rep.int(nl[i], length(ii))) + thoff[i]))    }))))
 2: t(do.call(sparseMatrix, do.call(rbind, lapply(seq_along(blist),     function(i) {        mm <- matrix(seq_len(nb[i]), ncol = nc[i], byrow = TRUE)        dd <- diag(nc[i])        ltri <- lower.tri(dd, diag = TRUE)        ii <- row(dd)[ltri]        jj <- col(dd)[ltri]        data.frame(i = as.vector(mm[, ii]) + boff[i], j = as.vector(mm[,             jj]) + boff[i], x = as.double(rep.int(seq_along(ii),             rep.int(nl[i], length(ii))) + thoff[i]))    }))))
 3: mkReTrms(findbars(RHSForm(formula)), fr)
 4: lme4::lFormula(formula = Reaction ~ Days + (Days | Subject),     data = sleepstudy, control = list(optimizer = "nloptwrap",         restart_edge = TRUE, boundary.tol = 1e-05, calc.derivs = TRUE,         use.last.params = FALSE, checkControl = list(check.nobs.vs.rankZ = "ignore",             check.nobs.vs.nlev = "stop", check.nlev.gtreq.5 = "ignore",             check.nlev.gtr.1 = "stop", check.nobs.vs.nRE = "stop",             check.rankX = "message+drop.cols", check.scaleX = "warning",             check.formula.LHS = "stop"), checkConv = list(check.conv.grad = list(            action = "warning", tol = 0.002, relTol = NULL),             check.conv.singular = list(action = "message", tol = 1e-04),             check.conv.hess = list(action = "warning", tol = 1e-06)),         optCtrl = list()))
 5: eval(mc, parent.frame(1L))
 6: eval(mc, parent.frame(1L))
 7: lmer(Reaction ~ Days + (Days | Subject), sleepstudy)

```

**Comment by mmaechler** [comment]
@RachBioHaz :  as you mentioned `ANCOMBC`, I've browsed that and wrote a longish comment + hints:  https://github.com/FrederickHuangLin/ANCOMBC/issues/217#issuecomment-1816154462   
notably also mentioning that the Matrix package version needs to be >= 1.6-2 *and* you need to re-install some packages at the minimum;  definitely `lme4`  also:  https://stat.ethz.ch/pipermail/r-package-devel/2023q4/010054.html 
@bbolker mentioned this already above (6 days ago), pointing to #756

**Comment by bbolker** [comment]
I really don't know what else we can say about this other than that the solutions will be:

- wait/hope that upstream repositories for *binary* packages (RSPM, r2u, etc.) have been properly updated (if you want to contact repository managers, you can point them to [this r-package-devel message](https://stat.ethz.ch/pipermail/r-package-devel/2023q4/010051.html)
- or make sure that `Matrix` and the full stack of packages that depend on it have been re-installed **from source**

**Comment by RachBioHaz** [comment]
I have deleted the data and history files and deleted and reinstalled all related packages from source. I had to also delete the RData file.

**Comment by RachBioHaz** [comment]
FYI - Update: It still happens periodically - I need to remove the RData file and I can rerun my code without R crashing. So it seems to be something specific to R or RStudio. This is making me lose the will to live but if I need to keep doing this for a while to get through my backlog I will. Thanks for your help.
