### ISSUE TITLE
lmer: Error in initializePtr() :    function 'cholmod_factor_ldetA' not provided by package 'Matrix'

### ISSUE THREAD

**Issue by struckma** [lme4/lme4#758]
Dear *lme4* team,

unfortunately, I observe an error since your latest update, that I did not find on your bug list. It affects the function `lmer()`, which somehow triggers the error message about `cholmod_factor_ldetA` (see title). I've tried a bit with the Matrix package that also has been updated recently, but in our test jobs in Docker using `tidyverse` images (tried latest and latest-daily yesterday), I always get the error message.

Sorry, that I cannot tell more, but I've just not yet found time to dig in all the C++ code, because I'm mostly coding plain R for years now, so my C++ skills my be a bit outdated.

I would be happy, if someone could have a look at it.

Below are the steps to reproduce the problems (with a minimal example, to produce the error message, the original dataset is of course larger).

Thank you for your great work, as a maintainer as side job, I feel with you ;)

Greetings from Germany

Stephan

```r
# docker run -it rocker/tidyverse:latest-daily /bin/bash
root@e0f45aab56fb:/#  R

R version 4.3.2 (2023-10-31) -- "Eye Holes"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> lme4::lmer(v00004 ~ 1 + (1 | v00012), data = data.frame(v00004 = c(124, 123, 126), v00012 = as.factor(c("USR_243", "USR_456", "USR_243"))))
Error in initializePtr() : 
  function 'cholmod_factor_ldetA' not provided by package 'Matrix'
> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dataquieR_2.0.1

loaded via a namespace (and not attached):
 [1] Matrix_1.6-1.1    gtable_0.3.4      dplyr_1.1.3       compiler_4.3.2   
 [5] tidyselect_1.2.0  Rcpp_1.0.11       qmrparser_0.1.6   parallel_4.3.2   
 [9] splines_4.3.2     scales_1.2.1      boot_1.3-28.1     readxl_1.4.3     
[13] lattice_0.21-9    ggplot2_3.4.4     R6_2.5.1          plyr_1.8.9       
[17] generics_0.1.3    patchwork_1.1.3   MASS_7.3-60       tibble_3.2.1     
[21] nloptr_2.0.3      munsell_0.5.0     minqa_1.2.6       lubridate_1.9.3  
[25] pillar_1.9.0      R.utils_2.12.2    rlang_1.1.2       utf8_1.2.4       
[29] reshape_0.8.9     pkgload_1.3.3     timechange_0.2.0  cli_3.6.1        
[33] magrittr_2.0.3    rio_1.0.1         grid_4.3.2        lme4_1.1-35.1    
[37] nlme_3.1-163      lifecycle_1.0.3   MultinomialCI_1.2 R.methodsS3_1.8.2
[41] R.oo_1.25.0       vctrs_0.6.4       glue_1.6.2        cellranger_1.1.0 
[45] fansi_1.0.5       colorspace_2.1-0  tools_4.3.2       pkgconfig_2.0.3  
> 
```

**Comment by mmaechler** [comment]
I see you are using "old" Matrix;  Matrix was updated 2 days ago to 1.6-2 on CRAN,
*and* your lme4 may have been compiled against the new version of Matrix, but you somehow got the old now?

**Comment by struckma** [comment]
Indeed, you are right, thank you. I don't know, how that happens, my scripts usually install everything from scratch.

However, `install.packages("Matrix")` seems to solve the problem.

Thank you again, I'll close the issue, then.

**Comment by meghavarshini** [comment]
Hello! My colleague is also facing this issue and while troubleshooting on their system, while using `lme4`. We attempted the fix mentioned here by installing Matrix. Unfortunately, we were unable to resolve the problem- possibly because some incompatibility? 

System details are as follows: 
- `Rstudio: Version 2023.12.0+369 (2023.12.0+369)`
- `R version 4.3.2 (2023-10-31)`
- `Mac: Ventura 13.5.2`

Package details:
- `lme4: 1.1-35.1`
- `Matrix: 1.6-5`

Do you think there is some kind of incompatibility between the versions of the two packages or R? A comment on [this issue](https://github.com/lme4/lme4/issues/759) mentioned installing a specific version of Matrix (`Matrix (>=1.6-2)`) but this was not an option that worked.

We would appreciate any help with this matter.

**Comment by bbolker** [comment]
The most detailed description of the general problem is probably [here](https://stackoverflow.com/a/77532685/190277). While it looks like your package versions are OK, my primary advice is to make sure that you have installed `lme4` **from source** after installing the latest version of Matrix (it is, alas, apparently still possible to retrieve versions of `lme4` from binary repositories that were compiled against an older version of `Matrix` ...)

One more confirmation/double-check: you're seeing this problem even with the simple example given at the head of this thread ?

```r
dd <- data.frame(v00004 = c(124, 123, 126), v00012 = factor(c("USR_243", "USR_456", "USR_243")))
lme4::lmer(v00004 ~ 1 + (1 | v00012), data = dd )

I can confirm that this example works fine with `Matrix` 1.6-5 and a fresh install of `lme4` 1.1-35.1 (from source) from CRAN (although I would be 99% sure that the binaries from CRAN are also OK ...)

If this still fails after all the suggestions above, please let us know **exactly** from where, and how, your colleague is installing/has installed `lme4` (binary or source, from what repository)?

**Comment by meghavarshini** [comment]
Thank you so much for your response! I have let my colleague know andhe are in the process of testing this.
