### ISSUE TITLE
R studio Error while calling library(lme4) - Error: package or namespace load failed for ‘lme4’ in namespaceExport(ns, exports):  undefined exports: bobyqa, newuoa, uobyqa

### ISSUE THREAD

**Issue by JoeAM11** [lme4/lme4#760]
Hello!
I am new to linear mixed effects models and I am currently learning to used the with some tutorials (https://www.hiercourse.com/docs/00_SolutionsExercises_mixed.pdf)

I am running in **R Studio** and have some problems while calling the lme4 library! 

It seems installation is correctly done
![image](https://github.com/lme4/lme4/assets/113150506/aed8f20b-d6b2-4896-83cd-be48722a909b)

But when the library is called i obtain the following error: 
![image](https://github.com/lme4/lme4/assets/113150506/b49bd978-230a-4475-b444-03bf84bd947a)

I can't seem to solve it. I have uninstalled and installed packages but haven't been able to solve it. What do you suggest I can do? Thank you!

**Comment by bbolker** [comment]
Does `install.packages("minqa")` help? What do you get from `packageVersion("minqa")` ?

**Comment by JoeAM11** [comment]
Hello bbolker! 

Thank you for your help. I have installed the minqa package as suggested, but problem is still present. 

Here is the output for package version command 

> packageVersion("minqa")
[1] ‘1.2.4’

Any other suggestion of what may be happening. Thank you!

**Comment by bbolker** [comment]
`minqa` version 1.2.4 is very old ([this page](https://cran.r-project.org/src/contrib/Archive/minqa/) says it was released in 2014, although the next newer version is from 2022.  What version of R (not RStudio) are you running (run `getRversion()`)?   What is `packageVersion("lme4")` ?

**Comment by JoeAM11** [comment]
Hi!

Here are my versions 

> getRversion()
[1] ‘4.0.5’
> packageVersion("lme4")
[1] ‘1.1.27.1’

After running the update.packages() i get the same response. 
Thank you

**Comment by bbolker** [comment]
Your versions of everything are really quite old (in R-land, a couple of years old is considered "old"). If there's any way you can update everything to the latest version (R version 4.3.2, lme4 version 1.1-35.1) it will very likely make all of your problems go away, and if they don't it will be easier to troubleshoot. The latest version of R for Windows is here: https://cran.r-project.org/bin/windows/base/

**Comment by bbolker** [comment]
Any update on this? Otherwise I may close it ...
