### ISSUE TITLE
glmer does not work with Matrix version 1.6.4

### ISSUE THREAD

**Issue by M-Colley** [lme4/lme4#763]
Hello there, thank you for this great package. 

Unfortunately, it seems that with the new Matrix version 1.6.4, glmer does not work anymore. 

Here is a minimum working example, adapted from https://rdrr.io/cran/lme4/man/glmer.html#google_vignette 

```R
library(lattice)
library(lme4)

xyplot(incidence/size ~ period|herd, cbpp, type=c('g','p','l'),
       layout=c(3,5), index.cond = function(x,y)max(y))
gm1 <- lme4::glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
              data = cbpp, family = binomial)

```

The error is:

_Error in initializePtr() : 
  Function 'chm_factor_ldetL2' is not provided by 'Matrix'_

Edit: Downgrading to Matrix 1.6.3 does solve the problem, so it really seems to be a problem with the new version.

**Comment by bbolker** [comment]
Sigh. I don't know why this is happening, but I can confirm that (1) running (e.g.) `example(lmer)` with a fresh install of Matrix 1.6.4 from source fails with the error above, (2) a fresh `install.packages("lme4", type = "source")` resolves the problem.

@jaganmn, do you have any idea why this is happening despite the fact that (AFAICT) the Matrix ABI did *not* change in this release ... ??

**Comment by jaganmn** [comment]
I'll be able to take a look this evening.

**Comment by bbolker** [comment]
@M-Colley, it would be useful if you could confirm that the proposed fix (re-installing `lme4` from source) works for you.

**Comment by jaganmn** [comment]
I am unable to reproduce that error after running this script

```sh
#!/bin/sh
for file in Matrix_1.6-3.tar.gz Matrix_1.6-4.tar.gz lme4_1.1-35.1.tar.gz; do
    test -f ${file} || exit 1
done;
mkdir -p Library
R_LIBS_USER=Library
export R_LIBS_USER
R CMD INSTALL Matrix_1.6-3.tar.gz
R -e "install.packages(\"lme4\", dependencies = TRUE)"
R CMD check lme4_1.1-35.1.tar.gz
R CMD INSTALL Matrix_1.6-4.tar.gz
R -f lme4.Rcheck/lme4-Ex.R
```

in a directory containing those three `*.tar.gz` from CRAN.

I'm a bit confused about the error message.  Grepping the sources of the first order reverse LinkingTo of **Matrix**

```r
> tools::package_dependencies("Matrix", which = "LinkingTo", reverse = TRUE)[[1L]]
 [1] "ahMLE"               "bayesWatch"          "cplm"               
 [4] "GeneralizedWendland" "geostatsp"           "hibayes"            
 [7] "irlba"               "lme4"                "mcmcsae"            
[10] "OpenMx"              "PRIMME"              "robustlmm"          
[13] "spGARCH"             "TMB"                 "bcSeq"
```

reveals no usage of a function called `chm_factor_ldetL2`:

```
$ grep -rn reverseLinkingTo -e ldet
reverseLinkingTo/lme4/src/predModule.cpp:155:        d_ldL2 = ::M_chm_factor_ldetL2(d_L.factor());
reverseLinkingTo/geostatsp/src/gmrfLik.c:180:  *determinant = M_chm_factor_ldetL2(L) - *determinant;
reverseLinkingTo/geostatsp/src/gmrfLik.c:490:  determinant[0] = M_chm_factor_ldetL2(L);
reverseLinkingTo/cplm/src/cpglmm.c:276:    d[ldL2_POS] = M_chm_factor_ldetL2(L);
```

We _do_ see usage of our `M_chm_factor_ldetL2` (since **Matrix** 1.6-2 a macro expanding to `M_cholmod_factor_ldetA`); indeed, all API functions in the **Matrix** headers use the `M_` prefix, on purpose.  Finally:

```
$ nm Library/lme4/libs/lme4.so | grep -e ldet
0000000000041980 T _M_cholmod_factor_ldetA
```

i.e., the **lme4** symbol table does not contain a symbol called `chm_factor_ldetL2`, so why does your linker expect it ... ?  Of course we are maybe using different systems with different linkers, but still ...

**Comment by bbolker** [comment]
Hmm, weird, I can't reproduce any more either (although I definitely reproduced it once ...) This is my version of trying to set up the sequence that I thought would reproduce the problem (from within an R session):

```r
remotes::install_version("Matrix", version = "1.6.3")
install.packages("lme4", type = "source")  # 1.1.35.1
remotes::install_version("Matrix", version = "1.6.4")
library(lme4)
lmer(Reaction ~ Days + (1|Subject), sleepstudy)
```
... but now it works. Gremlins everywhere.

For what it's worth, Google purports to find that error message on [this page](https://bioc.ism.ac.jp/packages/checkResults/devel/bioc-LATEST/benchdamic/palomino3-buildsrc.html), but when I go there I can't find it in the page (and the dates look old/suspicious ...)

**Comment by bbolker** [comment]
I extended the script a little bit to `wget` the tarballs first (could be cleverer and download them conditionally, if they're not there ...), and use `--vanilla` when running R.  Runs fine on my system.

```
#!/bin/sh
wget https://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_1.6-3.tar.gz
wget https://cran.r-project.org/src/contrib/Matrix_1.6-4.tar.gz
wget https://cran.r-project.org/src/contrib/lme4_1.1-35.1.tar.gz
for file in Matrix_1.6-3.tar.gz Matrix_1.6-4.tar.gz lme4_1.1-35.1.tar.gz; do
    test -f ${file} || exit 1
done;
mkdir -p Library
R_LIBS_USER=Library
export R_LIBS_USER
R CMD INSTALL Matrix_1.6-3.tar.gz
R --vanilla -e "options(repos =\"https://cloud.r-project.org\"); install.packages(\"lme4\", dependencies = TRUE, type = \"source\")"
R CMD check lme4_1.1-35.1.tar.gz
R CMD INSTALL Matrix_1.6-4.tar.gz
R --vanilla  -f lme4.Rcheck/lme4-Ex.R
```

**Comment by M-Colley** [comment]
> ```r
> install.packages("lme4", type = "source") 
> ```

Hey @bbolker, installing from source also resolved the issue for me!

**Comment by mmaechler** [comment]
My guess is that you got a *binary*  lme4 package *not* from CRAN but one of the new non-CRAN package repositories. Their maintainers seem to not care reading E-mails on R-devel ... which gave a list of packages which need binary re-building (from source) with a newish (>= 1.6-2 IIRC) Matrix available.
But it seems we can close, as the OP solved his problem

**Comment by mkborregaard** [comment]
I'm teaching an R class, and many of the students had this exact issue today, on R-4.3.2 after running `update.packages`. Is there a known fix.?

**Comment by bbolker** [comment]
The known fix is either to install from source in the correct sequence (which may be hard as your students probably don't have developer tools installed) or to find a repository that has a compatible set of builds.  I would start with this:

```r
options(repos = c(CRAN = "https://cloud.r-project.org"))
install.packages("Matrix")
install.packages("lme4")
```

and see what happens.

**Comment by mkborregaard** [comment]
thanks, will try that. Yes I hope to avoid having them install source-building functionality, these are undergrads.

**Comment by mmaechler** [comment]
I understand.  But indeed, if they install from CRAN all should be well,
the problem are other "repositories" (r-universe, github,..)  or more typically just that they
had installed lme4 long ago, and for some reason had updated Matrix but not re-installed lme4.
@bbolker should work, because  `install.packages()`  *does* install even if the package is already installed,  and this exactly what we want.  HOWEVER,  Rstudio/Posit have their own version of `install.packages()` which I have heard (read on the R-devel mailing list) actually uses `update.packages()` instead of `install.packages()` and of course `update.packages()` my not re-install lme4 when it's already installed,  and hence the Rstudio-injected ("infected"  ;-) version of `install.packages()` does exactly the wrong thing here.
Workaround: They should use R's instead of Rstudio's function:

    utils::install.packages(.....)

**Comment by mebrooks** [comment]
On a machine where I followed the above advice to install from CRAN, from source in the order `Matrix`, then `lme4`, then `TMB`, then `glmmTMB`, I'm checking (via `revdepcheck::revdep_check`) the reverse dependencies for the new `glmmTMB` (master branch on GitHub). There are many new errors in examples of packages that use `glmmTMB`, but the errors come from examples using `glmer`. For example 
```
library(lme4)
Loading required package: Matrix
testData = createData(sampleSize = 100, overdispersion = 0.5, family = poisson())
fittedModel <- glmer(observedResponse ~ Environment1 + (1|group), 
family = "poisson", data = testData)

Error in initializePtr() : 
function 'chmfactorldetL2' not provided by package 'Matrix'
Calls: glmer ... initialize ->  -> initializePtr -> .Call
Execution halted
``` 

The output `problems.md` says that these errors occur in the new `glmmTMB` , but not the CRAN version. I don't understand why this is happening. When I tell the package maintainers about the problem, is there any solution I can suggest?

**Comment by jaganmn** [comment]
Is **revdepcheck** using a different library tree containing incompatible **Matrix** and **lme4** installations?  The error message does _not_ indicate a change to worse in the reverse dependency but rather a binary incompatibility on the machine running the checks ...

**Comment by bbolker** [comment]
I'm guessing that revdepcheck is using *cached* versions of packages ....

**Comment by mebrooks** [comment]
Yes, cached versions would make sense. I'll tell the maintainers that this shouldn't be a problem as long as everyone installs following the advice here.

**Comment by akmontoya** [comment]
I am having this same problem using Matrix version 1.6-3 (I initially had the error with 1.6-4, but tried reverting the package and it still gives the same error), lme4 version 1.1-21. I tried the working example from OP and get the same error.

**Comment by bbolker** [comment]
lme4 version 1.1-21 is very old (its date in the [archive](https://cran.r-project.org/src/contrib/Archive/lme4/) is 2019-03-05). Is there a reason you need to use an lme4 version that old? Based on the [Matrix archive](https://cran.r-project.org/src/contrib/Archive/Matrix/), the corresponding version of Matrix is 1.2-17.

If possible it will probably be easiest to update to the latest versions of Matrix  (1.6-5) and lme4 (1-1.35.1) (I *think* you should be able to install these straight from CRAN without worrying about installation from source). If you must use the old version of lme4 in order (for example) to exactly reproduce some results from 5 years ago, I would try `remotes::install_version()` to install the corresponding versions of the package.

**Comment by JosefineTM** [comment]
Hi! I am so sorry to bother again here. I have tried everything in this thread, and nothing seems to work. I created a new enviroment and even with very few packages installed (tidyverse and readxl) other than lme4, I still get the same error. Just wondering if anyone else is still having problems as well? 
It seems to be the case for basically all linear mixed effects packages. I tried lmerTest, nlme and GLMMadaptive and they all give me the same error.
Thanks !

**Comment by bbolker** [comment]
It's extremely surprising that this would be happening with `nlme`, which doesn't even use Matrix.  What we would like to see in order to have any chance of helping you would be a *minimal* reproducible example and the output of `sessionInfo()`.  For example, if you start a *clean* R session (no restored data files, no packages loaded, nothing in your environment - use the `--vanilla` command-line  argument if possible) and run 

```r
library(nlme)
fm1 <- lme(distance ~ age, data = Orthodont)
sessionInfo()
```

What do you get?  (Please post your results as text rather than as a screenshot ...)

```
R Under development (unstable) (2024-03-07 r86058)
Platform: x86_64-pc-linux-gnu
Running under: Pop!_OS 22.04 LTS

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so 
LAPACK: /usr/local/lib/R/lib/libRlapack.so;  LAPACK version 3.12.0

[locale/time zone info deleted]

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] nlme_3.1-163

loaded via a namespace (and not attached):
[1] compiler_4.4.0 tools_4.4.0    bspm_0.5.3     grid_4.4.0     lattice_0.22-5
```

**Comment by barracuda156** [comment]
> Hi! I am so sorry to bother again here. I have tried everything in this thread, and nothing seems to work. I created a new enviroment and even with very few packages installed (tidyverse and readxl) other than lme4, I still get the same error. Just wondering if anyone else is still having problems as well? It seems to be the case for basically all linear mixed effects packages. I tried lmerTest, nlme and GLMMadaptive and they all give me the same error. Thanks !

Oh well: https://stackoverflow.com/questions/77481539/error-in-initializeptr-function-cholmod-factor-ldeta-not-provided-by-pack

**Comment by bbolker** [comment]
@JosefineTM, unless you can provide more specific information we probably can't help you ...
