### ISSUE TITLE
Residual heteroscedasticity and complex variance–covariance structures?

### ISSUE THREAD

**Issue by allefeld** [lme4/lme4#766]
The package reference says

> - lme4 does not currently implement nlme’s features for modeling heteroscedasticity and correlation of residuals.
> - lme4 does not currently offer the same flexibility as nlme for composing complex variance–covariance structures …

Are there any plans to implement these features, so that lme4 can completely replace nlme?

**Comment by bbolker** [comment]
At present there are no concrete plans for implementing these features. `lme4` is supported on an entirely voluntary basis at present ... if someone were interested in working on this feature set I (BMB) would be happy to assist in design and implementation ...
