### ISSUE TITLE
install " tmleCommunity " package from github

### ISSUE THREAD

**Issue by anteneh12134** [lme4/lme4#771]
I have tried to install the " tmleCommunity " package from github and I entered the code:
library(remotes)
remotes::install_github("chizhangucb/tmleCommunity")
But when I run the code to install the package, I get this error:
•	Error: object 'pFormula' is not exported by 'namespace:plm'
•	Execution halted
•	ERROR: lazy loading failed for package 'tmleCommunity'

* removing 'C:/Users/AA/AppData/Local/R/win-library/4.3/tmleCommunity'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/AA/AppData/Local/Temp/RtmpuWKi6o/file1d243cd421ce/tmleCommunity_0.1.0.tar.gz’ had non-zero exit status
Please help me with this issue.
Thanks

**Comment by bbolker** [comment]
I'm afraid this question has nothing to do with `lme4`. Looking at the package's [DESCRIPTION file](https://github.com/chizhangucb/tmleCommunity/blob/master/DESCRIPTION), it doesn't even import/depend on `lme4`, so it seems completely unrelated. Please post to the [issues list for that package](https://github.com/chizhangucb/tmleCommunity/issues), or contact the package maintainer (e-mail is in the DESCRIPTION file linked above).
