### ISSUE TITLE
Apply custom contrast to all interactions in a mixed model (for a stacked dataset)

### ISSUE THREAD

**Issue by brizzen** [lme4/lme4#773]
Hi there,

I am conducting a multilevel mediation analysis with a multicategorical X (4 levels from a 2-by-2 design) for which I want to apply a custom contrast that codes two main effects and an interaction. For a stacked dataset with two indicator variables (Sm and Sy), a numerical outcome (Y) and mediator (M), I have following "issue" when calling a lmer: 

The "issue" that I get is that when calling `lmer` the initially set contrast for X is only applied to one interaction term (Sy:X) and for the remaining interaction the currently set contrast `options("contrasts")` is applied. However, my idea was to apply the custom contrast for `X` to all interactions in which the variable `X` is involved. Where am I missing something?

Below should be a reproducible example:

Example DF with `X` (predictor; numerical for the lmer, but originally treated as categorical), `M` (mediator; numerical), `Y` (outcome; numerical), `ID` (grouping variable; factors):

```
library(lme4)
# Number of subjects
n_subjects <- 30

# Number of conditions
n_conditions <- 4

# Levels of conditions
conditions <- factor(rep(1:n_conditions, times = n_subjects))

# Generate random data for predictor variable X with subject and condition effects
X <- rnorm(n_subjects * n_conditions, mean = rep(1:n_conditions, each = n_subjects), sd = 0.5)

# Generate random data for mediator variable M with subject and condition effects
M <- rnorm(n_subjects * n_conditions, mean = rep(1:n_conditions, each = n_subjects), sd = 0.5)

# Generate random data for outcome variable Y with subject and condition effects
Y <- rnorm(n_subjects * n_conditions, mean = rep(1:n_conditions, each = n_subjects), sd = 1)

# Create a data frame
DF <- data.frame(ID = rep(1:n_subjects, each = n_conditions),
                   X = as.factor(conditions),
                   M = M,
                   Y = Y)
```
Create custom contrast and apply to X: 

```
 custom_contrasts <- matrix(c(-1, -1, 1, 
                                   -1, 1, -1,
                                   1, -1, -1,  
                                   1, 1, 1),   
                                 nrow = 4, byrow = TRUE)
contrasts(DF$X) <- custom_contrasts
```

Now stack the dataset:

```
require(reshape2)
DF$fid <- 1:nrow(DF)
stacked <- melt(DF, id.vars = c("fid", "ID", "Y", "X","M"),
                measure.vars = c("Y", "X"), value.name = "Z")
stacked <- within(stacked, {
  Sy <- as.integer(variable == "Y")
  Sm <- as.integer(variable == "M")
})
```

The reason for stacking the dataset is to re-formulate the two formulas...
`model.m = lme4::lmer(M ~ 1 + X + (1 | ID) , data = DF)` 
`model.y = lme4::lmer(Y ~ 1 + X + M + (1|ID), data = DF)` 

...into one formula with a new response variable `Z` with `Y` stacked on `M` and estimate the model*:
 `mm = lme4::lmer(Z ~ 0 + Sm + Sy + Sm:X+ Sy:X+ Sy:M+ (0 + Sm + Sy | ID) , data = stacked)`

- `Sm`: The intercept for M 
- `Sy`: The intercept for Y // `Sm` and `Sy` are indicator variables.
- `SmX`: Regression coefficient for X->M (a path)
- `SyM`: Regression coefficient for M->Y (b path)
- `SyX`: Regression coefficient for X->Y (cprime path)

see: [multilevel mediation example](https://stats.oarc.ucla.edu/r/faq/how-can-i-perform-mediation-with-multilevel-data-method-2/) for another example of how and why to stack the dataset (in this case X is numerical, so no contrast needed)

\* I get a singular fit, but I think this is due to my "bad" data-frame simulation-skills. Shouldn't make a difference for the issue I am having.

Now, when inspecting the model.matrix (?) the contrast is correctly coded for Sy:X1 to Sy:X3. For Sm:X1 to Sm:X3 the contrast is still a treatment (?) contrast:

```
# Inspect the model matrix
m.matrix = mm@pp[["X"]]
View(m.matrix)
```

Best,
Brais

**Comment by bbolker** [comment]
Not a solution, but possibly helpful hints: stacking `X` with `M` is a bit problematic because you're mixing a factor and a numeric variable in the same column ...  did you mean to stack `Y` and `M` ???


* You can troubleshoot this problem outside of `lme4`,  by knowing that the fixed-effect model matrix `X` is generated by a call to `model.matrix()` on the fixed-effect part of the formula (using `nobars()`):

```r
X <- model.matrix(~ 0 + Sm + Sy + Sm:X+ Sy:X+ Sy:M, data = stacked)
head(X)
attr(X, "contrasts")
```

so this reduces to a "linear model formula machinery" question.

* if you do want the fixed-effect model matrix from a `merMod` (`lmer`/`glmer` fit) object, using `model.matrix(mm)` or `getME(mm, "X")` is a better way to do it ...
* Note that when you run `melt` there's a warning:

> attributes are not identical across measure variables; they will be dropped 

which may be relevant ...

* presumably you're converting `Z` back to numeric after stacking? (Trying to stack `X`, which is a factor, and `Y`, which is numeric, is the source of both the result that `Z` is `character` and the warning in the previous bullet point)

**Comment by brizzen** [comment]
Thanks, I've now submitted this question with updated/corrected code to:

https://stats.stackexchange.com/questions/641871/apply-custom-anova-like-contrasts-to-a-all-interactions-in-a-mixed-model-with
