### ISSUE TITLE
ASAN problems

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#776]
CRAN says:

> Please see the problems shown on
[<https://cran.r-project.org/web/checks/check_results_lme4.html>](https://cran.r-project.org/web/checks/check_results_lme4.html).

> Please correct before 2024-04-12 to safely retain your package on CRAN.

I strongly suspect these come from the new SuiteSparse/Matrix release.

original log [here](https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-ASAN/lme4/00check.log), copy here:  [00check.log](https://github.com/lme4/lme4/files/14805686/00check.log)

My guess would be that the easiest way to diagnose these will be to use the [SAN Rocker image](https://github.com/rocker-org/r-devel-san-clang) ...

Playing around below.  It looks like the `r-devel-san` container is still running R 4.3.3 ... ??? Should ask maintainers ...

---

e.g. something like this?  (*everything*, including weak dependencies
```
docker run --rm -ti rocker/r-devel-san
## within docker
install.packages("remotes")
remotes::install_version("Matrix", "1.6.5")
install.packages("lme4")
example(lmer)
```

Separate shell:

```
## assume we are only running one docker instance ...
DOCKER=`docker ps | tail -1 | cut -d ' ' -f 1`
docker exec -it $DOCKER bash
## in shell
apt install --assume-yes cmake
Rscript -e 'install.packages("remotes"); remotes::install_version("Matrix", version = "1.7.0"); install.packages("lme4")'
```

**Comment by jaganmn** [comment]
The second parameter of `cholmod_factorize_p` is `double[2]`, but you pass `double *` where the pointed-to buffer has the width of only `double[1]`.  `cholmod_rowfac_mask2` accesses the second `double` in the new version of CHOLMOD.

https://github.com/lme4/lme4/blob/e4dabdbd28f7f75b07a62ebdc14c7c0c9394a4fe/src/lme4CholmodDecomposition.h#L34-L51

**Comment by jaganmn** [comment]
[beta.diff.txt](https://github.com/lme4/lme4/files/14813959/beta.diff.txt)

**Comment by bbolker** [comment]
Applied in a780590e25e (haven't dealt with checking yet ...)

**Comment by jaganmn** [comment]
I'm assuming that you received an extension ... ? I would test the patch the old fashioned way by locally building R-devel with ASan support ...

https://stat.ethz.ch/R-manual/R-patched/doc/manual/R-exts.html#Using-Address-Sanitizer

**Comment by bbolker** [comment]
I misremembered the date!  I'll ask for an extension.
