### ISSUE TITLE
How to determine predicted value threshold from lmer() or glmmTMB()

### ISSUE THREAD

**Issue by Hanaworld** [lme4/lme4#781]
Hi everyone, 
I am new to coding and Bbolker referred me here. I would like to get the confidence interval (CI) for the predicted mean of a Linear Mixed Effect Model on a large dataset (50000 subjects). Below is the structure of the data. I centred `$age` and `$f_score` for readability. `age` variable which was originally 50-100 and new variable `$age50` is now (0-50) and `$f_score` originally was from -3.8190 to 5.4756 and a new score `$score` is now from 0 to 9.368007 .

```
'data.frame': 171872 obs. of  16 variables:
 $ id      : Factor w/ 52521 levels "AT-000674-01",..: 1 1 1 2 2 2 2 2 3 3 ...
 $ year    : num  0 1 2 0 1 2 3 4 0 1 ...
 $ sex     : Factor w/ 1 level "2": 1 1 1 1 1 1 1 1 1 1 ...
 $ adl     : num  NA 0 0 NA 0 0 0 0 NA 0 ...
 $ iadl    : num  NA 0 0 NA 0 0 0 1 NA 0 ...
 $ age     : num  59 59 59 72 72 72 72 72 59 59 ...
 $ age50   : num  9 9 9 22 22 22 22 22 9 9 ...
 $ f_score : Factor w/ 1231 levels "-3.8189011237",..: 226 226 226 252 252 252 252 252 125 125 ...
 $ score   : num  3.72 3.72 3.72 3.85 3.85 ...
```

I managed to create a prediction estimate and Confidence interval for the full dataset based on the fitted model but the prediction estimate included negative values and the outcome variable is score for 0-6 (count variable). 

```r
adl.f <- glmmTMB (adl ~ score*age50 + year*age50 + I(year^2) + (1 + year |id), data = df_female)
pred.df <- expand.grid(
  age50 = 0:50,
  year = 1:15,
  f_score = seq(min(df_female$score), max(df_female$score), length.out = 100),
  id = NA
)
adl.d <- predict (adl.f, newdata = pred.df, re.form = NA, se.fit = TRUE)
```

Is there a way to determine the threshold of the estimated values (0-6) and still be able to calculate CI? Any help would be appreciated. Thank you

**Comment by bbolker** [comment]
This is not really appropriate for the issues list (see https://github.com/lme4/lme4/blob/master/README.md#where-to-get-help). Your original question (by e-mail) was about an *error* that you were getting when trying to compute SEs of predictions (if I recall correctly). This question ("how do I appropriately model a response variable on a bounded scale?") is  more general modeling question that would be appropriate for [Cross Validated](https://stats.stackexchange.com) or `r-sig-mixed-models@r-project.org`.  My advice would be that an *ordinal model* would be most appropriate, although calculating CI of predictions could still be challenging.

*If* your question is primarily about how to resolve errors, you can re-open this issue, although it will still be useful (almost necessary) to provide a **reproducible** example.
