### ISSUE TITLE
Providing customized model matrices

### ISSUE THREAD

**Issue by covaruber** [lme4/lme4#785]
Dear Ben, is there a way to provide a customized incidence matrix in lme4? Something like:

```
X <- model.matrix(~ Subject -1, data=sleepstudy)
mix <- lmer(Reaction ~ Days + (Days | X), data=sleepstudy)

```
Instead of the classical?

```
mix <- lmer(Reaction ~ Days + (Days | Subject), data=sleepstudy)

```

Or any reference with a tricks to do so?

Cheers,
Eduardo

**Comment by bbolker** [comment]
The trick is to use the [modular interface](https://github.com/lme4/lme4/blob/master/man/modular.Rd); you can set up the basic model framework, substitute in different components, then fit the model. One example is shown here: https://rpubs.com/bbolker/groupmembers .  I'm going to close this here, but feel free to follow up on `r-sig-mixed-models@r-project.org`.

**Comment by covaruber** [comment]
This is awesome!! This enables a lot of things for my team. Thanks Ben.

Cheers,
Eduardo
________________________________
De: Ben Bolker ***@***.***>
Enviado: jueves, 2 de mayo de 2024 07:59 a. m.
Para: lme4/lme4 ***@***.***>
Cc: Gio Covarrubias ***@***.***>; Author ***@***.***>
Asunto: Re: [lme4/lme4] Providing customized model matrices (Issue #785)


The trick is to use the modular interface<https://github.com/lme4/lme4/blob/master/man/modular.Rd>; you can set up the basic model framework, substitute in different components, then fit the model. One example is shown here: https://rpubs.com/bbolker/groupmembers . I'm going to close this here, but feel free to follow up on ***@***.***
