### ISSUE TITLE
Migrate off deprecated Eigen class MappedSparseMatrix?

### ISSUE THREAD

**Issue by MichaelChirico** [lme4/lme4#792]
https://github.com/lme4/lme4/blob/2d82cbee952c23e2d3f8492489da7bd5a40dfb2f/src/predModule.h#L32

As noted e.g. here:

https://github.com/cran/RcppEigen/blob/4e0fdf6bf1e0f3d36a984ad32720c157d3a94c7d/inst/include/RcppEigenWrap.h#L295

`Map<SparseMatrix>` is the new type going forward. I'm not sure what type of lift is needed to switch to the new type.

**Comment by bbolker** [comment]
ugh, thanks for the heads up.

**Comment by MichaelChirico** [comment]
I wasn't able to confirm completely but it _looks_ like dropping in `Eigen::Map<Eigen::SparseMatrix<double>>` there should work.

**Comment by bbolker** [comment]
Do you know offhand if we might have backward compatibility issues (i.e., would it be wise to bump something like the required `RcppEigen` version)?

**Comment by MichaelChirico** [comment]
Sorry, I'm not very familiar. Shared all I know already

**Comment by bbolker** [comment]
We already depend on RcppEigen >= 3.3.9.4, RcppEigen version numbers match the corresponding Eigen release, the old incantation was deprecated starting from Eigen 3.3, so I think we're not breaking any backward compatibility (and I'm too lazy to go back and test to see if we're *actually* still compatible with RcppEigen 3.3.9.4).
