### ISSUE TITLE
Imprecision detected in test-predict.R on Linux aarch64 and ppc64le architectures

### ISSUE THREAD

**Issue by mfansler** [lme4/lme4#796]
We're seeing small inaccuracies in one of the `test-predict.R` tests when [building on Conda Forge](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=958187&view=results) for **linux-aarch64** and **linux-ppc64le** architectures. This pertains to [the v1.1-35.4 build](https://github.com/conda-forge/r-lme4-feedstock/pull/33). Here is the failure:

**linux-ppc64le**
```r
── Failed tests ────────────────────────────────────────────────────────────────
Failure ('test-predict.R:503:5'): predict works with factors in left-out REs
head(predict(m1B, re.form = ~(1 | g1)), 1) not equal to c(`1` = 0.146787496519465).
1/1 mismatches
[1] 0.147 - 0.147 == -2.6e-05

[ FAIL 1 | WARN 0 | SKIP 1 | PASS 630 ]
```

**linux-aarch64**
```r
── Failed tests ────────────────────────────────────────────────────────────────
Failure ('test-predict.R:503:5'): predict works with factors in left-out REs
head(predict(m1B, re.form = ~(1 | g1)), 1) not equal to c(`1` = 0.146787496519465).
1/1 mismatches
[1] 0.147 - 0.147 == -8.57e-06

[ FAIL 1 | WARN 0 | SKIP 1 | PASS 630 ]
```

Note that these builds are using QEMU on Azure linux-64 runners, i.e., emulating the architectures. It is unclear to what extent that  is a source of the imprecision. All native builds passed these same tests and this issue was not detected in the v1.1-35.3 builds. Also note that our **osx-arm64** builds *do not run tests* since we currently use cross-compilation for those builds.

This is just a report in case others encounter a similar situation, however, any suggestions for resolution are welcome.

**Comment by bbolker** [comment]
Thanks.  This was already reported by CRAN based on their [M1Mac test platform](https://www.stats.ox.ac.uk/pub/bdr/M1mac/lme4.out); I loosened the tolerance to 1e-5 in 062aaab, but I guess I should loosen it slightly further based on your first result. (I don't take the effort to try to chase down the exact reasons for fluctuations at this level; among other things, the examples chosen for tests are often small and numerically unstable, as the point is often just to see if the behaviour is qualitatively OK.)
