### ISSUE TITLE
Support for weights in lme4::bootMer()

### ISSUE THREAD

**Issue by jay-sf** [lme4/lme4#801]
Hi Ben and team,

I've used `weights` in `lmer()` with two random intercepts and am wondering if the weights are considered in `lme4::bootMer()`. Specifically, I've applied IPW and need a cluster bootstrap. Should be acceptable that the weights aren't recalculated.

Thanks,
J

**Comment by bbolker** [comment]
Hmm. `bootMer` only does parametric bootstrapping, which doesn't sound like a "cluster bootstrap" to me (there are other packages like `lmeresampler` that do various kinds of nonparametric, cluster-aware resamping ...)  As far as I know (haven't dug down), `bootMer` will refit models with whatever weights were specified initially ... (there was a [somewhat related issue](https://github.com/lme4/lme4/issues/678), now resolved, having to do with specifying *new* weights in the `refit()` function)

**Comment by jay-sf** [comment]
Well ok thanks, that's actually the information I needed: this somehow perpetuates the random effects, but the sample itself remains the same. So it made sense I wrote a function that draws clusters (i.e. subjects with their repeated measures) accounting for their weights then refitting (not to be confused with `refit()`) the model _B_ times.

**Comment by bbolker** [comment]
That sounds right.  It would be nice to leverage `refit()` for this, and it might be possible if your design is balanced (every subject has the same number of repeated measures) ...

**Comment by jay-sf** [comment]
Would definitely be helpful if `refit()` could deal with new predictor matrices as well, not just with a new response. 
Maybe a quick follow-up. What do you think: May we apply the DFs from the original model to calculate p values from the bootstrap standard errors, similar to Satterthwaite's approximation?

**Comment by bbolker** [comment]
I'm pretty sure we could hack something to substitute a new *fixed-effect* predictor matrix (`X`) (substituting a new `Z` will almost certainly *not* be possible).

A suggestion for p-values (with the caveat that I am *not* very well versed in the theory of bootstrap methods): if `x` is your vector of bootstrapped parameter estimates, why not `2*min(sum(x<0), sum(x>0))` (i.e., double the minimum tail)?

**Comment by jay-sf** [comment]
I'm actually not sure if in bootstrapping mixed models the RE structure should stay the same (which is what `refit()` does). If I'd let Z follow from X in each replication, what I'm currently doing, it would be a convenience issue and `update(fit, data=bs_sample)` sufficient.

Interesting p value approach, doesn't look very conservative at first glance, though.
