### ISSUE TITLE
[New feature] Add an optional argument to save lmer()/glmer() output as a local *.rds file (which can be re-loaded later)

### ISSUE THREAD

**Issue by HaiyangJin** [lme4/lme4#803]
# "Issue"
Fitting a (G)LMM can take a long time, especially when the data is huge and the model is complex. As such, it is not feasible to fit each (G)LMM one by one when rendering HTML/PDF from Rmd files. 

# Suggestion
It would be beneficial to add an optional argument to save the (G)LMM output as a local *.rds file. Then, when the same function/model is recalled, the previous saved *.rds can be re-loaded (instead of spending too much time re-fitting the model). The following analysis can be conducted accordingly. 

# Example
For example, an optional argument `file = “none”` (default to “none”) could be added. When `file` is not `“none”` (say `file = “lmer_example.rds”`), the (G)LMM output would be saved locally with the file name `file` (i.e., “lmer_example.rds”). Then later when the same in-argument was used (i.e., `file = “lmer_example.rds”`), the model would not be re-fitted. Instead, the local file (“lmer_example.rds”) would be loaded. 

# I'm happy to give a try
I’m not an expert in making R packages, but I have some experience. I am more than happy to try adding the optional in-argument if this is something that would be considered to be included in the lme4 package.

Many thanks for making this great package!

**Comment by bbolker** [comment]
It's not clear to me why this has to be built into `lme4` and why you couldn't just define your own wrapper function as follows:

```r
my_lmer <- function(..., file = "lmer_example.rds") {
    if (file.exists(file)) return(readRDS(file))
    fit <- lme4::lmer(...)
    saveRDS(fit, file = file)
    return(fit)
}
```

If you wanted to live dangerously you could even name this function `lmer` so that it masked the one in the `lme4` package. (It's only dangerous because it's potentially confusing.)

**Comment by pitakakariki** [comment]
This feature is also built into knitr already, see e.g. https://bookdown.org/yihui/rmarkdown-cookbook/cache.html.

**Comment by HaiyangJin** [comment]
Hi, @bbolker and @pitakakariki 
Many thanks for the suggestion. Both sound great to me. 

I will give it a try. Thanks again.

**Comment by HaiyangJin** [comment]
Hi @bbolker, @pitakakariki 
Many thanks for the suggestions. Both sound great to me. 
I will give it a try. Thanks again.
