### ISSUE TITLE
deviance() returning NaN due to numerical issues

### ISSUE THREAD

**Issue by wviechtb** [lme4/lme4#812]
I am running into the problem that `deviance()` can return `NaN` when one of the deviance residuals happens to be `NaN` due to numerical issues. Consider the following example:

    library(lme4)

    dat <- data.frame(x=1:6, n=100, id=1:6)
    res <- glmer(cbind(x,n-x) ~ 1 + (1 | id), data=dat, family=binomial)
    summary(res)
    deviance(res)
    sum(residuals(res, type="deviance")^2)

Everything works fine. Now consider this case:

    dat <- data.frame(x=1:5, n=100, id=1:5)
    res <- glmer(cbind(x,n-x) ~ 1 + (1 | id), data=dat, family=binomial)
    summary(res)
    deviance(res)
    residuals(res, type="deviance")

The problem is that the deviance residual for `x=3` should be 0, but due to the usual numerical inaccuracies, `residuals()` is trying to take the square-root of a just slightly negative number. This should be easy to fix up with a check for negative values, setting the corresponding deviance residuals to 0.

I am not super familiar with the `lme4` code, but I think a minor change to `residuals.glmResp` should do. Instead of `d.res <- sqrt(object$devResid())`, do this in two steps with:

    d2.res <- object$devResid()
    d.res <- ifelse(d2.res < 0, 0, sqrt(d2.res))

**Comment by bbolker** [comment]
Good point. (`sqrt(pmax(0, object$devResid()))` is a little easier.)
